### ISSUE TITLE
Reordering Sources

### ISSUE THREAD

**Issue by timokorkalainen** [Palakis/obs-websocket#101]
#### Issue type
Feature request
#### Description
Since there is already the "SourceOrderChanged" event, GetCurrentScene to get current order and all the other source related transforms are available, could we also get a request method to change the source ordering in a scene?
#### Proposal
SetSceneItemsOrder
##### Request fields :
* "items" (array) : Ordered list of the names of the scene items.
* "scene-name" (string) : scene the items belong to. Defaults to current scene.
##### Response : 
OK if all specified items exists and no other items do, error otherwise.

**Comment by TStod** [comment]
I may crank this out for 4.3.0 as I am looking for something like this.
1 issue with the proposed implementation is that duplicate sources have the same name and it would be impossible to infer what order the developer or user is specifying. We should consider this issue with https://github.com/Palakis/obs-websocket/issues/155 and https://github.com/Palakis/obs-websocket/issues/154

**Comment by TStod** [comment]
This is pretty easy but will require a haphazard implementation or a delay until we support scene item `id`s.

I am writing an implementation that will work for after `id`s are configured as per https://github.com/Palakis/obs-websocket/issues/154 using the method: `bool obs_scene_reorder_items(obs_scene_t *scene, obs_sceneitem_t * const *item_order, size_t item_order_size)` from obs
