### ISSUE TITLE
Should StreamStatus events be sent if the stream's off?

### ISSUE THREAD

**Issue by eropple** [Palakis/obs-websocket#103]
#### Issue type
Other

#### Description
More of a question of intent than anything else, maybe a feature request if so--it seems that, given the payload of the `StreamStatus` event (including a `streaming` field that can never be anything but true), maybe that event should be sent as a "heartbeat" regardless of whether the stream is running? It'd make creating dashboards that accurately reflect the current status of OBS a lot easier; right now I end up actually polling every 64ms so I can say "stream's on/stream's off, recording's on/recording's off." In a WebSocket world, polling is a yellow-to-red flag, so I figured I'd ask. =)

My unicorn wish would be some way to configure how fast `StreamStatus` gets sent, in order to have a timecode on the dashboard that updates more rapidly than every 2000ms, but I don't wanna be greedy. =) I've been dusting off my C++, though, so variable event timing might be something I look into doing myself if that'd be welcomed.

**Comment by Palakis** [comment]
Those are interesting ideas here.
I believe `StreamStatus` should only be sent when there's actual streaming in progress. However:

> maybe that event should be sent as a "heartbeat" regardless of whether the stream is running? It'd make creating dashboards that accurately reflect the current status of OBS a lot easier

A good compromise would be to add the ability to turn `StreamStatus` on or off, even when there's no streaming running

> My unicorn wish would be some way to configure how fast StreamStatus gets sent, in order to have a timecode on the dashboard that updates more rapidly than every 2000ms,

The timing is crucial to properly calculate the stream's output bitrate. This is something that must be modified to be independant from `StreamStatus`' interval, and that would make possible the additon of request types to get/set `StreamStatus`' interval.

**Comment by GufNZ** [comment]
Another idea would be simply to send a final payload when streaming stops with the `false` in it.  That way, something listening for that event gets the "stopped" message, and then nothing till streaming/recording starts again, which it seems to me is all it needs as nothing interesting is happening in between.

**Comment by Palakis** [comment]
> Another idea would be simply to send a final payload when streaming stops with the false in it. That way, something listening for that event gets the "stopped" message

There's already events for this. `StreamingStopping`, `StreamingStopped`, `RecordingStopping` and `RecordingStopped`.

**Comment by Palakis** [comment]
Closing this, as there's something like this currently being worked on in the Pull Requests. Discussion regarding new values for StreamStatus\Heartbeat is going on in #115.
