### ISSUE TITLE
How to upload .deb (ubuntu, Linux Mint)

### ISSUE THREAD

**Issue by chepecarlos** [Palakis/obs-websocket#107]
I really like obs-websocket, I'm still a beginner; I have compiled the source code and I have the .deb I would like to add it https://github.com/Palakis/obs-websocket/releases so that another install in ubuntu.

Thanks for the time and the excellent program.

http://alsw.net/wp-content/uploads/2017/07/obs-websocket.tar.gz

**Comment by abourget** [comment]
Looking forward for a Linux release too ! Thanks for this one..

**Comment by Palakis** [comment]
Thank you for your interest! Linux support has been worked on after the release of 4.0.0, so a .deb version will be available for the release of obs-websocket 4.2.0.
