### ISSUE TITLE
SetCurrentScene Request and SceneChange Event handled out of order

### ISSUE THREAD

**Issue by haganbmj** [Palakis/obs-websocket#11]
When calling [HandleSetCurrentScene](https://github.com/Palakis/obs-websocket/blob/master/WSRequestHandler.cpp#L185), [OnSceneChange](https://github.com/Palakis/obs-websocket/blob/master/WSEvents.cpp#L93) is emit before the scene change finishes? 

Based on the logs, it looks like the SceneChange emit is before the SetCurrentScene sends its OK response. Not familiar with the whole process of releasing obs_sources/scenes - but it might be related to that and may just be an issue with the obs api.

Example:
```
setCurrentScene('scene 2')
sceneChange => 'scene 1'
(setCurrentScene response)

setCurrentScene('scene 1')
sceneChange => 'scene 2'
(setCurrentScene response)

setCurrentScene('scene 1')
sceneChange => 'scene 1'
(setCurrentScene response)
```

On another note, I've had some crashes that might be related to [this commit](https://github.com/Palakis/obs-websocket/commit/12933486c976dd624f7eec3267e01dd703d50c13), but my new machine's build environment is all screwed up. I'll see if I can reconfigure and actually build the updates locally.

- I've also had some funky business where it will list a set of scenes, but attempting to switch to one will produce a "scene does not exist" - then going into OBS and trying to switch to that scene will crash the program. Crash logs point to obs_scene_release. 
- I've also had something similar crashes happen and have it clear my scene list on restart. 
- Disconnecting from the socket then reconnecting within a short time window (~2 seconds?) will crash obs.

Again, I'll see if I can update my machine and test with your changes since the last build.

**Comment by Palakis** [comment]
Maybe this is because `obs_frontend_get_current_scene` is called before the request scene is the current scene...  
Working on a fix based on the current transition.

**Comment by Palakis** [comment]
*"I've also had something similar crashes happen and have it clear my scene list on restart"*  
I've had an similar unidentified bug where my scene list would get cleared for no reason. I need to dig that issue deeper.

*"Disconnecting from the socket then reconnecting within a short time window (~2 seconds?) will crash obs."*  
Tried it several times in short interval and wasn't able to reproduce this. Please create a dedicated GitHub issue if it happens with the latest changes.

**Comment by Palakis** [comment]
@haganbmj  *"I've also had something similar crashes happen and have it clear my scene list on restart"*
Since https://github.com/Palakis/obs-websocket/commit/5fd1e978ec98a6361f23fa273e219cc6e6c9e66d, the majority of crashes, so the aforementioned bug might not happen anymore.
