### ISSUE TITLE
Self compiled version does not work on OBS

### ISSUE THREAD

**Issue by RainbowEK** [Palakis/obs-websocket#110]
##### Issue type
Bug report

##### Description
If I compile obs-websocket myself and install it in OBS (installed with official OBS installer in windows), it is not recognized.

##### Steps to reproduce and other useful info
1) Compile OBS 
2) Compile web-socket
3) Okay if: when I install websocket in my own compiled version of OBS it works fine.
4a) Problem when: when I install it in the official downloaded OBS installer (OBS-Studio-19.0.3-Full-Installer.exe) it does not work
4b) Messages in OBS log: 
22:59:18.799: Module '../../obs-plugins/64bit/obs-websocket.dll' not found
22:59:18.803: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/Qt5Network.dll' not found, loading of module failed
22:59:18.804: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/Qt5WebSockets.dll' not found, loading of module failed
5) What is going wrong in step 4 that I do need to correct or is it something else? (I am busy adding some functionality in obs-websocket but will not be able to release it on GIT if not working for others that are only users. As I only can use it on my own compiled OBS)

##### Technical information
- **Operating System** : W10 64bit Eng
- **OBS Studio version** : 19.0.3

##### Development Environment
- Problem appears in both VS2015 and VS2017
- CMake 3.9.0
- Using CMakeLists and instruction as provided in the OBS and obs-websocket build instructions.

Thanks in advance for your support !!!

**Comment by Palakis** [comment]
You need to compile obs-websocket with VS2013, same compiler as OBS releases.

**Comment by Palakis** [comment]
Btw, what exactly are you adding in obs-websocket?

**Comment by Palakis** [comment]
> Adding to obs-websocket: Heartbeat. Started with the need for recording information when there is no streaming.

You may want to look at and contribute to this discussion: https://github.com/Palakis/obs-websocket/issues/103.
Open a Pull Request whenever you feel your contributions are ready.

**Comment by makeen** [comment]
The previous errors are because you are using dependencies for VS2015, I had the same errors and repeat the install instructions with dependencies for VS2013 and 0 errors. 

Now I have obs-studio and obs-websocket compiled with VS2013 **and still the official OBS installer in windows is not recognizing obs-websocket**. I'm in a dead end.

I need obs-websocket 4.2.0 with "Save replay buffer" feature, because of that I'm trying self compliled.

**Comment by haganbmj** [comment]
If you're on Windows you can get the latest built files off of Appveyor. [Every commit is linked to Appveyor](https://github.com/Palakis/obs-websocket/commits/master) with a green checkmark and it you click the Artifacts tab you should be able to use that.

https://ci.appveyor.com/project/Palakis/obs-websocket/build/master-316/artifacts

**Comment by makeen** [comment]
Thanks!

**Comment by Palakis** [comment]
By the way, OBS Studio is currently built with Qt 5.7.0. Everything works fine with exactly Qt 5.7.0, not 5.8 or other minor releases to 5.7.
A link to download Qt 5.7.0 is provided in the Compile guide of obs-websocket.

**Comment by RytoEX** [comment]
OBS Studio is now built with VS2017 and Qt 5.10.x.  While some Qt versions are compatible with each other, it's best to just build with the same version that OBS Studio uses.

@Palakis I think this can be closed?

**Comment by Palakis** [comment]
@RainbowEK still having this issue?
