### ISSUE TITLE
StreamStatus vs OBS Stats window

### ISSUE THREAD

**Issue by GufNZ** [Palakis/obs-websocket#115]
##### Issue type
Not sure if I'd call it a bug, but the missing info makes a proper stream-health monitor impossible.

##### Description
`StreamStatus` seems to represent the lines in the bottom half of the OBS Stats window only (apart from FPS).  It does *not* include the rendering/encoding lag missed/skipped frames.

##### Steps to reproduce and other useful info
Start streaming; compare `StreamStatus` payload to the contents of the OBS Stats window, and note the missing information, which in my particular case keeps turning red, (along with YouTube reporting bad stream health).  I can only see a dip in FPS and bitRate to have anything to go on that OBS is struggling.

I was hoping to implement a UI for the stream health in my code that uses `obs-websocket` but that is proving difficult given `StreamStatus` doesn't carry all the info I expected.

Fixes, but also alternatives/workarounds welcome - have I missed something useful/obvious?

##### Technical information
- **Operating System** : Win10 x64
- **OBS Studio version** : 20.0.1 x64

**Comment by Palakis** [comment]
`StreamStatus` was introduced at the very beginning in obs-websocket at a time when OBS Studio had no Statistics window. Might be good to update it with more values and fix the bandwidth calculation code. If you want to help and know a bit of C/C++, you can explore OBS' API to see what's currently possible and report useful functions here, or (better) contribute code through Pull Requests.

**Comment by GufNZ** [comment]
Unfortunately I haven't used C/C++ in 2 decades, and a lot has changed since then.  I did have a go at reading the OBS API code and am not certain it exposes the numbers I'm after, but then again I'm not exactly sure it doesn't either.

**Comment by Lange** [comment]
I'd also like the `StreamStatus` event to include the `Frames missed due to rendering lag` and `Skipped frames due to encoding lag`.

[video_output_get_skipped_frames](https://obsproject.com/docs/reference-libobs-media-io.html#c.video_output_get_skipped_frames) seems relevant.

**Comment by lassos** [comment]
i have one question. is it also possible to check if the status bar is red ? sometimes we do not get a reconnect event but stream is going down from green to red for some minutes without disconnecting. is there a way to check this ? thank for any help
