### ISSUE TITLE
what is TransitionToProgram syntax?

### ISSUE THREAD

**Issue by illusdidi** [Palakis/obs-websocket#116]
##### Issue type
Bug report? Other?
 ##
##### Description
Hi, I don't undestand how to make a TransitionToProgram request, it keeps saying me "invalid request type".

I've tried multiple syntaxes in json but I'm not very good at this. :/

`obs.TransitionToProgram({'with-transition.name': trans_type});`

`obs.TransitionToProgram({});`

`var transition = {"with-transition.name": trans_type, "with-transition.duration": 300};
obs.TransitionToProgram({"with-transition": transition});`

`var transition = {"name": trans_type, "duration": 300};
obs.TransitionToProgram({"with-transition": transition});`

Do you have an example of code ?
Thank you

##### Technical information
- **Operating System** : Windows 10 Home
- **OBS Studio version** : 20.0.1

**Comment by haganbmj** [comment]
It's a json object like this
```json
{
    "with-transition": {
        "name": "some transition name",
        "duration": 300
    }
}
```

As for why I don't have the slightest idea.

**Comment by haganbmj** [comment]
Looks like you're using javascript, so you can do something like this if you want.

```js
var transition = {};
transition["with-transition"] = {};
transition["with-transition"].name = "some transition name";
transition["with-transition"].duration = 300;

obs.transitionToProgram(transition);
```

Which is absolutely hideous.

Or 

```
var transition = {
     "with-transition": {
          "name": "some transition name",
          "duration": 300
     }
};

obs.transitionToProgram(transition);
```

**Comment by haganbmj** [comment]
Hold on a second, nevermind. Just reread that you're getting `invalid request type`.

This example you had would work fine.
```js
var transition = {"name": trans_type, "duration": 300}; obs.TransitionToProgram({"with-transition": transition});
```

Whatever you're using doesn't know what TransitionToProgram is.
If you're using https://github.com/haganbmj/obs-websocket-js then it looks like TransitionToProgram was added after my latest release.
You can use 

```js
obs.registerRequest('TransitionToProgram');

obs.TransitionToProgram(transition);
```

I'll cut a new release in a little bit.

**Comment by haganbmj** [comment]
Make sure you're using at least obs-websocket v4.1.0
https://github.com/Palakis/obs-websocket/releases/tag/4.1.0

Wasn't implemented until then.

**Comment by illusdidi** [comment]
that's whyyyyyyyyyyyyyy ! Now it works ! thank you very much for your precious help !

**Comment by Palakis** [comment]
Shit, we really need a new full release of obs-websocket soon...

**Comment by haganbmj** [comment]
Hah, I'll go through and add a `@since` to the documentation later tonight or something to keep track of when requests/events were implemented.
