### ISSUE TITLE
keep the same preview scene in studio mode ?

### ISSUE THREAD

**Issue by illusdidi** [Palakis/obs-websocket#118]
##### Issue type
Bug report? or Feature request?

##### Description
When using **setCurrentScene** in studio mode, the preview scene changes. Is there a way to keep the same preview scene while switching the current scene in studio mode ?

I tried to use **SetPreviewScene** right after **setCurrentScene** to keep the same preview scene, but it doesn't stay. It works if I use **SetPreviewScene** after  **setCurrentScene** with a delay of 100ms, but it's not really a solution.

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 20.0.1

**Comment by Palakis** [comment]
Maybe that's what your looking for:
![image](https://user-images.githubusercontent.com/1812130/29745812-b8b3ab9a-8ac5-11e7-948f-ff1012bdf250.png)

**Comment by illusdidi** [comment]
Exactly ! didn't think to look here. thank you very much.
