### ISSUE TITLE
Obs-websocket and query strings

### ISSUE THREAD

**Issue by johnnyinthedark** [Palakis/obs-websocket#120]
##### Issue type
Feature request

##### Description
Recently found out about obs-websocket and really appreciate the work. Unfortunately due to the lack of knowledge in programming can't get to work using js. Is it possible to control OBS just sending commands to obs-websocket using query strings like:
localhost:4444/?switchscene=game

If not, what is the easiest way to write a script that does simple things like that?

Thanks a lot!

**Comment by haganbmj** [comment]
This uses a technology called WebSockets to communicate, so query parameters aren't the standard way to work with that.

You could download a Browser Extension or use an online tool if you'd like.
https://www.websocket.org/echo.html
https://chrome.google.com/webstore/search/websocket

You'd still need to send fully formatted commands though, so switching scene to 'Game' would require sending a proper JSON message like this
```
{
  "request-type": "SetCurrentScene",
  "message-id": "1",
  "scene-name": "Game"
}
```

`request-type` specifies what kind of action you want, `message-id` is for identifying responses, it's a required field even if you don't intend to use it.
`scene-name` is the field for `SetCurrentScene` as defined here: https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md#setcurrentscene

**Comment by johnnyinthedark** [comment]
Thanks! 
Eventually I was able to do what I needed. But is there a way to disable plugin notifications? Everytime I connect/disconnect it shows Windows alert. My script is just a command that sends single request and closes the connection. 

Alerts get quite annoying.

**Comment by haganbmj** [comment]
Looks like that's not configurable at the moment, I can add that later today or something unless Palakis wants it.
