### ISSUE TITLE
Update Playlist of a VLC Video Source

### ISSUE THREAD

**Issue by sebseb7** [Palakis/obs-websocket#125]
##### Issue type
Feature request

##### Description
If would like to update the playlist of a VLC video Source (adding + removing items)

**Comment by sebseb7** [comment]
minimal implementation that would fullfill my requirements:

SetVLCSourcePlaylist(scene-name,['url',item1,'file',item2]);

**Comment by chiefstank** [comment]
I agree that being able to view/manipulate the VLC video source items would be great. Thank you.

**Comment by chiefstank** [comment]
With the addition of VLC source hotkeys within OBS, I'm hoping websocket can integrate further with it.

**Comment by chiefstank** [comment]
> 
> 
> I'd love to be able to activate hotkeys for a VLC source remotely. That would be very useful.

Safe to say that this won't be updated anymore.

**Comment by Palakis** [comment]
@chiefstank ?

**Comment by tt2468** [comment]
A call like this is relatively redundant. You can use `GetSourceSettings` to grab the playlist, and `SetSourceSettings` to set the playlist.

Example `GetSourceSettings` response: `{'sourceName': 'VLC Video Source', 'sourceSettings': {'playlist': [{'hidden': False, 'selected': False, 'value': 'Z:/Videos/2020-02-04 20-31-19.mp4'}, {'hidden': False, 'selected': False, 'value': 'Z:/Videos/2020-02-04 20-31-47.mp4'}]}, 'sourceType': 'vlc_source', 'status': 'ok'}`
