### ISSUE TITLE
SwitchScenes via Hotkey does not trigger PreviewSceneChanged

### ISSUE THREAD

**Issue by haganbmj** [Palakis/obs-websocket#127]
##### Issue type
Bug report/inquiry.

##### Description
May be related to https://github.com/Palakis/obs-websocket/issues/72
and this bit https://github.com/Palakis/obs-websocket/blob/master/WSEvents.cpp#L304-L309

See https://github.com/haganbmj/obs-websocket-js/issues/79 for the original report.

##### Technical information
- **Operating System** :
- **OBS Studio version** : 20.0.1, plugin version 4.1.0

This might be an issue with OBS' API. I'm not entirely sure how well all of the hotkeys are wired up to the api.
Was wondering if you had any ideas though in case this was something that was getting mixed up in that hotfix for TransitionToProgram. Ideally these all get fixed at the OBS side eventually.

**Comment by haganbmj** [comment]
Also just uploaded a simple, no-frills test tool if you ever need it. Right click save and open locally to get around the whole https/insecure websocket thing.
https://raw.githubusercontent.com/haganbmj/obs-websocket-js/master/samples/web-tester/dist/tester.html

<img width="944" alt="obs-tester" src="https://user-images.githubusercontent.com/15820761/30895455-f68347e8-a30f-11e7-8e09-68cf13c4e52a.png">

**Comment by lamaral** [comment]
I can confirm this bug with OBS 20.1.3 and plugin version 4.2.0.

**Comment by Palakis** [comment]
@haganbmj Tested this on the latest `4.x-current` and it works on my end. Closing this.
