### ISSUE TITLE
Implement GetSourceList request

### ISSUE THREAD

**Issue by XBase-xOR** [Palakis/obs-websocket#128]
##### Issue type
Feature request

##### Description
Right now the list of sources can only be retrieved from the SwitchScenes event, PreviewSceneChanged event (Studio mode), the GetCurrentScene request and the GetPreviewScene request (Studio mode).  But all of these refer to the currently active or preview scene, there is no way to retrieve the sources for a scene that is not currently active. A new GetSourceList request would fill this gap.

If possible the list should not only show the name of the sources but also the locked/unlocked and visible/invisible status.

##### Technical information
- **Operating System** : Windows 10 64 Bit
- **OBS Studio version** : 20.0.1

**Comment by TStod** [comment]
@XBase-xOR Checkout the `GetSceneList` request. It seems to return a list of scenes (each with its own list of sources).

**Comment by XBase-xOR** [comment]
@TStod Thanks for pointing this out! I saw `GetSceneList` but apparently didn't pay enough attention to what the documentation really says. It refers to `GetCurrentScene` and that made me think somehow it would only show that for the current scene like all of the other requests. But now that I read it again I understand that actually it's telling me that it's giving me the same information I get from `GetCurrentScene` but for all of the scenes - which means I get all the details I want. That's great!

I am not even sure whether we need GetSourceList then, because I doubt that from a performance perspective (both on server and client side) it hurts too much if someone has to get the sources for all scenes even if he'd only need the sources of a specific scene (like me).
Maybe for the sake of completeness but then it's definitely a low priority thing. It would be fine by me to close this one but I'll leave that to the main contributors to decide.

Thanks again!

**Comment by TStod** [comment]
@XBase-xOR see https://github.com/Palakis/obs-websocket/issues/131

**Comment by Palakis** [comment]
> I am not even sure whether we need GetSourceList then, because I doubt that from a performance perspective (both on server and client side) it hurts too much if someone has to get the sources for all scenes even if he'd only need the sources of a specific scene (like me).

You could do some time measurements to verify this. e.g: how much time it takes between request and response with 1 scene, 2 scenes, 3 scenes, etc...
