### ISSUE TITLE
Implement GetSourceRender request

### ISSUE THREAD

**Issue by XBase-xOR** [Palakis/obs-websocket#129]
##### Issue type
Feature request

##### Description
Right now there is no way to tell whether a specific source is currently visible or not, except if it is a browser source (GetBrowserSourceProperties request), a GDI+ text source (GetTextGDIPlusProperties request) or the visibility was just changed (SceneItemVisibilityChanged event).
A new GetSourceRender request would fill this gap.

Alternatively #128 would help here too if it would include the visibility status for all listed sources and maybe would be sufficient for all the use cases so I'd say #128 should have priority, but maybe a single GetSourceRender request would be quicker and easier to implement?

##### Technical information
- **Operating System** : Windows 10 64 Bit
- **OBS Studio version** : 20.0.1

**Comment by XBase-xOR** [comment]
@TStod Referring to our comments in #128 if I only want to know the visibility status of one single source that is not in the currently active scene it seems like a lot of overhead to retrieve the full list of all scenes and sources using `GetSceneList` for that, although what I said in my comment there is still true: I guess in most systems it's not even much of an issue from performance perspective. It's just that it's feeling like burning a forest down to kill one ant :P

**Comment by TStod** [comment]
Yea @XBase-xOR I'm with you 100%

**Comment by TStod** [comment]
I think this could be closed with priority given to the generic method for getting scene items scene specific properties.
https://github.com/Palakis/obs-websocket/issues/131

**Comment by XBase-xOR** [comment]
Makes sense to me.
