### ISSUE TITLE
[Feature] Unified getter for scene specific source properties

### ISSUE THREAD

**Issue by TStod** [Palakis/obs-websocket#131]
##### Issue type
Feature Request

##### Description
Add functions for getting a scene items transform position and crop or add these numbers to responses that include source's position/size etc.

Additional methods could include:
`GetSceneItemTransform({scene-name(optional), item})`
`GetSceneItemPosition({scene-name(optional), item})`
`GetSceneItemCrop({scene-name (optional), item})`
or
`GetSceneItem({scene-name (optional), item})` which returns all 3 types of information

**Comment by TStod** [comment]
If someone knows of a method to get the`Crop (top, bottom, left, right)` `Transform (x-scale, y-scale, rotation)` and `Position (x, y, alignment [top, left, top-left, center, ...])`

It is worth noting that it might be fruitful to combine scene item setters to take all the parameters that are available in the edit transform dialog: `Position: x, y` `Rotation` `Size: x, y` `Positional Alignment` `Crop: top, bottom, left, right` `Bounding Box Type`? `Alignment in Bounding Box`? `Bounding Box Size: x, y`?

**Comment by TStod** [comment]
Just thought dumping here but if these requests can be combined there should be no reason why a batch of requests couldn't be combined. I'll dig into the code a bit this evening to see how invasive of a feature this is.

**Comment by TStod** [comment]
Properties of a scene item can be found here:
https://github.com/jp9000/obs-studio/blob/76b6266689fd88a2d085650b16e7baf72b8d2d5e/libobs/obs-scene.h

Seems like a good amount of these are not needed every time you get a scene list but perhaps using this type of request to pull the bulk of them would be the correct decision.

**Comment by TStod** [comment]
##### Issue type
Feature Request

##### Description
Defines getters for a sources properties for a given scene including:
- Position
- Rotation
- Size
- Positional Alignment
- Crop (left, right, top, bottom)
- Visibility (rendered)

- Bounding Box Type?
- Alignment in Bounding Box?
- Bounding Box Size?

**Comment by TStod** [comment]
@Palakis Going to start working on these issues. Is there a way I can push a branch for a PR?

**Comment by haganbmj** [comment]
@TStod Fork the repo using the button in the top right of the page.
Clone that forked repo (https://github.com/TStod/obs-websocket) and work on that. You can either work on master there or create your own branches, doesn't really matter.
Push changes to your forked repo then you can create a pull request from there back to Palakis/master.

**Comment by haganbmj** [comment]
Example.

```sh
~/git/obs-websocket (master) $ git remote -v
Palakis	https://github.com/Palakis/obs-websocket.git (fetch)
Palakis	https://github.com/Palakis/obs-websocket.git (push)
origin	https://github.com/haganbmj/obs-websocket.git (fetch)
origin	https://github.com/haganbmj/obs-websocket.git (push)
```

Then you'd push to whatever the name of that remote is. 

```
~/git/obs-websocket (master) $ git push <remote-name> <branch-name>
~/git/obs-websocket (master) $ git push origin master
```

**Comment by TStod** [comment]
Got a WIP PR: https://github.com/Palakis/obs-websocket/pull/136
