### ISSUE TITLE
Patch for enabling recording status via websocket

### ISSUE THREAD

**Issue by masikh** [Palakis/obs-websocket#137]
First of all, thanks for programming the obs-websocket. Really cool, little request though, could you/anyone add my patch to the obs-websocket code?

Kind regards,

Robert Nagtegaal
masikh@gmail.com

##### Issue type
Enhancement of the OBS-Websocket

##### Description
The code provided in (below) snippit will enable your obs-websocket to spit-out RecordingStatus (analog to StreamStatus!)

##### Steps to reproduce and other useful info
This snippit (below) should replace line 613-627 of the https://github.com/Palakis/obs-websocket/blob/master/WSEvents.cpp file

``` javascript
void WSEvents::StreamStatus() {
    bool streaming_active = obs_frontend_streaming_active();
    bool recording_active = obs_frontend_recording_active();

    obs_output_t* status_output = obs_frontend_get_streaming_output();

    if (recording_active) {
        status_output = obs_frontend_get_recording_output();
    }

    if (!status_output || (!streaming_active && !recording_active)) {
        if (status_output) {
            obs_output_release(status_output);
        }
        return;
    }

    uint64_t bytes_sent = obs_output_get_total_bytes(status_output);
    uint64_t bytes_sent_time = os_gettime_ns();
```

see also: https://github.com/Elektordi/obs-websocket-py/issues/10

**Comment by haganbmj** [comment]
This would replace the stream output if recording is active though, right?
Your solution only ever returns one or the other, not both.

I guess I would need to get both outputs then I'd have access to the bitrate and the time information?

**Comment by haganbmj** [comment]
Something along these lines. I'm boarding a plane, I'll look more into it later.
I'm not even sure some of the strain/etc info is relevant for recording.
https://github.com/Palakis/obs-websocket/compare/master...haganbmj:recording-status

**Comment by RainbowEK** [comment]
There is also already merged code in the mast for a Heartbeat, for a next release. When the Heartbeat is enabled it spits out the Recording data.

**Comment by haganbmj** [comment]
Does feel like the StreamStatus should output the same data if it's going to mention Recording at all in its response.

**Comment by masikh** [comment]
Dear all, I see indeed that there is a problem with my code returning either streamstatus XOR recording status. I made sure stream-status took precedence where I think that's used more often, but its obviously fundamentally wrong, both cases should be served! So yes its quick and dirty thus needs some extra work!

Note: The type of information coming from the heartbeat is NOT entirely the same as stream/recording status! Heartbeat is in my personal opinion kinda useless with a good stream/recording status in place.

What will make the websocket extremely useful is monitoring the input streams too! E.g. I am running a grid of 12 tv channels. Sometimes the input stream got stuck. If we can detect that, than both IN- and OUT-put, streams are covered, potentially making OBS more robust!

See attached image for an idea..
![image](https://user-images.githubusercontent.com/773227/31576046-8f624d2e-b0f3-11e7-9925-6b2236a434fa.png)

**Comment by Palakis** [comment]
@masikh I don't usually handle patch submissions through the Issues section. Could you please open a Pull Request for this?
