### ISSUE TITLE
Fix CI builds

### ISSUE THREAD

**Issue by RytoEX** [Palakis/obs-websocket#143]
##### Issue type
Bug/Other

##### Description
Currently, the CI builds are failing because https://www.slepin.fr is unreachable.  I think it'd be nice to fix CI builds.

##### Steps to reproduce and other useful info
Trigger the CI builds.

I'm opening this issue to discuss possible ways to streamline and fix the CI builds.  I thought this might be a better path forward than just going straight to opening a PR.  Here are some things I think could be done:
1. Use the built-in Qt (AppVeyor)
OBS' CI does this.  Yes, it's 5.7.1, and official OBS builds still seem to use 5.7.0, but there shouldn't be anything different between 5.7.0 and 5.7.1 that would cause build errors later, and it seems to be good enough for the OBS CI.  It would also remove the need to redownload Qt whenever the cache is invalid.
2. Cache relevant parts of the obs-studio build (AppVeyor)
Instead of building against the same tag every time, build it and cache `obs.lib` and `obs-frontend-api.lib` for each build/release type.  Before building OBS, you could check if the cached files exist, and whether or not a new version of OBS has been tagged/released.  I'm not sure how well this would work, but I think it's worth a shot.
3. Build against the latest obs-studio git tag (All)
Instead of building against an older tag (19.0.3) or having to remember to update CI every time OBS updates, you could determine the latest tag using `git describe`.  This will solve the build errors for the missing Studio Mode functions introduced in OBS 20.0.0 in [this commit](https://github.com/jp9000/obs-studio/commit/2e3888abd41de6931b6a38990df5ab061eddb347#diff-5f6fa92922f960e2b0f97d6af46646dc).
4. Switch to VS2015 (AppVeyor)
OBS' CI does this.  This isn't really necessary, but it would match what is done in the OBS CI setup.
5. Relocate Packages.pkg (Travis: OSX)
I'm not very familiar with OSX/macOS, so I'm not sure how best to address this.  I know OBS' CI uses its own nightly builds folder to host a `Packages.pkg` file.  I'm not sure if you can use that (with their permission), or if you need a version specific to your build.

I'm totally willing to help address items 1-4 by writing code or CI config files and submitting a PR.  I just wanted to check here first to see if that effort would be welcome or not first.

**Comment by haganbmj** [comment]
I've had issues with 5.7.1 vs 5.7.0, but I might have just had some configuration wrong. 
I was trying to get an appveyor build running but kind of abandoned it a few months ago.
This build was also looking at consuming different qt versions and caching obs-studio, though that should probably be stripped down to just be a couple necessary files. I had it set to just update whenever the obs tagged verison was updated in the appveyor.yml

https://github.com/haganbmj/obs-websocket/commit/d9efd6552af91d65c88145990ab7b8878ca8e5e3

Definitely need to get the slepin.fr issue sorted at the very least.

**Comment by haganbmj** [comment]
Slepin.fr issue fix in #141

**Comment by RytoEX** [comment]
Oh wow.  I must've just missed that one.  If #141 is going to take care of macOS CI, I can handle the other bits that I laid out.  It seems from that PR that @Palakis is generally in favor of fixing the CI stuff.  If I get a PR going, I'll reference back to this issue.

**Comment by Palakis** [comment]
Regarding 1) and 4) : Official release binaries are built on AppVeyor and Travis. Hence the reason why I try to stick to what OBS uses in official releases.

**Comment by Palakis** [comment]
> 3) Build against the latest obs-studio git tag (All)
Instead of building against an older tag (19.0.3) or having to remember to update CI every time OBS updates, you could determine the latest tag using git describe. This will solve the build errors for the missing Studio Mode functions introduced in OBS 20.0.0 in this commit.

It would be awesome if someone could write a bit of script that automatically fetch the latest stable OBS tag!

**Comment by Palakis** [comment]
And I absolutely agree with 2)

**Comment by RytoEX** [comment]
I can handle writing a script to fetch the latest obs-studio stable tag (item 3).  I'm working on that now.

I'm also working on caching parts of the obs-studio build so it doesn't have to be rebuilt every time here (item 2).

If you can resolve the unavailability of https://www.slepin.fr/, I'd agree on the point of keeping strictly to Qt 5.7.0.  But as it stands, it kind of defeats the purpose of CI if it can't build, and fetching 1GB of data from an external source on every build (if cache fails or doesn't exist yet) seems like overkill.  How about a compromise?  If CI can't find a cached Qt 5.7.0 file, and it can't fetch it, it uses the built-in Qt 5.7 (which is 5.7.1).  If CI can find or fetch a Qt 5.7.0 file, it uses that.  That way, at least the CI builds can catch build errors for now.  Would that be agreeable?

**Comment by RytoEX** [comment]
I think I've gotten items 2 and 3 working now.  AppVeyor builds of obs-websocket now take about 3 minutes instead of 10-20.  I'll clean up my work, rebase my branch for PR #146, and force push the changes there.

**Comment by Palakis** [comment]
> I think I've gotten items 2 and 3 working now. AppVeyor builds of obs-websocket now take about 3 minutes instead of 10-20, when the obs-studio bits are properly cached and not in need of a rebuild. I'll clean up my work, rebase my branch for PR #146, and force push the changes there.

Nice!

> If you can resolve the unavailability of https://www.slepin.fr/, I'd agree on the point of keeping strictly to Qt 5.7.0. But as it stands, it kind of defeats the purpose of CI if it can't build, and fetching 1GB of data from an external source on every build (if cache fails or doesn't exist yet) seems like overkill. How about a compromise? If CI can't find a cached Qt 5.7.0 file, and it can't fetch it, it uses the built-in Qt 5.7 (which is 5.7.1). If CI can find or fetch a Qt 5.7.0 file, it uses that, as long as that's still what OBS uses in official builds. That way, at least the CI builds can catch build errors for now. Would that be agreeable?

That's a good compromise. On my end, I'll add monitoring on either www.slepin.fr or the build script itself to get notifications if the AppVeyor builds can't use Qt 5.7.0.

I believe user tests should be conducted to determine if a Qt minor version mismatch between OBS and obs-websocket causes major troubles or not. Last time I had issues with a minor version mismatch was with Debug binaries, but maybe the Release ones don't behave the same.

**Comment by RytoEX** [comment]
Okay, I'll work on the Qt scripts next.

I had done some testing on version mismatches a few weeks ago.  I'll have to dig up my notes on that and re-test to see if they're still correct.

**Comment by Palakis** [comment]
Regarding the suggested switch to VS2015: release builds of OBS Studio are still built with VS2013 (saw msvcp120.dll and msvcr120.dll in Dependency Walker).
As I use AppVeyor to produce binaries for the official releases, I'll keep it that way.

Btw, I guess I should probably chat with Jim regarding the compiler + Qt differences between release and CI, and what are his plans for future releases...

**Comment by Palakis** [comment]
Fixed https://www.slepin.fr.

**Comment by RytoEX** [comment]
Okay, so I did write a script to manage the Qt dependency like I described above.  However, there are some issues with caching now that slepin.fr is back up.  The qt570.zip file is 966,850,644 bytes (after AppVeyor tries to recompress it) and the obs-studio directory (after building and getting compressed) is 238,712,286 bytes.  The build cache limit for Free/Basic plans is 1GB, so obviously these both cannot be cached together on those plans.  While changing the Qt dependency to 5.7.1 would solve this issue, here are some other workarounds:

1. I could try to change the compression settings for AppVeyor, but with the Qt file being so large, I'm not sure it would help.
2. I could try to delete everything from the obs-studio build directories except the needed .lib and source files and the .git directory.  The worst thing with this would probably be having to add a `git reset --hard` before trying to do a git pull/checkout.
3. You could try to recompress the Qt 5.7.0 files into something smaller.  I've done some local tests:
7zip using zip Ultra Deflate gets down to 881MB
7zip using 7z Fastest LZMA2 gets down to 724MB
7zip using 7z Normal LZMA2 gets down to 506MB
7zip using 7z Ultra LZMA2 gets down to 443MB

-----

However, as far as I can tell, obs-websocket compiled with Qt 5.7.1 _will_ work with an OBS compiled with Qt 5.7.0 so long as you include QNetwork.dll and QWebSockets.dll from Qt 5.7.0 instead of Qt 5.7.1.  You'll get this line in the logs:
> 11:02:30.813: [obs-websocket] qt version (compile-time): 5.7.1 ; qt version (run-time): 5.7.0

Similarly, if you drop obs-websocket 4.2.0 (built against Qt 5.7.0) into an OBS install built against Qt 5.7.1, but include QNetwork.dll and QWebSockets.dll from Qt 5.7.1, you'll get this:
> 02:29:31.081: [obs-websocket] qt version (compile-time): 5.7.0 ; qt version (run-time): 5.7.1

Both will run successfully.

I've also tested obs-websocket 4.2.0 against an OBS git build (20.x from a couple weeks before 20.1) where OBS was compiled against Qt 5.7.1 in VS2015.  I also tested OBS built against Qt 5.7.0, but packaged with the Qt 5.7.1 DLLs, with obs-websocket compiled and packaged with Qt 5.7.1.  The plugin seems to function correctly, from my testing in all above instances.

From the Qt 5.7.1 release notes:
> Qt 5.7.1 is a bug-fix release. It maintains both forward and backward compatibility (source and binary) with Qt 5.7.0.

From what I can tell, the included QNetwork.dll and QWebSockets.dll files _must_ match the version of the Qt DLLs packaged with OBS, but the Qt version obs-websockets is compiled against doesn't matter as much, so long as they're both 5.7.x.  So it really shouldn't be an issue to build against 5.7.1 and just include the 5.7.0 DLLs (to match OBS), as far as I'm aware.  Though, it could certainly use more testing.

-----

As an aside, I've noticed that your CI builds use Release, but OBS is built with RelWithDebInfo, including for official releases.  That's pretty simple to address, and I can add it to my list of adjustments.


I have plans to address some of my thoughts on compiler and Qt versions with Jim, but I wanted to try to wait until he's sufficiently decompressed after TwitchCon to do that.

**Comment by Palakis** [comment]
Wow @RytoEX, thanks for your comprehensive findings!
I guess the issue I had were because of a mismatch in the QtCore and QNetwork+QWebSockets pair.

For now, if AppVeyor can cache both the Qt 5.7.0 archive and a built OBS, let's stick to the current method. I'll replace the current Qt 5.7.0 archive on slepin.fr with a repackaged LZMA2-compressed version.

**Comment by Palakis** [comment]
> I guess the issue I had were because of a mismatch in the QtCore and QNetwork+QWebSockets pair.

Forgot to add this: a version mismatch between QtCore and Qt modules seems to cause problems, but a mismatch between Core+Modules and obs-websocket seems fine.

**Comment by Palakis** [comment]
> The build cache limit for Free/Basic plans is 1GB per account (all projects on your account count towards this), so obviously these both cannot be cached together on those plans

Damn, missed that part...
You can switch to AV's built-in Qt 5.7.1 then. I'll make a binary-only Qt 5.7.0 package, make it available on slepin.fr and add the link to your PR. There will be some AppVeyor-specific changes to make in CMakeLists.txt I guess.

**Comment by RytoEX** [comment]
So, we should compile against Qt 5.7.1, but then package the Qt 5.7.0 QNetwork.dll and QWebSockets.dll to match the current OBS packaged Qt DLLs?  I'm pretty sure that'll work based on my earlier findings.  Just making sure I understand before I make more changes.

If the qt570 archive file (with sources and DLLs) can be made small enough, you should still be able to use that, if needed, and it would remove the need to make AppVeyor specific changes to CMakeLists.  Let me know when you've made a new qt570 archive and what its size is, and I'll experiment with it.  Feel free to put both a full archive (full Qt 5.7.0) and binaries only (just Qt 5.7.0 DLLs) on slepin.fr with different filenames for now so that we can try out both techniques.

**Comment by RytoEX** [comment]
> Btw, I guess I should probably chat with Jim regarding the compiler + Qt differences between release and CI, and what are his plans for future releases...

> I have plans to address some of my thoughts on compiler and Qt versions with Jim, but I wanted to try to wait until he's sufficiently decompressed after TwitchCon to do that.

Fenrir and I finally talked to Jim about Qt.  For now, it sounds like he plans to move to Qt 5.9.x at OBS 21.  He's also possibly moving from VS2013 to VS2015/2017 at some point, in part because Qt is deprecating VS2013 support in Qt 5.9 and removing VS2013 support in Qt 5.11.

**Comment by RytoEX** [comment]
My code is pretty much cleaned up on my local repo and ready to go.  Just avoiding doing any unnecessary pushes to GitHub until I can sort out the Qt issue with @Palakis.  Namely, I either need access to a much smaller Qt 5.7.0 archive, or I need access to just the QNetwork.dll and QWebSockets.dll files for Qt 5.7.0.  Basically, I need them hosted somewhere that I can pull for the CI scripts.

**Comment by Palakis** [comment]
@RytoEx Woops, forgot to upload those!

**Comment by RytoEX** [comment]
@Palakis I figured that might have been the case.  No worries!  I'll keep an eye out.

**Comment by RytoEX** [comment]
Updated PR #146.  It should now be ready for merging.

**Comment by RytoEX** [comment]
With PR #146 merged, this can probably be closed once we can confirm that the caching is working properly.  Per [my comment there](https://github.com/Palakis/obs-websocket/pull/146#issuecomment-340207241), we may have to monitor the next few builds on master to make sure it's working correctly.  As I mentioned on that PR, I have a few ideas on how to further improve CI builds, but I'll file a separate issue/PR for that in order to keep the scope of this issue limited.

**Comment by RytoEX** [comment]
The caching seems to have finally taken effect and the Windows build times on AppVeyor are now down to about 4.5 minutes when OBS Studio doesn't require a rebuild.  Hopefully the cache continues to cooperate.  I'll take a look at other improvements that can be made, but this issue can now be closed.
