### ISSUE TITLE
Miscellaneous Thoughts for a potential 5.0.0 rewrite

### ISSUE THREAD

**Issue by haganbmj** [Palakis/obs-websocket#144]
- Standardize the request parsing and response handling.
- Add some methods for verifying required fields that generate standardized error messages.
- Error codes?
- Ditch kebab-case in favor of camelCase or even snake_case if necessary to adhere to [a more common json style guide](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format).
- Consistent method/variable names. Probably just inline with exactly what obs calls them. (ie. `StartStopStreaming` vs `ToggleMute`, `visible` vs `render`, etc).
- Combine some of the methods (`GetCurrentTransition` + `GetTransitionDuration`). Ensure all source manipulation uses whatever combined accessors are available.
- Consistency in errors. (`StartRecording` throws an error if already recording, `EnableStudioMode` doesn't despite both also offering a `Toggle` method).
- Split into smaller files.
- Is there a better way to handle tracking recording time and streaming time? Seems like obs should expose those.
- Combine `Heartbeat` and `StreamStatus` events.

as mentioned here: https://github.com/Palakis/obs-websocket/pull/136#discussion_r145278996

**Comment by Palakis** [comment]
> - Standardize the request parsing and response handling.

What do you mean?

> - Add some methods for verifying required fields that generate standardized error messages.
> - Error codes?

I agree on both regarding error messages, as string-only errors aren't machine-interpretable.

> - Ditch kebab-case in favor of camelCase or even snake_case if necessary to adhere to [a more common json style guide](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format)

I'd go for camelCase here. (btw kebab-case is legacy from OBSRemote)

> - Consistent method/variable names. Probably just inline with exactly what obs calls them. (ie. `StartStopStreaming` vs `ToggleMute`, `visible` vs `render`, etc).

I believe naming Inconsistencies between `StartStop*` and `Toggle*` should be settled to `Toggle*`.
Regarding property naming, these should be in active tense (don't know if it's an actual term).

> - Combine some of the methods (`GetCurrentTransition` + `GetTransitionDuration`). Ensure all source manipulation uses whatever combined accessors are available.

True.

> - Split into smaller files.

Doing this once all PRs of interest are merged.

> - Combine `Heartbeat` and `StreamStatus` events.

That's a mistake from my end. I didn't think enough on this before merging, even though I appreciate the contribution itself.

**Comment by Palakis** [comment]
I should probably make a diagram of OBS' taxonomy, to make protocol redesign easier.

**Comment by Palakis** [comment]
Another thought (which can be implemented in a 4.* release): instead of having request handler methods (prefixed with Handle) sending the response themselves by calling SendOKResponse, request handlers should `return` the response data, which in turn will be sent by the upper message processing function.

Current:
```cpp
static void WSRequestHandler::HandleWhatever(WSRequestHandler* req) {
    bool good = false;
    if (!good) {
        req->SendErrorResponse("something's not right");
        return; 
    }

    req->SendOKResponse();
}
```

Proposed:
```cpp
static obs_data_t* WSRequestHandler::HandleWhatever(WSRequestHandler* req) {
    bool good = false;
    if (!good) {
        return req->ErrorResponse("something's not right"); 
    }

    return req->OKResponse();
}
```

**Comment by Palakis** [comment]
P.S. : using libobs' C++ helper classes would be useful if switching to responses through `return`.

**Comment by haganbmj** [comment]
Yeah, returning the response data would allow a bit more flexibility with appending additional information when necessary.

By "Standardize the request parsing and response handling" I was referencing methods like `verifyRequiredField` that would generate consistent error messages and return those.
All responses should have the `messageId` and probably echo the `requestType`. Regardless of whether they're errors or not.

Active tense or present tense, I think I've heard both terms used. 👍

**Comment by Palakis** [comment]
Given the big time interval between releases, I'd suggest 4.3.0 to be the last 4.x release, and allow non backwards-compatible changes after that release to begin development of 5.0.

**Comment by Palakis** [comment]
Regarding 4.3.0, I have to check if everything's right in the source requests I introduced, and do a second-pass review of all the changes.
Also, maybe there are some useful feature than can be quickly implemented before the release of 4.3.0?

**Comment by Palakis** [comment]
Here are a few more thoughts for 5.0:
- I discovered the JSON-RPC protocol recently, which is pretty similar to our current message format and easy to implement. We should use this one in 5.0.
- I have a few architecture ideas to make the plugin as much unit-testable as possible. If we reach sufficient code coverage, we'll be more confident in the source code and be able to release more frequently.
- Still regarding architecture, the request handling should be as protocol agnostic as possible to allow further integration of additional protocols, such as HTTP. The goal here is to make `obs-websockets` more an RPC plugin than just a WebSockets control plugin.
- Since the addition of scripting in OBS 21, it would be nice to allow scripts to hook a method handler in `obs-websockets`. Combined with the suggestion above, any script could then be able to support RPC easily.

**Comment by malliaridis** [comment]
I am developing an android app and I tried to map the output objects properly. It would be great if in version 5.0.0 the point **"Consistent method/variable names"** would be written in bold. It is pretty hard to map the same information if it is provided with multiple information (like the source name key, `source-name`, `sourceName`, `source`).

Also some responses include information that would better fit in a different request / event, or at least with a more general name that includes all necessary information. This could be optimized in my opinion too.

The information of a `SceneItemTransform` is also included in `SceneItem`, just with different keys for the same values. Maybe nesting it properly and using the same keys would allow better consumption of the API too.

Alongside the last point, a clearer data model structure / hierarchy would also improve the mapping of any data sent by the server. Some common and simple data objects like filter (`name,`, `type`, `enabled`, `settings`) or crop (`top`, `right`, `bottom`, `left`) that occur in multiple places can be abstracted pretty easy. It gets harder and complicated however when we talk about scenes and sources. But even there patterns can be found:
- Source (`name`, `type`, `kind`, `settings`, `filters`)
  - Scene (adds to Source `items` which is a list of scene items)
- Scene Item (which is a wrapper for Source objects and adds `id`,  `visible`, `muted`, `volume`, `locked`, `parentGroupName`, `groupChildren` and `transformation`)

In my opinion if this nesting gets clarified and improved, the whole API would get much easier to consume.

**Comment by tt2468** [comment]
Thanks everyone for the ideas here. We have our new protocol documented here: https://docs.google.com/spreadsheets/d/1LfCZrbT8e7cSaKo_TuPDd-CJiptL7RSuo8iE63vMmMs
