### ISSUE TITLE
Upgraded to 4.2.0, GetCurrentScene no longer works

### ISSUE THREAD

**Issue by Huesdon** [Palakis/obs-websocket#147]
##### Issue type
Bug report

##### Description
Upgraded to 4.2.0, GetCurrentScene no longer works (no changes to my code)
Instead of the scene name it now returns the response:
`response = {
    "error": "missing request parameters",
    "message-id": "",
    "status": "error"
`

##### Steps to reproduce and other useful info
[2017-10-19 17-00-29.txt](https://github.com/Palakis/obs-websocket/files/1400466/2017-10-19.17-00-29.txt)

##### Technical information
- **Operating System** : Windows 10 Home - Fully Updated
- **OBS Studio version** : 20.1.0

**Comment by haganbmj** [comment]
`request-type` and `message-id` are the two required params unless you're accidentally sending another request type.

**Comment by Huesdon** [comment]
Really? The docs say: No specified parameters.

**Comment by haganbmj** [comment]
ah I see it now, `message-id` wasn't required in 0.3.2 for whatever reason. I'll open a PR to change that at some point - that's the kind of thing that shouldn't really be enforced.

**Comment by Huesdon** [comment]
Ok cool so I'm not crazy, I don't know what to put for that, can I just use a random integer like "1" ?

**Comment by haganbmj** [comment]
yeah any value would work. it's for matching up which response goes to which request. So if you send 1 you'll get a message back with that same id.

**Comment by Huesdon** [comment]
oh ok, gotcha. Awesome thank you.  :)

**Comment by haganbmj** [comment]
![](https://i.imgur.com/oBmjy7T.png)

On mobile or I'd link it.
