### ISSUE TITLE
OBS crash on second sent message

### ISSUE THREAD

**Issue by flash0110** [Palakis/obs-websocket#15]
OBS (32 and 64bit) crashes whenever I send a second message.

Steps to reproduce the crash:
- start OBS with enabled obs-websocket
- go to [http://www.websocket.org/echo.html](http://www.websocket.org/echo.html)
- enter correct location (`ws://localhost:4444`)
- press Connect
- enter into Message field: `{"message-id":"1","request-type":"GetSceneList"}`
- press Send
- correct answer is received:
`RECEIVED: { "current-scene": "Scene 1", "message-id": "2", "scenes": [ { "name": "Scene 1", "sources": [ { "cx": 1920.0, "cy": 1080.0, "name": "Image", "render": true, "type": "image_source", "volume": 1.0, "x": 0.0, "y": 0.0 } ] }, { "name": "Scene 2", "sources": [ { "cx": 1920.0, "cy": 1080.0, "name": "Image 1", "render": true, "type": "image_source", "volume": 1.0, "x": 0.0, "y": 0.0 } ] } ], "status": "ok" }`
- press Send again (changing the message-id to 2 doesn't change anything)
- OBS crashes with the following error:

```
Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	obs64.exe
  Anwendungsversion:	0.0.0.0
  Anwendungszeitstempel:	5831e36c
  Fehlermodulname:	StackHash_571a
  Fehlermodulversion:	6.3.9600.18438
  Fehlermodulzeitstempel:	57ae642e
  Ausnahmecode:	c0000374
  Ausnahmeoffset:	PCH_03_FROM_ntdll+0x0000000000090C6A
  Betriebsystemversion:	6.3.9600.2.0.0.144.8
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	571a
  Zusatzinformation 2:	571a82f8f669fe6504f96cd83e647d6c
  Zusatzinformation 3:	fbfe
  Zusatzinformation 4:	fbfe6d11217e4e4d97ba18df8e2619c0

```

When I click debug VisualStudio tries to open the following file: `obs2\deps\w32-pthreads\pthread_mutex_trylock.c`

**Comment by haganbmj** [comment]
Tried this as well.

- First with 1 scene, sent two requests, both succeeded. Closed OBS successfully.
- Secondly with 1 scene, sent five requests, all succeeded. Closed OBS successfully.
- Third with 3 scenes, sent three requests, OBS crashed on request. Also deleted all my inactive scenes.
- Fourth with 3 scenes, sent three requests counting to 5 between each request, OBS crashed on request. Deleted all my inactive scenes.

I suspect it's just related to https://github.com/Palakis/obs-websocket/issues/12

**Comment by haganbmj** [comment]
Updated to https://github.com/Palakis/obs-websocket/releases/tag/0.3.1
Not encountering crashes using the same test pattern as in my previous post.

**Comment by flash0110** [comment]
Agreed. Just tested it as well and no more crashes.
