### ISSUE TITLE
Feature Request: Audio level monitoring (vu meter)

### ISSUE THREAD

**Issue by dblanco215** [Palakis/obs-websocket#152]
##### Issue type
Feature request

##### Description
Sometimes, the OBS lost the audio in the scene, and I must to reset the scene to recover the audio channel. Are there any way to check if I have any audio level in the scene to automate the scene reset?

##### Technical information
- Windows 10
- OBS 20
- OBS-WebSocket 4.20

**Comment by TStod** [comment]
Can you clarify if this is a bug in OBS that you are trying to mitigate with obs-websocket?

If so definately file a bug with the obs-studio project with a reproduction case if possible!

**Comment by dblanco215** [comment]
Thanks for your response!
I sent a request to the OBS team about the audio issue, but I want to ask with the OBS-WebSocket the audio input level for some reasons, like check if the audio input level of a source it's too high or if there aren't any audio entrace in a source.

Best regards and many thanks for your help.

**Comment by karlthepagan** [comment]
I sometimes experience a similar issue with USB devices disconnecting. Most often this is a hardware bug or a camera has gone to sleep. I would find this feature useful for monitoring my system health.

**Comment by suryaprasad7500** [comment]
Anyone working on this issue?

**Comment by tt2468** [comment]
Planned for 5.x

**Comment by Mr-Mmhhmm** [comment]
Is this currently functional? I see the "InputVolumeMeters" event listed in the docs, and wrote some code to subscribe to it, but it doesn't seem to get hit, or throw any errors...

`const obs = new OBSWebSocket();

$(window).on("load", function () {
	obs.connect(undefined, "password").then((res) => {
		console.log(res);
	}, (error) => {
		console.error(error);
	});

	obs.on("InputVolumeMeters", (data) => {
		console.log(data);
	});
});`

**Comment by Miniontoby** [comment]
@Mr-Mmhhmm Try this:

```js
const obs = new OBSWebSocket();

obs.connect(undefined, "password", { eventSubscriptions: OBSWebSocket.EventSubscription.All | OBSWebSocket.EventSubscription.InputVolumeMeters }).then((res) => {
	console.log(res);
}, (error) => {
	console.error(error);
});

obs.on("InputVolumeMeters", (data) => {
	console.log(data);
});
```
