### ISSUE TITLE
Unable to distinguish between duplicate items in a scene for all current and future applicable methods

### ISSUE THREAD

**Issue by TStod** [Palakis/obs-websocket#154]
##### Issue type
Feature Request / Brainstorm

##### Description
Duplicate scene items have the same name so it is impossible to change get or set properties of each duplicate other than the first.

Possible implementations:
- Integer indicator for instance of a scene item with the same name
- Integer indicator for position of an item in a scene
- ID of the item (unique and persisting through restart ideally)

@haganbmj thoughts/feeback?

**Comment by TStod** [comment]
@Palakis would love to hear you thoughts on this as well.
This is pseudo blocking for all the features I am working on at the moment.

**Comment by haganbmj** [comment]
Are there any identifiers exposed by obs that could be used?

**Comment by TStod** [comment]
Each scene item has an `<int64_t>` `id` which is unique for a given scene. Each scene has a local counter that is incremented when scene items are added. I don't think that duplicate scenes will have matching IDs if at some point sources were reordered or removed in the original scene.

This `id` seems sufficient for solving our issue here.

Ids do not change when scene items names change. Names are still useful for telling what sources are duplicates by reference, thus sharing a common source.

OBS has an exposed method `obs_sceneitem_get_id` which we could use in a utils function `Utils::GetSceneItemFromId` (basically by abstracting or copy pasting the logic)

I am verifying if `id`s persist through OBS restart.

**Comment by TStod** [comment]
`id`s persist through restart as expected.

It is worth noting that names are the `id`s of sources and are unique. This includes scenes, sources, filters, etc. (NOT scene items)

**Comment by TStod** [comment]
This means `id`s are directly relevant for all scene item specific methods and indirectly related to other methods.
Some (probably not all) directly relevant methods.

Requests:
- `GetSceneList`
- `GetCurrentScene`
- `SetSceneItem*`
- `GetSceneItem*`
- `SetSceneItemOrder` WIP
- `DuplicateSceneItem` WIP
- `DeleteSceneItem` WIP

Events:
- `SourceOrderChanged`
- `SceneItem*`
- `SwitchScenes`

**Comment by Palakis** [comment]
> It is worth noting that names are the ids of sources are unique.

Sources don't have an ID. A source's name is its unique identifier. However, the "id" of a source (got from obs_source_get_id, for instance) is its kind ("browser_source", "media_source", etc).

**Comment by Palakis** [comment]
What about functions to can resolve scene items to and from a specific unique name?
Something in this syntax: `<url-encoded scene name>::<scene item ID>::<url-encoded scene item name>`.
Examples: "Waiting%20Screen::16::Video%20Loop", "Scene1::11::Background"

**Comment by TStod** [comment]
@Palakis for scene item related functions I will default to using `id` and verifying `name` matches if it is specified. If no ID is specified I will use name and verify there are no collisions if it would be of detriment (such as order changing).

This would mean that reordering scenes request would be literally reordering the objects returned with `GetSceneList` and then sending them back in the new order as part of the `SetSceneItemOrder` request

**Comment by Palakis** [comment]
So.
As I messed up with `master` last year and messed up while backporting changes to `4.x-current`, I don't know if the changes from #164 are still there 🤦‍♂ 
Hence the "investigation needed" label.

**Comment by rickyrombo** [comment]
I don't think these changes are still present. I made a draft PR to carry the changes from the original PR to the project. @TStod could you drive the relanding of your PR? I don't have any experience working with this project, but if needed I can try to start familiarizing myself.

**Comment by Palakis** [comment]
Thanks. I'll take care of it.
