### ISSUE TITLE
Mac obs-websocket not reporting when port already in use

### ISSUE THREAD

**Issue by reedog117** [Palakis/obs-websocket#156]
##### Issue type
Bug

##### Description
obs-websocket for Mac does not output an error message when the listening port (4444) is already taken, even with debug enabled. This makes it a pain to troubleshoot why apps like http://t2t2.github.io/obs-tablet-remote don't work. Not sure if this issue also exists with other operating systems.

##### Steps to reproduce and other useful info
Run any service on the same port that obs-websocket is configured to listen on, and then startup OBS. The below log output will appear but nothing about the port already being taken. The only way I could figure this out was closing OBS, running netstat, and seeing that some other process was still listening on 4444.

Pertinent log entries
```
14:52:44.439: [obs-websocket] you can haz websockets (version 4.2.1)
14:52:44.439: [obs-websocket] qt version (compile-time): 5.9.2 ; qt version (run-time): 5.9.2
14:52:44.444: [obs-websocket] module loaded!
```

##### Technical information
- **Operating System** : MacOS 10.13.1
- **OBS Studio version** : 20.1.0
- **obs-websocket version**: The newest build mentioned in #105

**Comment by Palakis** [comment]
Should be fixed in the latest commits. Can provide a built binary if needed.

**Comment by UnivateBV** [comment]
Nice work, may i ask for a mac binary?
Thanks

**Comment by aliksend** [comment]
+1 for mac release

**Comment by Palakis** [comment]
@UnivateBV @aliksend you mean of the latest dev build?

**Comment by aliksend** [comment]
@Palakis I mean the .pkg package to install without building from source

**Comment by Palakis** [comment]
@reedog117 @UnivateBV @aliksend version 4.3.1 has been released on Jan 22. Can one of you test this release and report if this bug still happens?
