### ISSUE TITLE
More details for SourceOrderChanged event

### ISSUE THREAD

**Issue by iarspider** [Palakis/obs-websocket#168]
##### Issue type
[x] Feature request?

##### Description
More details for SourceOrderChanged event

##### Steps to reproduce and other useful info
Please add "sources" field to SourceOrderChanged event (the same as in SwitchScenes event) so that users won't have to re-request the order of sources when this event is fired.

**Comment by TStod** [comment]
I agree that this is important and will try to add it with my scene item ID refactor https://github.com/Palakis/obs-websocket/pull/164

**Comment by TStod** [comment]
This method should probably be renamed to `SceneItemORderChanged`. Simillarly the key `sources` in the response that I have added should be changed to `sceneItems`.
