### ISSUE TITLE
Obs Remote on Streamlabs OBS?

### ISSUE THREAD

**Issue by Weedyx** [Palakis/obs-websocket#174]
##### Issue type
 Feature request

##### Description
Streamlabs realeased the version of obs called streamlabs obs... i wrote with a staff member of streamlabs and they said i need to talk you. so i write you because streamlabs and me would love to get obs remote going on streamlabs obs.

Grettings 

Weedyx346 aka. Kevin Schwindling

**Comment by Palakis** [comment]
Done a quick technical analysis of SLOBS. Here what I found:
- obs-frontend-api (a component of OBS Studio) is mandatory to have access to obs-websocket settings. SLOBS has a special implementation of obs-frontend-api which does... nothing. Folks at Streamlabs should at least implement this to give plugins the ability to give access to user interfaces.
- OBS Studio relies on Qt for UI, and so does obs-websocket. SLOBS is an HTML5 interface running in Electron, a modified Chromium for desktop apps, and does include nor provide Qt.
- OBS Studio is built with Visual Studio 2013, SLOBS is built with Visual Studio 2015. Although this isn't a major showstopper, tricky bugs could appear when mixing compiler versions.

Conclusion: SLOBS is a good peace of engineering, and a nice software for beginners, but I have no plans right now to support SLOBS unless Streamlabs does an effort to provide a bit of compatibility with existing OBS Studio plugins. If more OBS Studio derivatives are to come in the future, Streamlabs should set an example for these.

**Comment by Weedyx** [comment]
Okay thanks for the quick answer and sorry for my bad englisch …iam German. But i try to do my best get this going with streamlabs and write them what you wrote me with hopes to good Things will happen :D

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Stéphane L. <notifications@github.com>
Gesendet: Saturday, January 6, 2018 1:17:16 PM
An: Palakis/obs-websocket
Cc: Weedyx; Author
Betreff: Re: [Palakis/obs-websocket] Obs Remote on Streamlabs OBS? (#174)


Done a quick technical analysis of SLOBS. Here what I found:

  *   obs-frontend-api (a component of OBS Studio) is mandatory to have access to obs-websocket settings. SLOBS has a special implementation of obs-frontend-api which does... nothing. Folks at Streamlabs should at least implement this to give plugins the ability to give access to user interfaces.
  *   OBS Studio relies on Qt for UI, and so does obs-websocket. SLOBS is an HTML5 interface running in Electron, a modified Chromium for desktop apps, and does include nor provide Qt.
  *   OBS Studio is built with Visual Studio 2013, SLOBS is built with Visual Studio 2015. Although this isn't a major showstopper, tricky bugs could appear when mixing compiler versions.

Conclusion: SLOBS is a good peace of engineering, and a nice software for beginners, but I have no plans right now to support SLOBS unless Streamlabs does an effort to provide a bit of compatibility with existing OBS Studio plugins. If more OBS Studio derivatives are to come in the future, Streamlabs should set an example for these.

**Comment by ChrisM-Rogers** [comment]
This would be pretty good to have. Though I too find it irritating that they decided to use Electron. But we'll save that (graphical) glitch for another day.

And I couldn't agree more with @Palakis comment. You'd have thought they'd keep compatibility with existing OBS plugins, considering the vast quantity of plugins available to use. Terrible choice of route in my honest opinion, but there will always be one of them in every community.

**Comment by Palakis** [comment]
SLOBS has its own WebSockets API now. Closing this.
