### ISSUE TITLE
windows remote control with obs websocket

### ISSUE THREAD

**Issue by huitre39** [Palakis/obs-websocket#175]
Hello i download obs studio for remote control my pc.
I'm in windows 10 pro 64bits.

1) I downloaded OBS Studio 64bits and i install this software
2) I downloaded and installed OBS Websocket
https://github.com/Palakis/obs-websocket
3) I enable websocket server
4) I connect to my websocket server with this client:
http://t2t2.github.io/obs-tablet-remote/
i start with localhost and 4444 port number. Connection to my obs websocket server is work.
But i have not screen of my computer why ?
![obs](https://user-images.githubusercontent.com/22101022/34720247-4b7e8d36-f53e-11e7-8746-4693b33da2ac.jpg)

why my browser have white screen ? 
thanks for advance for your help

**Comment by Palakis** [comment]
@huitre39 Hi, thanks for using obs-websocket and t2t2's control app!
The plugin and control apps are only meant to control OBS Studio, not showing any preview video of some sort.
If you'd like to have a second preview window, open a preview projector in OBS. If you'd like to have a live OBS video feedback on a separate computer, have a look at the obs-ndi plugin.
