### ISSUE TITLE
Feature Request: Scene Item Preview Image / Thumbnail

### ISSUE THREAD

**Issue by Acenth** [Palakis/obs-websocket#178]
##### Issue type
Feature Request

##### Description
Add API to get preview of scene item. It would be great if we could access a preview / thumbnail of scene items and even entire scenes.

**Comment by ethaniel** [comment]
This is an amazing thing actually! We use OBS for a remote webcamera and sometimes our HDMI feed dies. It would be cool if we could get a thumbnail remotely. This way we could compare it with a previous thumbnail and if there are no changes, then perform a HDMI reset procedure.

**Comment by filippsudanov** [comment]
There's a possible workaround for this - with NDI plugin you can stream your inputs as NDI. Then you can use ffmpeg (compiled with NDI support) to capture one frame of the stream as image like this:
`ffmpeg -f libndi_newtek -i 'NDI_STREAM_NAME' -vframes 1 -y image.bmp`
this way ffmpeg exits after it captures the frame, and it takes some time for it to startup and find the stream, before the frame is captured.

I also tried it in that way:
`ffmpeg -f libndi_newtek -i 'USER-DESKTOP (Camera1)' -vf fps=0.5 -update 1 -y out.png`
then ffmpeg captures the frames without exiting (1 frame every 2 seconds), but, unfortunately, it takes much more CPU then the first way (tested with ffmpeg version N-91567-g076b196)

**Comment by iBobik** [comment]
I saw web app sending IP camera image over websockets and it performed pretty well for image like 600:400 px. I thing if it will stream something like 200:120 px it will be able to do pretty good FPS and could have much lower latency than RTMP.

**Comment by Palakis** [comment]
Fixed by #313, gonna be released with 4.6
