### ISSUE TITLE
Feature request: Create new scene items

### ISSUE THREAD

**Issue by NickAcPT** [Palakis/obs-websocket#179]
##### Issue type
Feature request

##### Description
My request is to add the feature to create new scene items (image; browsersource; text) and add them to a scene.

##### Technical information
- **Operating System** : Windows 8.1
- **OBS Studio version** : 20.1.3

**Comment by Palakis** [comment]
That definitely would be a nice addition!

**Comment by eyalcohen4** [comment]
Does someone work on this? can I help somehow?

**Comment by miaotmac** [comment]
Does any update?
