### ISSUE TITLE
SwitchScenes event: scene name is empty in studio mode

### ISSUE THREAD

**Issue by t2t2** [Palakis/obs-websocket#18]
Gfy: https://gfycat.com/UniqueCoordinatedBrant

On every scene change the event is `{ "scene-name": "", "update-type": "SwitchScenes" }`

**Comment by Palakis** [comment]
This seems specific to Studio mode, didn't checked that one.

**Comment by Palakis** [comment]
The issue has been fixed in the latest commit. I'll make a new binary release in the coming days if no other bugs are discovered.

**Comment by Palakis** [comment]
The latest binary release is out !
