### ISSUE TITLE
Feature request: Control OBS Scripts

### ISSUE THREAD

**Issue by lebaston100** [Palakis/obs-websocket#180]
##### Issue type
Feature request

##### Description
It would be a nice additon, now with the release of obs 21 to work out some sort of way to control scripts(Start, Pass information).
I'm not into the obs source code so no idea how this can be done technically, but there is already a scripting function to register a hotkey: https://obsproject.com/docs/scripting.html#obs_hotkey_register_frontend

**Comment by tt2468** [comment]
This can now be done via #595 's requests.
