### ISSUE TITLE
Problem with the event PreviewSceneChanged

### ISSUE THREAD

**Issue by illusdidi** [Palakis/obs-websocket#181]
##### Issue type
Event not triggered ?

##### Description
Hi,
I think there is a bug with the event PreviewSceneChanged. When I switch the preview scene on studio mode in OBS, the event is correctly triggered. Here is what the websocket connexion receives :
`{ "scene-name": "1_Intro", "sources": [], "update-type": "PreviewSceneChanged" }`
But when I switch the preview scene on my webpage using obs-websocket-js, the preview scene is switching but the event is not triggered and the websocket connexion receives nothing.

And when I switch the current live scene on my webpage, the event PreviewSceneChanged is triggered because the websocket connexion receives these 3 messages :
`{ "transition-name": "Coupure", "update-type": "SwitchTransition" }`
`{ "scene-name": "1_Intro", "sources": [], "update-type": "SwitchScenes" }`
`{ "scene-name": "4_End", "sources": [], "update-type": "PreviewSceneChanged" }`

(I hope that is clear)

##### Steps to reproduce and other useful info
I used http://www.websocket.org/echo.html to track the websocket messages.

##### Technical information
- **Operating System** : Windows 10 Home x64 16299.125
- **OBS Studio version** : 21.0.1

**Comment by Lange** [comment]
I can confirm that I am seeing this issue on obs-websocket v4.3.0 and up, but it is still okay on v4.2.0.

**Comment by Palakis** [comment]
It's that bit of code: https://github.com/Palakis/obs-websocket/blob/master/src/WSEvents.cpp#L83-L85
`PreviewSceneChanged` is bound to the UI event... And I guess signals are disabled when the core manipulates this list.

**Comment by illusdidi** [comment]
Do you plan to fix it? 
Or is there a way to get around? 🙂

**Comment by Palakis** [comment]
@illusdidi Gonna have a look at it this week.

**Comment by illusdidi** [comment]
cool, thank you !

**Comment by Palakis** [comment]
@haganbmj It's not in master, unfortunately. Gonna try this anyway to see if it fixes the issue.

**Comment by haganbmj** [comment]
Yeah, it's on the horizon at least. Hopefully that's enough to solve most of these issues.

**Comment by Palakis** [comment]
`jimtree` fixes the issue. Prepared an according fix: https://github.com/Palakis/obs-websocket/commit/87437d3c643c354bfea0879224a06956af9c07c0

**Comment by haganbmj** [comment]
Nice, that'll be good once it's ready.

**Comment by illusdidi** [comment]
Thank you so much for fixing this bug. :D

**Comment by haganbmj** [comment]
Took a while, but it's in obs 22 now.
