### ISSUE TITLE
OBS 21 hangs during scene collection change with websockets.so installed

### ISSUE THREAD

**Issue by narcogen** [Palakis/obs-websocket#182]
Issue Type
Bug Report (sort of-- just a notice of incompatibility with new OBS)

Description
OBS becomes unresponsive or crashes with the plugin installed.

Steps to reproduce
With Websockets installed, launch OBS 21. Create a new scene. Switch back to previous scene. OBS becomes unresponsive and must be forcibly quit.

OBS Logfile (does not appear to show any problem happening)
https://pastebin.com/FH1aeegS

Technical Information
Ubuntu 17.10
OBS 21.0.1

**Comment by dodgepong** [comment]
Are you on the [latest release](https://github.com/Palakis/obs-websocket/releases/tag/4.3.1)? It came out specifically to fix this problem.

**Comment by narcogen** [comment]
Yes.

**Comment by narcogen** [comment]
Well, I'm an idiot-- looks like I thought I had the latest and instead had just uninstalled and reinstalled the old version.

Looks like the crash is not happening in 4.3.1-1.
