### ISSUE TITLE
Server-side datastore

### ISSUE THREAD

**Issue by eropple** [Palakis/obs-websocket#184]
##### Issue type
Feature request (and implementation discussion; I'm happy to do the work)

##### Description
I use multiple endpoints to control my OBS instances via obs-websocket--I have a few different tablets available to different people, on camera and off, for flipping between scenes. However, as I start looking to add some configuration and some options to my tooling outside of just modifying the running state of the application it's becoming evident that I need a place to store data that all my clients can access. I can totally do something with Dropbox or some other out-of-band store--but it probably makes sense for it to just be on the box so that any client with the password can connect to it and just be done with it. I kind of just envision a "obs-websocket.json" file in %appdata% or the like where individual tools can define their own top-level key, i.e. mine would be "StreamCopilot", and just provide something like a [jsondiffpatch](https://github.com/benjamine/jsondiffpatch) or even a jsonpath to setting a particular key with a value. That way, a client just has to connect to OBS and all of the dedicated programmed settings for their hotkeys, etc. work on every client they want to use. I'm sure other folks using obs-websocket probably have a use for it too.

I am happy to do the legwork to implement this feature if we can nail down what it should look like, as this would be _super_ helpful to me and I'd love to contribute.

**Comment by haganbmj** [comment]
I'm confused. So you want just want to expose a json to every client?

**Comment by eropple** [comment]
Effectively, yeah. There are per-server settings that the new features in the [client I've built](https://play.google.com/store/apps/details?id=com.tracecomplete.streamcopilot.obs) can use. I can either build a remote sync thing (which requires an Internet connection--ugh) or I can have OBS be the canonical store of OBS-related stuff that the clients use. The latter seems to make a lot more sense to me.

**Comment by tt2468** [comment]
Planned for 5.x
