### ISSUE TITLE
System Tray Alerts don't fail gracefully.

### ISSUE THREAD

**Issue by brandonllocke** [Palakis/obs-websocket#189]
##### Issue type
Bug Report

##### Description
I'm running an ultra minimalist window manager (openbox) without a system tray or notification system for potential use in an embedded situation. If "Enable System Tray Alerts" is checked, I get a crash and segmentation fault when an alert is triggered. This issue took me a long time to track down. If I run on a "fuller" desktop environment like lxde or xfce, no crash happens likely because a system try and notification system are installed. If I disable "Enable System Tray Alerts" on my ultra minimalist wm, I do not get a crash either. It seems that should be something that fails gracefully, correct?

##### Steps to reproduce and other useful info
1.) Install system without system tray or notification system.
2.) Install OBS Studio via Ubuntu PPA.
3.) Install OBS-Websockets via deb release on github page.
4.) Leave all settings at default (including "Enable System Tray Alerts")
5.) Attempt to connect via any connector, remote, or programming language (tested t2t2, obs-remote, and obs-websocket-py).
6.) OBS crashes with a segmentation fault upon "successful connection" to websocket.

Log: https://gist.github.com/3c8c848d41be5a0882c7135a61e94979

##### Technical information
Ubuntu Server 16.04.3
OBS 21.0.1 & 20.1.3

**Comment by Palakis** [comment]
@brandonllocke Can you provide the crash stack trace as well, please?

**Comment by brandonllocke** [comment]
Forgive my ignorance, how would I get that?

**Comment by Palakis** [comment]
@brandonllocke Nevermind, I think I found a fix. Can be please test the following build and tell me if the crash still happens when notifications are enabled and no system tray is available? http://obs-websocket-linux-builds.s3-website.eu-central-1.amazonaws.com/obs-websocket_1-7fdace9-master-git-1_amd64.deb

**Comment by Palakis** [comment]
Fix tested on my end. All good. Closing this.
