### ISSUE TITLE
Authentication Password isn't saved between OBS restarts

### ISSUE THREAD

**Issue by 2press** [Palakis/obs-websocket#193]
##### Issue type
Bug

##### Description
Authentication Password isn't saved correctly. Thus after restarting OBS the password is no longer valid. I tried to reinstall from scratch as well as version 4.3.1 and 4.3.0. But I didn't have this problem previously with version 4.3.0.

##### Technical information
- **Operating System** : Windows 64 Bit.
- **OBS Studio version** : 21.0.1 64-Bit

**Comment by dx9s** [comment]
I've discovered the issue.. a "Control-Z" is added to the end of the config.ini file!

For LINUX it is ~/.config/obs-studio/config.ini :+1: 


[WebsocketAPI]
...
AuthSecret=[....]zlk=^Z
AuthSalt=[...]XHEY=^Z

Remove the Control-Z (last character from each line) and the new password will be accepted. Must be a bug in stringing the Secret/Salt that was introduced.

I can poke at the diff from 4.3.1/0 and prior to see what changes occurred (I don't know the source code). If I find a fix and make a patch.. I'll try to get back to it, but suspect Palakis might fix this before then. Seems pretty simple.

--Doug (dx9s)

**Comment by dx9s** [comment]
Found ruffly where it is:

https://github.com/Palakis/obs-websocket/commit/66a059ecdfc935001f32b2d2e4a34e32e848411a#diff-cb079b850c3588a5bdc77fc7e298194eR64

**Comment by dx9s** [comment]
I am not sure what qstring_data_copy does():

used to be:
-    config_set_string(obs_config, SECTION_NAME, PARAM_SECRET, Secret);
-    config_set_string(obs_config, SECTION_NAME, PARAM_SALT, Salt);

now:
+    config_set_string(obsConfig, SECTION_NAME, PARAM_SECRET,
+        qstring_data_copy(Secret));
+    config_set_string(obsConfig, SECTION_NAME, PARAM_SALT,
+        qstring_data_copy(Salt));


--Doug (dx9s)

**Comment by dx9s** [comment]
see it here: Utils.cpp :

```
const char* qstring_data_copy(QString value) {
    QByteArray stringData = value.toUtf8();
    const char* constStringData = new const char[stringData.size()]();
    memcpy((void*)constStringData, stringData.constData(), stringData.size());
    return constStringData;
}
```

Not sure if you want to actually convert base64-like data into UTF .. that can damage the data. I'd recommend rolling it back, but the types went from char * to QString .. would need to look further is "Salt" and "Secret" is the binary form, base64-like form, or what. It effects on where you should do any "UTF-ness" to it or not.

--Doug (dx9s)

**Comment by Palakis** [comment]
@dx9s Thanks for the investigation! That's a very nasty bug...

**Comment by Palakis** [comment]
I guess this has something to do with `constData()`. maybe `data()` doesn't have that issue.

**Comment by dx9s** [comment]
@Palakis I think it might be const .. I did (and from memory) something along the following:
```
    //very hackish no each "size" ? or strlen equiv
    QChar* data = value.data();
    int size=0;
    while (!data->isNull()) {
        // data.unicode(); or something like this -- printed out the number and this appeared good!
        data++;
        size++;
    }
```

**Comment by dx9s** [comment]
wow.. still getting this (hackish to simple step debug closer) same output:

```
obs-websocket [SettingsDialog::FormAccepted Password Set]:test123
obs-websocket [qstring_data_copy_test value]:bplRFv+PaoXp0VOCZ5kxKTFrRlHoSdzyJ0kZVZpRg0Y=
obs-websocket [qstring_data_copy_test constStringData]: bplRFv+PaoXp0VOCZ5kxKTFrRlHoSdzyJ0kZVZpRg0Y=
obs-websocket [qstring_data_copy_test value]:4tKDXc0N0FzncgsBcfXtQP6C3sUqgcOVQB3JMkFKY4c=
obs-websocket [qstring_data_copy_test constStringData]: 4tKDXc0N0FzncgsBcfXtQP6C3sUqgcOVQB3JMkFKY4c=

```


Using this function (also updating Utils.h to prototype correctly):
```
const char* qstring_data_copy(QString value) {
    QByteArray stringData = value.toUtf8();
    const char* constStringData = new const char[stringData.size()]();
    memcpy((void*)constStringData, stringData.constData(), stringData.size());
    return constStringData;
}

char* qstring_data_copy_test(QString value) {
    QByteArray stringData = value.toUtf8();

    qDebug("obs-websocket [qstring_data_copy_test value]:" + value.toUtf8() );

    //very hackish no each "size" ? or strlen equiv
    QChar* data = value.data();
    int size=0;
    while (!data->isNull()) {
        data++;
        size++;
    }

    char* stringDataOut = new char[size]();
    //memcpy((void*)stringDataOut, stringData.data(), size);

    int x;
    data = value.data();
    size=0;
    while (!data->isNull()) {
        x = data->unicode();
        stringDataOut[size]=(char)x;
        data++;
        size++;
    }

    fprintf(stdout, "obs-websocket [qstring_data_copy_test constStringData]: %s\n", stringDataOut);

    return stringDataOut;
}


```

**Comment by dx9s** [comment]
The bug is either in new /const/ char[size]();

or QChar/QByteArray/QString conversions

**Comment by dx9s** [comment]
```
    size=6;

    char* stringDataOut = new char[size]();
    //memcpy((void*)stringDataOut, stringData.data(), size);

    //int x;
    //data = value.data();
    //size=0;
    //while (!data->isNull()) {
    //    x = data->unicode();
    //    stringDataOut[size]=(char)x;
    //    data++;
    //    size++;
    //}
    stringDataOut[0]='H';
    stringDataOut[1]='e';
    stringDataOut[2]='l';
    stringDataOut[3]='l';
    stringDataOut[4]='o';
    //stringDataOut[5]=0;
```

with and without setting last character \[5\] to zero (null, end of string) it printed out fine.. so just need to work around this and NOT allow control-z through (for now).. a dirty work around?!

Should I fork and submit patch from fork for a working workaround ?!

**Comment by dx9s** [comment]
Have this out there... 

https://github.com/Palakis/obs-websocket/pull/196 -- It might not be the best solution / workaround ?!

**Comment by Palakis** [comment]
@dx9s Can you test the changes introduced in https://github.com/Palakis/obs-websocket/commit/e168b78cc13cb0a44d4bb32c795eae2b3e884eb9, please?

**Comment by dx9s** [comment]
checked out 7fdace9b79759ef9d558b5d6f00b1677f2338612 and it seems to have fixed the stringing issue..

Still seeing memory leaks with JUST obs-websocket installed (also seeing memory leaks from obs-ndi).. I am not verse in gdb and debugging leaks and crashes / core-dumps.

Worried about the memory leaks (obs-websocket and obs-ndi) being (in related) to obs crashing and obs-ndi not working (sourcing video to OBS). Or what I saw in another issue about recent obs-websocket crashing in newer version of OSX .. probably something so subtle!

--Doug (dx9s)

**Comment by Palakis** [comment]
Fixed! Release coming soon.
