### ISSUE TITLE
obs-websocket memory leaks

### ISSUE THREAD

**Issue by dx9s** [Palakis/obs-websocket#197]
##### Issue type
Possible BUG

##### Description
Think inner-thread communication is causing memory leak

##### Steps to reproduce and other useful info
base OBS-STUDIO install (upon shutdown) profiler shows no memory leak, install obs-websocket and it has memory leak(s)

##### Technical information
- Ubuntu 16.04 and 17.10
- 21.0.1 (current)

##### Development Environment
If I compile myself on 17.10 I get messages during runtime indicating that one thread is trying to modify another thread in a way that is incorrect

**Comment by dx9s** [comment]
Questions
* Is there no problem with having memory leaks?
* Latest release for https://github.com/Palakis/obs-websocket/releases/tag/4.3.2 Linux is for 21.0.3 ?
* What release is supposed to work with 21.1.0 (Linux)? 
* Still get memory leak with 21.1.0 and 21.0.1 (current/previous Linux obs release) and 4.3.2, 4.3.1 ?

Just curious.

**Comment by pjmagee** [comment]
@dx9s  Do you still get leaks? I have the same problem it seems, I have software that automates connects/disconnects and slowly over time the machine just hogs up, everything ends up going to pagefile.sys.
