### ISSUE TITLE
SceneItem IDs not included in GetSceneList

### ISSUE THREAD

**Issue by TStod** [Palakis/obs-websocket#200]
##### Issue type
Bug

##### Description
SceneItem IDs are not reported in `GetSceneList` in current release build.
They are working when I build and run locally.

On the latest and greatest of obs-websocket and on 21.1.0 for obs-studio.

The line in question:
https://github.com/Palakis/obs-websocket/blob/0e40342162ed97f977120a8e2397db11f89a8938/src/Utils.cpp#L89

**Comment by TStod** [comment]
Perhaps it needs to be typecast `(int)` like source width and height are?

**Comment by Palakis** [comment]
@TStod the latest release 4.3.* doesn't include compatibility-breaking changes and is based off the `4.3-maintenance` branch. I plan to release SceneItem ID support along 5.0.0 and its other compat-breaking changes. In the meantime you can use the CI builds (installers are now automatically built on AppVeyor).

**Comment by Palakis** [comment]
P.S.: Latest `master` build here: https://ci.appveyor.com/project/Palakis/obs-websocket/build/master-589/artifacts

**Comment by TStod** [comment]
Awesome @Palakis thanks
