### ISSUE TITLE
Making a source visible from a script timer stops OBS-Websocket updates

### ISSUE THREAD

**Issue by JustinLove** [Palakis/obs-websocket#206]
##### Issue type
Bug Report (cross posted from OBS forum, not sure where things are going wrong)

##### Description
I've got a weird interaction going on. I've two types of extensions interfering with each other.

1. OBS-Websockets application that listens for StreamStatus messages and polls some information 
2. Lua Script where I am trying to move some of that functionality.

An operation in the script is causing updates to the websocket messages to cease arriving. Reconnecting the websocket works. I believe I've isolated the cause to making a source visible from within a script timer, see attached script.

##### Steps to reproduce and other useful info
See attached script.
[script-websockets-example.lua.txt](https://github.com/Palakis/obs-websocket/files/1860527/script-websockets-example.lua.txt)

I've been using [http://wondible.com/obs-mic-check/](http://wondible.com/obs-mic-check/) as the websocket client

##### Technical information
- **Windows 10** :
- **OBS Studio 21.1.0** :

**Comment by JustinLove** [comment]
I traced in a bit. OBS events are still happening and getting to pClient->sendTextMessage(message), but it is a bit of a black box from there.

**Comment by Palakis** [comment]
@JustinLove Seems fixed on the latest `4.x-current`. I think this is partly thanks to the new server backend that will be introduced in 4.6 and doesn't use Qt's WebSocket server.
