### ISSUE TITLE
Problem with GetSceneItemProperties

### ISSUE THREAD

**Issue by Fantmx** [Palakis/obs-websocket#208]
##### Issue type
Other

##### Description
First off, this has been a huge help to me writing for Twitch in C#. I have been able to get almost everything working. However I am having a lot of problems with Get and Set SceneItemProperties. I am sure it is how I am passing the request but I can't figure it out. I have read through all of the documentation I can find. I am using the dotnet/C# linked on the main page. I am continuously getting: 

> WebSocket.message|System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

I am trying to test changing a color box from visible to invisible.

This is the code I am using:
```
JObject item = new JObject();
item.Add("message-id", "1234");
item.Add("scene", "Intro");
item.Add("Item.name", "Color");
item.Add("Item.visible", false);
var response = _obs.SendRequest("SetSceneItemProperties", item);
```

Again looking through it I feel like I am not sending the correct information to SendRequest().

I am using SendRequest() because it appears the dotnet version of this will not be updated past 4.2 which does not include SceneItemProperties.

Thanks for any help!

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 21.1.0

**Comment by pantonvich** [comment]
I think your issue is that SetSceneItemProperties is for the unreleased 5.0.0 - but just a guess on my part - so you might need to use the 4.2.0 protocols

https://github.com/Palakis/obs-websocket/blob/master/docs/generated/protocol.md

**Comment by Fantmx** [comment]
Thanks. That helps to clarify things.

My initial problem was an error in the "message-id".

However this helps to clarify exactly what is being passed in. And it's now working!

**Comment by Fantmx** [comment]
I have one more question if you don't mind.  For something like item.position.alignment. How does that get passed in? If I just use "alignment" there is another property item.bounds.alignment that I would not want to change. So how do I distinguish between the two?

Thanks again

**Comment by pantonvich** [comment]
you might need to look at the code to see how its defined - for the SetTextGDIPlusProperties I set the font-size this way as size is a child of font:   $",\"font\":{{\"size\":{fontSize}}}"
