### ISSUE TITLE
Looking to Integrate with Elgato Stream Deck

### ISSUE THREAD

**Issue by Zackery** [Palakis/obs-websocket#209]
##### Issue type
Feature Request

##### Description
Hi there! I'm looking to integrate this with my Elgato Stream Deck so I can control both my gaming PC OBS (running NDI) and my streaming PC OBS scenes with my Stream Deck. That way I can control both instances of OBS with my Stream Deck (which can only be hooked up to one computer). I was wondering if there's any sort of API call I can point to, or even a link I can access to automatically change scenes if I were to trigger that web page? (Such as `?scene=scene1` or something along those lines.) The Stream Deck has support to [open a URL in the background](https://i.zelakto.tv/images/4mgK.png), so I can see this being totally possible. Thanks for your support!

**Comment by brabe** [comment]
Hi,

I'm currently working on a program that achieves what I think you are looking for it. It's not currently written for Windows, but should be easily transferred as it is written using the Xamarin.Mac framework in C# using much of the .NET Framework and OBS-WebSocket-NET plugin.

For example currently the server interprets everything following the address. Everything after "http://127.0.0.1/" as the command. The commands can be structured however you like and none of them actually pull a web page. For instance, "http://127.0.0.1/score/left/increase2/" will call a specific function that will increase the Left Score on the ScoreBug. All URLs for the server can be custom as they are just strings to the server. 

I think this achieves what you are looking for.

**Comment by twisted86** [comment]
Any updates on that program you were working on? Im trying to do the same thing the OP posted about.  Thanks.

**Comment by HeedfulCrayon** [comment]
This is what I planning on using:
https://ianmorrish.wordpress.com/2017/05/20/automating-obs-from-powershell-script/

**Comment by jwulf** [comment]
Streamdeck controlling OBS over websockets:

https://github.com/jwulf/obs-streamdeck/tree/master/src/obs
https://github.com/jwulf/obs-streamdeck/tree/master/src/stream-key
https://github.com/jwulf/obs-streamdeck/blob/master/src/mute-audio/mute-audio.controller.ts

**Comment by LanceLake** [comment]
Can someone translate that into a curl call that I can use to communicate with the websocket please?

**Comment by tt2468** [comment]
@LanceLake @Zackery 

If you are still interested, I've made a simple script in Python that exposes obs-websocket as a simple HTTP server (so you can use stream deck or whatever you want). See https://github.com/IRLToolkit/obs-websocket-http

**Comment by Talon876** [comment]
I was able to get this working using this [command line tool](https://obsproject.com/forum/resources/command-line-tool-for-obs-websocket-plugin-windows.615/).

I do all scene management on my gaming PC but I am using this to start and stop recordings. However, you can configure it to set the scenes as well. One thing that this doesn't do is hook back in to the Stream Deck to update the icons based on the state in OBS.

@tt2468 it looks like you just started working on that application, are you planning on integrating with a [Stream Deck library](https://github.com/abcminiuser/python-elgato-streamdeck) so you can get the current state of OBS and update icons on the Stream Deck? Or are you going to leave it as a pure http <-> websocket layer?

**Comment by tt2468** [comment]
@Talon876 I suppose I could look into building something to directly interface with the stream deck, but it would be separate from the project above.

**Comment by karlthepagan** [comment]
Since I have a stream deck I've also been looking at Bitfocus's Companion app, which already has an OBS-websocket module. Unfortunately it's very lean. I hope to make some contributions here: https://github.com/bitfocus/companion-module-obs-studio/

I don't know if this is what you're looking for because it is a competing Stream Deck implementation.

**Comment by spdermn02** [comment]
could move over to using [TouchPortal](https://touch-portal.com) it already has OBS websocket support built in (and can control OBS on another PC so if you use Gaming and Streaming PC setup it can handle OBS on the other PC no problem. That's how i have mine setup. All you need is an Android or iOS device to run the client and then your PC/Mac runs the app (server) to do all the work.

**Comment by tt2468** [comment]
Closing this question now as it is quite old. Please open a new issue if you still need help.
