### ISSUE TITLE
Removing from mac

### ISSUE THREAD

**Issue by ognjetina** [Palakis/obs-websocket#216]
##### Issue type
Other

##### Description
How can I remove it from mac... I have two instances installed and its failing to start obs now...

**Comment by Palakis** [comment]
@ognjetina The plugin is installed in `/Library/Application Support/obs-studio/plugins/obs-websocket`. Remove that folder and the plugin will be gone.

**Comment by ognjetina** [comment]
@Palakis I am not having plugins folder...

**Comment by ognjetina** [comment]
@Palakis thank you...
