### ISSUE TITLE
Problems building on Windows

### ISSUE THREAD

**Issue by TestRunnerSRL** [Palakis/obs-websocket#22]
I setup the solution and I can compile the project without errors. However I when try to add the DLLs in obs's plugin directory and try to run obs I get a number of errors like:

`The procedure entry point ?toUtf8@QString@@QEGBA?AVQByteArray@@XZ could not be located in the dynamic link library C:\Program Files (x86)\obs-studio\obs-plugins\64bit\obs-websocket.dll`

`The procedure entry point ?toLatin1@QString@@QEGBA?AVQByteArray@@XZ could not be located in the dynamic link library C:\Program Files (x86)\obs-studio\obs-plugins\64bit\QT5Network.dll`

I'm using Qt5.8 and building using VS2015 on Windows 10. Not sure what I'm doing wrong, but I assume that I am not building obs-websocket.dll properly even though I seem to compile without issue.

**Comment by Palakis** [comment]
Which version of OBS Studio are you using ? Does it works when using the binaries from this repo's "Releases" section ?

**Comment by TestRunnerSRL** [comment]
I'm using the latest code on the obs-studio repo which is 17.0.0. I also tried out 16.5 just in case and had the same results. Using the release binaries for obs-websocket works fine. It only fails when I try to built it myself.

Actually I found something out just now. My own build works of obs-sockets works with my build of obs-studio, but not with the release build of obs-studio. I'd still like to be able to get this to work with the obs release if possible.

**Comment by MakerTim** [comment]
Got the same error i suppose
http://i.imgur.com/X37yVIb.png
crashes on startup with this popup and directly after this dialog
http://i.imgur.com/CgEg5ck.png

Both about the Qt5WebSockets.dll

**Comment by TestRunnerSRL** [comment]
So I'm thinking that the issue might be the version of VS I'm building with. It might be that the release build of OBS is using VS2013 so I can't like DLLs from my VS2015 build. Not completely sure that's the issue, because I can't find any documentation on the OBS github on which version they used to build or if it matters. I'd rather not install VS2013 if I I can help it but I would like to be able to distribute the DLL without having to include all of OBS.

**Comment by MakerTim** [comment]
@TestRunnerSRL It looks like some method calling of the plugin to Qt5WebScockets that is mapped wrong
im a java dev, so i have no experience with dll's

but OBS is not using the dll itself so it seems like the one you providing is not the same version you use by yourself
> i could be totally wrong

**Comment by Palakis** [comment]
Qt 5.7 is currently the latest stable release and the one I currently use when building obs-websocket. Try building it with Qt 5.7 instead of 5.8.

**Comment by TestRunnerSRL** [comment]
Building with QT 5.7 seems to have fixed the issue, thank you
