### ISSUE TITLE
Any interest in having RecordStatus analogous to StreamStatus?

### ISSUE THREAD

**Issue by AdamSzofran** [Palakis/obs-websocket#222]
##### Issue type
Feature request

##### Description
Is there any interesting in extending the protocol to support sending recording status updates with the same type of data we can currently get for streaming status?

For example, for streaming status, we currently have:
```
/**
 * Emit every 2 seconds.
 *
 * @return {boolean} `streaming` Current streaming state.
 * @return {boolean} `recording` Current recording state.
 * @return {boolean} `preview-only` Always false (retrocompatibility).
 * @return {int} `bytes-per-sec` Amount of data per second (in bytes) transmitted by the stream encoder.
 * @return {int} `kbits-per-sec` Amount of data per second (in kilobits) transmitted by the stream encoder.
 * @return {double} `strain` Percentage of dropped frames.
 * @return {int} `total-stream-time` Total time (in seconds) since the stream started.
 * @return {int} `num-total-frames` Total number of frames transmitted since the stream started.
 * @return {int} `num-dropped-frames` Number of frames dropped by the encoder since the stream started.
 * @return {double} `fps` Current framerate.
 *
 * @api events
 * @name StreamStatus
 * @category streaming
 * @since 0.3
 */
void WSEvents::StreamStatus() { ... etc ...
```
What if we added something like this?
```
/**
* Emit every 2 seconds.
*
* @return {boolean} `streaming` Current streaming state.
* @return {boolean} `recording` Current recording state.
* @return {boolean} `preview-only` Always false (retrocompatibility).
* @return {int} `bytes-per-sec` Amount of data per second (in bytes) being recorded.
* @return {int} `kbits-per-sec` Amount of data per second (in kilobits) being recorded.
* @return {double} `strain` Percentage of dropped frames.
* @return {int} `total-recording-time` Total time (in seconds) since the recording started.
* @return {int} `num-total-frames` Total number of frames transmitted since the recording started.
* @return {int} `num-dropped-frames` Number of frames dropped by the encoder since the recording started.
* @return {double} `fps` Current framerate.
*
* @api events
* @name RecordStatus
* @category recording
* @since 5.0.0
*/
void WSEvents::RecordStatus() { ... etc ...
```
Perhaps it would be best to make the two types of status updates share the same payload instead of being only slightly different. Of course, backwards compatibility is an issue so maybe it's better to just introduce a new payload for `RecordStatus` and leave `StreamStatus` alone.

In any event, I have a prototype of this working on 64-bit Windows with matching changes to `obs-websocket-dotnet`. Let me know if there's interest in putting together a pull request. I haven't done anything to support the Javascript or Python bindings however.

**Comment by ntoff** [comment]
If this gets implemented, it'd be nice to also include the replay buffer info / status as per my request https://github.com/Palakis/obs-websocket/issues/183 since it'd be useful for things like the obs tablet remote to know whether the replay buffer is on or off when it first connects / page gets refreshed.

**Comment by AdamSzofran** [comment]
That's a good idea. I'll see if I can support replay status as well without too much fuss.

**Comment by ntoff** [comment]
I don't know how much more fuss it is to add to your own code, I just added the replay buffer status to the output of the stream status thing. It already give you the status of recording (true / false) so I figured that was just the generic obs status output place to be.

**Comment by AdamSzofran** [comment]
How does this look? I decided to leave the `StreamStatus` event alone to avoid breaking existing apps. Instead, I created three new events: `StreamingStatistics`, `RecordingStatistics`, and `ReplayBufferStatistics`. All three events share the same payload structure. 

https://github.com/AdamSzofran/obs-websocket/commit/52666d3f1390dc2a766d9469fa97f235e518448c

https://github.com/AdamSzofran/obs-websocket-dotnet/commit/a72f92fa89d5afff1d31371e8b0fa45f775e62e6

**Comment by ntoff** [comment]
I guess now we just wait. 

Though, if you're creating a new output event, why not just combine all of it into one overall ```ObsStatus``` (or similar) event where you could put *everything*? Does it have to be 3 separate events?

**Comment by AdamSzofran** [comment]
Well, there's nothing to wait for since my changes aren't in the form of a pull request yet. At this point I'm just hoping to get some feedback (like yours, thanks!). If people think these changes are on the right track then I'll make up a pull request to bug Stéphane 😄. One question I have is whether I'll need to port the changes to the Python and Javascript clients. If so, then I'll need help because I'm not fluent in those languages at all.

**Comment by AdamSzofran** [comment]
In answer to your question about having three events versus one event, I guess it could go either way. The reason I went with three events was because I personally only care about one or maybe two of them. 😄 Forcing everyone to consume data for all the output types seemed a bit heavy handed unless, of course, you wanted statistics for all three outputs to begin with.

**Comment by Lange** [comment]
I'm also interested in a `RecordingStatus` request.

**Comment by AdamSzofran** [comment]
Thanks @Lange. I'll try to find some time to clean up the code and submit a pull request.

**Comment by tt2468** [comment]
Added
