### ISSUE TITLE
TransitionBegin is not always emitted when transitioning to a scene with a Transition Override

### ISSUE THREAD

**Issue by alvancamp** [Palakis/obs-websocket#223]
##### Issue type
Bug report

##### Description
When transitioning to a scene with a "Transition Override", `obs-websocket` will not emit the `TransitionBegin` event.

##### Steps to reproduce and other useful info
1. Import this [`obswebsocket_bug.json`](https://gist.github.com/Lange/10c9b7a08e7aec6639b9caf0f60d2794) scene collection, which has two scenes. `Scene 1` has a Transition Override, `Scene 2` does not.
2. Transition as much as you like, and observe that the `TransitionBegin` event is not always fired when transitioning to `Scene 1`.

[Log file](https://hastebin.com/aladiyuded)

##### Technical information
- **Operating System** : Windows 10 x64
- **OBS Studio version** : 21.1.2 (64bit)

**Comment by Lange** [comment]
Confirming that this still happens as of the latest OBS 23 and obs-websocket 4.6.1. Have not tested with OBS 24 or any pre-release builds of obs-websocket.

**Comment by Palakis** [comment]
@Lange Could please test this with OBS v25 and the latest test build? https://dev.azure.com/Palakis/obs-websocket/_build/results?buildId=1125&view=artifacts&type=publishedArtifacts

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks
