### ISSUE TITLE
Request: add information about source and destination scenes to TransitionBegin event

### ISSUE THREAD

**Issue by Lange** [Palakis/obs-websocket#224]
##### Issue type
Feature request

##### Description
I would like the `TransitionBegin` event to include the names of the scenes involved in the transition (i.e., which transition is being transitioned from, and which one is being transitioned to).

##### Rationale
I have some code which needs to toggle the visibility of a few sources on a scene right before that scene is put live on PGM. The transitions are all stinger transitions so I have plenty of time to do this. However, the problem I'm running into is that it is difficult to always be 100% sure which scene is being transitioned to when I receive the `TransitionBegin` event.

**Comment by Lange** [comment]
Bumping priority on this. We currently have some race conditions at SGDQ that I don't think I can fix without this data being added to the `TransitionBegin` event. Any spare time that can be put towards this would be greatly appreciated.

**Comment by Palakis** [comment]
Done, implemented in edc0fed9e2b2cb96b394250ff493eff3c549edd9
