### ISSUE TITLE
[Enhancement] Allow user to change port.

### ISSUE THREAD

**Issue by enzanki-ars** [Palakis/obs-websocket#23]
Currently, there can only be one OBS window open at a time if I want to use this project.  I would love for there to be a feature allowing me to change the listen port for each window, and if possible, set it in the main OBS settings so it remains set for the specific profile.

**Comment by Palakis** [comment]
As this relates to the core of the plugin, I'll work on this after finding a solution to #21.

**Comment by Palakis** [comment]
Planning it for the next release. Will be implemented as a "restart-needed" functionality.

**Comment by Palakis** [comment]
Implemented. Will be fully working once #36 is closed.
