### ISSUE TITLE
Can't compile under Debian

### ISSUE THREAD

**Issue by aaarghhh** [Palakis/obs-websocket#230]
##### Issue type
Can't compile.

##### Description
I have download the last sources of obs to link correctly to libobs because i noticed that it try to locate that lib.
I followed the instruction you have provided but:

error: ‘obs_module_get_string’ was not declared in this scope
     obs_frontend_push_ui_translation(obs_module_get_string);

##### Technical information
Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

##### Development Environment
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
#

**Comment by shane-axiom** [comment]
@aaarghhh What was the problem?

**Comment by aaarghhh** [comment]
It was closed. Anyway I don't remember. 😓

**Comment by johnnypanrike** [comment]
Could we reopen this and find a solution? 

I also get the same error message when trying to compile.

**Comment by tt2468** [comment]
@johnnypanrike please open a new issue with your system info
