### ISSUE TITLE
Use websocket without OBS

### ISSUE THREAD

**Issue by Kelin2025** [Palakis/obs-websocket#234]
##### Issue type
Question

##### Description
Hi. Great plugin! I'm working on tool for streamers and thinking about opportunity to use websocket without OBS window opened. Any chances for that?

**Comment by jpietek** [comment]
+1 I guess that would require quite some changes in obs-studio itself. I've been trying to figure it out, but still no luck.

That would be nice to have a proper backend - frontend separation. Right now I had some problems with obs-studio holding the source references while keeping source names in QTLists (expecially the 2.2 version).

That makes source management via the websockets quite buggy. I guess that was the reason source add/remove was not implemented in plain obs-websocket @Palakis ?

**Comment by Bangybug** [comment]
You can rebuild OBS Studio and comment "show();" method calls out window-basic-main.cpp, also add "mainWindow->hide();" call in obs-app.cpp after "mainWindow = new OBSBasic();". This obs studio will start without any windows. You will only see a tray icon, if you double click it, it will open the main window.

I'm working my way towards detaching the UI in OBS Studio. It's not complete and is quite dirty actually.
https://github.com/Bangybug/obs-studio/ 

I do not know cmake, neither do I like it. So in my repository I have added obs2 visual studio project, which depends on the core obs project that cmake will generate for you. In my project I have a BroadcastWindow class that implements my interface IMainWindow. 

In obs-app.cpp you can control whether to use OBSBasic default window class or my BroadcastWindow:
	mainWindow = new BroadcastWindow(0);
//	mainWindow = new OBSBasic();

Right at the moment, my BroadcastWindow looks empty. It initializes obs core and creates a default scene. Actually I wanted to have my own app that starts streaming "programmatically", without all the UI and configs. I'm going to check if websocket plugin will work with my BroadcastWindow implementation.

**Comment by Kelin2025** [comment]
@Bangybug sounds interesting. I sent the message to your mail, can we contact?

**Comment by jpietek** [comment]
@Bangybug looks interesting, thanks. For my use case it would be enough to run the OBS MultiviewWindow instead of the whole OBSBasic, but I'm not sure if it's possible to run just the Multiview Projection or is it tied up in the code to OBSBasic. Right now I just cover the Basic Window with the fullscreen Multiviewer, it works, but needs ugly workarounds, as the basic windows still blocks some source operations.

**Comment by tt2468** [comment]
Closing this since it's more of a request for OBS and not obs-websocket. I will say that in the future we will likely not support headless versions of OBS unless they are made by OBSProject.
