### ISSUE TITLE
obs-websocket 4.3.3 linux build missing from releases page

### ISSUE THREAD

**Issue by filippsudanov** [Palakis/obs-websocket#235]
obs-websocket version 4.3.3 seems to be the only one compitable with newest OBS 21.1, but it's not available as linux build. Will it be provided?

**Comment by Palakis** [comment]
@filippsudanov 4.3.3 was a Windows-only hotfix, hence why there is no macOS and Linux binaries with this release.
You can use 4.4.0 which has a Linux binary provided and is compatible with 21.1.
