### ISSUE TITLE
GetStreamingStatus does not return correct record or stream timecode 4.4.0

### ISSUE THREAD

**Issue by congoblue** [Palakis/obs-websocket#236]
##### Issue type
Bug report

##### Description
GetStreamingStatus command does not return the correct record or stream timecode. The time is returned but does not increment correctly. This worked ok in the previous versions of obs-websocket and obs before v22

##### Steps to reproduce and other useful info
Start OBS recording, send GetStreamingStatus command. Websocket returns a field "rec-timecode" which does not increment as expected - the numbers change but not in any expected way - possibly showing 10's as units and 100's as 10's

##### Technical information
OS Windows 10 Pro.
OBS v22.0.2
Obs-websocket v4.4.0

**Comment by Palakis** [comment]
@congoblue Could you show me an example of a bad timecode? Like OBS recording timer vs. GetStreamingStatus result

**Comment by Palakis** [comment]
@congoblue Gonna close this, as I can't reproduce it and I don't have more informations regarding the situation you're describing.
