### ISSUE TITLE
Time-Codes Please EX: {"recTimecode": "00:05:47"}

### ISSUE THREAD

**Issue by BaddMann** [Palakis/obs-websocket#24]
Can you have the events return recording timecodes on each event? 
EX: {"recTimecode": "00:05:47"}

or better Ex:

```
{
    "scene-name": "Game",
    "update-type": "SwitchScenes",
    "rec-Timecode": "00:05:47",
    "stream-Timecode": "00:05:37"
}
{
    "scene-name": "Intro",
    "update-type": "SwitchScenes",
    "rec-Timecode": "00:08:53",
    "stream-Timecode": "00:06:37"
}
```
I'm hopping to use this to whole thing to dynamically create an EDL file so we can Quickly edit the recordings instantly after recording has completed.
Maybe in the future OBS can introduce Chapter Markers too, then we can use our web socket connection to add events to the feed, making it easy to do quick edits based on time-coding events within a recording...

Thank you for the consideration

**Comment by Palakis** [comment]
Good idea! Will plan this as an enhancement.

Regarding the Chapter Markers, this is more complicated to do, as it
requires a deeper integration with the encoder.

**Comment by BaddMann** [comment]
There is another plugin that appears to have done a lot of he work needed to extract the timecodes from OBS and create something meaningful out of it.
https://obsproject.com/forum/resources/infowriter.345/
Unfortunately I can't find any source code listed so maybe a discussion between two like minded devs, hint hint, say no more...

I wish I could be more helpful, but my C experience is none-existent and my python experience is only just now becoming less than useless.

thank you again for the consideration

**Comment by enzanki-ars** [comment]
The InfoWriter plugin seems to have source code on GitHub (https://github.com/partouf/OBSInfoWriter).

**Comment by BaddMann** [comment]
thank you

**Comment by BaddMann** [comment]
You are the man!!
If I had any clue on how to compile, this I would, but learning Node.js and python are killing me as is, so I'll just wait or your release. :p

Thank you again.

**Comment by haganbmj** [comment]
Latest windows build is available here 

https://ci.appveyor.com/project/Palakis/obs-websocket/build/artifacts

**Comment by BaddMann** [comment]
Just updated OBS then Web-sockets, got this:
![image](https://cloud.githubusercontent.com/assets/211092/23574769/ac2045ac-003f-11e7-9ac5-905fc2f6035d.png)

I know I know, I caused this myself

**Comment by haganbmj** [comment]
It worked with 18.0? Him.

**Comment by Palakis** [comment]
obs_output_get_congestion was added in 18.0.0. Please update your OBS, you'll get tons of new features with it.

**Comment by BaddMann** [comment]
I did. It's working awesome now. Will be performing fill test Sunday.

The error message on earlier versions might be upsetting for those who do
not update though, Right?

**Comment by Palakis** [comment]
Yup, it will. Gonna add a disclaimer telling people that obs-websocket 4.0.0 works with OBS Studio >= 18.0.0
