### ISSUE TITLE
Change directory for image slideshows

### ISSUE THREAD

**Issue by JeffJaf** [Palakis/obs-websocket#243]
##### Issue type
Feature request

##### Description
I would like a feature to be able to change directories for image slideshows, or a way to 'refresh' a directory from a slideshow whenever the directory is modified. This would provide a way to automatically update the slideshow whenever an image is added or removed, which I think is a long requested feature for OBS and obs-websocket could provide a simple way to get around this issue.  Thank you.

**Comment by tt2468** [comment]
I believe that both updating and refreshing the image slideshow can be done using the `SetSourceSettings` request.
