### ISSUE TITLE
Problem when modifying properties of source and obs-websocket changes the scene.

### ISSUE THREAD

**Issue by reedog117** [Palakis/obs-websocket#244]
##### Issue type
OBS crashes if changing properties of a source and obs-websocket changes the scene to a different one without that source.

##### Description
OBS crashes if changing properties of a source and obs-websocket changes the scene to a different one without that source.

##### Steps to reproduce and other useful info
Open properties for a source within a scene. Change to another scene without that source. Try to save the properties.

Crash log: https://obsproject.com/logs/Cl1shxwFZNsJBIRR

##### Technical information
- **Operating System** : Windows Server 2016
- **OBS Studio version** : 22.0.2 (64-bit)

**Comment by Palakis** [comment]
@reedog117 Uh wait, that's an issue with OBS itself, not obs-websocket.

**Comment by Palakis** [comment]
@reedog117 And I can't reproduce this issue in OBS 23 on Ubuntu. I have three scenes, opened the settings dialog of a Media Source in scene 2, switched to Scene 1 (which doesn't have said media source) through obs-websocket, changed a value in the Media Source settings and hit "OK": no crash.
