### ISSUE TITLE
SetTextFreetype2Properties listed in GetVersion on 4.4.0 despite not being a valid request method

### ISSUE THREAD

**Issue by haganbmj** [Palakis/obs-websocket#253]
##### Issue type
Bug Report

##### Description
See https://github.com/haganbmj/obs-websocket-js/issues/123 for original report.
As far as I can tell on both 4.3.3 and 4.4.0 `SetTextFreetype2Properties` is reported as a valid method when calling `GetVersion`, despite it not existing at the 4.4.0 tagged commit.

https://github.com/Palakis/obs-websocket/blob/master/src/WSRequestHandler.cpp#L117

The method was added in the following commit, which as far as I can tell was never released as it got wrapped up in the rewrite.
https://github.com/Palakis/obs-websocket/commit/63338b2ac564828100a05a620fc83b8d3fba9fae

##### Technical information
- obs-websocket versions: 4.3.3, 4.4.0

**Comment by Palakis** [comment]
...damn

**Comment by haganbmj** [comment]
Yeah, not exactly sure how that got there.

**Comment by Palakis** [comment]
Should be fixed in 4.5.0.
