### ISSUE TITLE
Get the list of Sources

### ISSUE THREAD

**Issue by Lanpingner** [Palakis/obs-websocket#257]
##### Issue type
Coding and I have no idea how to get the list of the sources

##### Description
Hi everyone I am currently making a small program. And I would like to get the list of Sources in a Scence

##### Technical information
- **Windows10** :
- **22.0.2 x64** :

##### Development Environment
*I am working in Visaul Basic (vb.net)

**Comment by CSMBY** [comment]
You can use GetSceneList, each scene will contain a list of sources

**Comment by Lanpingner** [comment]
I found a way but my problem is thats only can show if i give the number of the source.
Do you know I can show all the sources.
here is my code
0 mean the first socues I want to list out all
`For Each scene In obs.ListScenes
ListBox2.Items.Add(scene.Items.ToList.Item(0).SourceName.ToString)
Next`

**Comment by tt2468** [comment]
Closing this thread since it has been inactive for quite a while. If you still need help, reopen the issue or start a new one.
