### ISSUE TITLE
Publish filters

### ISSUE THREAD

**Issue by Kelin2025** [Palakis/obs-websocket#260]
##### Issue type
Feature request

##### Description
Hi, you guys do a great work but there are 2 months since [this PR](https://github.com/Palakis/obs-websocket/pull/221) have been merged and there is still no release. Can you publish it? I need opportunity to work with filters asap

**Comment by Palakis** [comment]
A release is on its way.

**Comment by Palakis** [comment]
@Kelin2025 4.5.0 is out! https://github.com/Palakis/obs-websocket/releases/tag/4.5.0

**Comment by Kelin2025** [comment]
@Palakis yay, thanks a lot! Sad that it requires OBS **22+** but thanks!
