### ISSUE TITLE
Incompatibility with 4.5.0 & Bitfocus Companion on Mac

### ISSUE THREAD

**Issue by thermidorthelobster** [Palakis/obs-websocket#264]
##### Issue type
Suspected bug report - but could be within Bitfocus Companion - unconfirmed.

##### Description
Using obs-websocket to interface between OBS and Bitfocus Companion on MacOS. I had to use 4.5.0 as 4.4.x won't load on Mac (see bug report elsewhere).

Companion can control OBS through obs-websocket, but all Dynamic Variables returned to Companion appear as "undefined"; Companion only lists "Change scene" as the only action it can take through obs-websocket.

##### Steps to reproduce and other useful info
Have tried restarting all 3 components and rebooting machine.

##### Technical information
- MacOS 10.13.6
- OBS Studio 22.0.3

[2018-12-28 15-10-35.txt](https://github.com/Palakis/obs-websocket/files/2715082/2018-12-28.15-10-35.txt)

**Comment by Palakis** [comment]
@thermidorthelobster 
> but all Dynamic Variables returned to Companion appear as "undefined"

What are the variables?

**Comment by thermidorthelobster** [comment]
OK, you probably get the idea that I'm not a technically-oriented user. I've attached a screenshot from OBS which illustrates what I mean. However, subsequently I tried connecting directly to obs-websocket through 127.0.0.1:4444 from a browser. I get "the server unexpectedly dropped the connection." Presumably this means this is more likely to be a config issue than a bug.
![obs](https://user-images.githubusercontent.com/46196909/50636162-f8f13800-0f4c-11e9-9b18-83ae33f2110e.png)

**Comment by thermidorthelobster** [comment]
Having tried this dozens of times I'm now getting valid variables passed back to Companion. I think this is user error rather than a bug.

**Comment by Palakis** [comment]
@thermidorthelobster These variables are provided in the `StreamStatus` event. Once you start streaming and/or recording, this event is emitted every 2 seconds or so. Start streaming and/or recording while Companion is connected and these DV should get populated.
