### ISSUE TITLE
Settings per Profile

### ISSUE THREAD

**Issue by Chewza** [Palakis/obs-websocket#269]
##### Issue type
Feature Request

##### Description
Store OBS-WebSocket settings per profile instead of globally.

##### Steps to reproduce and other useful info
I run two instances of OBS, one in a Production profile, and another in a Monitor profile on a machine that streaming operators access via automation, and don't have physical access to.
The Production profile contains all of our scenes and live feeds and sends them along to twitch.
The Monitor profile is a full screen capture of the Production instance so that we can provide our stream operators access to the studio mode of OBS.

We want to run two instances of OBS, each with a different port configuration for OBS-WebSocket.
However when changing the port settings for the plugin and opening the other profile, the settings for WebSocket are globally stored as opposed to stored per profile.

Additionally, I cannot launch the second instance of OBS with the websocket enabled, as it will crash the new instance of OBS due to the socket being in use.
I then have to launch an instance of OBS, disable the websocket, launch the second instance, re-enable the web socket after changing the port number.

##### Technical information
- **Operating System** : Windows 10 Home
- **OBS Studio version** : 22.0.2 x64

**Comment by whytheheckme** [comment]
I have this exact need as well. Thank you!

**Comment by rollykaunang** [comment]
Please adding this feature.. Thank You So Much!

**Comment by 4ntibala** [comment]
same here.. also in the need of different ports per profile. 
u can start multiple instances of OBS via terminal in linux though.. and do the WS config afterwards.
