### ISSUE TITLE
Issue & Request

### ISSUE THREAD

**Issue by MRVDOG** [Palakis/obs-websocket#27]
Hi, my Issue is, for some reason source bounds (cx & cy) are `0`, I'm using `obs-websocket-js` and I can't work out if this issue is from here or there

![image](https://cloud.githubusercontent.com/assets/4422624/21951531/9df842b0-d9ff-11e6-9765-25d61aa86950.png)

my request is for more events/functions, for example, I want to be able to change a sources position and dimensions when, for example, I use jQueryUI `draggable()` and `resize()` to change them on my webUI

![image](https://cloud.githubusercontent.com/assets/4422624/21951493/32b4d6f8-d9ff-11e6-9376-07425f08f8ef.png) The WebUI so far, this is for a friend to be able to control his OBS when he's at conventions, etc...

I also posted this over at `obs-websocket-js`

**Comment by Palakis** [comment]
Please specify your OBS Studio version.
Did you checked the content of the WebSocket frames using your browser's developer console ?

**Comment by MRVDOG** [comment]
ohh yeah I always forget version numbers... `OBS Studio 17.0.0`, and the latest `obs-websocket`, and not quite sure what you mean by WebSocket Frames

**Comment by Palakis** [comment]
Under the Network tab of Chrome's developer tools, you can analyze the network traffic of a page, including WebSocket connections, and filter the traffic you want to analyzed based on its type (e.g : stylesheets, AJAX requests, etc...).

![chrome_2017-01-14_20-38-50](https://cloud.githubusercontent.com/assets/1812130/21957583/a5183f10-da99-11e6-98f5-0f30e134013e.png)

**Comment by MRVDOG** [comment]
ohh sweet, I never knew that was a thing haha, thanks

**Comment by Palakis** [comment]
@MRVDOG any update on this ?

**Comment by Palakis** [comment]
Can reproduce the issue, investigating it.

**Comment by Palakis** [comment]
The bounds issue has been fixed. Regarding the ability to move and resize an item, I created a specific issue  for it : https://github.com/Palakis/obs-websocket/issues/35

**Comment by MRVDOG** [comment]
sorry, I stopped work on the project for a while due to the issues, thanks for fixing :D
