### ISSUE TITLE
obs-websocket not working with OBS NVENC beta

### ISSUE THREAD

**Issue by djardine** [Palakis/obs-websocket#270]
##### Issue type
Bug

##### Description
I've been doing some testing with the OBS beta build that integrates some of the Nvidia Shadowplay-esk features (direct NVENC video encoding from the gpu render buffer instead of having to run frame data through system DRAM), but it seems like obs-websocket does not run with the beta build of OBS (doesn't show up in the dropdown menu). I'm not sure if this has to do with the fact that the beta build isn't signed properly (there was a hack that was needed to get game capture working) and this might be fixed when the OBS beta build goes to production (end of Jan?), but I was wondering if there was a "hacky" way to get obs-websocket to work with the OBS beta build at this time.

##### Steps to reproduce and other useful info
OBS beta: https://obsproject.com/forum/threads/nvenc-performance-improvements-beta.98950/

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : OBS NVENC beta

**Comment by Palakis** [comment]
@djardine Copy Qt5Network.dll and Qt5WebSockets.dlld from `obs-plugins\64bit` to `bin\64bit` (paths relative to your OBS install folder). Should do the trick.

**Comment by djardine** [comment]
You the man!
