### ISSUE TITLE
Get Currently Selected Item

### ISSUE THREAD

**Issue by paul-lrr** [Palakis/obs-websocket#271]
##### Issue type
Feature request

##### Description
Would it be possible to find out what source the user has currently selected (either in the sources list or selected on the stage)? Ideally there could be be a `SceneItemSelected` event emitted with the source name when a source is selected and maybe also a `GetCurrrentItem` request that returns the currently selected source

**Comment by Palakis** [comment]
@paul-lrr It's a quick win, currently implementing this as item select/deselect events. A `GetSelectedItem` method is not possible yet, as far as I found out in the OBS' API docs.
