### ISSUE TITLE
Feature Request/Todo: Events Pub/Sub

### ISSUE THREAD

**Issue by Palakis** [Palakis/obs-websocket#275]
- Major refactor of the events subsystem
- Ability for clients to subscribe to specific event topics
- Will make things easier for source-specific events (like audio level events or update events)
- Topic templates with parameters and setup/teardown methods: only setup event publishers when actually needed
- Current event types become default topics and can be unsubscribed

**Comment by johncoles** [comment]
This would be great if still planned. I would like to see an option to subscribe to the  audio VU meters out of the UI allowing for monitoring of them on mobile devices or in our custom UIs.

**Comment by zen85** [comment]
oh nice. i also want to build a vu-meter in the remote to have visual feedback. is this still planned?

**Comment by tt2468** [comment]
Coming to 5.0.0
