### ISSUE TITLE
Plugin does not load on OBS RC1

### ISSUE THREAD

**Issue by Huesdon** [Palakis/obs-websocket#278]
##### Issue type
Bug report

##### Description
*I installed OBS Studio 23.0 Release Candidate 1, plugin no longer loads or appears in the tools menu.

##### Steps to reproduce and other useful info
install RC 1

##### Technical information
-Windows 10
-OBS Studio 23.0 Release Candidate 1

**Comment by Palakis** [comment]
Download the Zip archive of the plugin (under Releases) and extract its content to `C:\Program Files\obs-studio`

**Comment by Vextalex** [comment]
Hey. I have the same problem, no longer working after installing OBS Studio 23.0 Release Candidate 1.

I already tried the thing you mentioned, didn't help.

OBS Studio 22.0.2 works without problems, but I would like to use OBS Studio 23.0

**Comment by camalot** [comment]
All it says in the logs is:

`17:20:27.004: Module '../../obs-plugins/64bit/obs-websocket.dll' not loaded`

**Comment by Huesdon** [comment]
I tried both the installer and the zip file. The plugin dll is in there, just not loading.

**Comment by BlackyWhoElse** [comment]
Have the same problem

**Comment by Huesdon** [comment]
You on RC1 or the new RC2?

**Comment by dodgepong** [comment]
If you installed RC1, you will need to delete the `bin/64bit/Qt5Network.dll` file in your OBS folder. This was included by accident in RC1.

**Comment by camalot** [comment]
what @dodgepong said does indeed fix it, and it is also fixed in RC2

**Comment by BlackyWhoElse** [comment]
Just updated to RC2. Works fine now

**Comment by Huesdon** [comment]
Resolved as per above.

**Comment by GmanAtheist** [comment]
OBS 27.0.1 (64 bit) . Installed obs-websocket-5.0.0-alpha2-Windows. It does not show up in OBS tools. There is no plugin. Can anyone help. Did delete the Qt5Network.dll , But the websocket does not show up. Any help please. :/

**Comment by tt2468** [comment]
@GmanAtheist Please do not hijack old issues to ask for help.

I don't know how we could have been any more clear about the alpha versions:
![image](https://user-images.githubusercontent.com/28720189/134749675-40f97028-66b8-4e60-bbcc-9ee80c4fb0a4.png)

Use 4.9.1

**Comment by GmanAtheist** [comment]
> @GmanAtheist Please do not hijack old issues to ask for help.
> 
> I don't know how we could have been any more clear about the alpha versions:
> ![image](https://user-images.githubusercontent.com/28720189/134749675-40f97028-66b8-4e60-bbcc-9ee80c4fb0a4.png)
> 
> Use 4.9.1

Thanks. Got it working. No thanks to you and your sarcastic comment. Have a nice day. :/
