### ISSUE TITLE
Issues with Character Encoding

### ISSUE THREAD

**Issue by haganbmj** [Palakis/obs-websocket#28]
Originally mentioned in https://github.com/haganbmj/obs-websocket-js/issues/6

Desired Scene Name: Änd

```
16:29:59.123: Source 'Scene 2' renamed to 'Ã„nd'
16:30:25.151: obs-data.c: [obs_data_create_from_json] Failed reading json string (1): unable to decode byte 0xc4 near '"'
16:30:25.151: [obs-websockets] invalid JSON payload for '{"scene-name":"Änd","message-id":"11","request-type":"SetCurrentScene"}'
```

Sending 'getCurrentScene' or similar functions returns the correct scene name, but sending a request to setCurrentScene fails 
https://github.com/Palakis/obs-websocket/blob/master/WSRequestHandler.cpp#L64-L77

**Comment by Palakis** [comment]
Hmmm, might need to enforce UTF-8 in my code...

**Comment by Palakis** [comment]
I replaced all my calls of `toLocal8Bit()`with `toUtf8()`. Can you test from your side, please ?

**Comment by haganbmj** [comment]
Yeah, I'll get that built when I get home and get back to you on it.

**Comment by haganbmj** [comment]
```
16:10:54.145 [OBSWebSocket] [sendRequest] Object { scene-name: "Änd", message-id: "3", request-type: "SetCurrentScene" } 1 obs-websocket.js:135:7
16:10:54.149 [OBSWebSocket] [onMessage] Object { scene-name: "Änd", update-type: "SwitchScenes", sceneName: "Änd", updateType: "SwitchScenes" } 1 obs-websocket.js:158:5
16:10:54.151 [OBSWebSocket] [onMessage] Object { message-id: "3", status: "ok", messageId: "3" } 1 obs-websocket.js:158:5
```

Also tried a couple other test strings and everything seemed to be in order.

Thanks for the help!
