### ISSUE TITLE
Volume "0-1" correspondence to "-infinity to 0"

### ISSUE THREAD

**Issue by PCMACHero** [Palakis/obs-websocket#280]
##### Issue type
Other?
Clarification needed.

##### Description

The websocket gets and sets volumes on a 0-1 range, meaning 0 is mute and 1 is full volume. This is different than how OBS itself identifies volume levels. OBS uses "negative infinity to 0" to represent the mute-max range. I could convert it, but the problem is that it isnt linear. What I mean is that the correspondence has some kind of a curve to it. If I make a range slider and set it to min=0 and max=1, placing it at .5 (the middle of the range, and the middle of the visual range bar) it corresponds to a "-6" in OBS, and not in the middle of the bar in OBS. The middle of the bar is somewhere around -15 in OBS. This causes 2 issues. One, the range button placement doesnt visually match the bar slider knob's position in OBS, and second, I dont know what function to pass the 0-1 value that would result in
-infinity when "0"
 -6 when ".5"
0 when "1"

**Comment by Palakis** [comment]
@PCMACHero at the very least I can put a mention in the protocol specs which says volume values are linear. But because the conversion between linear and dB log is trivial, this is not much of an issue currently.
