### ISSUE TITLE
SetSourceFilterSettings on Scenes

### ISSUE THREAD

**Issue by Huesdon** [Palakis/obs-websocket#281]
##### Issue type
**Feature request**

##### Description
Ability to set the setting of filters on scenes (nested scene used as a source) identical to SetSourceFilterSettings but for scenes used as sources in parent scenes.

You can apply a filter in the same way but cannot set the filter settings as you can on a source.

**Use case**, I am doing some automation around visibility of the camera. This involves hitting the socket many times per second to get a smooth opacity change. 

**Issue:** the camera also involves other elements like a camera frame, this means to make the camera fade out I also have to change the opacity of the frame, so double the hits on the socket.

**Whereas,** if I could affect the settings of filters on scenes, I can make my camera a sub-scene and only have to make calls against one object.

**Comment by Huesdon** [comment]
Palakis, please drop a comment if this will receive any attention.

**Comment by Palakis** [comment]
Scenes are sources, so you should be able to use source management commands on scenes. Can you tell me which ones don't work with scenes?

**Comment by Huesdon** [comment]
I can successfully create a fade in/out with the code below but it does nothing when pointed at a scene...

```
// camera
    await obs.send(
      "SetSourceFilterSettings", {
        sourceName: "SRC_Cam_1",
        filterName: "Color Correction",
        filterSettings: {
          opacity: opacity
        }
      });

    // frame
    await obs.send(
      "SetSourceFilterSettings", {
        sourceName: "SRC_Cam_Frame",
        filterName: "Color Correction",
        filterSettings: {
          opacity: opacity
        }
      });
```

In order to do this with my camera it has to do the calls in a fast loop on multiple items, if I could do it on a nested scene with would be much more viable.

**Comment by Huesdon** [comment]
Oh hmm, based on your comment I tried to make a new test... .and it seems to be working..   :/
I will close this after a bit more testing.

**Comment by Huesdon** [comment]
Ok, guess I was on crack, thanks for the comment Palakis.

For the record, filter settings set via obs-websocket do in fact affect normal sources as well as scenes used as sources.
