### ISSUE TITLE
SetSceneItemProperties not accepting scale values

### ISSUE THREAD

**Issue by macharborguy** [Palakis/obs-websocket#286]
Using the latest release candidate, 4.5, of obs-websocket

I am trying to simulate a zoom-in-out effect with obs-websocket and obs-websocket-js (posting this issue over on the obs-websocket-js GitHub as well to cover all my bases)

I am sending the following data with SetSceneItemProperties...

`{
item : 'SourceName',
position : {
x : <number value>,
y : <number value>,
},
scale : {
x : <number value>,
y : <number value>
}
}`

The Protocol document says that Position X and Y accept Ints, and Scale X and Y accept Doubles.

If I send a number value of 100, or 100.00, or even 100.001, the actual scale that gets propagated onto the Scene Item in OBS is 90001.0000

If I send it as a string, such as "100", "100.00" or "100.001", the scale is set to 0.

Oddly enough, if I do a GetSceneItemProperties request after having set the value as a Number in JavaScript, the results I get back from the request show that the proper numbers are in fact saved.

So setting the scale is showing up in the OBS preview and Edit Transform window as 90001, but GetSceneItemProperties requests shows the proper values I set.

**Comment by Palakis** [comment]
> If I send a number value of 100, or 100.00, or even 100.001, the actual scale that gets propagated onto the Scene Item in OBS is 90001.0000

It's a limitation of the UI field that shows the width in the Edit Transform dialog. Internally, everything is set and fetched properly and it should be the case as well in the rendering.

**Comment by macharborguy** [comment]
> > If I send a number value of 100, or 100.00, or even 100.001, the actual scale that gets propagated onto the Scene Item in OBS is 90001.0000
> 
> It's a limitation of the UI field that shows the width in the Edit Transform dialog. Internally, everything is set and fetched properly and it should be the case as well in the rendering.

Sadly, that doesnt seem to be the case.   To verify, I created a new scene collection, added a single image into the scene.  I then added in a bare-minimum script to adjust the size and position of the image.  The physical rendering of the object IS increased to the 90001 x 90001 dimensions once the SetSceneItemProperties command is sent.

I tested this with both obs-websocket-js as well as natively with a direct WebSocket connection, and in both cases the same thing happened.  90001 x 90001 dimensions in the Edit Transform window, and the rendering of the Scene Item instantly reflected that upon the request being made.  This happens regardless of the Edit Transform window being open or closed.

Here is the code that I used...

`<html>
	<head></head>
	<body>
		<script src="../shared_assets/js/obs-websocket-3.js"></script>
		<script>
			
			/* Using WebSocket() */
			const obs = new WebSocket('ws://localhost:4444');
			
			obs.addEventListener('open', (event)=>{
				console.log('connected', event);
				
				let _string = JSON.stringify({
					'request-type' : 'SetSceneItemProperties',
					'message-id' : '12345',
					item : 'My Image',
					position : {
						x : 100,
						y : 100
					},
					scale : {
						x : 500,
						y : 500
					}
				});
				console.log(_string);
				
				setTimeout(()=>{
					obs.send(_string);
					
				},5000);
			});
			
			
			
			/* Using obs-websocket-js 3.0
				
			const obs = new OBSWebSocket();
			obs.connect({ address: 'localhost:4444' }).then(()=>{
				console.log('connected');
				
				setTimeout(()=>{
					obs.send('SetSceneItemProperties', {
						item : 'My Image',
						position : {
							x : 100,
							y : 100
						},
						scale : {
							x : 500,
							y : 500
						}
					}).then(()=>{
						console.log('done');
					});
				},5000);
			});
			*/
			
		</script>
	</body>
</html>`

The above was added to the scene as a Browser Source.


OBS Studio Version : 23.1.0
OBS Websocket Version : 4.5.0

**Comment by macharborguy** [comment]
Oddly enough, testing on a completely separate install of OBS on another PC, the same thing happens, but the size set is 56000 x 56000, instead of 90001 x 90001.  The visible rendering of the item is once again adjusted to that specific size.  I can scroll the item manually into view and it is indeed that extremely large size

**Comment by macharborguy** [comment]
Consider this closed.  I looked at the Comments.json file and the description of the Scale specifically stated "the scaling FACTOR", rather than what I had assumed which was a direct size, so in the above example code I posted, I was assuming the size would be 500x500, instead of 500x x 500x.

THe Protocol document may need an update to specifically state it is a "scale factor" instead of being ambiguous as it is currently.

**Comment by schindlerit1984** [comment]
i still get the same error as written above. 

in connection with obs command it can only trigger SetSceneItemTransform and not SetSceneItemProperties. written in the forum by fsc it says there might be an error inside websocket where it only takes the Deprecated values. 

it wouldnt be a problem if it just resizes proper - it cant get anything other working apart from 1 2 3 and 0.1 0.2. 0.3 if i trigger the written values from the log file it simply goes to the values written above
