### ISSUE TITLE
Error in OBS studio running 

### ISSUE THREAD

**Issue by shadow0162** [Palakis/obs-websocket#29]
After build sucess, I just copy obs-websocket.dll & obs-websocket.pdb to obs studio plugin path.
And then got an debug error:
QWidget: Must construct a QApplication before a QWidget
![image](https://cloud.githubusercontent.com/assets/2087112/22242549/b6188cda-e25e-11e6-8331-91f42d1854ac.png)

**Comment by Palakis** [comment]
Does OBS runs fine without the plugin's DLL ?

**Comment by Palakis** [comment]
@shadow0162 You also need to copy Qt5Network.dll and Qt5WebSockets.dll to the plugin path of OBS Studio. Can you please tell me if at least your OBS runs fine without the plugin ?

**Comment by shadow0162** [comment]
Yep ,OBS studio & plugin runs well.I made a mistake about wrong dlls.After copy right dlls , its works.You can close the issue now.
