### ISSUE TITLE
Plugin not loading on OBS 23.1.0 Windows

### ISSUE THREAD

**Issue by Rushmead** [Palakis/obs-websocket#291]
##### Issue type
Bug report

##### Description
The latest version of the OBS Websocket plugin is not being loaded on my installation of OBS 23.1.0 on windows. The Log simply says "Module '../../obs-plugins/64bit/obs-websocket.dll' not loaded"

##### Steps to reproduce and other useful info
Heres a log file: https://pastebin.com/bdXPvjKZ I don't really know any steps to re-produce

##### Technical information
- **Operating System** : Windows 10 1809
- **OBS Studio version** : 23.1

**Comment by catb0t** [comment]
how did you install it?

**Comment by Rushmead** [comment]
Using the windows installer

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Promic2** [comment]
not the only one 
i have try the windows installer. and the ZIP 
i only get Module '../../obs-plugins/64bit/obs-websocket.dll' not loaded in log
OBS-studio 23,0,1 64bit

**Comment by CSMBY** [comment]
All is working fine (Windows 10 Home 1809, OBS 23.1 64 bit, obs-websocket 4.5.1)

**Comment by rivafarabi** [comment]
I have the same problem, is there any fix for this yet?

**Comment by dodgepong** [comment]
Check to make sure you don't have a file called `Qt5Network.dll` in your in your `obs-studio/bin/64bit` folder. If you do, go ahead and delete it (it's left over from one of the v23 release candidates).

**Comment by Promic2** [comment]
Thanks that fix it

**Comment by Huesdon** [comment]
You should close out the issue here if you are good...

**Comment by Rushmead** [comment]
This is issue is technically fixed, there is just a work-around. I'm sure something could be done to prevent the need for users to manually delete the dll file?

**Comment by Palakis** [comment]
@Rushmead Starting from 4.6.0, obs-websocket doesn't use these DLLs anymore
