### ISSUE TITLE
Unable to get Authenticate working in JS at all...

### ISSUE THREAD

**Issue by Jaxel** [Palakis/obs-websocket#292]
I'm unable to get authentication working at all in my JavaScript.
I'm using the SHA256 library here: https://github.com/emn178/js-sha256

When authentication is required, it produces a prompt:

	if (data['authRequired'])
	{
		var pass = prompt("This OBS Websocket server requires a password:");
		
		if (pass != null)
		{
			var secret_string = pass + data['salt'],
				secret_hash = sha256(secret_string),
				secret = btoa(secret_hash),
				auth_response_string = secret + data['challenge'],
				auth_response_hash = sha256(auth_response_string),
				auth_response = btoa(auth_response_hash);
				
			
			args = {
				'request-type': 'Authenticate',
				'message-id': 'Authenticate',
				'auth': auth_response,
			};
			this.socket.send(JSON.stringify(args));
		}
	}

However, I always get an authentication failed error in response.

What am I missing here?

**Comment by Jaxel** [comment]
I am still completely lost on this after a week... please help.

**Comment by Genteure** [comment]
Maybe this can help you: https://github.com/t2t2/obs-tablet-remote/blob/7e7048d68f12cc00c532cbd59b71f8eaf2bb3f31/src/obs-remote.js#L81-L106

**Comment by Jaxel** [comment]
Hmm... that references `sha.js/sha256`, but I can't find that JS anywhere in the package.

**Comment by Jaxel** [comment]
I've tried several different libraries now, and can never get it to work.

I've even used online generators to check my code, and everything matches up... yet Auth still fails.

**Comment by HeyITGuyFixIt** [comment]
t2t2 has sha.js as a dependency. It must be imported from somewhere else.

**Comment by Jaxel** [comment]
Either way... I've tried multiple sha256 libraries... and my code still isn't working.

**Comment by HeyITGuyFixIt** [comment]
Found it here: https://www.npmjs.com/package/sha.js

**Comment by Jaxel** [comment]
I don't use NodeJS... so I have no idea how to implement that.

**Comment by Jaxel** [comment]
`	var secret = btoa(sha256(this.passwd + data['salt'])),
		response = btoa(sha256(secret + data['challenge']));`

This should work no matter what sha256 library I use. sha256 is a defined standard. Checking the results using online generators is telling me that I'm getting the right results. But authentication continues to fail... and I have no idea why.

**Comment by Jaxel** [comment]
Let me try to provide some more information... hopefully someone can help me figure this out:

This is the code:
	var secret_string = this.passwd + data['salt'],
		secret_hash = sha256(secret_string),
		secret = btoa(secret_hash),
		auth_response_string = secret + data['challenge'],
		auth_response_hash = sha256(auth_response_string),
		auth_response = btoa(auth_response_hash);

And this is the response:
	passord: 12345
	salt: oxaZZyvG8G04gF6O1PdcslAE6iXc7sj5Vejppl7bJfQ=
	challenge: smYuG7kkxShZLS6iDt/hbj3egvDFWRNz2I9pywmS3Dg=
	
	secret_string: 12345oxaZZyvG8G04gF6O1PdcslAE6iXc7sj5Vejppl7bJfQ=
	secret_hash: 92018f428262dfc3b16e653b66ec3f05358c3a73f660463ccc45015de81f1ca9
	secret: OTIwMThmNDI4MjYyZGZjM2IxNmU2NTNiNjZlYzNmMDUzNThjM2E3M2Y2NjA0NjNjY2M0NTAxNWRlODFmMWNhOQ==
	auth_response_string: OTIwMThmNDI4MjYyZGZjM2IxNmU2NTNiNjZlYzNmMDUzNThjM2E3M2Y2NjA0NjNjY2M0NTAxNWRlODFmMWNhOQ==smYuG7kkxShZLS6iDt/hbj3egvDFWRNz2I9pywmS3Dg=
	auth_response_hash: bee1494080f9f3632d28df7a482023a4923265ad215842b7aa73fe9608f14cc0
	auth_response: YmVlMTQ5NDA4MGY5ZjM2MzJkMjhkZjdhNDgyMDIzYTQ5MjMyNjVhZDIxNTg0MmI3YWE3M2ZlOTYwOGYxNGNjMA==

**Comment by HeyITGuyFixIt** [comment]
How are you using it to authenticate?

**Comment by Genteure** [comment]
You can also use [obs-websocket-js](https://github.com/haganbmj/obs-websocket-js). It's a well maintained library ready to use, with the ability to use it without nodejs and npm. [prebuild version here](https://github.com/haganbmj/obs-websocket-js/blob/v3.0.0/dist/obs-websocket.min.js)

**Comment by Jaxel** [comment]
this.sendRequest('Authenticate', {'auth': auth_response});
	
which calls

	sendRequest: function(request, params = {})
	{
		let args = { 'request-type': request, 'message-id': request };
		this.socket.send(JSON.stringify({...args, ...params}));
	}

this roughly translates to:

	let args = {
		'request-type': 'Authenticate',
		'message-id': 'Authenticate'
	};
	
	let params = {
		'auth': auth_response
	}
	
	this.socket.send(JSON.stringify({...args, ...params}));

I've got all my other websocket functions working perfectly fine. It's only authenticate that fails. Disabling authentication within OBS works fine.

**Comment by Jaxel** [comment]
> You can also use [obs-websocket-js](https://github.com/haganbmj/obs-websocket-js). It's a well maintained library ready to use, with the ability to use it without nodejs and npm. [prebuild version here](https://github.com/haganbmj/obs-websocket-js/blob/v3.0.0/dist/obs-websocket.min.js)

I have no need for this library. Literally every single one of my other functions works fine, is done and is already written. The ONLY thing that doesn't work is authentication if required.

**Comment by Genteure** [comment]
> I have no need for this library.

If you already spent a week and still has no clue why, you might as well spent one hour switch from your own implementation based on native websocket to other people's work that is guaranteed working. I think this definitely is an option when running into problems that one can't figure out why.

---

And here's your problem:

The value you are doing base64 on is string value, not binary bytes.

quote [protocal.md](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md)

> password = "supersecretpassword"
> challenge = "ztTBnnuqrqaKDzRM3xcVdbYm"
> salt = "PZVbYpvAnZut2SS6JNJytDm9"
> 
> secret_string = password + salt
> secret_hash = binary_sha256(secret_string)
> secret = base64_encode(secret_hash)
> 
> auth_response_string = secret + challenge
> auth_response_hash = binary_sha256(auth_response_string)
> auth_response = base64_encode(auth_response_hash)

The library `js-sha256` you're using returns hex string by default. Your result of `base64(sha256("12345oxaZZyvG8G04gF6O1PdcslAE6iXc7sj5Vejppl7bJfQ="))` is `OTIwMThmNDI4MjYyZGZjM2IxNmU2NTNiNjZlYzNmMDUzNThjM2E3M2Y2NjA0NjNjY2M0NTAxNWRlODFmMWNhOQ==`, which is actually the result of `base64(bytes2hex(sha256(value)))`.

The answer to the problem:

The library `js-sha256` provides byte array output. instead of calling `sha256(value)`, you use `sha256.array(value)`. Then you can do base64 operation on the sha256 result array.

**Comment by Jaxel** [comment]
Hmm... I changed it to this:

	var secret_string = this.passwd + data['salt'],
		secret_hash = sha256.array(secret_string),
		secret = btoa(secret_hash),
		auth_response_string = secret + data['challenge'],
		auth_response_hash = sha256.array(auth_response_string),
		auth_response = btoa(auth_response_hash);

But it's still failing authentication

**Comment by Genteure** [comment]
[`btoa`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa) does not support encoding of binary array, it is automatically converted to string (like `"1,2,3,4,5"`). 
Use a converter like [this](https://gist.github.com/jonleighton/958841) I found on Google. The code I'm linking require a `ArrayBuffer` as argument, `js-sha256` have a method `sha256.arrayBuffer(value)` returns `ArrayBuffer`.

**Comment by Jaxel** [comment]
Ah... thank you. That appears to have been my issue with all the other libraries too. BTOA not supporting binary arrays. Instead of fetching a binary sha256, I fetched a string sha256 and now its working!

Thank you very much for your help!

**Comment by Jaxel** [comment]
BTW. I ended up using this library: https://anmar.eu.org/projects/jssha2/

**Comment by Huesdon** [comment]
Please close this issue then.
