### ISSUE TITLE
Way to query OBS canvas size?

### ISSUE THREAD

**Issue by Rosuav** [Palakis/obs-websocket#296]
##### Issue type
Question, possible feature request

##### Description
Is there a way to find out the OBS canvas size? Placement of all widgets is by pixels but the canvas size doesn't seem to be given anywhere.

##### Technical information
- **Operating System** : Linux
- **OBS Studio version** : 19.0.3, 23.0.2

**Comment by Palakis** [comment]
@Rosuav it is indeed a feature request. This will potentially be released in 4.7, unless someone can take care of this for inclusion in 4.6.

**Comment by Rosuav** [comment]
Okay, cool. At least I don't have egg on my face for being blind (which is a weird mixed metaphor, but where's the fun in unmixing them?). For now, I'll just hard-code it in my app.

**Comment by Rosuav** [comment]
Closed by the above PR
