### ISSUE TITLE
Attempting to set "bounds type" returns Invalid error

### ISSUE THREAD

**Issue by macharborguy** [Palakis/obs-websocket#309]
I am attempting to set the bounds type of a source item.  Using any of the valid strings...

"OBS_BOUNDS_STRETCH", "OBS_BOUNDS_SCALE_INNER", "OBS_BOUNDS_SCALE_OUTER", "OBS_BOUNDS_SCALE_TO_WIDTH", "OBS_BOUNDS_SCALE_TO_HEIGHT", "OBS_BOUNDS_MAX_ONLY" and"OBS_BOUNDS_NONE"

...all return an error message showing the following...

`
{error : {
    bounds : {
        type : "invalid"
    }
} status : "error", ..... }
`

**Comment by Palakis** [comment]
@macharborguy Found the cause https://github.com/Palakis/obs-websocket/blob/4.x-current/src/WSRequestHandler_SceneItems.cpp#L210-L211
