### ISSUE TITLE
Problems installing obs-websocket on obs-ftl

### ISSUE THREAD

**Issue by hamatzu** [Palakis/obs-websocket#31]
Hi, I am using obs-ftl found here: https://github.com/WatchBeam/obs-studio-ftl/releases 

I am trying to install obs-websocket plugin on this version, but cannot seem to figure out why it isn't working. I am getting the following error when I am trying to start obs after a successful install. 

![capture](https://cloud.githubusercontent.com/assets/2776635/22407748/d20a5b14-e66c-11e6-92f3-70f10828ef8b.PNG)

The error seems similar to the one mentioned in this issue: https://github.com/Palakis/obs-websocket/issues/22

I have no experience in compiling anything, I have only tried the windows-installer. I hope anyone can help me out, or have any ideas. Or maybe point me in the right direction on how to compile the obs-ftl version with obs-websocket.

Regards,
Hamatzu

**Comment by Palakis** [comment]
Seems like a Qt version mismatch between the main app and the plugin.
Another user of OBS FTL has this issue : https://github.com/WatchBeam/obs-studio-ftl/issues/52 (I can see that you're participating too)

**Comment by hamatzu** [comment]
Yeah, I found it after I posted this issue here. Thanks! :)

**Comment by hamatzu** [comment]
@Palakis Just a thought, how hard would it be to get a build of the websocket plugin for qt 5.6 ?

**Comment by Palakis** [comment]
@hamatzu Not that hard actually. But as the main OBS Studio is built with Qt 5.7, it would be better for the OBS FTL maintainers to build it with Qt 5.7 too so that other plugins can be compatible without having to rebuild each of them for OBS FTL.

**Comment by hamatzu** [comment]
Yes, I understand that. Thanks for your input.

**Comment by Palakis** [comment]
The latest OBS FTL is out, built with Qt 5.8. Gonna test this.

**Comment by Palakis** [comment]
Still no luck. OBS FTL is built with Qt 5.8 but exactly Qt 5.7.0 is needed, which is the Qt version Jim uses to build OBS Studio.

**Comment by hamatzu** [comment]
Yeah, I tried with the newest release, still no luck as you said. Thanks for checking! :)
