### ISSUE TITLE
duration wrong in TransitionBegin for "Cut" and "Stinger" Transitions

### ISSUE THREAD

**Issue by lebaston100** [Palakis/obs-websocket#314]
##### Issue type
Bug report

##### Description
When using a "Cut" Transition the duration in "TransitionBegin" is the value from the last chosen transition that has a real duration like fade.
Besides that the protocol.md states that the event shouldn't even be emitted for a "Cut" transition:
> A transition (other than "cut") has begun.

For the Stinger transition it's the same. The duration value is neither 0 nor the real lenght of the stinger video file, but instead the value from the transition that has a real duration.

##### Steps to reproduce and other useful info

Cut Transition:
- Set up a "Fade" transition with eg 3000ms in the "Scene Transitions" Dock
- Switch to the "Cut" transition and cut to another scene
- The websocket data will show ""duration": 3000, "name": "Cut""

Stinger Transition:
- Set up a "Fade" transition with eg 2000ms in the "Scene Transitions" Dock
- Choose "Stinger" transition with some video
- Transition with the stinger to another scene
- The websocket data will show ""duration": 2000, "name": "Stinger""

##### Technical information
- Win 10
- OBS 23.1.0
- obs-webocket 4.5.1

If there is anything more you want to know, let me know.

**Comment by Palakis** [comment]
I think I see what's going on. Thanks for reporting this.

> Besides that the protocol.md states that the event shouldn't even be emitted for a "Cut" transition:
> > A transition (other than "cut") has begun.

It's because I refactored how the plugin listens for transition events. For consistency, I think I'll leave it as is and remove that bit from the docs.

**Comment by MichleLI** [comment]
hello. I want to control visibility option of current scene that streaming now.
can you help me?
Thanks a lot!
