### ISSUE TITLE
SetSceneItemProperties parameters are all marked as required

### ISSUE THREAD

**Issue by Lange** [Palakis/obs-websocket#318]
##### Issue type
Bug report

##### Description
[`SetSceneItemProperties`](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#setsceneitemproperties) parameters are all marked as required, even though they are optional.

This causes the typedefs generated by `obs-websocket-js` to reject valid code such as this, because it thinks every single parameter is required.:

```ts
obs.send('SetSceneItemProperties', {
	'scene-name': '_ In-Game Base',
	'item': 'Mulligan Overlay',
	visible: true
});
```

##### Proposed Fix

In the source, mark more (all?) of these parameters as being optional.

**Comment by Palakis** [comment]
@Lange Thanks, should be fixed now
