### ISSUE TITLE
issue carsh

### ISSUE THREAD

**Issue by ystar8** [Palakis/obs-websocket#32]
hello .

I installed obs-studio 17.0.2 and obs-websocket 0.3.2 with client connection for a few times to change the source show off will occur crash

**Comment by ystar8** [comment]
this is log .
17:59:33.316: ==== Streaming Start ===============================================
18:01:58.701: [obs-websockets] new client connected from :3353
18:01:59.086: [obs-websockets] client :3353 disconnected
18:02:18.843: [obs-websockets] new client connected from :3367
18:02:19.086: [obs-websockets] client `想?:3367 disconnected
18:08:18.870: [obs-websockets] new client connected from :3609
18:08:19.083: [obs-websockets] client 斜;:3609 disconnected
18:08:39.012: [obs-websockets] new client connected from :3627
18:08:39.085: [obs-websockets] client 皎b?:3627 disconnected
18:10:56.839: [obs-websockets] new client connected from :2618
18:10:57.163: [obs-websockets] client `??:2618 disconnected
18:11:12.223: [obs-websockets] new client connected from :2628
18:11:13.087: [obs-websockets] client 愧1?:2628 disconnected
18:13:24.089: [obs-websockets] new client connected from :2645
18:13:25.156: [obs-websockets] client P??:2645 disconnected
18:13:28.919: [obs-websockets] new client connected from :2654
18:13:29.087: [obs-websockets] client 肖1?:2654 disconnected
18:14:39.038: [obs-websockets] new client connected from :3876
18:14:39.087: [obs-websockets] client 牎1?:3876 disconnected
18:14:59.221: [obs-websockets] new client connected from :3895
18:15:01.087: [obs-websockets] client 繠,?:3895 disconnected
18:16:22.052: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds
18:20:59.248: [obs-websockets] new client connected from :4142
18:21:01.087: [obs-websockets] client :4142 disconnected
18:21:19.380: [obs-websockets] new client connected from :4148
18:21:21.085: [obs-websockets] client 穗?:4148 disconnected
18:27:19.407: [obs-websockets] new client connected from :4410
18:27:21.086: [obs-websockets] client 0齐?:4410 disconnected
18:27:39.565: [obs-websockets] new client connected from :4427
18:27:41.086: [obs-websockets] client €须?:4427 disconnected
18:28:07.540: [obs-websockets] new client connected from :2742
18:28:09.206: [obs-websockets] client  ゜?:2742 disconnected
18:28:55.150: [obs-websockets] new client connected from :2751
18:28:55.261: [obs-websockets] new client connected from :2752
18:28:57.092: [obs-websockets] client ?)?:2752 disconnected
18:28:57.093: [obs-websockets] client ?)?:2751 disconnected
18:33:39.593: [obs-websockets] new client connected from :4702
18:33:41.084: [obs-websockets] client @+)?:4702 disconnected
18:33:59.737: [obs-websockets] new client connected from :4726
18:34:01.092: [obs-websockets] client ?)?:4726 disconnected

this is carsh .
Thread 2914 (Crashed)
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
000000B0C37DB380 00007FF8C7C0DCC0 0000000000000006 0000000000000001 00000213876AB160 00007FF8C94C1282 obs.dll!obs_data_release+0x30
000000B0C37DB3B0 00007FF8D78443A5 000000000000000C 0000000000000001 00000213FEA9B200 00000213BD124550 obs-websocket.dll!0x7ff8d78443a5
000000B0C37DB3E0 00007FF8D78444B4 000002138BB534B0 00000213FEA9B2C0 0000000000000000 000002138BB535D0 obs-websocket.dll!0x7ff8d78444b4
000000B0C37DB410 00000000643C5907 00000213FEAB1940 00000213FEA7CB70 000002138BB534B0 00000213BD1244C0 qt5core.dll!0x643c5907
000000B0C37DB5C0 0000000064767CA0 00000213FEA9B290 000000B0C37DB6F0 00000213BD1244C0 0000000064162C6E qt5widgets.dll!0x64767ca0
000000B0C37DB5F0 0000000064766BFA 000000B0C37DF6A0 00000213FEA9B290 00000213BD1244C0 000002138BB53400 qt5widgets.dll!0x64766bfa
000000B0C37DBD30 00000000643A23C9 0000000000000401 00000213BD124550 00000213BD1244C0 000000006420BFB5 qt5core.dll!0x643a23c9
000000B0C37DBDB0 00000000643A4161 00000213FEA9B2C0 0000000000000000 00000213FEAC2070 000000B0C37DBE60 qt5core.dll!0x643a4161
000000B0C37DBE60 00007FF8C6DF6F7F 0000000000000000 0000000000000000 0000000000000000 0000000000000401 qwindows.dll!0x7ff8c6df6f7f
000000B0C37DBE90 00000000643E7B25 0000000080000012 00007FF8EAD53552 0000000000000000 0000000000000000 qt5core.dll!0x643e7b25
000000B0C37DBFA0 00007FF8EAD41C24 0000021380131C00 00000000643E77A0 0000000003F80D42 000000B0C3814800 user32.dll!0x7ff8ead41c24
000000B0C37DC100 00007FF8EAD4156C 000000B0C37DC1C0 0000000006000301 000000B0C37DC280 0000000000000000 user32.dll!0x7ff8ead4156c
000000B0C37DC180 00000000643E7299 0000000000000000 0000021300000024 0000000000000000 000000B0C37DF6A0 qt5core.dll!0x643e7299
000000B0C37DF510 00007FF8C6DF6F59 00000213FEAB1940 0000021300000014 000000B0C37DF5E8 00000213FEA9B290 qwindows.dll!0x7ff8c6df6f59
000000B0C37DF540 000000006439EDA1 00000213FEA96BB0 0000021300000000 00000213FEA9B290 00007FF65B0E03F0 qt5core.dll!0x6439eda1
000000B0C37DF5C0 00000000643A1237 00000213FEAA2C70 00007FF65B0E03F0 000000B0C37DF890 00000213FEAA5200 qt5core.dll!0x643a1237
000000B0C37DF630 00007FF65AFC5D13 0000000000000000 0000000000000001 0000021300000000 0000000000000000 obs64.exe!run_program+0x1a3
000000B0C37DF790 00007FF65AFC7B0E 0000000000000001 0000000000000000 000000B0C37DF7C8 00000213FEAA1390 obs64.exe!main+0x35e
000000B0C37DF910 00007FF65B0BCF45 00000213FEA74AD0 0000000000000000 0000000000000001 0000000000000000 obs64.exe!WinMain+0x155
000000B0C37DF9A0 00007FF65B0BC94D 0000000000000000 0000000000000000 0000000000000000 0000000000000000 obs64.exe!__tmainCRTStartup+0x149
000000B0C37DF9E0 00007FF8EAA48364 0000000000000000 0000000000000000 0000000000000000 0000000000000000 kernel32.dll!0x7ff8eaa48364
000000B0C37DFA10 00007FF8EC0770D1 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ntdll.dll!0x7ff8ec0770d1

Thread 95A4
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
000000B0C3DFF5D8 00007FF8EC0B6154 00000213FF78C210 0001F558FC056707 0000000000000000 0000000000000000 ntdll.dll!0x7ff8ec0b6154
000000B0C3DFF5E0 00007FF8E8DE75FF 00000213FF750640 0000000000000000 0000000000000000 00000000000002E8 kernelbase.dll!0x7ff8e8de75ff
000000B0C3DFF680 00007FF8C7BDFB77 00000213FF750640 0000000000000000 00000213FF78BC60 00000213FF7973B0 obs.dll!os_event_timedwait+0x17
000000B0C3DFF6B0 00007FF8C7C1272D 00000213FF78BAA0 00000213FF78BAA0 0000000000000000 0000000000000000 obs.dll!obs_hotkey_thread+0xbd
000000B0C3DFF6E0 00007FF8DDEC722A 00000213FEA895B0 0000000000000000 0000000000000000 0000000000000000 w32-pthreads.dll!ptw32_threadStart+0x8a
000000B0C3DFF770 00007FF8DB2F4F7F 00007FF8DB3ACB80 0000000000000000 0000000000000000 0000000000000000 msvcr120.dll!0x7ff8db2f4f7f
000000B0C3DFF7A0 00007FF8DB2F5126 0000000000000000 0000000000000000 0000000000000000 0000000000000000 msvcr120.dll!0x7ff8db2f5126
000000B0C3DFF7D0 00007FF8EAA48364 0000000000000000 0000000000000000 0000000000000000 0000000000000000 kernel32.dll!0x7ff8eaa48364
000000B0C3DFF800 00007FF8EC0770D1 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ntdll.dll!0x7ff8ec0770d1

**Comment by Palakis** [comment]
This issue has already been fixed in https://github.com/Palakis/obs-websocket/commit/4439ce71d0cdacc731f440a6ea6fbf7fa7b73216. It will be included in the next binary release.
