### ISSUE TITLE
Request "ReorderSceneItems" causes OBS crash

### ISSUE THREAD

**Issue by IceFlom** [Palakis/obs-websocket#326]
##### Issue type
Bug Report

##### Description
There is a problem with the request "ReorderSceneItems". After using this request, sources will be reordered, but immediately after that OBS is crashing.
OBS crash report is attached.

##### Steps to reproduce and other useful info
For reproduction, send a JSON with a list of all sources in a different order. The sources have only the names as data. Tried it also with ids.

##### Technical information
- **Operating System** : Windows 10 1903 (x64) Build: 18362.113 
- **OBS Studio version** : 23.1.0 (64 bit)

[Crash 2019-05-17 11-55-58.txt](https://github.com/Palakis/obs-websocket/files/3190977/Crash.2019-05-17.11-55-58.txt)

**Comment by evilarceus** [comment]
Can confirm this issue as well. Sometimes, it also sends back "Invalid sceneItem order" as an error.
Here's a WebSocket log of this happening:
`SENT: {"request-type": "ReorderSceneItems", "items": [{"name": "Display Capture"}, {"name": "Text (FreeType 2)"}], "message-id": "hi"}

RECEIVED: { "error": "Invalid sceneItem order", "message-id": "hi", "status": "error" }

SENT: {"request-type": "ReorderSceneItems", "items": [{"name": "Display Capture"}, {"name": "Text (FreeType 2)"}], "message-id": "hi"}

RECEIVED: { "sourceKind": "display_capture", "sourceName": "Display Capture", "sourceType": "input", "update-type": "SourceDestroyed" }

RECEIVED: { "sourceKind": "text_ft2_source", "sourceName": "Text (FreeType 2)", "sourceType": "input", "update-type": "SourceDestroyed" }

RECEIVED: { "error": "Invalid sceneItem order", "message-id": "hi", "status": "error" }

DISCONNECTED (OBS crashes)`
