### ISSUE TITLE
Heartbeat docs reference non-existent Stats type (should be OBSStats)

### ISSUE THREAD

**Issue by Lange** [Palakis/obs-websocket#328]
##### Issue type
Docs issue

##### Description
`Heartbeat` docs reference non-existent `Stats` type (should be `OBSStats`)

##### Steps to reproduce and other useful info
Compiling the new typedefs for `obs-websocket-js` fails, due to this reference.

##### Suggested fix
Change this line to use `OBSStats`, instead of `Stats`: https://github.com/Palakis/obs-websocket/blob/061ab12b10e67506a09df0eb1c1c5905b3ec003c/src/WSEvents.cpp#L739

Long-term, we'll want to figure out some way to catch things like this in the build step. I don't have any good ideas for that off the top of my head.

**Comment by Palakis** [comment]
@Lange Thanks, gonna retag 4.6.0 once CI regenerates the documentation.
