### ISSUE TITLE
SceneItemTransformChanged docs reference non-existent SceneItemProperties type (should be SceneItemTransform)

### ISSUE THREAD

**Issue by Lange** [Palakis/obs-websocket#329]
##### Issue type
Docs issue

##### Description
`SceneItemTransformChanged` docs reference non-existent `SceneItemProperties`  type (should be `SceneItemTransform`)

##### Steps to reproduce and other useful info
Compiling the new typedefs for `obs-websocket-js` fails, due to this reference.

##### Suggested fix
Change this line to use `SceneItemTransform`, instead of `SceneItemProperties`: https://github.com/Palakis/obs-websocket/blob/061ab12b10e67506a09df0eb1c1c5905b3ec003c/src/WSEvents.cpp#L1333

Long-term, we'll want to figure out some way to catch things like this in the build step. I don't have any good ideas for that off the top of my head.

**Comment by Palakis** [comment]
@Lange Thanks, gonna retag 4.6.0 once CI regenerates the documentation.
