### ISSUE TITLE
I want to change visibility of current scene that will be streaming now.

### ISSUE THREAD

**Issue by dream811** [Palakis/obs-websocket#332]
Thanks for your advice, Stephane.
I want to change visibility, transition, rotate and timeline(start time and end time) of current scene that will be streaming now.
Is it possible via node-js (obs-websocket-js 3.0.1 package)?
I need your help, please save my life!
Thanks a lot.
- **Operating System** : win 10
- **OBS Studio version** : 23.1
-** obs-websocket-js 3.0

**Comment by MichleLI** [comment]
also I hope to create new scene and scene item with local source(mp4).
any good ideas?

**Comment by MichleLI** [comment]
Hello! Dear Stephane!
Sorry, but I have urgent task, so I need your help.
If you are busy now, please share for me base code or any idea!
Thanks again!

**Comment by tt2468** [comment]
Hi,

We've recently enabled Github discussions on this repo. Issues are now reserved only for bug reports and feature suggestions. If this issue is still relevant, I encourage you to open a new discussion for it.

Thanks
