### ISSUE TITLE
Feature Request: SetSourceSettings for Media source with Start time for playback

### ISSUE THREAD

**Issue by michaeltoohig** [Palakis/obs-websocket#342]
##### Issue type
Feature request

##### Description
I would like a means to set a Media Source to begin playback at a certain time in the video file. Perhaps someone would want to then also request and end time but that's not important to me personally.

```
'sourceSettings' : {'local_file': "path/to/file", 'start': 10.5}
```

I'm not sure if this is already available but I don't see it while searching around with the python implementation of this project.

Thank you.

*EDIT*

Is this functionality available to VLC sources?

**Comment by tt2468** [comment]
This function would require heavy changes to OBS on both the media source and vlc source, along with API for each.

The solution I would give you is to wait for #497 . When it gets finished, you will be able to listen for media playback events and use `SetMediaTime` to immediately set the current media's timestamp.
