### ISSUE TITLE
Atomic transactions

### ISSUE THREAD

**Issue by Lange** [Palakis/obs-websocket#345]
##### Issue type
Very low-priority feature idea

##### Description
I sometimes need to dispatch a bunch of commands to OBS all at once. I never really know if this is safe to do, and it kinda spooks me out every time, especially if they are order-sensitive.

I think it would be cool if I could create a "transaction", which contained many protocol commands in it. `obs-websocket` would receive the transaction as a whole, and then execute the commands in the order specified by the transaction.

Going further, it would be amazing if the transaction could be atomic. That is to say: if any command in the transaction fails, roll back the entire transaction such that it never happened, and we don't end up in a partially applied state. This is much harder than just batching commands together into a transaction, so it would be like a stretch goal on top that could be added later than just basic transactions

**Comment by Palakis** [comment]
@Lange in the meantime, if you're concerned about the order in which requests are executed, on the client-side you can wait for request A to complete before sending request B (in obs-websocket-js I think you can just `await` successive calls). At the cost of potentially higher latency though.

**Comment by Palakis** [comment]
Similar to #134

**Comment by Palakis** [comment]
Tied to #134

**Comment by Palakis** [comment]
Closing this, as it is similar to #134
