### ISSUE TITLE
Switching to studio mode causes OBS crash

### ISSUE THREAD

**Issue by mihalynemeth** [Palakis/obs-websocket#347]
##### Issue type
Bug report

##### Description
OBS crashes when switching to studio mode via websocket-server 
(SetStudioMode/ToggleStudioMode) 
It works perfectly with 4.5.1 plugin version, but v4.6.1 causes crash.
Crash report and obs log attached.

##### Steps to reproduce and other useful info
Install obs-websocket plugin v4.6.1 
Just send SetStudioMode or ToggleStudioMode command to ws server. 

##### Technical information
- **Operating System** : Win10.0 Build 17134 (revision: 829; 64-bit)
- **OBS Studio version** : OBS 23.2.1 (64-bit, windows)

[2019-06-17 11-00-33.txt](https://github.com/Palakis/obs-websocket/files/3296097/2019-06-17.11-00-33.txt)
[obs_crash.txt](https://github.com/Palakis/obs-websocket/files/3296099/obs_crash.txt)

**Comment by Rosuav** [comment]
Can confirm that this happened on Linux using trunk builds of both OBS and OBS-WebSocket. My thinking is that it may be an issue with which thread things are being done on? There's a tiny Qt window that appears just before the crash (which is inside Qt somewhere).

Possibly related to an OBS stall when trying to take a snapshot of a source.

**Comment by illusdidi** [comment]
Can confirm this is happening to me too, when triggering ToggleStudioMode or TransitionToProgram apparently. 
[obs crash.txt](https://github.com/Palakis/obs-websocket/files/3704690/websocket.crash.txt)
[obs crash2.txt](https://github.com/Palakis/obs-websocket/files/3704691/websocket.crash2.txt)
[obs crash3.txt](https://github.com/Palakis/obs-websocket/files/3704692/websocket.crash3.txt)

**Comment by tgudelj** [comment]
Windows 10, OBS Studio 24.0.3 (64 bit)
obs-websocket 4.6.1
crash on: changing studio mode and transition to program
[Crash 2019-11-07 16-58-16.txt](https://github.com/Palakis/obs-websocket/files/3820498/Crash.2019-11-07.16-58-16.txt)

**Comment by me-vlad** [comment]
Hi, I can confirm crash on Windows 10, OBS Studio 24.0.3 (64 bit) + obs-websocket 4.6.1 after transition

**Comment by Palakis** [comment]
This should be fixed by now, will be released in a few days with 4.7.0
