### ISSUE TITLE
Bug Report: Password not saving

### ISSUE THREAD

**Issue by ptree44** [Palakis/obs-websocket#352]
##### Issue Type
Bug report

##### Description
Passwords are not saved

Goes into OBS Studio then topbar, Tools > WebSockets Server Settings > *changes password field* > *double checks enable auth is checked* > ok

Then it never saves. This plugin was working before but it randomly stopped working after opening OBS one day

##### Steps to reproduce and other useful info
23:34:57.620: [obs-websocket] WSServer::start: server already on this port. no restart needed
23:36:27.626: [obs-websocket] WSServer::start: server already on this port. no restart needed
23:39:39.764: [obs-websocket] WSServer::start: server already on this port. no restart needed
23:39:44.902: adding 23 milliseconds of audio buffering, total audio buffering is now 69 milliseconds (source: Mic/Aux)
23:39:44.902: 
23:39:45.036: adding 23 milliseconds of audio buffering, total audio buffering is now 92 milliseconds (source: Desktop Audio)
23:39:45.036: 
23:46:10.903: [obs-websocket] WSServer::start: server already on this port. no restart needed
23:50:21.757: [obs-websocket] WSServer::start: server already on this port. no restart needed
23:54:10.849: [obs-websocket] WSServer::start: server already on this port. no restart needed
23:54:28.630: ---------------------------------
23:54:28.630: video settings reset:
23:54:28.630: 	base resolution:   1920x1080
23:54:28.630: 	output resolution: 1920x1080
23:54:28.630: 	downscale filter:  Bicubic
23:54:28.630: 	fps:               60/1
23:54:28.630: 	format:            NV12
23:54:28.630: 	YUV mode:          601/Partial
23:54:28.630: NV12 texture support enabled
23:54:28.647: Settings changed (advanced)
23:54:28.647: ------------------------------------------------
23:55:26.180: [obs-websocket] WSServer::start: server already on this port. no restart needed
23:55:29.567: [obs-websocket] Update << '{
23:55:29.567:     "item-id": 1,
23:55:29.567:     "item-name": "Audio",
23:55:29.567:     "scene-name": "Twist",
23:55:29.567:     "update-type": "SceneItemSelected"
23:55:29.567: }'
23:56:05.449: [obs-websocket] io thread exited
23:56:05.450: [obs-websocket] server stopped successfully
23:56:05.451: [obs-websocket] server started successfully on port 4445
23:56:05.451: [obs-websocket] io thread started
23:56:18.756: [obs-websocket] io thread exited
23:56:18.757: [obs-websocket] server stopped successfully
23:56:18.757: [obs-websocket] server started successfully on port 4435
23:56:18.757: [obs-websocket] io thread started
23:56:24.851: [obs-websocket] io thread exited
23:56:24.852: [obs-websocket] server stopped successfully
23:56:24.852: [obs-websocket] server started successfully on port 4444
23:56:24.852: [obs-websocket] io thread started

Just to demonstrate it never tries to update the password

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 23.2.1

**Comment by Nameless9** [comment]
I have the same issue. obs.connect() isn't connecting at all. Please fix this. I thought it was fixed in another issue

**Comment by Nameless9** [comment]
It was working properly a few days ago, and then all of a sudden I'm unable to connect it. I'm using the js version to connect remotely to OBS, but I've come across issue #193 That issue was closed and Mr. Palakis said he'll come up with a new branch to fix it soon. I'm looking forward to hearing about it. cheers

**Comment by Palakis** [comment]
@ptree44 @Nameless9 which version of obs-websocket are you running? Tested this with 4.6.1 and t2t2's remote control app on OBS Studio 23.2.1 and I don't have that issue.

Here's what I did:

1. Enable authentication
2. Change password to "somethingA" and validate
3. Try to login on tablet remote, gets asked for password, types "somethingA", auth success
4. Restarted OBS
5. Did step 3 again: success
6. Changed password to "somethingB" and validate
7. Tried logging in to tablet remote with "somethingB", auth success
8. Restarted OBS
9. Did step 7 again: success
