### ISSUE TITLE
What is the default password for OBS-studio?

### ISSUE THREAD

**Issue by Nameless9** [Palakis/obs-websocket#353]
##### Issue type
Bug report? Feature request? Other?
Other
##### Description
What is the default Password of the OBS client? I see 8 hidden characters. My initial guess of "password" is incorrect. I have an issue with password changes not getting saved so I just want to know the default password for my simple use

##### Technical information
- **Operating System** :Windows 10
- **OBS Studio version** :23.2.1

**Comment by Palakis** [comment]
@Nameless9 iirc it's `changeme`
