### ISSUE TITLE
Bug report: OBS crashes sometimes when triggering recording with FSC's commandline tool. 

### ISSUE THREAD

**Issue by kutibotond** [Palakis/obs-websocket#359]
OBS crashes sometimes when triggering recording with FSC's commandline tool. I haven't tested other methods.

[Crash report](https://obsproject.com/logs/etW3Q5J6WYFK_42U)

##### Technical information
- Windows 10 64-bit
- OBS Studio 23.2.1

**Comment by Palakis** [comment]
@kutibotond Can you also please put your crash log here? So that I can keep a track of it.

**Comment by kutibotond** [comment]
The link is in my post.

**Comment by kutibotond** [comment]
here is another one from last night :( https://obsproject.com/logs/oRcJCohc_lPZqduf

**Comment by Palakis** [comment]
@kutibotond Can you please test this version of obs-websocket with FSC's command line tool? https://ci.appveyor.com/api/buildjobs/we8lq75s7kmnsyij/artifacts/obs-websocket-d7f5c04-Windows-Installer.exe

I think I found the cause of the crash, and this version should have the fix for it.
