### ISSUE TITLE
Ability to Start/Stop WebSocket Server

### ISSUE THREAD

**Issue by haganbmj** [Palakis/obs-websocket#36]
**Desired:**  
- The ability to start or stop the server in the settings menu.  
- The ability to store that choice for future sessions.  

**Nice to have:**  
- Main window Indicator/Icon that shows if the server is running.  
- Indication of the server address in the options menu. Ideally the public facing IP with port number.

**Comment by jnovack** [comment]
> Indication of the server address in the options menu.

Tough, it would have to know if it's publicly available (the port is open externally) otherwise the info is potentially bad.  If it's potentially wrong, why show it?

I would rather it not show a user the public address since it cannot verify that it is externally available on that port/address.  Too many "it says 1.2.3.4:1234 but it's not working.. plshalpthx!" threads.

**Comment by Palakis** [comment]
@jnovack what @haganbmj suggests is showing the LAN IP address of the computer, not the public WAN one.

**Comment by jnovack** [comment]
> Ideally the public facing IP with port number.

> ... suggests is showing the LAN IP address of the computer, not the public WAN one.

![image](https://cloud.githubusercontent.com/assets/387006/23037077/19bc4ab4-f453-11e6-8b68-4b39172ae81a.png)

**Comment by haganbmj** [comment]
Hah. Yeah, I had meant the public. 
Maybe the local address with port and a brief instruction about obtaining your public facing address.

**Comment by jnovack** [comment]
We've tangented, that's my fault, and I'm sorry.

Process-wise showing the WAN IP and port is situational at best.  How often are you going to want to expose the websocket side (that doesn't have authentication or encryption) to the public WAN?  Additionally, if you have a functional reason to expose the websocket port publicly, you already understand how to get a public IP and already understand port-forwarding.  If you understand port forwarding, you know that the public port MAY not be equal to the private port.  Thus, I feel like providing it will only CAUSE issues with people who see it and think it's a simple "one-click" and "why isn't it working?"

_The start/stop is extremely helpful, and showing the private ip/port is important._  But, I feel, the "perceived" public ip/port, will only cause issues.  I wouldn't want an awesome project plagued with a misunderstood feature.

**Comment by haganbmj** [comment]
Sure I can get behind that being something that requires system knowledge to access. I do think something of the sort should be documented somewhere though to avoid questions. 

A link to some instructions on github here would be plenty.

**Comment by Palakis** [comment]
Exposing an instance of obs-websocket on the Internet is absolutely not recommanded and heavily discouraged. People doing so should acknowledge they're doing it at their own risk.

**Comment by Palakis** [comment]
My bad, didn't quite got @haganbmj's suggestion right. 
I really wasn't expecting this kind of suggestion, as I always had loopback and LAN access in mind since I started the project, and never though that WAN access would be a legit use case (and I still don't think so).

However, the best contributors and I can do is make sure the server is perfect security-wise.

**Comment by haganbmj** [comment]
WAN is probably not a legit use case,  but it's something to consider documentation about with a big giant warning.

**Comment by Palakis** [comment]
Server Start/Stop is implemented and available in the Settings dialog. 
However it's still a WIP and I already spotted one bug : the program hangs/deadlocks when doing a `QWebSocketServer::close()` on a server with at least one client connected.

**Comment by Palakis** [comment]
Deadlock fixed in https://github.com/Palakis/obs-websocket/commit/0ff4411abf5b1df09200abd1476df71f103e1691.

**Comment by haganbmj** [comment]
Sick, I'll have to load this up when I get the chance. Changes look good.
