### ISSUE TITLE
Is there support capturer option "Enable Transparency" getting/setting?

### ISSUE THREAD

**Issue by MikiraSora** [Palakis/obs-websocket#373]
##### Issue type
Feature request

##### Description
I checked out document and I didn't found anything about how to set/get capturer option named "Enable Transparency". Was I missing something or there is a plan to add it?
![image](https://user-images.githubusercontent.com/7549173/64145488-989ff680-ce4b-11e9-93f5-ddc8d5945fdd.png)

**Comment by Palakis** [comment]
@MikiraSora you can use `SetSourceSettings` to change source settings on the fly from obs-websocket. To find out which property name is behind "Allow Transparency", enable it and use `GetSourceSettings` to fetch the current source settings
