### ISSUE TITLE
[Feature Request] Control volume level

### ISSUE THREAD

**Issue by vorob1** [Palakis/obs-websocket#374]
Good afternoon, 

I just wanted to suggest adding not just the ability to turn on / off the sound from the source, but also control the volume. Viewers often ask to adjust the volume of the game or the voice of the streamer, it is convenient to do this remotely.

Thank!

**Comment by mihalynemeth** [comment]
I think mute/setvolume available in current release:
https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#setvolume

**Comment by vorob1** [comment]
I only see "toggle audio device on off"
https://sun9-42.userapi.com/c852024/v852024954/1b7386/wMZMr1JCXMM.jpg

**Comment by Palakis** [comment]
@vorob1 `GetVolume`/`SetVolume` serve this exact purpose. I think your request belongs in the scope of [t2t2/obs-tablet-remote](https://github.com/t2t2/obs-tablet-remote)
