### ISSUE TITLE
SetStreamSettings not applying when switching from rtmp_common to rtmp_custom

### ISSUE THREAD

**Issue by tt2468** [Palakis/obs-websocket#378]
##### Issue type
Bug report

##### Description
When switching the settings type from rtmp_common to rtmp_custom (along with saving), the server responds as if the settings have changed, but they stay as rtmp_custom.

##### Steps to reproduce and other useful info
1. Set the output stream to twitch, then set any stream key
2. With the websocket, set the new type to rtmp_custom, along with a stream server and key
3. The server will respond with the info you provided.
4. Going into the gui, no info has changed.
5. This is both after setting the save bool to true, and also after running the SaveStreamSettings event.

##### Technical information
- **Operating System** : Windows 10 1809
- **OBS Studio version** : 23.2.1

I've even tried populating any combination of variables. Nothing has worked. This problem exists on any of the common services, not just twitch. When the rtmp type is already set to rtmp_custom, the settings will apply just fine. There is also a notable lack of documentation on the "settings" object.It is referenced but no examples or explanations are ever given.

**Comment by artemjackson** [comment]
Same, OBS 24.02, Mac OS 10.15.1

**Comment by tt2468** [comment]
I think I may have found the issue.
The libobs api call `obs_service_create` [here](https://github.com/obsproject/obs-studio/blob/master/libobs/obs-service.c#L74) looks like it should take `STREAM_SERVICE_ID` before `requestType`, yet the implementation in the various calls [here](https://github.com/Palakis/obs-websocket/blob/4.x-current/src/WSRequestHandler_Streaming.cpp) appears to put `requestType` *before* `STREAM_SERVICE_ID`.

Example: `service = obs_service_create(requestedType.toUtf8(), STREAM_SERVICE_ID, requestSettings, hotkeys);` [this](https://github.com/Palakis/obs-websocket/blob/4.x-current/src/WSRequestHandler_Streaming.cpp#L214)`
