### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Palakis** [Palakis/obs-websocket#38]
It would be nice to have more localizations, like ~~German~~ ([done](https://github.com/Palakis/obs-websocket/pull/40)), Spanish, ~~Portuguese~~ ([done](https://github.com/Palakis/obs-websocket/pull/53)), ...

**Comment by laris151** [comment]
I helped you with the portuguese translate =)

**Comment by Palakis** [comment]
@Iaris151 Thanks! Gonna check this.

**Comment by inpothet** [comment]
Have send some dutch translations over

**Comment by Palakis** [comment]
@inpothet Yes, merged your PR. Thanks!

**Comment by Palakis** [comment]
@inpothet @asquelt @laris151 @Frahmer @Genteure Translations have been moved to Crowdin : https://crowdin.com/project/obs-websocket
Please join the project there to get notified of new strings!
