### ISSUE TITLE
Invalid requests execution order

### ISSUE THREAD

**Issue by CSMBY** [Palakis/obs-websocket#382]
##### Issue type
Bug report

##### Description
Requests are executed in random order

##### Steps to reproduce and other useful info
For example, we send requests in this order:
ResetSceneItem ("Item1")
ResetSceneItem ("Item2")
ResetSceneItem ("Item3")
The execution order of these requests can be absolutely any: Item1, Item2, Item3 or Item2, Item1, Item3, or Item3, Item1, Item2 and etc..
Could this be fixed or is it not a bug, but a feature?
For some scenarios, the execution order of the requests plays an important role.
Important clarification! Before sending the next request, we are waiting for a response on the successful completion of the previous request. The order of execution of the requests is still violated.

##### Technical information
- **Operating System** : Microsoft Windows [Version 10.0.18362.388]
- **OBS Studio version** : 24.0.1

**Comment by Palakis** [comment]
@CSMBY It's not a bug. obs-websocket handles requests asynchronously and provides a `message-id` field to make it easy to tie a response to a request.

If you're in a scenario where request and response order is important and you're using an obs-websocket library with async support (such as the JS library and the Python library), you only need to `await` on each request to wait for the first one to complete before executing the next one.

In the near future there will be a special request type in obs-websocket that can execute a "batch" of several in-order requests (#345).

**Comment by CSMBY** [comment]
The scenario is as follows:
messageId = ResetSceneItem("Item1");
WaitAnswer(messageId);
messageId = ResetSceneItem("Item2");
WaitAnswer(messageId);

The actual order of execution may be:
Item2 has been reset
Item1 has been reset

I understand that I need to wait for an answer with the appropriate message-id.
But this does not always work. In some cases, the execution order changes.
