### ISSUE TITLE
TakeSceneScreenshot

### ISSUE THREAD

**Issue by BarryCarlyon** [Palakis/obs-websocket#383]
##### Issue type
Feature request

##### Description
Similar to `TakeSourceScreenshot` I'd like a `TakeSceneScreenshot`

I imagine this would only be possible to take a shot of the active scene. Which I don't have a problem with if that was the case

**Comment by Palakis** [comment]
@BarryCarlyon You can already do this with TakeSourceScreenshot. Just specify the scene name in `sourceName`.
