### ISSUE TITLE
I managed to come across this crash log while trying to figure out a different problem.

### ISSUE THREAD

**Issue by Druffert** [Palakis/obs-websocket#387]
This happens just letting OBS run, no specific interactions, no starting or ending stream/record or anything. I have 1 scene 1 source that is NDI and nothing else. One note is that, prior to installing Websocket for no reason, I was having OBS CTD with 0 crash logs.
[Crash 2019-11-09 04-15-59.txt](https://github.com/Palakis/obs-websocket/files/3827259/Crash.2019-11-09.04-15-59.txt)

**Comment by Palakis** [comment]
Thanks for this. I'll have a look at what happens in that crashlog. In the meantime, closing this.
