### ISSUE TITLE
OBS crashes after calling ToggleStudioMode/EnableStudioMode

### ISSUE THREAD

**Issue by BarRaider** [Palakis/obs-websocket#389]
##### Issue type
Bug report (obs-websocket 4.7.0 with OBS Studio 24.0.3 - 64 bit)

##### Description
When trying to call EnableStudioMode or ToggleStudioMode the OBS screen flickers but does not actually move into Studio Mode. However, the "Studio Mode" button in OBS *is* enabled. Trying to press the Studio Mode button again to disable it OR trying to call ToggleStudioMode/DisableStudioMode from obs-websocket will cause a crash.
Crash seems to be related to qt5widgets.dll

##### Steps to reproduce and other useful info
*If it's a bug, please describe the steps to reproduce it and PLEASE include an OBS log file. Otherwise, remove this section.*
1. Call EnableStudioMode() or ToggleStudioMode() in obs-websocket-dotnet
-or- Send a request-type of "ToggleStudioMode" or "EnableStudioMode" to obs-websocket
2. Try to click the "Studio Mode" button in OBS
3. Crash

##### Technical information
- **Operating System** : Windows 10 1903 64 bit
- **OBS Studio version** : 24.0.3 64 bit

##### Development Environment
Using both obs-websocket and obs-websocket-dotnet. No issues with compilation.

**Comment by BarRaider** [comment]
Hi,
Just checking back on this, I see it was targeted for 4.7.1 - any idea when this will be released?

**Comment by BarRaider** [comment]
Trying again:
4.7.1 milestone seems empty, is this targeted to 4.7.1 or 4.8

**Comment by mknooihuisen** [comment]
Doesn't this bug belong in the 4.8 Milestone @Palakis , since it looks like the 4.7.1 release has scrapped?

**Comment by Palakis** [comment]
@mknooihuisen @BarRaider This was fixed in 4.7.1 indeed. Forgot to properly close it when it was released.

**Comment by Palakis** [comment]
Managed to reproduce the bug, lifting the "investigation needed" label away.

**Comment by mknooihuisen** [comment]
Thanks for working on this @Palakis!
