### ISSUE TITLE
recording folder

### ISSUE THREAD

**Issue by Ang3ls** [Palakis/obs-websocket#39]
congratulations for the project, I would like to know if it is possible to get through the API target of the recordings folder. I would not set them only for reading
Thank you

**Comment by Palakis** [comment]
@Ang3ls This seems possible but I'll double-check this in the OBS API just to be sure of this.

**Comment by Ang3ls** [comment]
wonderful
If you can direct me to the correct documentation will help you in this check.

**Comment by haganbmj** [comment]
@Ang3ls here's what the frontend api exposes. https://github.com/jp9000/obs-studio/blob/master/UI/obs-frontend-api/obs-frontend-api.cpp

**Comment by Palakis** [comment]
I believe that implementing this would require using `obs_frontend_get_global_config()` or `obs_frontend_get_profile_config()`.

**Comment by paul-lrr** [comment]
Related to the above, It would be useful if` GetStreamingStatus()` and the `StreamStatus` and `RecordingStarted/Stopped` events returned the name (and path) of the recording file instead of (or in addition to) the boolean status of the recording.

**Comment by Palakis** [comment]
Implemented in https://github.com/Palakis/obs-websocket/commit/f001d18eeaa8786273364e2be659b6ffaf2297f5.
