### ISSUE TITLE
Building into temp dir still reads includes from wrong location

### ISSUE THREAD

**Issue by Rosuav** [Palakis/obs-websocket#392]
##### Issue type
Bug report

##### Description
Setting `LIBOBS_INCLUDE_DIR` does not prevent incorrect header files from being included.

If libobs exists as a system installation, it is difficult to build a temporary libobs and then compile obs-websocket against the temporary one. It appears that pkg-config still points to the system installation. Setting PKG_CONFIG_PATH doesn't cure this.

##### Technical information
- **Operating System** : Linux
- **OBS Studio version** : 24.0.3

##### Development Environment
    PKG_CONFIG_PATH=/home/rosuav/tmp/obs/lib/pkgconfig
    cmake -DLIBOBS_INCLUDE_DIR=/home/rosuav/obs-studio/libobs -DCMAKE_INSTALL_PREFIX=/home/rosuav/tmp/obs ..

In theory, this should include files exclusively from the temporary directory and/or the source directory. In practice, it still compiles with `-isystem /usr/include/obs` and gets the wrong versions of some header files.

Note that `pkg-config libobs --cflags` from the shell *does* point to the correct directory.

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks

**Comment by Rosuav** [comment]
@Palakis Is it true that work on 4.x has stopped? What's going on here? The repo's default branch is still 4.x-current.
