### ISSUE TITLE
Implement SelectSceneItem

### ISSUE THREAD

**Issue by Livastyle** [Palakis/obs-websocket#395]
##### Issue type
Feature request

##### Description
There are events for SceneItemSelected & SceneItemDeselected.
For completion I would like to see requests for this:
 - SelectSceneItem
 - DeselectSceneItem

**Comment by tt2468** [comment]
Figured I'll just bring it up. I don't think that these requests should be added unless there is an actual use for them. I'm starting to get worried about the amount of requests we have causing feature bloat.

**Comment by tt2468** [comment]
Decided against implementing. Thank you for your suggestion
