### ISSUE TITLE
Video playback not beginning

### ISSUE THREAD

**Issue by michaeltoohig** [Palakis/obs-websocket#396]
##### Issue type
Bug Report.

##### Description
Let me know if this is my error/expected behavior or a bug or if this is outside of this repo's control.

A little background first, I am using this repo to control a remote OBS instance to play a continuous streaming TV channel. With different scenes for main content, advertisement breaks, weather updates, etc. The main scene plays videos from a media source and I update the `local_file` setting to point to the video to start playing.

When setting the source `local_file` attribute prior to setting the scene the source will not start the new video file play back about 1 in 10 times. The times that the file does not begin playback, I can open the source settings by double clicking on it in OBS and then immediately the file does begin playback as expected.

Setting the scene first (even when the scene is the current scene) then setting that scene's source settings does seem to playback immediately every time or at least the last 24 hours I've been periodically keeping my eye on the video playback.

Of course I have fixed my own issue it seems but I thought I should report this.

##### Steps to reproduce and other useful info
I am using the `obs-websockets-py` wrapper so here is my code for example to reproduce the issue.

```
obsreq.SetSourceSettings(SourceName, {'local_file': '/local/path/to/file'})
obsreq.SetCurrentScene(SceneName)
```

But swapping the order of the two commands results in no problems. I'm not sure why I can not theoretically set the Source Settings first then when I call the Scene it should begin playback or not interfere with it playing if it already began.

##### Technical information
Windows 10
OBS 23.1.0 64 bit version

**Comment by tt2468** [comment]
This sounds like it could be an obs issue. Can you confirm that the issue is still active in the latest obs version? (25.0.7)

**Comment by michaeltoohig** [comment]
I have seen the issue in 24 and I already made a work around that checks if the video is playing by taking a screenshot and comparing some pixels so I haven't been paying attention to this issue anymore.

I'll have to test 25 a bit before I move it into production where I could add some logger to my code to see how often the work around is called.

**Comment by tt2468** [comment]
This should be patchable on the clientside by applying the settings, then retrieving the playback state with `GetMediaState`
