### ISSUE TITLE
API: SetSceneItemProperties should accept item.id for handling 1 scene:N items:1 source

### ISSUE THREAD

**Issue by strotlog** [Palakis/obs-websocket#398]
##### Issue type
Feature request

##### Description
Many requests provide for a scene item ID field `item.id (int)` in the request, but `GetSceneItemProperties` and `SetSceneItemProperties` do not yet. Instead, currently scene items are addressed by name only, and the API implementation picks the first matching item.

However, **duplicated scene items always have the same name. ID specificity, or a similar feature, is required in order for clients to be able to address duplicated items within the same scene.**

Example use case: Restreaming someone else's stream for a race. Often there is 1 VLC source for the racer's own stream. This stream is used as an input source in the restream's OBS, where it is then cropped into multiple pieces (to pull in the racer's game, racer's timer, racer's webcam...). To achieve multiple crops from a single high bandwidth input, the OBS user duplicates the VLC scene item and crops each copy differently. These items have the same source and scene item name, but different IDs and crops. I would like to read and write each of these crops.

(No Workaround: I considered a workaround where I would reorder the scene items to cause the Properties request to address different items as the "first item". However, I don't see a way to maintain scene item groups when reordering. Much obliged if anyone else can find a workaround for now.)

##### Technical information
- **Operating System** : Windows 10, Linux
- **OBS Studio version** : 24.0.3

**Comment by Palakis** [comment]
Tied to #154

**Comment by strotlog** [comment]
Thank you very much Palakis!

**Comment by Palakis** [comment]
@strotlog You can play with these changes using the latest test build (requires the [Universal VC++ Runtime](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads). It's the VC2015, VC2017 and VC2019 runtimes in a single redistributable): https://dev.azure.com/Palakis/obs-websocket/_build/results?buildId=1032&view=artifacts&type=publishedArtifacts
