### ISSUE TITLE
Add support for controling the T-Bar

### ISSUE THREAD

**Issue by lebaston100** [Palakis/obs-websocket#399]
##### Issue type
Feature request

##### Description
It would be very handy to have support for the new T-Bar feature that was added with https://github.com/obsproject/obs-studio/commit/a97039db64abd788a675b019bd7f2dd61f69952b

**Comment by me-vlad** [comment]
T-bar feature included to the OBS release 25.0 (RC4 for now)

**Comment by joedemax** [comment]
Which release will this be included in?

**Comment by regiside** [comment]
Really excited to have this functionality in OBS! Been waiting on it for years! Thanks for your hard work on this guys!
