### ISSUE TITLE
[Bug] [Regression] Can't Set Stream Settings

### ISSUE THREAD

**Issue by OpaqueStephanie** [Palakis/obs-websocket#402]
#### Issue type
Bug report!
Follow up of this post: https://obsproject.com/forum/threads/obs-websocket-remote-control-of-obs-studio-made-easy.58018/page-9#post-409838

#### Description
Setting the stream settings using SetStreamSettings or StartServer doesn't work. StartServer works in 4.5.1 but is broken in 4.6.1 and 4.7.0. SetStreamSettings doesn't save the settings in any version.

#### Details
After connecting I tried the following two commands. The first command's values do not show up in the streaming settings in any version of obs-websockets. The second command throws an error in 4.6.1 & 4.7.0 they about the url having the incorrect format (because it's not being set, and I have the input set to empty in the UI), however the exact same command works fine in 4.5.1 (I didn't touch the code, only downgraded the version to the one specified in the post linked above).
```
{
		"request-type": "SetStreamSettings",
		"stream": {
			type: "rtmp_custom",
			settings: {
				server: IngestURL,
				key: "default",
				"use-auth": false,
			},
			save: true
		}
	}
```
```
{
		"request-type": "StartStreaming",
		"stream": {
			type: "rtmp_custom",
			settings: {
				server: IngestURL,
				key: "default",
				"use-auth": false
			}
		}
	}
```
Log: https://opaque.sharepoint.com/:t:/s/AIVA/EfiGY3pu1xNIs29nAC29dWoB4xbCsqg2UZxASEQP2MBtFg?e=yd7srm

#### Technical information
- **Windows Version:**  10.0 Build 18362
- **OBS Version:** 24.0.3 (64-bit, windows)

**Comment by tt2468** [comment]
What stream settings mode is OBS already in? #378 reports that if the stream settings mode is rtmp_common, it fails to switch to rtmp_custom when it should.

**Comment by OpaqueStephanie** [comment]
Yeah I saw that bug, it's already set to custom though. I will need that one fixed too though because I'm making a tool that should automatically configure a user's obs installation to stream to an available remote server (for evaluation).

**Comment by tt2468** [comment]
I've submitted a PR which fixes the issue I mentioned above. Could you retest this using 4.7 and post the obs log with debug logging enabled?

**Comment by oscadev** [comment]
In my case, it works if I manually change server to "custom" first. Hoping for a fix, though.

**Comment by oscadev** [comment]
@OpaqueStephanie "use-auth" should be "use_auth". I reported this docs issue earlier today.
