### ISSUE TITLE
Feature Request: Set/Get Audio Monitoring on sources

### ISSUE THREAD

**Issue by michaeltoohig** [Palakis/obs-websocket#403]
##### Issue type
Feature

##### Description
Control the Audio Monitoring options from the Advanced Audio Properties window. I want to be able to change a source dynamically from "Monitor Off" to "Monitor and Output".

##### Steps to reproduce and other useful info
This may be related to an old issue from 2017 https://github.com/Palakis/obs-websocket/issues/152 or not. However, this is absolutely related to an issue I opened with OBS about overflowing audio buffers. If I can remotely set the Audio Monitoring option of a source I can prevent the audio buffers from overflowing. https://github.com/obsproject/obs-studio/issues/2348

I've tried setting volumes, muting, and even changing audio sync offset to cause the audio buffer to reset but it has no effect. Changing the Audio Monitoring option to "Monitor Off" and back to "Monitor and Output" is the only thing that works besides restarting OBS but that is not an option.

**Comment by strikedamic** [comment]
I concur. Having this ability would help me tremendously.

**Comment by strikedamic** [comment]
I concur. Having this ability would help me tremendously.
