### ISSUE TITLE
Feature request: set recording filename

### ISSUE THREAD

**Issue by InQBuilder** [Palakis/obs-websocket#407]
##### Issue type
Feature request

##### Description
 i was really hoping for a feature to remotely name the save file for obs studio. I was under the assumption that the SetFilenameFormatting was a protocol to name/rename the save file. Am i correct on this, is there another suitable available protocol, or no current protocol to name save file remotely?

##### Technical information
- **Operating System** : windows, android, ios
- **OBS Studio version** : 24.0.3 (64bit, windows)

**Comment by tt2468** [comment]
The filename itself is set with `SetFilenameFormatting` (default `%CCYY-%MM-%DD %hh-%mm-%ss`). OBS appends the file extension to the filename formatting.

The record file directory is set with `SetRecordingFolder`.

**Comment by STL1811** [comment]
Hi, 
`SetFilenameFormatting` and `GetFilenameFormatting` disappear in V5.1
It is the same for `SetRecordDirectory`.
Is it possible to add them again ?

**Comment by minorDeveloper** [comment]
@tt2468 do you know if there was a practical reason for this being removed?

**Comment by DoubleF3lix** [comment]
I'm proud to report that this works (in `obsws-python`):
```py
connection.get_profile_parameter("Output", "FilenameFormatting").parameter_value
connection.set_profile_parameter("Output", "FilenameFormatting", "My File Name")
```

**Comment by STL1811** [comment]
Thank you @DoubleF3lix !
it works fine  !
using OBSWebSocketDotNet : 
`obs.SetProfileParameter("Output", "FilenameFormatting", "My Filename");
 var ret = obs.GetProfileParameter("Output", "FilenameFormatting");
 ret["parameterValue"]` contains the current filenameformatting.

**Comment by SunboX** [comment]
Can I use this with https://github.com/obs-websocket-community-projects/obs-websocket-js ? If so, how?

**Comment by SunboX** [comment]
ahh, got it! 😄

```
obs.call('SetProfileParameter', {
     'parameterCategory': 'Output',
     'parameterName': 'FilenameFormatting',
     'parameterValue': 'Test'
})
```
