### ISSUE TITLE
TransitionBegin reports the wrong duration of Stinger Overrides

### ISSUE THREAD

**Issue by Lange** [Palakis/obs-websocket#408]
##### Issue type
Bug report 🐛

##### Description
`TransitionBegin` reports the `duration` of the transition incorrectly when the transition is both an Override and a Stinger.

##### Steps to reproduce and other useful info
1. Create a Stinger transition
2. Assign it as a Transition Override on a Scene
3. Transition to that scene
4. Observe that the `duration` reported by `TransitionBegin` will be whatever this numeric input is set to, and not the actual duration of the Stinger: 
![image](https://user-images.githubusercontent.com/873012/73988487-7c2b4d00-4908-11ea-81c9-9f33da21648b.png)

##### Technical information
- **Operating System** : Win 10 x64 Pro 18363
- **OBS Studio version** : 24.0.3

**Comment by Palakis** [comment]
Fixed by #411
