### ISSUE TITLE
StreamingTime assigned to recordingTime.

### ISSUE THREAD

**Issue by harm27** [Palakis/obs-websocket#412]
##### Issue type
Bug report

##### Description 
I was reading your to understand where the recording time would come from, but i saw that the streaming time was incorrectly also assigned to the recordingTime.
https://github.com/Palakis/obs-websocket/blob/e1a2f0c0f4ce0fe868b664cf4cdc4e77650de9bb/src/WSEvents.cpp#L244

**Comment by Palakis** [comment]
@harm27 Thanks, gonna fix this
