### ISSUE TITLE
TakeSourceScreenshot doesn't work with JPEG output on Windows

### ISSUE THREAD

**Issue by Palakis** [Palakis/obs-websocket#415]
##### Issue type

Bug report

##### Description

TakeSourceScreenshot called with `jpeg` or `jpg` as its output format doesn't work on freshly installed Windows 7 or Windows 10 systems.

##### Steps to reproduce and other useful info

Test this on a fresh Windows install.

**Comment by Palakis** [comment]
Per Lioran's report on Discord:

> jpg,JPG,jpeg,JPEG,PNG all return unsupported format
bmp works, file is created and i get the based64 reply from obs. 
png Create the png file and i get disconnected from obs instantly without a reply.
I do not get disconnected and i get the base64 code fine if i dont specify the file path

> png request im sending
{"saveToFilePath":"hello.png","sourceName":"Stream ongoing main","embedPictureFormat":"png","request-type":"TakeSourceScreenshot","message-id":"6666"}

> bmp request i'm sending
{"saveToFilePath":"hello.bmp","sourceName":"Stream ongoing main","embedPictureFormat":"bmp","request-type":"TakeSourceScreenshot","message-id":"6666"}
where is it saved if i dont specify the file path

**Comment by Palakis** [comment]
PNG saving works on Windows 7, both for file saving and embedded export. However, JPEG doesn't work at all on Windows 7.

**Comment by Palakis** [comment]
JPEG doesn't work at all on Windows 10 as well.

**Comment by tt2468** [comment]
Can confirm though that png and jpg works fine on linux

**Comment by Palakis** [comment]
@tt2468 Thanks!

**Comment by BerkeKaragoz** [comment]
Jpg and jpeg still doesn't work on my machine: 
![image](https://user-images.githubusercontent.com/34271483/111030773-24b5b580-8415-11eb-916c-6609f885cbd2.png)

However, png and bmp are fine: 
![image](https://user-images.githubusercontent.com/34271483/111030790-37c88580-8415-11eb-99f3-cfc1bcb01559.png)

![image](https://user-images.githubusercontent.com/34271483/111030809-575fae00-8415-11eb-9de2-a6df90355bdf.png)
