### ISSUE TITLE
[QUESTION] How to use multiple instances of obs-websocket ?

### ISSUE THREAD

**Issue by Boulzor2019** [Palakis/obs-websocket#417]
##### Issue type
It's just a question It is simply a question of how to start multiple instances of OBS and start obs-websocket with different ports.

##### Description
I start several instances of OBS. I would like to be able to save the port used by obs-websocket in my different profiles but I have not found how to do it. It is always the same port that opens for each instance. I have found in closed requests that the problem has been resolved, but I do not know how to do it.

##### Technical information
- **Operating System** : Windows 10 Professionnal (x64)
- **OBS Studio version** : OBS 24.0.3 (x64)
- **OBS-websocket version** : 4.7.0 win.

Thanks for your help.

**Comment by tt2468** [comment]
Try using OBS in portable mode and having one folder per obs

**Comment by Boulzor2019** [comment]
Great. Thank you so much.

It works perfectly.
