### ISSUE TITLE
Where to view API usage documents

### ISSUE THREAD

**Issue by Jimt2019** [Palakis/obs-websocket#418]
Where to view API usage documents？For example, I choose window capture, how to get all windows？

**Comment by Palakis** [comment]
@Jimt2019 
> For example, I choose window capture, how to get all windows？

What do you mean? Getting the list of available windows from window capture settings?

**Comment by Palakis** [comment]
Btw, API documentation for the latest release of obs-websocket is available here: https://github.com/Palakis/obs-websocket/blob/4.7.0/docs/generated/protocol.md
