### ISSUE TITLE
Play/pause media source?

### ISSUE THREAD

**Issue by andreymal** [Palakis/obs-websocket#423]
Media and VLC sources have hotkeys that control playback. It would be nice to control them using websocket if it's technically possible. As I understand PROTOCOL.md, now I can only restart playback by changing the `local_file` property using `SetSourceSettings`, but it's not enough in some cases.

![](https://i.imgur.com/YORq4qT.png)

**Comment by michaeltoohig** [comment]
I would really love to have this also, especially the play/pause and restart actions. It would help me with #396 since I am currently monitoring for playback failures and have to re-send the `local_file` to restart playback, which works mostly.

**Comment by Palakis** [comment]
I believe this should belong to the scope of #288
