### ISSUE TITLE
HotKeys: requests and events

### ISSUE THREAD

**Issue by emendes-daitan** [Palakis/obs-websocket#427]
##### Issue type
Feature request

##### Description
Provide the ability to register events and send requests related to Hotkeys. (the main goal is to send 'PressHotkey' request)
Possible contents:
- Events
  - Hotkeys
    - HotkeyPressed
    - HotkeyUpdated
- Requests
  - Hotkeys
    - GetHotkeys
    - SetHotkey
    - PressHotkey

**Comment by tt2468** [comment]
The request functionality has been implemented in 5.0.0. Unfortunately, the event functionality is not possible without major OBS changes.
