### ISSUE TITLE
Add request type to get the settings specification for a specified source type

### ISSUE THREAD

**Issue by macharborguy** [Palakis/obs-websocket#432]
##### Issue type
GetSourceFilterInfo and GetSourceFilters return an empty "settings" property when default values are set.

##### Description
When requesting filters via GetSourceFilterInfo and GetSourceFilters, the response data has an empty object for the "settings" property UNLESS the fields are set to something other than their default value OR they are manually set to their default value (via text fields, dropdowns, sliders, etc).  "Default Settings" buttons will result in the values not being reported via the websocket interface.

##### Steps to reproduce and other useful info
Create a new filter on a source, but do not change from the default values.  Call GetSourceFilterInfo or GetSourceFilters.  The "settings" property is an empty object.

Changing a single setting in the Filters options and rerunning the same request code results in that single setting appearing in the setting object.

Changing the setting back to the original setting (manually, NOT via defaults button) properly sends the setting.

Clicking the Defaults button resets everything, resulting in the empty settings object again.

- The Color Correction filter, for example, has a default GAMMA value of 0 (zero).
- Requesting settings for that filter results in {}
- Manually change Gamma to 1
- Requesting settings again results in { gamma : 1 }
- Manually change Gamma back to 0
- Requesting settings results in { gamma : 0 }
- Press Defaults button to reset settings
- Requesting settings results in {}

NOTE: Settings visibility DOES persist after closing and relaunching OBS.  If the settings appear in one request, they will continue to appear after closing and relaunch.

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 24.0.3
- **OBS WebSocket version** : 4.7.0
- **OBS WebSocketJS version** : 4.0.1

**Comment by macharborguy** [comment]
Amendment to Description : Default value for filter settings CAN be set, but must be set manually, rather than automatically via Filter creation or Defaults button.

- The Color Correction filter, for example, has a default GAMMA value of 0 (zero).
- Requesting settings for that filter results in {}
- Manually change Gamma to 1
- Requesting settings again results in { gamma : 1 }
- Manually change Gamma back to 0
- Requesting settings results in { gamma : 0 }
- Press Defaults button to reset settings
- Requesting settings results in {}

**Comment by macharborguy** [comment]
Looking into the code for both obs-websocket and obs-studio regarding the processing of getting the filter settings, it appears that this is more of an obs-studio specific issue, as obs-websocket is just using a native method of obs-studio to access the filter information.

until a workaround or fix can be found and implemented directly into obs-websocket or obs-studio, if anyone needs access to specific filter settings, make sure you adjust each setting and document the different property names and what each value represents in the case of a dropdown with named settings (they sometimes appear as a simple integer via the websocket request).

Plugin-provided sources such as "User-Defined Shader" is an interesting case, since each Shader has its own properties.

**Comment by Palakis** [comment]
@macharborguy This is normal behaviour in OBS. Settings objects only have user-set values. What I can do I provide a way to get the default settings for a specific source kind, if that's not already the case.

**Comment by Palakis** [comment]
What I can do is add the ability to fetch the settings spec for a specified source kind.
