### ISSUE TITLE
GetVolume gives wrong values when slider under -35db

### ISSUE THREAD

**Issue by BarRaider** [Palakis/obs-websocket#441]
##### Issue type
Bug report (obs-websocket 4.7.0 with OBS Studio 25.1 - 64 bit)

##### Description
GetVolume returns values that do not correlate with neither the db or the the slider's position. 
For example :
0db = 1
-1db = 0.89
-2db = 0.79
-3db = 
...
-10db=0.31
-20db=0.099
-30db=0.031
-35db=0.0178
-40db=0.01
.... <--- Everything under this is under 0.01
-60db=0.0009
-90db=3.1708583264844492E-05

Seems to be a regression from previous versions.

##### Steps to reproduce and other useful info
Call GetVolume() (tested through obs-websocket-dotnet)

##### Technical information
- **Operating System** : Windows 10 1909 64 bit
- **OBS Studio version** : 25.1 64 bit

**Comment by tt2468** [comment]
I have previously had this issue but didn't connect the dots that it was a glitch. Can confirm reproducible on 24.0.3 using Windows 10

**Comment by tt2468** [comment]
So update on this. The value coming out of obs-websocket is actually the linear current of the audio. Measered in uA.

Using [this chart](http://emc.toprudder.com/formulas2.pdf), the calculation to go from the linear measurement (uA) to logarithmic measurement (dBuA) is `dBmA = 20log(uA)`

I'll push a clarification in the documentation after I learn more about these calculations.

**Comment by BarRaider** [comment]
Wow, that's an interesting find @tt2468!
