### ISSUE TITLE
Seemingly successful install, but no "Websocket server settings" in Tools menu. Windows 7.

### ISSUE THREAD

**Issue by tscizzlebg** [Palakis/obs-websocket#447]
##### Issue type
Bug report

##### Description
Installed obs-websocket, but then I opened OBS, and the "Tools" menu does not contain an item for "Websocket server settings".

##### Steps to reproduce and other useful info
1. From this repo's releases, run the installer "obs-websocket-4.7.0-Windows-Installer.exe".
2. Take all the defaults, including clicking "Ok" or whatever, when it says the obs folder already exists.
3. Open OBS and click the Tools menu, and see that "Websocket server settings" is not there.

I will include an OBS log file when I get the chance (can't access the machine right now).

Everything worked on my Windows 10 computer no problem, so I'm wondering if it has to do with this other machine being Windows 7 (unfortunately, that part's not in my control).

Note that the install didn't give me any error, and I see the obs-websocket.dll/pdb in the C:\Program Files\obs-studio\obs-plugins\64bit folder, so things appear to have worked to some degree, but not fully.

##### Technical information
- **Operating System** : Windows 7
- **OBS Studio version** : 23.0.1

**Comment by tscizzlebg** [comment]
Ok, here's the beginning of the log, up through the relevant part (I assume).

Looks like a few modules failed to load, including the websocket dll. That file is present, so I don't think it's about the file not existing, but perhaps one of the earlier failures caused that failure.

```
14:24:38.533: Command Line Arguments: --minimize-to-tray
14:24:38.583: CPU Name: Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
14:24:38.583: CPU Speed: 2494MHz
14:24:38.583: Physical Cores: 4, Logical Cores: 4
14:24:38.584: Physical Memory: 8174MB Total, 1147MB Free
14:24:38.584: Windows Version: 6.1 Build 7601 (revision: 24545; 64-bit)
14:24:38.584: Running as administrator: true
14:24:38.584: Aero is Enabled
14:24:38.727: Current Date/Time: 2020-03-27, 14:24:38
14:24:38.727: Browser Hardware Acceleration: false
14:24:38.727: Portable mode: false
14:25:18.040: OBS 23.0.1 (64-bit, windows)
14:25:18.040: ---------------------------------
14:25:18.040: ---------------------------------
14:25:18.040: audio settings reset:
14:25:18.040: 	samples per sec: 44100
14:25:18.040: 	speakers:        2
14:25:18.435: ---------------------------------
14:25:18.435: Initializing D3D11...
14:25:18.435: Available Video Adapters: 
14:25:18.563: 	Adapter 1: AMD RADEON HD 6450 
14:25:18.563: 	  Dedicated VRAM: 523075584
14:25:18.563: 	  Shared VRAM:    3207593984
14:25:18.563: 	  output 1: pos={0, 0}, size={1920, 1080}, attached=true
14:25:19.193: Loading up D3D11 on adapter AMD RADEON HD 6450  (0)
14:25:22.572: D3D11 loaded successfully, feature level used: 45056
14:25:25.922: ---------------------------------
14:25:25.922: video settings reset:
14:25:25.922: 	base resolution:   1920x1080
14:25:25.922: 	output resolution: 1280x720
14:25:25.922: 	downscale filter:  Bicubic
14:25:25.922: 	fps:               30/1
14:25:25.922: 	format:            NV12
14:25:25.922: 	YUV mode:          601/Partial
14:25:25.923: NV12 texture support not available
14:25:25.924: Audio monitoring device:
14:25:25.924: 	name: Default
14:25:25.924: 	id: default
14:25:26.007: ---------------------------------
14:25:26.452: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
14:25:26.715: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
14:25:27.952: [AMF] AMF Test failed due to one or more errors.
14:25:27.952: Failed to initialize module 'enc-amf.dll'
14:25:31.760: Module '../../obs-plugins/64bit/libEGL.dll' not loaded
14:25:33.814: [obs-browser]: Version 2.3.0
14:25:41.011: Module '../../obs-plugins/64bit/obs-websocket.dll' not loaded
14:25:43.089: Couldn't find VLC installation, VLC video source disabled
14:25:44.113: No blackmagic support
14:25:45.035: ---------------------------------
14:25:45.035:   Loaded Modules:
14:25:45.035:     win-wasapi.dll
14:25:45.035:     win-mf.dll
14:25:45.035:     win-dshow.dll
14:25:45.035:     win-decklink.dll
14:25:45.035:     win-capture.dll
14:25:45.035:     vlc-video.dll
14:25:45.035:     text-freetype2.dll
14:25:45.035:     rtmp-services.dll
14:25:45.035:     obs-x264.dll
14:25:45.035:     obs-vst.dll
14:25:45.035:     obs-transitions.dll
14:25:45.035:     obs-text.dll
14:25:45.035:     obs-qsv11.dll
14:25:45.035:     obs-outputs.dll
14:25:45.035:     obs-filters.dll
14:25:45.036:     obs-ffmpeg.dll
14:25:45.036:     obs-browser.dll
14:25:45.036:     image-source.dll
14:25:45.036:     frontend-tools.dll
14:25:45.036:     enc-amf.dll
14:25:45.036:     decklink-ouput-ui.dll
14:25:45.036:     coreaudio-encoder.dll
14:25:45.036: ---------------------------------
14:25:45.036: ==== Startup complete ===============================================
```

**Comment by Palakis** [comment]
@tscizzlebg Try installing the Universal VC++ Runtime (VC2015, 2017 and 2019 in a single redistributable) and tell me if it works on your end: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by tscizzlebg** [comment]
@Palakis Thanks!

After installing that, just reopen OBS? Or might it require an uninstall and reinstall of obs-websocket?

**Comment by Palakis** [comment]
@tscizzlebg Just reopen OBS

**Comment by tscizzlebg** [comment]
Reporting back after installing Universal VC++ Runtime: No change. And checked the log file and it looks the same.

**Comment by tscizzlebg** [comment]
Any thoughts based on that result?

**Comment by Palakis** [comment]
@tscizzlebg Can you try this build, please? https://dev.azure.com/Palakis/obs-websocket/_build/results?buildId=1125&view=artifacts&type=publishedArtifacts

**Comment by ArjixGamer** [comment]
Wow, this issue is going on for weeks now. That's some dedication, I would have already given up at this point.

**Comment by tscizzlebg** [comment]
Slowness from my end is cuz I don't have access to the device all the time unfortunately.

**Comment by Palakis** [comment]
@tscizzlebg Oh btw I see you're running OBS v23. I'd recommend updating to OBS v25, as obs-websocket 4.8 depends on features introduces in v25

**Comment by tscizzlebg** [comment]
Sounds good. (Reason I used 23 is that the current OBS download page says it supports Windows 8, 8.1, and 10, so I looked at changelogs and dates for older versions and guessed that 23 would still support 7. But sounds like that was unnecessary, and may yet be the issue itself.)

**Comment by tscizzlebg** [comment]
Used the latest versions of OBS and obs-websockets and it works. So OBS is 25, obs-websocket is 4.7, and it works fine. Me preemptively trying to use compatible versions was worse then just using the latest. Lesson learned. Thanks for the responses!
