### ISSUE TITLE
[Bug] GetTextGDIPlusProperties/SetTextGDIPlusProperties reports "not a text gdi plus source"

### ISSUE THREAD

**Issue by 22hn** [Palakis/obs-websocket#454]
##### Issue type
Bug report

##### Description
Seems like GetTextGDIPlusProperties/SetTextGDIPlusProperties fails to correctly identify supplied source name as a gdi text source.

##### Steps to reproduce and other useful info
Simple test from VB.NET
var test01 = _obs.Api.GetTextGDIPlusProperties("TEST01");
throws the error.

##### Technical information
debug log shows that the TEST01 source is indeed of type text_gdiplus_v2:
21:03:24.500: [obs-websocket] Update << '{
21:03:24.500:     "sourceKind": "text_gdiplus_v2",
21:03:24.500:     "sourceName": "TEST01",
21:03:24.500:     "sourceSettings": {
21:03:24.500:         "text": "TEST"
21:03:24.500:     },

and here's the request/response:
21:03:55.071: [obs-websocket] Request >> '{
21:03:55.071:   "request-type": "GetTextGDIPlusProperties",
21:03:55.071:   "message-id": "1uOsAD18jjCNXXgi",
21:03:55.071:   "source": "TEST01"
21:03:55.071: }'
21:03:55.071: [obs-websocket] Response << '{
21:03:55.071:     "error": "not a text gdi plus source",
21:03:55.071:     "message-id": "1uOsAD18jjCNXXgi",
21:03:55.071:     "status": "error"
21:03:55.071: }'

**Comment by Palakis** [comment]
Fixed in #448
