### ISSUE TITLE
Listens only on IPv6. The user should be able to choose IPv6 vs. IPv4

### ISSUE THREAD

**Issue by yurivict** [Palakis/obs-websocket#458]
##### Issue type
Feature request

##### Description
Listens only on IPv6.
> tcp6       0      0 *.4444               *.*                    LISTEN     

There should be a way to control which type of network does the user prefer: IPv4, IPv6 or both.

##### Technical information
FreeBSD 12

**Comment by Palakis** [comment]
This bug seems specific to FreeBSD, as other platforms both support IPv4 and IPv6.
I don't officially support FreeBSD for obs-websocket releases, though I don't mind receiving a patch for that bug if you open a Pull Request to fix it.

**Comment by trinitronx** [comment]
This appears to effect Linux too:

```
$ netstat -tunl -p  | grep -i 4444
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::4444                 :::*                    LISTEN      319776/obs

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

$ uname -a
Linux saturn 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Ideally the user should be able to select which it listens on IPv4 vs. IPv6, and/or the option to listen on both.
