### ISSUE TITLE
OBS Will Not Open 

### ISSUE THREAD

**Issue by jborris** [Palakis/obs-websocket#459]
##### Issue type
Bug report? Feature request? Other?

##### Description
Whenever I try to this plugin, OBS Stops working.  The application will not open.  Crash/Freeze and unloads

##### Steps to reproduce and other useful info
Install OBS latest 64 bit version 25.0.1 64Bit, Then install the WEbSockets
Start OBS.  It never opens.   App opens for a second in task manager and closes.

[2020-04-05 01-21-06.txt](https://github.com/Palakis/obs-websocket/files/4432990/2020-04-05.01-21-06.txt)

##### Technical information
- **Operating System** : Windows 10 1909
- **OBS Studio version** : 25.0.1 64Bit

**Comment by Palakis** [comment]
@jborris Your version of obs-websocket (4.3.0) is way too old, and the version of Qt it was built for (5.7.0) doesn't match the version of Qt OBS uses (5.10.1). Please update obs-websocket and try again.
