### ISSUE TITLE
TransitionBegin has duration field when using T-bar

### ISSUE THREAD

**Issue by lebaston100** [Palakis/obs-websocket#466]
##### Issue type
Bug report/Feature request/nitpicking ;)

##### Description
When using the T-bar in obs 25 starting a fade creates the TransitionBegin event. But this event includes a duration field with a value of 300 in my case. Technically you can't know how long that transition will be so it is kinda "misleading". Some way to know that the t-bar was used instead of reporting a duration might be nice to have.

##### Steps to reproduce and other useful info
- enable studio mode
- transition using the t-bar
- watch output with a websocket client

##### Technical information
- Win 10
- obs 25.0.4
- obs-websocket 4.7.0

**Comment by Palakis** [comment]
This is a bit tricky to detect whenever a transition is a tbar. I need to contribute a fix to libobs so that I can access the transition mode (auto or manual) which is available internally in transitions but not through the libobs API.

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks
