### ISSUE TITLE
Release Timeline

### ISSUE THREAD

**Issue by Huesdon** [Palakis/obs-websocket#47]
Hi Palakis,

Apologies, as I could not figure out any other way to communicate with you. 
I am excited to consume your next version with the fixes and features I am aware of to date.
Asking for release dates is contentious so I would be content with an estimate of days, weeks or months :)

**Comment by Palakis** [comment]
Hello Huesdon,
I've entered testing phase today for release 4.0.0. It definitely won't take months to complete testing, but it might take a week or two depending on my workload on and outside of the project. It's an rough estimate, so **don't take my word from it**.

Open-source projects are generally made with free/spare/unpaid time from volunteers and contributors, so a deadline on a small project like obs-websocket is not something I'd like to impose on myself.

You can reach me by e-mail on `contact at slepin dot fr`. Thanks for communicating, as it show that there are people out there interested in the project, and that's really cool ;)
