### ISSUE TITLE
Automate a scene switch when Start Streaming

### ISSUE THREAD

**Issue by nnm103** [Palakis/obs-websocket#472]
##### Issue type
Other / Feature Request

##### Description
When I hit start streaming on the remote, is there a way to automate a change of scenes immediately as part of one button press (start Streaming)?

Thank you.

**Comment by tt2468** [comment]
This functionality would entirely depend on whatever remote client you are using. In which case, you will need to contact the developers of that application. This library is only the server-sided plugin.
