### ISSUE TITLE
OBS Remote protocol support

### ISSUE THREAD

**Issue by ArhScriptEngineer** [Palakis/obs-websocket#479]
##### Issue type
Bug report

##### Description
Websocket error:
Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

##### Steps to reproduce and other useful info
try connect from http://client.obsremote.com/

##### Technical information
- **Operating System** : Windows 10 (1903)
- **OBS Studio version** : 25.0.8 (64bit)

**Comment by tt2468** [comment]
OBSRemote is no longer in development. Now while I'm not sure if obs-websocket is supposed to still support it, have you tried the newer t2t2 interface? http://t2t2.github.io/obs-tablet-remote/

**Comment by ArhScriptEngineer** [comment]
Thanks for this information
