### ISSUE TITLE
Notify clients when sources are changed in a scene

### ISSUE THREAD

**Issue by Frahmer** [Palakis/obs-websocket#48]
An event to notify clients when sources are renamed or the visibility has been changed.

**"SceneItemChanged"**

An item has been changed in the current scene.
- **"scene-name"** (string) : name of scene
- **"item-name"** (string) : old name of the changed item 
- **"new-item-name"** (string) : old or new name of the changed item if renamed

**Comment by Palakis** [comment]
Ah, good catch, I forgot this one.

**Comment by Palakis** [comment]
I need to investigate this more before implementing it, as I can't find a simple way to listen for source name changes through the OBS Studio API.
One way I'd implement this is by subscribing to signals of each source of the current scene, but I believe this needs more thinking for a good way to subscribe to event types from every source in OBS (and get closer with Studio Mode functionalities).

I've entered testing phase for release 4.0.0, so I won't implement this feature in it, but it will be planned for one of the minor release (maybe 4.1 or 4.2).

**Comment by Frahmer** [comment]
@Palakis Is it possible to implement this event only for visibility change in 4.0? And later for rename and other changes?

**Comment by Palakis** [comment]
@Frahmer visibility change is easily possible though.

**Comment by Frahmer** [comment]
@Palakis It would be great if you can still add this for release 4.0 :)

**Comment by Palakis** [comment]
@Frahmer added in the last commit

**Comment by Frahmer** [comment]
@Palakis That's great, thanks. Can't wait for release :)

**Comment by pantonvich** [comment]
I'm looking for something for when the "Text (GDI+)" "Read from file" data in file gets updated and would return the current StreamStatus i.e. Live/Record seconds (note: it looks like StreamStatus only returns the Live/total-stream-time).
