### ISSUE TITLE
Remote Application Name in OS Notifications

### ISSUE THREAD

**Issue by kylebjordahl** [Palakis/obs-websocket#480]
##### Issue type
Feature request

##### Description
On connect, OBS shows a message to say that a new connection has occurred (a great feature!); it would be great to be able to provide an optional remote application name as part of one of the initial messages to display in that message (along with the IP address info). 

I think it could be added as an argument to `GetAuthRequired` so that the application name is available whether or not any further authentication is required, and could be used in alerts regarding authentication failure as well.

##### Technical information
- **Operating System** : MacOS 10.15.3 (19D76)
- **OBS Studio version** : 25.0.8

**Comment by tt2468** [comment]
While I think this would be a cool feature, can you think of any other parts of the system that this can be used in? Having a request field which only sets a string in the notification seems a bit odd.

**Comment by Palakis** [comment]
The problem I have with this is that the application name can easily be spoofed that way.

What I have in mind for a potential future security model for obs-websocket:
- User provides the global password to the client app
- Client app tries to connect use the global password
- The plugin pops up "X is trying to connect to your obs-websocket server. Approve, Approve once or Deny?"
- If the user clicks "Deny", the connection is dropped. If the user clicks "Approve" or "Approve once", the plugin issues app-bound credentials (akin to an access token in OAuth) to the client.
- The client then uses this "access token" to authenticate to the obs-websocket server without approval prompts for a limited time.
