### ISSUE TITLE
GetStudioModeStatus

### ISSUE THREAD

**Issue by CVHvisuals** [Palakis/obs-websocket#485]
##### Issue type
Bug report

##### Description
I am not receiving an update with the GetStudioModeStatus call

##### Steps to reproduce and other useful info
obs.send('GetStudioModeStatus').then(result => {
            _studioStatus = result.studioMode;

##### Technical information
Mac
- **OBS Studio version** :
25.0.8  Websocket v4.8.0

I have almost no knowledge of js besides what I learned this week, so I may just be doing something wrong in my code. The status updates when I load the html UI.
I have the same code for recording/streaming and both update live.
Any pointers would be appreciated.

**Comment by tt2468** [comment]
What OS is obs-websocket running on? I was able to perform the request just fine: `{'status': 'ok', 'studio-mode': False}`

**Comment by CVHvisuals** [comment]
Thanks for the reply. I can get the initial status. The issue I am having is that is does not seem to stay alive after the request. 
I am using the websocket on PC and Mac. 4.8v
I am having the same issue with the timecodes for record and stream. 
it loads the initial time as a snapshot instead of staying alive. 
I am using this with java and html interface on iOS. 
![C79A361F-0E45-4931-81D5-5F929B415B53](https://user-images.githubusercontent.com/52896813/81459149-65490080-916c-11ea-8d49-efacb62d3aa5.jpeg)

**Comment by tt2468** [comment]
Sounds like you are now talking about a different problem. What events/requests are you using with this new problem? I haven't had any timecode issues and I use it all the time.

**Comment by CVHvisuals** [comment]
obs.send('GetStudioModeStatus').then(result => {
_studioStatus = result.studioMode;

I am learning java, I may not be implementing this correctly.

**Comment by tt2468** [comment]
So the response key name is `studio-mode`, not `studioMode`. I don't know java, but this stackoverflow article seems to describe how to use kebab case: https://stackoverflow.com/questions/43536921/json-response-with-dash-in-the-key-name

**Comment by nxtreaming** [comment]
> Thanks for the reply. I can get the initial status. The issue I am having is that is does not seem to stay alive after the request.
> I am using the websocket on PC and Mac. 4.8v
> I am having the same issue with the timecodes for record and stream.
> it loads the initial time as a snapshot instead of staying alive.
> I am using this with java and html interface on iOS.
> ![C79A361F-0E45-4931-81D5-5F929B415B53](https://user-images.githubusercontent.com/52896813/81459149-65490080-916c-11ea-8d49-efacb62d3aa5.jpeg)

This interface looks very beautiful
Where can I get it ?

Thanks.

**Comment by CVHvisuals** [comment]
Thank you tt2468. I will do research for conversion or translating from kebab. You can mark this as closed since it is a coding issue on my part. 

Thanks nxtreaming. The app is still a work in progress, and getting feedback from a couple parameters needs to be addressed. I will most likely post in OBS Forums once it is complete. 
Thanks for the interest.
