### ISSUE TITLE
OBS crash on streaming restart when start and stopped through WebSocket

### ISSUE THREAD

**Issue by faithoflifedev** [Palakis/obs-websocket#486]
##### Issue type
Bug report

##### Description
 I can make OBS crash by sending the command sequence "StartStopStreaming", "GetStreamingStatus","StartStopStreaming", "GetStreamingStatus", "StartStopStreaming", after authentication of course.

Essentially what I am trying to do is start a second streaming session. The second "start" always crashes OBS.

##### Steps to reproduce and other useful info
Connect and authenticate through obs-websocket send a StartStopStreaming or StartStreaming then StartStopStreaming or StopStreaming.  With the next StartStreaming the streaming won't start and attempting to exit OBS will cause it to crash.

##### Technical information
- OSX 10.15.4
- OBS 25.0.8
- obs-websocket (recently compiled)

[crash_report.txt](https://github.com/Palakis/obs-websocket/files/4569542/crash_report.txt)

**Comment by tt2468** [comment]
I attempted to reproduce this with latest obs-websocket and obs v25.0.8 on Ubuntu 20, but was unable to reproduce.

I performed each request sequentially, each one waiting until obs-websocket sends a response before continuing to the next request. No artificial delays added.

**Comment by faithoflifedev** [comment]
An update, I tried with obs-studio_20200503-git-1_amd64.deb which I just compiled and obs-websocket 4.7.0-1 since I could not get the latest source to compile. O/S is Ubuntu 18.04.4 LTS.

I'm seeing the identical problem as with OSX.  @tt2468 , how are you sending commands through obs-websocket?  I've used ws-websocket-js as well as a dart language library that I'm working on, bith have the same result.

**Comment by tt2468** [comment]
I'm controlling using my simpleobsws library. Here is the code:
```Python
import asyncio
import simpleobsws
import sys

loop = asyncio.get_event_loop()
ws = simpleobsws.obsws(host='192.168.1.147', port=4444, password='MYSecurePassword', loop=loop)

async def on_exit(data=None):
    sys.exit()

async def make_request():
    await ws.connect()
    ws.register(on_exit, 'Exiting')
    await ws.call('StartStopStreaming')
    await ws.call('GetStreamingStatus')
    await ws.call('StartStopStreaming')
    await ws.call('GetStreamingStatus')
    await ws.call('StartStopStreaming')

loop.run_until_complete(make_request())
```

**Comment by faithoflifedev** [comment]
I simplified you test to provided to the following:
> import asyncio
> import simpleobsws
> import sys
> 
> loop = asyncio.get_event_loop()
> ws = simpleobsws.obsws(host='192.168.1.84', port=4444, password='test', loop=loop)
> 
> async def on_exit(data=None):
>     sys.exit()
> 
> async def make_request():
>     await ws.connect()
>     ws.register(on_exit, 'Exiting')
>     await ws.call('StartStopStreaming')
> 
> loop.run_until_complete(make_request())

I can make the problem occur with the following sequence of actions:

1. python3.7 test.py (then wait for streaming to start)
2. python3.7 test.py (then wait for streaming to stop)
3. python3.7 test.py (the connecting button goes grey and I have to force quit causing a crash dump)

**Comment by tt2468** [comment]
I still couldn't get it to crash. Does streaming encoder change the behavior at all?

**Comment by faithoflifedev** [comment]
I'll test the above hopefully later today.  My current work-around is to restart OBS before starting the stream through a websocket.  So my shell script first starts OBS then runs my websocket related code.  Another script runs later and uses websockets to stop the stream and then shutdown OBS.

**Comment by tt2468** [comment]
@faithoflifedev Any update on this?

**Comment by faithoflifedev** [comment]
Sorry for the delay @tt2468 , with a work-around in place I had trouble finding time to get back to this.  I just tested with Apple TV H264 Hardware Encoder and Software Encoder, the only other options available beyond the default x264 and OBS crashes as described above.

**Comment by tt2468** [comment]
Are you able to produce a crash log for this?

**Comment by faithoflifedev** [comment]
@tt2468 , it appears that the problem has disappeared in the recent version of OBS.
