### ISSUE TITLE
Custom filter settings?

### ISSUE THREAD

**Issue by dakom** [Palakis/obs-websocket#487]
##### Issue type
Other

##### Description

I'm just sortof looking things, gathering some preliminary info for an idea...

If I write a filter that controls, say, chromakey in a specific way - and exposes a few settings like Source Color and Replace Color - can I use obs-websocket to change those settings on the custom filter remotely?

If so- do you mind sharing a rough high-level view of what's involved?

**Comment by tt2468** [comment]
So in the api there is no option to directly update a source filter, however there are options to get, remove, and add filters.

See [here](/docs/generated/protocol.md#getsourcefilterinfo) for how to get the source filter info and settings. Below it are `AddFilterToSource` and `RemoveFilterFromSource`.

So if you want to update a filter's settings, you would get the filter settings format with `GetSourceFilterInfo`, then delete the filter with `RemoveFilterFromSource`, then immediately add it back with updated settings with `AddFilterToSource`

If more people express interested in having a request like `UpdateFilterSettings`, I can look into it.

**Comment by Palakis** [comment]
[`SetSourceFilterSettings`](https://github.com/Palakis/obs-websocket/blob/4.7.0/docs/generated/protocol.md#setsourcefiltersettings) is available since obs-websocket 4.5.0

**Comment by dakom** [comment]
Very cool... @Palakis is there an example of using `SetSourceFilterSettings` somewhere? I tried searching the repo but didn't see anything

**Comment by MarkWasfy00** [comment]
I tried searching for SetSourceSetting for the browser source, but it seems like there's no approach for it.
