### ISSUE TITLE
Inconsistency for scene name in currentScene data object

### ISSUE THREAD

**Issue by dinther** [Palakis/obs-websocket#488]
##### Issue type
Inconsistency for currentScene data object.

##### Description
SwitchScenes event returns a data object holding the currentScene information. The data.sceneName property holds the scene name.

getCurrentScene returns a data object however, in this case data.name property holds the scene name.

As I believe we are dealing with the same data I would expect the variable name for the scene name to be consistent. Hereby the preference for .name as we already know it's a scene object.

Not a huge deal as I can normalise this in my application code but it tripped me up for a while.

##### Technical information
- Windows 10
- OBS 25.0.8

**Comment by tt2468** [comment]
Yeah this is known. You will also find scene name keys called `scene`, `scene-name`, and `sceneName` in various parts of the api. We are going to completely redo the data naming in a future release, and it will follow google's json standards.

**Comment by dinther** [comment]
Cool. There are a lot of API calls that need adding at this point. Will it get wss ?
If you need any help reviewing design aspects of the API I'd be happy to help out.
Years back I did the same for the Google Earth Team at Google.

**Comment by tt2468** [comment]
wss is up to Palakis but for now stunnel can be used.
