### ISSUE TITLE
OBS crashes when closing

### ISSUE THREAD

**Issue by derMiepz** [Palakis/obs-websocket#489]
##### Issue type
Bug report

##### Description
OBS crashes when shutting down. Nothing was connected via websocket

##### Steps to reproduce and other useful info
I just started and closed OBS. Crashlog: https://pastebin.com/1qFP4R2C

##### Technical information
- **Operating System** : Windows 10 1909
- **OBS Studio version** : 25.0.8

**Comment by tt2468** [comment]
Please provide your obs-websocket version, along with any other OBS plugins you have installed. Using OBS 25.0.8 on windows 1909 and obs-websocket 4.7 (release build), I have not experienced any crashes. These are the plugins I have installed 
![image](https://user-images.githubusercontent.com/28720189/81447360-598c1880-9131-11ea-9f7d-da5dd6430d24.png)

**Comment by derMiepz** [comment]
I was actually on 4.6.1 and wasn't able to repro this issue. We'll see if it happens on 4.7.0. I think we can close this issue for now and I will reopen it if I have the ability to do so.
