### ISSUE TITLE
Setup CI on Appveyor

### ISSUE THREAD

**Issue by Palakis** [Palakis/obs-websocket#49]
Appveyor for Windows builds and Travis for Linux + eventually OS X.

**Comment by haganbmj** [comment]
https://www.appveyor.com/docs/deployment/github/

Automated releases would be fantastic.

**Comment by Palakis** [comment]
@haganbmj Currently working on AppVeyor config : https://ci.appveyor.com/project/Palakis/obs-websocket

**Comment by Palakis** [comment]
@haganbmj Nice finding, that would be something cool to setup.

**Comment by Palakis** [comment]
Appveyor successfully but I noticed it builds with MSVC 2015... OBS Studio 18.0.0 is built with MSVC 2013.

**Comment by Palakis** [comment]
Switched to MSVC 2013 and Qt 5.7.0. Windows builds compile successfully and work fine with OBS Studio 18.0.0.

**Comment by haganbmj** [comment]
Under 10 minutes per build and it hosts the built artifacts with prerelease versioning, that's awesome. Looks great.
https://ci.appveyor.com/project/Palakis/obs-websocket/build/4.0.0-23/artifacts

**Comment by Palakis** [comment]
Fortunately the Qt 5.7.0 archive is cached, because it would normally take 20 minutes of download from my server to the build runner...

**Comment by Palakis** [comment]
Setting up Travis is going to be tricky. The Linux environment is based on Ubuntu Trusty, which doesn't have an up-to-date Qt version with QtWebsockets...
