### ISSUE TITLE
Feature request: GetWindowsTitles

### ISSUE THREAD

**Issue by kelexel** [Palakis/obs-websocket#490]
##### Issue type
Feature Request

##### Description
In order to remotely set the "Window Capture" source settings via the API, we require a way to list the "window titles" as OBS sees them, in order to later do something like:
```obs.send('SetSourceSettings', {sourceName: 'Window Capture', sourceSettings: {window: 'SOME_APP_WINDOW_TITLE'} })```

Would it be possible to implement such method that would list opened apps titles..?
Maybe as Requests > General > GetWindowsTitles ?

Thank you!!

##### Technical information
- **Operating System** : OSX, Linux, Windows
- **OBS Studio version** : 25.0.8+

**Comment by tt2468** [comment]
I'm not sure if that feature would be worth adding, since it is outside of the scope of OBS, and more about the window system of the OS. It would also require special handling for windows, macos, and linux.

**Comment by kelexel** [comment]
Hmm, well I understand..
I'm controlling chrome on windows via puppeteer, opening & closing chrome windows remotely.
The Window Capture source is supposed to pick another instance of Chrome if I close and restart it, which it does, but than the image is frozen (exactly like the Window Capture Xcomposite issue in linux).
But, setting the "window" option of Window Capture, or, removing and adding a new Window Capture source fixes the issue.
So I was hopping to be able to remove / create a source each time I close & open a new Chrome.. Or at least, edit the "window" setting of the current Window Capture source.
But to do this, I need the list of window titles for the opened windows, exactly like Window Capture does, which is indeed OS related...
So I guess it's a no go... :(

**Comment by tt2468** [comment]
Well if your window names are predictable, you should be able to reset the source by doing `ResetSceneItem`

**Comment by kelexel** [comment]
Oh, thank you, it works!
When I close and restart a Chrome instance, I also emit a ResetSceneItem on the Window Capture item, and it refreshes the UI properly, both in regular and studio mode!
Thank you so much!

ps: I guess you can close that ticket ;)

**Comment by tt2468** [comment]
Glad it worked
