### ISSUE TITLE
EnableStudioMode, DisableStudioMode crashes OBS on Windows 1909

### ISSUE THREAD

**Issue by tt2468** [Palakis/obs-websocket#492]
##### Issue type
Bug report

##### Description
Using the `EnableStudioMode`, `DisableStudioMode`, and `ToggleStudioMode` requests crashes OBS on Windows 10 1909.

##### Steps to reproduce and other useful info
- Load OBS v25.0.8 on a Windows 1909 system with OBS-Websocket v4.7
- Use a script to send any of the above mentioned requests
- OBS Crashes while trying to toggle studio mode.

##### Technical information
- **Operating System** : Windows 10 1909
- **OBS Studio version** : v25.0.8
- **obs-websocket version**: v4.8

**Comment by tt2468** [comment]
Forgot to mention, I tested this on 2 computers running Windows 1909, and one running Ubuntu 20.04. Both windows PCs crashed, but the Ubuntu pc worked just fine.

**Comment by borazslo** [comment]
Same here.
Windows 10 1909 Pro.
OBS v25.0.0

**Comment by CVHvisuals** [comment]
same results on mac.

**Comment by borazslo** [comment]
Opps.  Duplicate of #389 and #455.  It should have been fixed in #434.

**Comment by tt2468** [comment]
@borazslo Oh wow talk about a mega oversight on my end. I forgot that my test windows PC was still on 4.7! Marking this as closed now.
