### ISSUE TITLE
OBS Media functions

### ISSUE THREAD

**Issue by exeldro** [Palakis/obs-websocket#494]
##### Issue type
Feature request

##### Description
Since version 25 obs has new media functions, it would be very useful if we can use them.

##### Technical information
void obs_source_media_play_pause(obs_source_t *source, bool pause);
void obs_source_media_restart(obs_source_t *source);
void obs_source_media_stop(obs_source_t *source);
void obs_source_media_next(obs_source_t *source);
void obs_source_media_previous(obs_source_t *source);
int64_t obs_source_media_get_duration(obs_source_t *source);
int64_t obs_source_media_get_time(obs_source_t *source);
void obs_source_media_set_time(obs_source_t *source, int64_t ms);
enum obs_media_state obs_source_media_get_state(obs_source_t *source);
void obs_source_media_started(obs_source_t *source);
void obs_source_media_ended(obs_source_t *source);

**Comment by tt2468** [comment]
Good idea. I'll work on this soon
