### ISSUE TITLE
Reliably testing a removed scene

### ISSUE THREAD

**Issue by artdevgame** [Palakis/obs-websocket#500]
##### Issue type
Feature request

##### Description
I would like to know when a scene is removed.

* `ScenesChanged` doesn't fit my purpose as it doesn't disclose what the scene name was or the action that happened
* `SourceDestroyed` is a pretty close fit, but the event is also dispatched when OBS is closed and I can't see a way to distinguish it from the one that is dispatched when deleting a scene.

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 25.0.8 (64 bit)

**Comment by tt2468** [comment]
obs-websocket emits the `Exiting` event before it emits `SourceDestroyed` on exit, so you can disable whatever your code is that runs when `SourceDestroyed` is emitted when `Exiting` is recieved.

**Comment by artdevgame** [comment]
Thanks @tt2468, I'll do that.
