### ISSUE TITLE
Method to rename a scene

### ISSUE THREAD

**Issue by YorVeX** [Palakis/obs-websocket#507]
##### Issue type
Feature request

##### Description
Right now there doesn't seem to be a method to rename a scene. I can find out about scene renames using the ScenesChanged event but not rename a scene myself.

**Comment by tt2468** [comment]
Good idea. I'll work on this and maybe I will be able to include it into 4.8 if there's time.

**Comment by YorVeX** [comment]
Thanks, that would be great! <3
