### ISSUE TITLE
Exit application functionality

### ISSUE THREAD

**Issue by JuanPabloGonzalez1** [Palakis/obs-websocket#511]
##### Issue type
Other

##### Description
Hi! I'm developing an application in Qt using websocket to control OBS. I have already implemented a lot of functionalities using the QWebSocket class. Now I need to be able to close obs from my application but I don't think that this is possible with the current features of the obs-websocket. I also tried closing it with normal QProcess but this causes the obs tray icon to persist in the taskbar until you hover it with the mouse, this doesn´t happen when closed manually.

My questions are:

- This functionality exists and I'm missing something in the documentation?
- If not, is there a plan to add it in the future? Or is it even possible?
- Is it normal for the icon to persist after the application is closed in some cases?

Windows 10
Qt 5.12.3
OBS 23.0.2

**Comment by tt2468** [comment]
The ability to exit OBS remotely does not currently exist. I can look into what it would take to add a request like this.

**Comment by tt2468** [comment]
Also no, it is not normal for the tray icon to persist, and you may be causing OBS to inadvertently crash. On top of that, it can cause OBS to lose data.

**Comment by JuanPabloGonzalez1** [comment]
Thank you for your respone, it would be great to have this request added.

**Comment by tt2468** [comment]
Unfortunately it just doesn't look like the API exists on OBS's end to call a shutdown.
