### ISSUE TITLE
Get/set per-scene transition override

### ISSUE THREAD

**Issue by AlcaDesign** [Palakis/obs-websocket#512]
##### Issue type
Feature request

##### Description
Allow getting and setting the per-scene transition override.

My intended use is to change certain scene transition overrides automatically to enable scene-to-scene transitions. Similar to the "[OBS Transition Matrix](https://obsproject.com/forum/resources/obs-transition-matrix.751/)" plugin.

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 25.0.7 (experimental build)

**Comment by tt2468** [comment]
Is this built into OBS or is it from the transition matrix plugin? If its from the plugin then this would depend #288

**Comment by AlcaDesign** [comment]
It's built-in. Right-click a scene and choose "Transition Override
![image](https://user-images.githubusercontent.com/7132646/82155619-d3ac5380-983b-11ea-8d53-fd9bb857e504.png)

**Comment by tt2468** [comment]
I've just spent some time looking into what can be done and unfortunately, OBS would quite a few changes in order to implement a request for this.

**Comment by AlcaDesign** [comment]
How can OBS Transition Matrix do the work without modifying the OBS source?

[set_source_transition_override](https://github.com/admshao/obs-transition-matrix/blob/15f096ea143051be450e6cc8d07b501df55aa515/obs-transition-matrix.cpp#L102-L116)

**Comment by tt2468** [comment]
Hmm yeah looks like it could work. I'll try it out.
