### ISSUE TITLE
SceneCollectionChanged crashes OBS

### ISSUE THREAD

**Issue by CVHvisuals** [Palakis/obs-websocket#514]
##### Issue type
Bug report

##### Description
SceneCollectionChanged crashes OBS

##### Steps to reproduce and other useful info
Changing Scene Collection in OBS crashes with Event Listener

##### Technical information
- **PC/Mac** :
- **25.0.8** :

**Comment by tt2468** [comment]
I'll need your operating system version, and the obs-websocket version, along with a crash dump and OBS log if you can. It would also be helpful if you could describe in detail the steps to reproduce. I don't have much to work with here.

**Comment by CVHvisuals** [comment]
tt2468, thank you. 
10.15.5(19F83c)
OBS v25.0.8
WebSocket v4.8.0

I sent you an invitation for the app I am working on, if you have the time to take a look. Any insight would be appreciated. I am new to creating software - 2weeks into it. It's possible this may be another mistake on my part.

**Comment by tt2468** [comment]
Alright I'll give it a look.

**Comment by CVHvisuals** [comment]
Still having this issue, did you get a chance to take a look?
here is the thread crash:
Thread 29 Crashed:: Thread (pooled)
0   com.obsproject.obs-studio     	0x000000010d7e82b8 0x10d7b4000 + 213688
1   obs-websocket.so              	0x00000000331ffff7 Utils::GetScenes() + 39 (Utils.cpp:372)
2   obs-websocket.so              	0x00000000331e2c19 WSRequestHandler::GetSceneList(RpcRequest const&) + 41
3   obs-websocket.so              	0x00000000331dc3ff WSRequestHandler::processRequest(RpcRequest const&) + 463 (WSRequestHandler.cpp:176)
4   obs-websocket.so              	0x0000000033203650 OBSRemoteProtocol::processMessage(WSRequestHandler&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 640 (OBSRemoteProtocol.cpp:52)
5   obs-websocket.so              	0x00000000331da756 QtConcurrent::StoredFunctorCall0<void, WSServer::onMessage(std::__1::weak_ptr<void>, std::__1::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >)::$_1>::runFunctor() + 278 (qtconcurrentstoredfunctioncall.h:70)
6   obs-websocket.so              	0x00000000331d8920 QtConcurrent::RunFunctionTask<void>::run() + 48 (qtconcurrentrunbase.h:144)
7   org.qt-project.QtCore         	0x00000001108f111b 0x1108cc000 + 151835
8   org.qt-project.QtCore         	0x00000001108ecfd9 0x1108cc000 + 135129
9   libsystem_pthread.dylib       	0x00007fff6d237109 _pthread_start + 148
10  libsystem_pthread.dylib       	0x00007fff6d232b8b thread_start + 15

**Comment by CVHvisuals** [comment]
obs web-socket was compiled today.

**Comment by CVHvisuals** [comment]
I switched to GetSourcesList instead of GetSceneList and the crash is gone. I am only using the command for source names, what would be the difference?

**Comment by CVHvisuals** [comment]
Im going to close this, as this seems to be related when OBS is on an eGPU monitor. It is the only way I can replicate it.
