### ISSUE TITLE
How to get all the Audio Only Sources in the current Scene independent of OS ?

### ISSUE THREAD

**Issue by soumyadeep-ghosh** [Palakis/obs-websocket#515]
##### Issue type
QUESTION

##### Description
So I was able to get the Sources that are only Audio based on Type-ID that says wasapai-audio-input/output, along with Get Special Sources Command. But wasapi is a Windows feature. Is there any way/request to make it cross platform such that it works equally in Windows as well as Linux ? Or we need to configure it according to the OS OBS is running on ?

**Comment by tt2468** [comment]
This would need to be configured according to the OS. We don't have any audio device API in obs-websocket, only whatever OBS provides through things like `GetSourceSettings`
