### ISSUE TITLE
obs-websocket awesomelist ?

### ISSUE THREAD

**Issue by tconley** [Palakis/obs-websocket#517]
##### Issue type
 Other

##### Description
Has anyone made an awesomelist  (https://github.com/topics/awesome-list ) for obs-websocket? I tried looking for a list of all cool projects that connect to obs via obs-websocket and couldn't find anything.    Shall I start a repo?

**Comment by karlthepagan** [comment]
Hopefully the Companion module is worthy some day, but right now it's not equal to the Elgato offering: https://github.com/bitfocus/companion-module-obs-studio/

**Comment by Palakis** [comment]
@tconley This doesn't exist yet so feel free to start your own!
