### ISSUE TITLE
calling GetAudioMonitorType , SetAudioMonitorType results in invalid request type

### ISSUE THREAD

**Issue by bilguungda** [Palakis/obs-websocket#519]
##### Issue type
Bug report

##### Description
i have obs-websocket version 4.8 but i'm unable to call GetAudioMonitorType and Set method from js , it returns invalid request type error
sending other commands such as SetSourceSettings , ChangeScene working fine

##### Steps to reproduce and other useful info
                obs.send('GetAudioMonitorType', {
                    'sourceName' : 'FFMpegSource'
                })
i'm calling the method like above using v4.8 from html script , sending other commands such as SetSourceSettings , ChangeScene working fine
##### Technical information
- **Operating System** : Ubuntu 20.04
- **OBS Studio version** : 25.0.7

**Comment by tt2468** [comment]
How exactly did you install the latest version of obs-websocket?

**Comment by bilguungda** [comment]
@tt2468 
I followed this instructions https://github.com/Palakis/obs-websocket/blob/4.x-current/BUILDING.md

**Comment by tt2468** [comment]
And can you confirm that you set `-DUSE_UBUNTU_FIX=true` when you ran the cmake command?

**Comment by bilguungda** [comment]
@tt2468 
yes

**Comment by tt2468** [comment]
Ok well I'd say that it must be something on your end, since I'm also on ubuntu 20.04 and have 0 issues running the request.

**Comment by bilguungda** [comment]
@tt2468 
at first i thought this is some version issue so i tested SceneItemLockChanged event which is v4.8 added event but this one working as intended when i change lock GetAudioMonitorType , Set... are the only ones that is not working :(

**Comment by tt2468** [comment]
Ok run `git log` and at the top of your screen you should see the line `commit 590943ed957386a483ec6fca2a8178f7bbd5a0d3`

if that latest commit is not the same, do `git pull` to pull the latest version of the repo and do `make -j4` and `sudo make install` again within the `build` directory

**Comment by bilguungda** [comment]
@tt2468  Thank you a lot for your suggestions after i pulled and did sudo make install my SetAudioMonitorType request finally working.

i have another question if possible , after i sudo make install do i need to copy obs-websocket.so file into my obs-studio plugins folder ? in order for it work ? 
because right know websocket is working without copying .so file

**Comment by tt2468** [comment]
By doing `sudo make install` you install the plugin globally for OBS.

Any time you build obs-websocket on ubuntu you have to always make sure to use the `-DUSE_UBUNTU_FIX=true` flag when using cmake, otherwise it will not install the .so to the correct directories

**Comment by bilguungda** [comment]
@tt2468  got it . thanks a lot i'm closing this now
