### ISSUE TITLE
IP address scan

### ISSUE THREAD

**Issue by CVHvisuals** [Palakis/obs-websocket#520]
Is there an id we can use to receive the IP address of a local OBS Studio session?
I am investigating a method for auto filling a form for connection.

**Comment by tt2468** [comment]
As in get the ip address that the websocket server is bound to?

**Comment by CVHvisuals** [comment]
More like a web socket scanner for available connections. I would like to auto populate the IP address for connection.

**Comment by tt2468** [comment]
obs-websocket does not have any network scanning ability, and unless you scanned a given IP range for connections listening on port 4444, there is no discovery functionality.
