### ISSUE TITLE
Crating scenes and sources

### ISSUE THREAD

**Issue by ProstoSanja** [Palakis/obs-websocket#522]
##### Issue type
Feature request

##### Description
Hey there, currently working on a small scheduler/auto-pilot for obs, and was planning on using this solution for remote control, but was surprised by there not being functions to create scenes and sources.

The option is clearly there in ` libobs/obs-source.h` and `obs.h` as i could tell from taking a glance at OBS docs.

I noticed that in this project you only import frontend and module api. Is there a reason behind that, or am i missing something?

Also if that's a thing worth doing from your standpoint, i'd be happy to investigate and try write this.

**Comment by tt2468** [comment]
#341 I believe adds what you are speaking about.

**Comment by ProstoSanja** [comment]
> #341 I believe adds what you are speaking about.

Yeah, looks pretty much like it. So is it set to be there in 4.9? Or is just on an indefinite hold?

**Comment by tt2468** [comment]
I'm actually kind of unsure of the state. It comes from before my time and from what I can tell is kind of Frozen. Might just restart from scratch since there are probably better ways to implement it

**Comment by ProstoSanja** [comment]
it looked kind of okay from a glance, but ill take a proper look at the situation at some point this week then. 👌

**Comment by ProstoSanja** [comment]
Hey there, i know its kinda offtop, but i seem to be unable to resolve this issue myself.
I've set everything up as is described in instructions, and i even got obs itself to build without any problems and it lauches and workes without issues.

however when i try to configure cmake for obs-websockets, i get this error, even though i set path to the libobs
```
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "FindLibObs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibObs", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibObs" with any
  of the following names:

    LibObsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "LibObs" to CMAKE_PREFIX_PATH or set
  "LibObs_DIR" to a directory containing one of the above files.  If "LibObs"
  provides a separate development package or SDK, be sure it has been
  installed.


Configuring incomplete, errors occurred!
See also "C:/Users/Alex/Documents/Projects/obs-websocket/obs-websocket/build/CMakeFiles/CMakeOutput.log".
```
i also tried doing it on my ubuntu machine and  got the exact same problem there. Any help with that?

**Comment by tt2468** [comment]
@ProstoSanja are you building because you want to test a pr?

**Comment by ProstoSanja** [comment]
Yep, and just to debug some stuff in general.

**Comment by ProstoSanja** [comment]
nvm, solved it
sorry for unnecessary pings, but i guess rubber duck helped
