### ISSUE TITLE
Refresh browser source

### ISSUE THREAD

**Issue by ethaniel** [Palakis/obs-websocket#523]
Sending a "ResetSceneItem" to a browser source does not reload the page.
The only way of doing it is by changing the URL via SetBrowserSourceProperties, however that's a nuisance. 

Can this be fixed?
Thank you.

**Comment by lebaston100** [comment]
Have a look at https://github.com/Palakis/obs-websocket/issues/456 . I think that's what you want.

**Comment by ethaniel** [comment]
Yup, thank you, @lebaston100
