### ISSUE TITLE
19/5000 Download problem! It downloads very slowly! Is there a solution?

### ISSUE THREAD

**Issue by massiach** [Palakis/obs-websocket#530]
##### Issue type
Bug report? Feature request? Other?

##### Description
*Replace this with a description of the bug encountered or feature requested.*

##### Steps to reproduce and other useful info
*If it's a bug, please describe the steps to reproduce it and PLEASE include an OBS log file. Otherwise, remove this section.*

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** :

##### Development Environment
*If you're trying to compile obs-websocket, please describe your compiler type and version (e.g: GCC 4.7, VC2013, ...), and the CMake settings used.  
Remove this section if it doesn't apply to your case.*

**Comment by tt2468** [comment]
Please try to describe your issue in more detail by filling out the issue template.
