### ISSUE TITLE
Websocket only listening on localhost ipv6 in Linux

### ISSUE THREAD

**Issue by lightning-software** [Palakis/obs-websocket#531]
##### Issue type
Other

##### Description
I have installed the websocket 4.6.1-1 amd64 and it only listens on localhost. I need it to listen on all IP's or be able to specify which IP to listen on so I can communicate remotely. Do I need a go between program that resides on the OBS computer to which I connect from a different computer?

##### Steps to reproduce and other useful info
Install Debian. Install OBS from repos. Install obs-websocket that matches the version of OBS. Go to terminal and type netstat -ln

##### Technical information
- **Operating System** : Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux
- **OBS Studio version** : 22.0.3+dfsg1-1

**Comment by lightning-software** [comment]
Does anybody have any ideas/comments? This is a little bit urgent, as I was hoping to use this for Sunday (luckily I have a backup plan). I know it's not necessarily a bug (though, could be), but I was hoping some advice would be forthcoming.

Is this a Linux problem?
Is this normal behavior for the obs-websocket?
Am I missing something completely obvious?

**Comment by tt2468** [comment]
Can you post your netplan/ifupdown configuration? I've had no problems with obs-websocket listening on ipv4 on linux. (Ubuntu 20.04)

**Comment by enzanki-ars** [comment]
I can confirm that this is an issue for me on Ubuntu 20.04.  I have to disable IPv6 because AT&T's IPv6 routing is failing epically. If I don't disable IPv6, then I would have issues connecting to a number of things such as GitLab.  

From my Windows system:
![image](https://user-images.githubusercontent.com/8580211/87101665-bd0ff080-c21d-11ea-86a9-a7932409af77.png)

I disabled it in the kernel and in the sysconfig:

`/etc/default/grub.d/99-enzanki.cfg`:
```
GRUB_CMDLINE_LINUX="ipv6.disable=1"
GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1"
```

`/etc/sysctl.d/98-enzanki.conf`:
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

OBS Logs:

```
07:47:19 PM.416: Kernel Version: Linux 5.4.0-40-generic
07:47:19 PM.416: Distribution: "Ubuntu" "20.04"
07:47:19 PM.417: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.8
07:47:19 PM.417: Portable mode: false
07:47:19 PM.498: OBS 25.0.8 (linux)

[...]

07:47:19 PM.745: [obs-websocket] you can haz websockets (version 4.8.0)
07:47:19 PM.746: [obs-websocket] qt version (compile-time): 5.9.5 ; qt version (run-time): 5.12.8
07:47:19 PM.748: [obs-websocket] module loaded

[...]

07:47:32 PM.215: [obs-websocket] server: listen failed: Address family not supported by protocol
07:47:43 PM.055: [obs-websocket] server: listen failed: Address family not supported by protocol
```

**Comment by enzanki-ars** [comment]
I found the reason for the issue. 

See https://github.com/zaphoyd/websocketpp/blob/f810ca2e800e9b55be41c5911cf1d1185fcd516b/websocketpp/transport/asio/endpoint.hpp#L508-L522

```cpp
    /// Set up endpoint for listening on a port (exception free)
    /**
     * Bind the internal acceptor using the given port. The IPv6 protocol with
     * mapped IPv4 for dual stack hosts will be used. If you need IPv4 only use
     * the overload that allows specifying the protocol explicitly.
     *
     * The endpoint must have been initialized by calling init_asio before
     * listening.
     *
     * @param port The port to listen on.
     * @param ec Set to indicate what error occurred, if any.
     */
    void listen(uint16_t port, lib::error_code & ec) {
        listen(lib::asio::ip::tcp::v6(), port, ec);
    }
```

So, the listen command used in the current code, https://github.com/Palakis/obs-websocket/blob/04c60fd1acb6ca468b35d06dd0def048977f28e5/src/WSServer.cpp#L79 defaults to listening on IPv6, if I am understanding correctly, by listening on `::/0`, and has no fallback to listen on `0.0.0.0` instead if IPv6 is not available.  

This is kind of documented in https://github.com/zaphoyd/websocketpp/issues/157#issuecomment-10039523, with the fix being `_server.listen(boost::asio::ip::tcp::v4(), _serverPort, errorCode)` instead, but I worry about the side effects if for some strange reason people were relying on the IPv6 address for localhost instead, for example as seen in https://github.com/t2t2/obs-tablet-remote/issues/41.

**Comment by tt2468** [comment]
Good find! I'll experiment with it today. For a fix, we could add a settings option to prefer ipv6 listening.

**Comment by enzanki-ars** [comment]
Thanks.  My c++ game is still a work in progress, otherwise I would take a look at implementing this.  I still might, but I'm willing to bet somebody might beat me to the fix.

**Comment by tt2468** [comment]
Can you test https://github.com/Palakis/obs-websocket/tree/enhancement/ipv4-option and verify that it is forcing obs-websocket to bind ipv4?

**Comment by enzanki-ars** [comment]
```
11:40:00 PM.395: [obs-websocket] server started successfully on port 4444
11:40:00 PM.395: [obs-websocket] io thread started
```

That is forcing it to bind to IPv4 now as expected.

```
tcp        0      0 0.0.0.0:4444           0.0.0.0:*               LISTEN      245988/obs
```

**Comment by tt2468** [comment]
Great to hear! I'll work on a PR within the next day or so to add it as a config option.

**Comment by tt2468** [comment]
@enzanki-ars Ok it took a lot less time than I expected lol. Never underestimate the power of hyperfocusing. Go ahead and test #559 for me if you can.

**Comment by enzanki-ars** [comment]
```
02:38:36 PM.505: [obs-websocket] WSServer::start: Not locked to IPv4 bindings
02:38:36 PM.507: [obs-websocket] server: listen failed: Address family not supported by protocol

02:38:46 PM.358: [obs-websocket] WSServer::start: Locked to IPv4 bindings
02:38:46 PM.360: [obs-websocket] server started successfully on port 4444
02:38:46 PM.361: [obs-websocket] io thread started
```

Change looks good and fixes the problem for me.  

```
tcp        0      0 0.0.0.0:4444           0.0.0.0:*               LISTEN      712355/obs
```

It listens correctly, and the setting saves as expected.  Thanks for the fix!
