### ISSUE TITLE
Debian/Ubuntu package versioning scheme is broken since 4.8.0

### ISSUE THREAD

**Issue by schirmeier** [Palakis/obs-websocket#534]
##### Issue type
Bug report

##### Description
Since obs-websocket 4.8.0, the .deb release seems to provide a version in a schema that is incompatible to the previous 4.7.0, making dpkg believe it actually performs a downgrade:

$ sudo dpkg -i obs-websocket-4.8.0-1_amd64.deb 
dpkg: warning: downgrading obs-websocket from 4.7.0-1 to 1-5d12dfa-4.8.0-git-1

The version also looks like this will randomly reoccur with future releases. However, the installation works fine other than being confused about up- vs. downgrade.

##### Steps to reproduce and other useful info
Have obs-websocket 4.7.0 installed. Then download obs-websocket-4.8.0-1_amd64.deb, install it via "dpkg -i".

##### Technical information
- **Operating System** : Ubuntu 20.04
- **OBS Studio version** : 25.0.8-0obsproject1~focal (irrelevant for this bug)

**Comment by tt2468** [comment]
For reproducing, one should have 4.7.0 installed before trying to install 4.8.0, correct?

**Comment by Palakis** [comment]
@tt2468 seems likely, yes

**Comment by schirmeier** [comment]
Yes, sure. I modified the report accordingly. I think this boils down to dpkg (along with the whole Debian/Ubuntu packaging infrastructure) considering "4.7.0-1" > "1-5d12dfa-4.8.0-git-1". See https://www.debian.org/doc/debian-policy/ch-controlfields.html#version

**Comment by tt2468** [comment]
This should be fixed in 4.9.1
