### ISSUE TITLE
Installer fails on Mac OS

### ISSUE THREAD

**Issue by zerozero** [Palakis/obs-websocket#539]
##### Issue type
Bug report

##### Description
Trying to install for a customised version of OBS (https://dash.millicast.com/docs.html?pg=obs-with-millicast). The installer indicates success but no plugin is installed.

##### Steps to reproduce and other useful info
- Download and install the customised version of OBS
- Download version 4.7.0 of obs-websocket (Millicast-OBS is based on OBS v23)
- Run the installer - see the success message
- Open OBS (from command-line to prevent crash)
- Expected result: "Websocket server settings" dialog appears under OBS' "Tools" menu
- Actual result: "Websocket server settings" dialog does not appear under OBS' "Tools" menu

##### Technical information
- OS X 10.15.4
- 23

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks
