### ISSUE TITLE
Azure pipelines variables

### ISSUE THREAD

**Issue by cpyarger** [Palakis/obs-websocket#540]
I am trying to build my OBS plugin on azure pipelines, and used your code as a skeleton framework. I am having build issues on azure, where as if I build locally I have no issues. 

What variables do you have set. And can you post a sanitized version of them so that I may see if that is where my issues lie (:

**Comment by Palakis** [comment]
Have a look at https://github.com/obsproject/obs-plugintemplate. It's a template I made and donated to the OBS org, and it's based on the CI scripts of obs-websocket. All variables are properly documented there.
