### ISSUE TITLE
installation fail on Pop!os

### ISSUE THREAD

**Issue by flasher69** [Palakis/obs-websocket#541]
##### Issue type
Bug report

##### Description
when I try to install obs-websocket on Pop! Os with Eddy I get this installation fail pop up:

The following packages have unmet dependencies:
  obs-websocket: Hängt ab von: obs-studio (>= 25.0.7) but it is not going to be installed

##### Steps to reproduce and other useful info
This is not a bug. I can't install this package at all

##### Technical information
- **Pop! Os** :
- **OBS Studio 25.0.8** :

**Comment by tt2468** [comment]
Hi,

We've recently enabled Github discussions on this repo. Issues are now reserved only for bug reports and feature suggestions. If this issue is still relevant, I encourage you to open a new discussion for it.

Thanks
