### ISSUE TITLE
Won't install with obs-studio 25.0.8 installed via snap (default for software center)

### ISSUE THREAD

**Issue by bmcgonag** [Palakis/obs-websocket#542]
##### Issue type
Bug

##### Description
With obs-studio 25.0.8 installed via snap on ZorinOS 15.2 (Ubuntu 18.04) I get the following error

```
dpkg: dependency problems prevent configuration of obs-websocket:
 obs-websocket depends on obs-studio (>= 25.0.7); however:
  Package obs-studio is not installed.
```
Here's the output of `obs-studio --version`
```
>  obs-studio --version
OBS Studio - 25.0.8-modified (linux)
```

##### Steps to reproduce and other useful info
1. Install obs-studio from the software center or via cli with `sudo snap install obs-studio`.
2. download the latest release `4.8.0.1 amd 64 .deb` version, and attempt to install using `sudo dpkg -i obs-websocket-4.8.0-1_amd64.deb`
3. Install Error occurs

##### Technical information
- **Operating System** : ZorinOS 15.2 (Ubuntu 18.04 reskinned)
- **OBS Studio version** : 25.0.8-modified <- whatever modified means.

##### Development Environment
*If you're trying to compile obs-websocket, please describe your compiler type and version (e.g: GCC 4.7, VC2013, ...), and the CMake settings used.  
Remove this section if it doesn't apply to your case.*

**Comment by tt2468** [comment]
obs-studio on snap is unofficial and not supported. You should take it up with them about it.
