### ISSUE TITLE
Minor: TakeSourceScreenshot is returning a message with an empty message-id

### ISSUE THREAD

**Issue by ethaniel** [Palakis/obs-websocket#543]
Version 4.8.0.
I send off:
```
$client->send(json_encode(array("request-type"=>"TakeSourceScreenshot", "sourceName"=>"Media Beach","embedPictureFormat"=>"jpg","message-id"=>++$message_id)));
```

But get a reply with an empty message-id (all other data is OK however).

Since i'm using a custom websocket library, it adds complexity in searching for replies to requests since I'm expecting the message-id to be available.

**Comment by tt2468** [comment]
Tested on Ubuntu 20.04 and Windows 10, both versions work fine using your provided request parameters.

**Comment by Palakis** [comment]
@ethaniel It seems like the message id you're passing is a number. Convert it to a string before sending it to obs-websocket.
