### ISSUE TITLE
SetSceneItemProperties doesn't work about "position" and "scale", what is the problem in the request?

### ISSUE THREAD

**Issue by mizumasa** [Palakis/obs-websocket#544]
##### Issue type
Bug report

##### Description
SetSceneItemProperties doesn't work well.
Following is the log about request and return.
In SetSceneItemProperties request, "rotation", "locked", and "visible" are working, but 
"position", "crop", "scale" doesn't work. What is the problem?

03:36:48.928: [obs-websocket] Request >> '{"crop.left": 0, "position.y": 0, "position.x": 3.0, "request-type": "SetSceneItemProperties", "visible": null, "position.alignment": 5, "rotation": 5, "crop.right": 0, "crop.bottom": 0, "scene-name": null, "locked": false, "item": "f2", "bounds.y": 1, "scale.y": 1.0, "scale.x": 1.0, "crop.top": 0, "bounds.alignment": 0, "message-id": "7", "bounds.type": "OBS_BOUNDS_NONE", "bounds.x": 1}'
03:36:48.928: [obs-websocket] Update << '{
03:36:48.928:     "item-id": 4,
03:36:48.928:     "item-name": "f2",
03:36:48.928:     "scene-name": "test 2",
03:36:48.928:     "transform": {
03:36:48.928:         "bounds": {
03:36:48.928:             "alignment": 0,
03:36:48.928:             "type": "OBS_BOUNDS_NONE",
03:36:48.928:             "x": 0.0,
03:36:48.928:             "y": 0.0
03:36:48.928:         },
03:36:48.928:         "crop": {
03:36:48.928:             "bottom": 0,
03:36:48.928:             "left": 0,
03:36:48.928:             "right": 0,
03:36:48.928:             "top": 0
03:36:48.928:         },
03:36:48.928:         "height": 504.0,
03:36:48.928:         "locked": false,
03:36:48.928:         "position": {
03:36:48.928:             "alignment": 5,
03:36:48.928:             "x": 1065.0,
03:36:48.928:             "y": 16.0
03:36:48.928:         },
03:36:48.928:         "rotation": 5.0,
03:36:48.928:         "scale": {
03:36:48.928:             "x": -0.69999998807907104,
03:36:48.928:             "y": 0.69999998807907104
03:36:48.928:         },
03:36:48.928:         "sourceHeight": 720,
03:36:48.928:         "sourceWidth": 1280,
03:36:48.928:         "visible": true,
03:36:48.928:         "width": -896.0
03:36:48.928:     },
03:36:48.928:     "update-type": "SceneItemTransformChanged"
03:36:48.928: }'
03:36:48.929: [obs-websocket] Response << '{
03:36:48.929:     "message-id": "7",
03:36:48.929:     "status": "ok"
03:36:48.929: }'

##### Steps to reproduce and other useful info
send socket to OBS with (obs-socket-py)
'{"crop.left": 0, "position.y": 0, "position.x": 3.0, "request-type": "SetSceneItemProperties", "visible": null, "position.alignment": 5, "rotation": 5, "crop.right": 0, "crop.bottom": 0, "scene-name": null, "locked": false, "item": "f2", "bounds.y": 1, "scale.y": 1.0, "scale.x": 1.0, "crop.top": 0, "bounds.alignment": 0, "message-id": "7", "bounds.type": "OBS_BOUNDS_NONE", "bounds.x": 1}'

##### Technical information
mac OS Catalina
OBS 25.0.8(64bit)

##### Development Environment
installed obs-websocket with obs-websocket-4.8.0-macOS.pkg

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks
