### ISSUE TITLE
Feature request: websocket video stream

### ISSUE THREAD

**Issue by Niek** [Palakis/obs-websocket#545]
##### Issue type
Feature request

##### Description
First of all, thanks for building obs-websocket - it's an amazing plugin!

I've built [OBS-web](https://github.com/Niek/obs-web), a SPA to control OBS. In order to get a view of the preview/program scenes, I take a small screenshot every second (`TakeSourceScreenshot`). This works, but obviously it's not the best experience (delayed, laggy). What would be great if there would be a `StartSourceStream` function or similar that starts a separate video encode that streams to the websocket.

Would this be possible? If not, any other ideas on how to improve the preview experience?

**Comment by tt2468** [comment]
I dont think that this would be a feature worth the incredible amount of work it would take to implement unfortunately. My only suggestion is to use a faster screenshot rate.

**Comment by nxtreaming** [comment]
I suggest you use SRT to transmit an adittional preview stream to your host.

it is not related with obs-websocket.

**Comment by Niek** [comment]
> I suggest you use SRT to transmit an additional preview stream to your host.
> 
> it is not related with obs-websocket.

Once WebSRT (P2P SRT) is [released in some months](https://github.com/Haivision/srt/issues/341#issuecomment-654702064) that would be an option, together with https://github.com/obsproject/rfcs/pull/27

**Comment by tt2468** [comment]
Implementing websrt would be enough work to warrant its own plugin. It is out of the scope of obs-websocket
