### ISSUE TITLE
Crashes when sending GetSceneList after ScenesChanged on scene delete

### ISSUE THREAD

**Issue by t2t2** [Palakis/obs-websocket#55]
Was randomly adding and removing scenes when suddenly removing scenes ended up in a crash, so far been able to constantly reproduce by opening test case, refreshing the page and then removing a scene in obs

test case, logs and stack trace: https://www.dropbox.com/sh/uc0vhjm76ozoy43/AAAHv4vSrz9WI0Is2E8EmhMBa?dl=0

socket traffic:

```
obs:recieve Object { update-type: "ScenesChanged" }  test.html:28:4
obs:sending Object { request-type: "GetSceneList", message-id: String }  test.html:36:5
obs:recieve Object { current-scene: "Scene 3", message-id: "1", scenes: Array[6], status: "ok" }  test.html:28:4
obs:recieve Object { scene-name: "Scene 3", update-type: "SwitchScenes" }  test.html:28:4
obs:recieve Object { update-type: "ScenesChanged" }  test.html:28:4
obs:sending Object { request-type: "GetSceneList", message-id: String }  test.html:36:5
obs:recieve Object { current-scene: "Scene 2", message-id: "2", scenes: Array[5], status: "ok" }  test.html:28:4
```

**Comment by Palakis** [comment]
Can reproduce it on my laptop while in Power Saving mode, but not in Performance or Balanced mode.
Seems like a race conditon.

**Comment by Palakis** [comment]
The race condition seems to be caused by two consecutive calls to `signal_handler_disconnect`, and happens within pthreads.
