### ISSUE TITLE
Output requests fail with 'missing request parameters`

### ISSUE THREAD

**Issue by Zingabopp** [Palakis/obs-websocket#553]
##### Issue type

Bug report

##### Description
With obs-websocket 4.8.0, the requests `GetOutputInfo`, `StartOutput`, and `StopOutput` fail with 'missing request parameters'. All three of these requests work on 4.7.0 (although StartOutput fails if the Output hasn't been previously started by some other method). I've also has OBS crash on 4.8.0 a few times when making these requests, I don't know if that's related.

##### Steps to reproduce and other useful info
I implemented the requests in my [fork of obs-websocket-dotnet](https://github.com/Zingabopp/obs-websocket-dotnet/tree/outputs) on the `outputs` branch and added a section in the TestClient for them.

1. Build and run the TestClient.
2. Connect to OBS.
3. Click the `List Outputs` button in the `Outputs` group box.
4. Select one of the outputs in the list so its name shows up in the text box.
5. Click `Get Output`

Log:
[2020-07-03 18-15-23.txt](https://github.com/Palakis/obs-websocket/files/4871960/2020-07-03.18-15-23.txt)
Log from the working responses on 4.7.0:
[2020-07-03 20-23-19.txt](https://github.com/Palakis/obs-websocket/files/4871965/2020-07-03.20-23-19.txt)

##### Technical information
- **Operating System** : Windows 10 Pro 1909 x64
- **OBS Studio version** : 25.0.8 (64 bit)
- **obs-websocket version** : 4.8.0

**Comment by tt2468** [comment]
Can confirm that the issue exists on Windows. Linux, however, doesn't have the issue for some reason.

**Comment by Palakis** [comment]
Managed to reproduce it on Windows, even as far as making the plugin crash.
