### ISSUE TITLE
Feature request: Get recording file name

### ISSUE THREAD

**Issue by Dunk52** [Palakis/obs-websocket#554]
##### Issue type

Feature request

##### Description

Hello. May I request additional features?
I am using OBS Websocket well.
I want to get the recording file name and replay buffer file name.
I made the current program C#.
I would like to import the replay or recording file name to `GetReplayBufferFile` or `GetRecordingFile` of C#.

This is an example because I'm making a C#.
Example) label1.Text = _obs.GetReplayBufferFile();
Example) label1.Text = _obs.GetRecordingFile();

"Translated by Google Translator and Papago Translator."

##### Technical information
- **Operating System** : Windows 10 Pro x64
- **OBS Studio version** :  25.0.8
- **obs-websocket version** :  4.8

**Comment by tt2468** [comment]
We already have `GetRecordingFolder` and `SetRecordingFolder`

Are you suggesting that we add `GetReplayBufferFolder` and `SetReplayBufferFolder`?

**Comment by Dunk52** [comment]
> We already have `GetRecordingFolder` and `SetRecordingFolder`
> 
> Are you suggesting that we add `GetReplayBufferFolder` and `SetReplayBufferFolder`?

No, I'd like to get the recording file name.
I want to finish recording or get the name of the replay buffer file.
(`2020-MM-DD hh-mm-ss.mp4` or `[Replay]2020-MM-DD hh-mm-ss.mp4`)
`GetRecordingFolder` is in use. 

I want to get the file name in the picture.
![obs](https://user-images.githubusercontent.com/28643783/86861372-e9cee580-c101-11ea-881e-ddc4cd9f1a85.PNG)

**Comment by Zingabopp** [comment]
You can get the full path to the currently recording file by using `ListOutputs` or `GetOutput` (Although GetOutput seems to be bugged in obs-websocket 4.8). They aren't implemented in obs-websocket-dotnet though. You're out of luck regarding the replay buffer file, besides doing something like setting a format that doesn't use wildcards or getting the most recently changed file from the replay directory.

**Comment by tt2468** [comment]
Sorry for dropping off. I have your answer.

https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getfilenameformatting

You can get the formatting for the filename there. It is the same string that you see in `Filename Formatting` in your streenshot. At the moment, there is no way to change the record format though. I have it on my list to move these requests the the `Recording` section to improve clarity.

**Comment by tt2468** [comment]
Closing this now since I assume your issue has been fixed by the lack of response.
