### ISSUE TITLE
Doesn't understand how the sourceSettings object works

### ISSUE THREAD

**Issue by Shaltear** [Palakis/obs-websocket#556]
Hello,
I don't understand how the "sourceSettings" object contained in "SetSourceSettings" works.
I'm looking to activate / desactivate a media source (ffmpeg_source).

I would do something similar to this:
obs.send('SetSourceSettings', {'sourceName' : 'Source', 'sourceSettings' : 'enable = false'});

Can you give me an example please?

Operating System : Windows 10 Pro x64
OBS Studio version : 25.0.8
obs-websocket version : 4.8

**Comment by watfordjc** [comment]
sourceSettings is an object, and its contents will vary by sourceType.

To use your example, if ***Source***'s sourceType has an ***enable*** property in *sourceSettings*, the JSON request would be similar to the following (note the braces):

```json
{
  "request-type": "SetSourceSettings",
  "sourceName": "Source",
  "sourceSettings": {
    "enable": false
  }
}
```

Looking at ffmpeg_source specifically, [I didn't see an **enable** property](https://github.com/watfordjc/csharp-stream-controller/blob/master/OBSWebSocketLibrary/Models/TypeDefs/SourceTypes/Video.cs) when I was recently modelling the source types.

I think you are after SetSceneItemProperties (true = visible/enabled, false=invisible/disabled):
```json
{
  "request-type": "SetSceneItemProperties",
  "scene-name": "Optional Scene Name",
  "item": "Source",
  "visible": true
}
```

Depending on the source's settings and the video, you might also want to use SetSourceSettings to change **close_when_inactive** before playback and/or after disabling it (i.e. false before playback so it is ready to go, true after using SetSceneItemProperties so it isn't kept open):

```json
{
  "request-type": "SetSourceSettings",
  "sourceName": "Source",
  "sourceType": "ffmpeg_source",
  "sourceSettings": {
    "close_when_inactive": true
  }
}
```

**Comment by Shaltear** [comment]
This is exactly what I was looking for, thank you very much.
It was a great help to me!
thanks thanks thanks
