### ISSUE TITLE
Raise events for preview window changes?

### ISSUE THREAD

**Issue by eropple** [Palakis/obs-websocket#56]
Hey there! First off, I wanted to thank you for `obs-websocket`--this is awesome software and I love integrating with it.

Second, a feature request--maybe it's not possible because of the way that OBS works, but I'm wondering about the feasibility of preview scene notifications in Studio Mode. I use HTML5/Canvas overlays (a shared BrowserSource per "scene category"; cameras can switch in a single scene category without replacing the overlay) and it would be _super_ useful from a CPU conservation standpoint to be able to disable rendering on inactive scenes. But, obviously, we want to render them in preview, too.

My C++ is rusty to the point of comedy but I'd be happy to help out if I can.

**Comment by Palakis** [comment]
Hi Ed,
This is a feature I'd like to implement. I need to dig OBS' code to see if this is possible.

**Comment by Palakis** [comment]
I also would like to implement more request types related to the Studio Mode.

**Comment by eropple** [comment]
Awesome - happy to help if I can, because Studio Mode is great. Right now I just disable all overlays for non-primary windows and trust that I've set them up correctly, but that's a little bit sketchy. :)

**Comment by Palakis** [comment]
@eropple Studio Mode support has been implemented!

**Comment by eropple** [comment]
Whoa. You're awesome, dude, this'll help a lot with the stuff I'm doing. Cough cough:

https://github.com/bossmodecg/module-obsstudio

Thanks for pinging me, too, otherwise I probably would have taken a few days to notice.

**Comment by Palakis** [comment]
@eropple Thanks for sharing! Btw the way, the Studio Mode features of the plugin were sponsored work commissioned by Support Class.
