### ISSUE TITLE
Feature Request: Add support for scene-name in GetSourceSettings/SetSourceSettings

### ISSUE THREAD

**Issue by BarRaider** [Palakis/obs-websocket#562]
##### Issue type
Feature request

##### Description
To align with the obs-websocket-dotnet implementation, it would be helpful to have an optional scene-name which will allow fetching/setting information on a source which is not necessarily the current selected source.

##### Steps to reproduce and other useful info
Example of this in obs-websocket-dotnet:
https://github.com/Palakis/obs-websocket-dotnet/blob/4b4931eef8941e7196761db59f652762349b0e21/obs-websocket-dotnet/OBSWebsocket_Requests.cs#L1216

**Comment by tt2468** [comment]
Scenes have no relevance to sources, only scene items. As such, the `SetSourceSettings` and `GetSourceSettings` requests apply to the source itself and therefore all of its scene item references (it doesnt apply directly to the sceneitems, just inherits)
