### ISSUE TITLE
Error with obs-frontend-api.h when compiling.

### ISSUE THREAD

**Issue by MarioMey** [Palakis/obs-websocket#567]
##### Issue type
- Bug report

##### Description
There's an error when compiling obs-websocket as compile [instructions](https://github.com/Palakis/obs-websocket/blob/4.x-current/BUILDING.md) says:

```
mario@debian:~/src/obs-websocket/build$ sudo make install
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mario/src/obs-websocket/build
[  3%] Automatic MOC and UIC for target obs-websocket
[  3%] Built target obs-websocket_autogen
Scanning dependencies of target obs-websocket
[  7%] Building CXX object CMakeFiles/obs-websocket.dir/src/obs-websocket.cpp.o
/home/mario/src/obs-websocket/src/obs-websocket.cpp:20:10: fatal error: obs-frontend-api.h: No existe el fichero o el directorio
 #include <obs-frontend-api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-websocket.dir/build.make:63: CMakeFiles/obs-websocket.dir/src/obs-websocket.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/obs-websocket.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

##### Steps to reproduce and other useful info
Compile obs-websocket as compile [instructions](https://github.com/Palakis/obs-websocket/blob/4.x-current/BUILDING.md) says.

##### Technical information
- **Operating System** : Debian Buster 10, Mate Desktop
- **OBS Studio version** : 25.0.7-198-g8ec1edb6
- **obs-websocket version** : Just cloned

##### Development Environment
gcc 8.3.0-6

**Comment by MarioMey** [comment]
My mistake, but maybe there's an error in compile instructions: I compiled with Debian but, as instructions say **"in Debian/Ubuntu"**, I used:

`cmake -DLIBOBS_INCLUDE_DIR="<path to the libobs sub-folder in obs-studio's source code>" -DCMAKE_INSTALL_PREFIX=/usr -DUSE_UBUNTU_FIX=true ..`

But it seems that `-DUSE_UBUNTU_FIX=true` is not for Debian, just for Ubuntu.

**Comment by tt2468** [comment]
Are you still having an issue? `-DUSE_UBUNTU_FIX` simply installs the binary into a second directory, so it should have nothing to do with your compile. From your log, it seems that there may be missing files.

**Comment by julijane** [comment]
@MarioMey You need to get the sources of obs studio and then actually put the path to a subfolder of it in this parameter:

```
-DLIBOBS_INCLUDE_DIR="<path to the libobs sub-folder in obs-studio's source code>" -
```

**Comment by MarioMey** [comment]
I don't know why, it was fixed. Maybe I did something, maybe it fixed itself.

@tt2468 You are right, now it compiles with or without that flag.
@julijane Yes, I had configured it... I just wrote above it in the generic way, I will edit it.

**Comment by lblabr** [comment]
i do have the same error, how do you fixed that ?

`sudo cmake -DLIBOBS_INCLUDE_DIR=../../obs-studio/libobs -DCMAKE_INSTALL_PREFIX=/usr/obs_master ..`



```
pi@raspberrypi:~/Downloads/obs-websocket/build $ sudo make
[  3%] Automatic MOC and UIC for target obs-websocket
[  3%] Built target obs-websocket_autogen
[  6%] Building CXX object CMakeFiles/obs-websocket.dir/obs-websocket_autogen/mocs_compilation.cpp.o
In file included from /home/pi/Downloads/obs-websocket/build/obs-websocket_autogen/UVLADIE3JM/moc_WSEvents.cpp:10,
                 from /home/pi/Downloads/obs-websocket/build/obs-websocket_autogen/mocs_compilation.cpp:2:
/home/pi/Downloads/obs-websocket/build/obs-websocket_autogen/UVLADIE3JM/../../../src/WSEvents.h:23:10: fatal error: obs-frontend-api.h: Datei oder Verzeichnis nicht gefunden
   23 | #include <obs-frontend-api.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-websocket.dir/build.make:76: CMakeFiles/obs-websocket.dir/obs-websocket_autogen/mocs_compilation.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/obs-websocket.dir/all] Fehler 2
make: *** [Makefile:136: all] Fehler 2
pi@raspberrypi:~/Downloads/obs-websocket/build $

```

**Comment by tt2468** [comment]
Please do not hijack old issues for support.
