### ISSUE TITLE
Feature Request: DeleteScene Request

### ISSUE THREAD

**Issue by ccMatrix** [Palakis/obs-websocket#568]
##### Issue type
Feature request

##### Description
While there is a request `CreateScene` which creates new scenes, there currently is no request which deletes a scene.

Please add a new request `DeleteScene` that allows us to delete a scene from OBS. 

`DeleteScene` should probably remove the scene with all it's sources. The scene to delete can therefore be empty or populated with scene items. Both cases should work.

##### Steps to reproduce and other useful info
- Create a scene using `CreateScene`
- Populate it with `AddSceneItem`
- Try to remove the scene :)

##### Technical information
- **Operating System** : Windows 10 64bit
- **OBS Studio version** : 25.0.8
- **obs-websocket version** : 4.8.0

**Comment by tt2468** [comment]
Unfortunately, after looking into it, this request would not be possibly to *properly* implement. It can technically be done, but it would possibly cause intermittent crashing or undefined behavior, so it will need to depend on OBS changes.

**Comment by Hannah-GBS** [comment]
Is there any word on whether the required OBS changes are planned or is this still just in limbo?

**Comment by tt2468** [comment]
This has been implemented in 5.0.0
