### ISSUE TITLE
Web socket connection issues

### ISSUE THREAD

**Issue by Bl3rdbox** [Palakis/obs-websocket#572]
##### Description
 I believe it looses connection whenever I try to activate a trigger in obs. Im trying to setup Filter Toggle and a Liornboard. So when I intialy set them up they work for about 2 minutes or so then tell they disconnect. The disconnection happens when I I try to trigger an event or just randomly as my computer is sitting idle. 
##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : OBS 25.0.8
- **obs-websocket version** : OBS-Websocket 4.8.0
![Socket issue](https://user-images.githubusercontent.com/69053588/89064266-4acb9100-d32f-11ea-8de5-8c3b132c4998.png)

**Comment by tt2468** [comment]
Could you post an OBS log?

**Comment by Bl3rdbox** [comment]
[2020-07-31 12-59-30.txt](https://github.com/Palakis/obs-websocket/files/5008459/2020-07-31.12-59-30.txt)

**Comment by Bl3rdbox** [comment]
[2020-07-31 12-49-36.txt](https://github.com/Palakis/obs-websocket/files/5008466/2020-07-31.12-49-36.txt)

**Comment by tt2468** [comment]
Not seeing anything wrong here. Sounds like an issue with either your firewall or lioranboard. Since this issue has been inactive for a long period of time, I'm going to assume that it has since been fixed and I'll close this.
