### ISSUE TITLE
OBS Crash when closing OBS

### ISSUE THREAD

**Issue by xalexslx** [Palakis/obs-websocket#574]
##### Issue type

- Bug report

##### Description
This crash happened after finishing my stream and clicked to close my OBS while some applications might be still using websocket.

Log File: 
[Crash 2020-08-05 02-18-01.txt](https://github.com/Palakis/obs-websocket/files/5026290/Crash.2020-08-05.02-18-01.txt)

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 25.0.8 (64-bit)
- **obs-websocket version** : 4.9 Beta build sent to me via Discord on #569

**Comment by kurodz** [comment]
same as mine
Operating System : Windows 10 (1909)
OBS Studio version : 26.1.0 (64-bit)
#
[Crash 2020-12-22 04-26-00.txt](https://github.com/Palakis/obs-websocket/files/5726372/Crash.2020-12-22.04-26-00.txt)

**Comment by tt2468** [comment]
This should now be fixed in #644

I'm keeping #645 open for now in case anyone has any further comments about it.
