### ISSUE TITLE
TakeSourceScreenshot - sourceName not optional

### ISSUE THREAD

**Issue by BarryCarlyon** [Palakis/obs-websocket#577]
##### Issue type

- Bug report

##### Description

PROTOCOL says that `sourceName` is optional for TakeSourceScreenshot

When omitting the `sourceName` an error is returned.

##### Steps to reproduce and other useful info

Using obs-websocket-js to manage the connection and send requests

```
    obs.send(
        'TakeSourceScreenshot',
        {
            embedPictureFormat: 'png',
            width: 200,
            height: 130
        }
    )
        .then(resp => {
            console.log(resp);
        })
        .catch(err => {
            console.error(err);
          });
```

Results in an error

    missing request parameters

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 25.0.8
- **obs-websocket version** : 4.8.0

**Comment by tt2468** [comment]
Fixed in v4.9.0
