### ISSUE TITLE
Won't load module in Linux

### ISSUE THREAD

**Issue by jfreak53** [Palakis/obs-websocket#58]
I'm using ubuntu 16.04 with OBS 0.16.2 and plugin version 0.3.1. I've installed via deb.

When I go to run OBS I get this:

```
error: os_dlopen(/usr//lib/obs-plugins/obs-websocket.so->/usr//lib/obs-plugins/obs-websocket.so): libobs-frontend-api.so.0: cannot open shared object file: No such file or directory

warning: Module '/usr//lib/obs-plugins/obs-websocket.so' not found
```

I've listed the directory in question and the file `obs-websocket.so` is there.

**Comment by Palakis** [comment]
How is your version of OBS installed?

**Comment by jfreak53** [comment]
Through Ubuntu's APT repos if I remember right.

**Comment by Palakis** [comment]
Have a look at the automated builds and try the latest on your system : http://obs-websocket-linux-builds.s3-website.eu-central-1.amazonaws.com/

**Comment by Palakis** [comment]
@jfreak53 Any update on your issue? You may want to try one of the latest builds : https://obs-websocket-linux-builds.s3-eu-central-1.amazonaws.com/obs-websocket_1-bc24497-master-git-1_amd64.deb
