### ISSUE TITLE
SourceCreated event not providing 'sourceSettings'

### ISSUE THREAD

**Issue by Zingabopp** [Palakis/obs-websocket#580]
##### Issue type
 - Bug report 

##### Description
The `SourceCreated` event doesn't seem to ever populate the `sourceSettings` property, possibly because the event is raised as soon as the source configuration window appears. I've tested it with `Image`, `Window Capture`, and `Game Capture` sources. It looks like when OBS is started the `SourceCreated` event is raised for each source when everything is being loaded, and it does have the settings then.

##### Steps to reproduce and other useful info
* Open OBS and start the websocket server and enable debug logging, if needed.
* Add some sources to a scene.
* Look at the `SourceCreated` updates in the log.

##### Technical information
- **Operating System** : Windows 10 Pro 2004
- **OBS Studio version** : 25.0.8
- **obs-websocket version** :  4.8.0

[2020-08-15 19-58-34.txt](https://github.com/Palakis/obs-websocket/files/5079816/2020-08-15.19-58-34.txt)

**Comment by tt2468** [comment]
This is because when you create a source with `CreateSource`, it will (almost) always have default settings. Default settings in OBS data are not returned when converting to JSON. This is fixed in 5.0.0 by also returning a `defaultInputSettings` field.
