### ISSUE TITLE
OBS Freezing while switching Scene Collections

### ISSUE THREAD

**Issue by juanliempo** [Palakis/obs-websocket#582]
##### Issue type

 I read that this was supposed to be fixed, but i'm running into the issue of obs freezing when I switch scene collections.

##### Description
Basically when I change scene collections, its freezes (the window goes opaque and it says "(not responding)" on the title bar).
I've tried waiting and nothing happens, then I end up having to X out and then close OBS when prompted.
After I restart obs I'm on the original scene collection.
But if i uninstall obs websocket and then restart obs, I am able to switch scene collections without any issue.

Need some guidance, because i definitely make use of obs websocket since i'm using programs that require it to sync with obs.

Was just trying to clean up my scene list by separating things into there own collections and reduce some of the clutter.

thanks in advance for any help.

##### Steps to reproduce and other useful info
 See Description

##### Technical information
- **Operating System** : win10 x64 latest updates as of this post
- **OBS Studio version** : obs 25.0.8
- **obs-websocket version** : 4.8.0

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks
