### ISSUE TITLE
StartStreaming does not apply cmd settings

### ISSUE THREAD

**Issue by murillo128** [Palakis/obs-websocket#585]
##### Issue type
Bug report 

##### Description
When sending a StartStreaming with custom settings on the command, those settings are ignored and the settings from the configured service in OBS are used instead

##### Steps to reproduce and other useful info
Just send a StartStreaming with settings different than the configured ones

##### Technical information
The problem is that in 
https://github.com/Palakis/obs-websocket/blob/4.x-current/src/WSRequestHandler_Streaming.cpp#L150

We do the following operations:
```

		obs_frontend_set_streaming_service(newService);
		obs_frontend_streaming_start();
		obs_frontend_set_streaming_service(configuredService);
```

The `obs_frontend_set_streaming_service` are performed immediately by OBS but the `obs_frontend_streaming_start` is enqueued to be executed on the main window event loop by OBS:

https://github.com/obsproject/obs-studio/blob/master/UI/api-interface.cpp#L255

Changing the connection type on OBS to wait the calling thread until the method is executed fixes the issue

```
QMetaObject::invokeMethod(main, "StartStreaming", Qt::BlockingQueuedConnection);
```

**Comment by tt2468** [comment]
Sounds like this functionality is fundamentally flawed. We would either need to remove this feature or invoke `StartStreaming` ourselves, as changing the frontend api like that is a no-go

**Comment by murillo128** [comment]
The change in obs could be quite harmless, although not sure how easy is to propose this changes in OBS:

```
EXPORT void obs_frontend_streaming_start(bool async = true);

void obs_frontend_streaming_start(bool async) override
{
		QMetaObject::invokeMethod(main, "StartStreaming", async ? 
                  Qt::AutoConnection : Qt::BlockingQueuedConnection); 
}
```

Another alternative is to get main window thread and invoke the whole StartStreaming function there, although never done that in QT.

**Comment by tt2468** [comment]
> Another alternative is to get main window thread and invoke the whole StartStreaming function there, although never done that in QT.

That's what my thought was to do. A proposed change like that at the very least needs to have a default value as the bool.

**Comment by BtbN** [comment]
I just ran into this as well, and could luckily just apply that fix to our version of OBS.
Would be interested in a proper solution though.

The proposed change would not work though, since the API is C, and C does not support default values for parameters.
Would also be an ABI break.
So it'd have to be a whole new function just for that.

But I'd propose a more generic function to just "sync with the event queue", which runs a no-op dummy event via BlockingQueuedConnection.

So the websocket code would then just be something like

```
		obs_frontend_set_streaming_service(newService);
		obs_frontend_streaming_start();
                obs_frontend_synchronize();
		obs_frontend_set_streaming_service(configuredService);
```

**Comment by tt2468** [comment]
So we can actually queue the StartStreaming event ourselves by getting the mainwindow handle and acting upon it. However, I'm marking this as a wontfix as we have no plans to fix this in 4.x. 5.0.0 should not have this issue (and will also not include the ability to provide a streaming service with StartStream)
