### ISSUE TITLE
Compiling cannot find -lobs-frontend-api

### ISSUE THREAD

**Issue by jowin202** [Palakis/obs-websocket#586]
##### Issue type

I tried to compile obs-websocket for the newest version of obs-studio. I followed the instruction 1:1 and got

> /usr/bin/ld: cannot find -lobs-frontend-api

as an error message

##### Steps to reproduce and other useful info
1. Followed this instruction:
https://obsproject.com/wiki/install-instructions#linux-portable-mode-all-distros
to compile obs studio portable (it works)

2. Followed this instruction: https://github.com/Palakis/obs-websocket/blob/4.x-current/BUILDING.md

I also replaced <path to the libobs sub-folder in obs-studio's source code> by the actual path

> /usr/bin/ld: cannot find -lobs-frontend-api
> collect2: error: ld returned 1 exit status
> CMakeFiles/obs-websocket.dir/build.make:748: recipe for target 'obs-websocket.so' failed
> make[2]: *** [obs-websocket.so] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/obs-websocket.dir/all' failed
> make[1]: *** [CMakeFiles/obs-websocket.dir/all] Error 2
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2

##### Technical information
- **Operating System** : Ubuntu 16.04
- **OBS Studio version** : 26.0.0. (64 bit)
- **obs-websocket version** : newest 

##### Development Environment
Ubuntu 16.04 standard installation with build essential installed as normal.

> apt-get build-dep obs-studio

I installed everything which was mentioned in the tutorials

**Comment by MarioMey** [comment]
Debian 10, OBS 26.0.2-36-gf190a9f7, same problem.

```
mario@debian:~/src/obs-websocket/build$ make -j8
[  3%] Automatic MOC and UIC for target obs-websocket
[  3%] Built target obs-websocket_autogen
Scanning dependencies of target obs-websocket
[  7%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_Recording.cpp.o
[ 10%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSServer.cpp.o
[ 14%] Building CXX object CMakeFiles/obs-websocket.dir/src/obs-websocket.cpp.o
[ 17%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler.cpp.o
[ 21%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_General.cpp.o
[ 25%] Building CXX object CMakeFiles/obs-websocket.dir/src/ConnectionProperties.cpp.o
[ 28%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_ReplayBuffer.cpp.o
[ 32%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_Profiles.cpp.o
[ 35%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_SceneCollections.cpp.o
[ 39%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_Scenes.cpp.o
[ 42%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_SceneItems.cpp.o
[ 46%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_Sources.cpp.o
[ 50%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_Streaming.cpp.o
[ 53%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_StudioMode.cpp.o
[ 57%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_Transitions.cpp.o
[ 60%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_Outputs.cpp.o
[ 64%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSRequestHandler_MediaControl.cpp.o
[ 67%] Building CXX object CMakeFiles/obs-websocket.dir/src/WSEvents.cpp.o
[ 71%] Building CXX object CMakeFiles/obs-websocket.dir/src/Config.cpp.o
[ 75%] Building CXX object CMakeFiles/obs-websocket.dir/src/Utils.cpp.o
[ 78%] Building CXX object CMakeFiles/obs-websocket.dir/src/rpc/RpcRequest.cpp.o
[ 82%] Building CXX object CMakeFiles/obs-websocket.dir/src/rpc/RpcResponse.cpp.o
[ 85%] Building CXX object CMakeFiles/obs-websocket.dir/src/rpc/RpcEvent.cpp.o
[ 89%] Building CXX object CMakeFiles/obs-websocket.dir/src/protocol/OBSRemoteProtocol.cpp.o
[ 92%] Building CXX object CMakeFiles/obs-websocket.dir/src/forms/settings-dialog.cpp.o
[ 96%] Building CXX object CMakeFiles/obs-websocket.dir/obs-websocket_autogen/mocs_compilation.cpp.o
[100%] Linking CXX shared module obs-websocket.so
/usr/bin/ld: no se puede encontrar -lobs-frontend-api
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/obs-websocket.dir/build.make:463: obs-websocket.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/obs-websocket.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
mario@debian:~/src/obs-websocket/build$ 
```

**Comment by lingfish** [comment]
Same as well; missing a `libobs-frontend-api.so` symlink?

**Comment by m-weigand** [comment]
Hi there,

had the same issue and it turned out that I didn't include the library path of the portable installation, so ld couldn't find the library.
Also note the the directory structure of the portable installation does not work with the `make install`command, so I ended just copying the obs_websocket.so file manually. However, I didn't bother to find out where to put the locale-files normally installed in **/usr/share**. And finally, turning on the **-DUSE_UBUNTU_FIX** flag fixed the installation prefix to /usr/lib/obs-plugins (however, since the install command installed into the wrong directory structure this is irrelevant at this point).

```bash
#!/usr/bin/env sh
# OBS Studio portable installed in $HOME/obs-studio-portable
# OBS Source residing in $HOME/PACKAGES/obs-studio

export LIBRARY_PATH=${HOME}/obs-studio-portable/bin/64bit/:$LIBRARY_PATH

cmake \
	-DCMAKE_INSTALL_PREFIX="${HOME}/obs-studio-portable" \
	-DLIBOBS_INCLUDE_DIR="${HOME}/PACKAGES/obs-studio/libobs" \
	-DUSE_UBUNTU_FIX=false \
   	..

make -j 2

# make install

cp obs-websocket.so ${HOME}/obs-studio-portable/obs-plugins/64bit/
```

**Comment by tt2468** [comment]
Hi,

We've recently enabled Github discussions on this repo. Issues are now reserved only for bug reports and feature suggestions. If this issue is still relevant, I encourage you to open a new discussion for it.

Thanks
