### ISSUE TITLE
Fedora package

### ISSUE THREAD

**Issue by JiangHongTiao** [Palakis/obs-websocket#588]
##### Issue type
 - Feature request

##### Description
Hi guys, do you plan to release also package for Fedora? I'm using OBS there and this would help a lot. 
Didn't try to compile it yet, but looking compile command it seems it's not that straightforward. 
Have someone tried that already?

##### Technical information
- **Operating System** : F32
- **OBS Studio version** : 25.0.8
- **obs-websocket version** : 4.8

**Comment by tt2468** [comment]
Not unless someone is willing to commit to maintaining it. Same rules apply here as obs-studio

**Comment by Vi1234sh12** [comment]
I Think same issue with obs Studio .

**Comment by giacomoferretti** [comment]
You can install the plugin this way:
1. Extract the `.deb` file using `ar x obs-websocket-4.8.0-1_amd64.deb`
2. Extract the `data.tar.xz` using `tar -Jvxf data.tar.xz`
3. Copy `usr/lib/obs-plugins/obs-websocket.so` to `~/.config/obs-studio/plugins/obs-websocket/bin/64bit/obs-websocket.so` (you may need to create the folder)
4. Copy `usr/share/obs/obs-plugins/obs-websocket/locale/` to `~/.config/obs-studio/plugins/obs-websocket/data/` (you may need to create the folder)
5. Enjoy!

**Comment by alexanderlima** [comment]
Sorry for the comment here on an already closed issue, but I tried the procedure mentioned by @giacomoferretti and it didn't work, maybe because I already have a new version, can anyone help?

Estou usando o fedora 37.

Thank you!

**Comment by joshtenorio** [comment]
> Sorry for the comment here on an already closed issue, but I tried the procedure mentioned by @giacomoferretti and it didn't work, maybe because I already have a new version, can anyone help?
> 
> I'm using fedora 37.
> 
> Thank you!

What worked for me is, instead of copying to `~/.config/obs-studio/plugins/obs-websocket/bin/64bit/obs-websocket.so`, I copied it to `/usr/lib64/obs-plugins/` (as described [here](~/.config/obs-studio/plugins/obs-websocket/bin/64bit/obs-websocket.so) on Reddit.
I'm not sure if there's any side effects and I'm not sure where to place the locale files, but it's been working for me so far. I'm on Fedora 37 and using OBS v28.

**Comment by Vashinator** [comment]
Anyone have further details on how to install the legacy version of websockets into OBS in Fedora at this point?

I want to use boatswain which requires v4 of the plugin.
