### ISSUE TITLE
Feature request: GetAudioMixer

### ISSUE THREAD

**Issue by BarryCarlyon** [Palakis/obs-websocket#590]
##### Issue type

- Feature request

##### Description

Provide a method to get what "Audio items" are showing/enabled to appear in the "Audio Mixer Dock".

![image](https://user-images.githubusercontent.com/20999/93367200-17dc4e80-f844-11ea-8180-7b00ecaae9a7.png)

The blue boxed section.

Normally you'd "assume" that all sources have a volume control (and produce sound) and want to be able to control them all.
Right now there's no way to see, what _should_ be controlled, making using OBS Websocket, unable to build a "duplicate" of the "dock" elsewhere.

This would also mean it would lend itself to having event" when a Volume Item is added(shown)/removed(hidden) from the "Audio Mixer".

Which may also trigger on a scene change as items appear/disappear. But that could get noisy/send multiple payloads. So a "AudioMixerChanged" event would be more sane

**Comment by BarryCarlyon** [comment]
An alternative would be if,sSources returned in various Get calls, was extended for another flag

So it has a `volume` and a `muted` item, add a `mixer` or similar named item to show if the source is included in the mixer.

**Comment by glukinho** [comment]
Monitoring and controlling audio levels would be extremely useful.

**Comment by PerfectSlayer** [comment]
It could be very useful as getting the current audio source in the scene is not really easy as audio source could be in nested sources and are not return in `SwitchScenes` events.

**Comment by tt2468** [comment]
Planned for 5.0.0. Will not be implemented in 4.x. Thank you for your suggestion.
