### ISSUE TITLE
SetSceneItemRender bug : Scene-name parameter without effect

### ISSUE THREAD

**Issue by XReyRobert** [Palakis/obs-websocket#591]
##### Issue type
Bug report
##### Description
Setting render/visibility on a scene item with SetSceneItemRender only work if scene is the currently active one. If fails with no error message (Request status = ok)

The scene-name parameter is without effect.

##### Technical information
MacOS 10.15.6
OBS Studio version: 25.0.8
obs-websocket version: 4.8

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks
