### ISSUE TITLE
CI: Azure Pipeline for macOS failing to build OBS

### ISSUE THREAD

**Issue by LorenaGdL** [Palakis/obs-websocket#596]
##### Issue type

- Bug report

##### Description

The PR Azure Pipeline for macOS builds is failing due to misconfiguration related to Qt while trying to build OBS. Example log [here](https://dev.azure.com/Palakis/obs-websocket/_build/results?buildId=1420&view=logs&j=c44e3ce6-80b8-5090-9435-9627042472dc&t=ce2e826b-e4fc-5510-da3b-3d79a079e151&l=83) (or you can check any of the most recent PRs)

**Comment by tt2468** [comment]
Yeah, it's on our list to fix.
