### ISSUE TITLE
New request type: StartVirtualWebcam feature

### ISSUE THREAD

**Issue by dander11** [Palakis/obs-websocket#599]
##### Issue type
- Feature request

##### Description
Starting in OBS 26.0 there is the option to start a virtual webcam output just like there is an option to start streaming or recording. It would be great if we could request the virtual webcam to start/stop using this plugin.

##### Steps to reproduce and other useful info
OBS 26.0 release notes on virtual webcam [https://github.com/obsproject/obs-studio/releases/tag/26.0.2](https://github.com/obsproject/obs-studio/releases/tag/26.0.2)

##### Technical information
- **Windows/Mac** :
- **26.0^** :
- **obs-websocket 4.7.0** :

**Comment by tt2468** [comment]
Merged, will be released in 4.9.1
