### ISSUE TITLE
"scale" in SetSceneItemProperties BUG

### ISSUE THREAD

**Issue by fruf2992** [Palakis/obs-websocket#601]
##### Issue type
SetSceneItemProperties

##### Description
Since last OBS update, "scale" in SetSceneItemProperties does no more work BUG

##### Steps to reproduce and other useful info

    params = {
      "scene-name": "Scene",
      "item": "Cam1",
      "scale": {
        "x": 0.6,
        "y": 0.6
      }
    };
    obs.send('SetSceneItemProperties', params);

##### Technical information
- **Operating System** : Catalina 10.15.7
- **OBS Studio version** : 26.0.2
- **obs-websocket version** : 4.8.0

##### Development Environment
Testing : Firefox and Safari

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks
