### ISSUE TITLE
Should the 'Heartbeat' event also be marked as deprecated in protocol.md?

### ISSUE THREAD

**Issue by TenkenNoSoujiro** [Palakis/obs-websocket#604]
##### Issue type
- Bug report

##### Description
In the docs, the [SetHeartbeat](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#setheartbeat) request is marked as deprecated since 4.9.0 and will be removed in 5.0.0. Shouldn't the [Heartbeat](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#heartbeat) event also be marked as deprecated?

**Comment by tt2468** [comment]
Irrelevant now with how we have broken 4.x and 5.x into different branches.
