### ISSUE TITLE
Support for RPAN Studio (OBS fork that broadcasts to reddit)

### ISSUE THREAD

**Issue by reedog117** [Palakis/obs-websocket#606]
##### Issue type

- Feature request

##### Description
Support for [RPAN Studio](http://github.com/reddit/rpan-studio) (Fork for broadcasting to reddit)

Attempting using the zip and decompressing to the RPAN Studio directory but the plugin is not recognized.

##### Technical information
- **Operating System** : Windows x64
- **OBS Studio version** : 25.0.7
- **obs-websocket version** : 4.8.0

**Comment by reedog117** [comment]
Crossposted in the RPAN Studio repo - https://github.com/reddit/rpan-studio/issues/4

**Comment by tt2468** [comment]
I don't think its worth us implementing it unless someone commits to maintaining support.
