### ISSUE TITLE
Documentation for GetSceneItemProperties is wrong

### ISSUE THREAD

**Issue by TenkenNoSoujiro** [Palakis/obs-websocket#607]
##### Issue type
- Bug report

##### Description
The documentation for [GetSceneItemProperties](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getsceneitemproperties) mentions an `alignment` property on the result that is not actually produced by the server.

- Mentioned in a documentation comment here: https://github.com/Palakis/obs-websocket/blob/4.x-current/src/WSRequestHandler_SceneItems.cpp#L121
- However `alignment` is only set on `posData` (nee. `position` in the result) and `boundsData` (nee. `bounds` in the result), but not on `data` in `GetSceneItemPropertiesData` here: https://github.com/Palakis/obs-websocket/blob/4.x-current/src/Utils.cpp#L726

##### Technical information
- **Operating System** : N/A
- **OBS Studio version** : N/A
- **obs-websocket version** : N/A (documentation in the `4.x-current` branch)

**Comment by Palakis** [comment]
Thanks! Good catch.
