### ISSUE TITLE
Cannot connect to websocket from within local network

### ISSUE THREAD

**Issue by mrsydster** [Palakis/obs-websocket#608]
##### Issue type
Bug report

##### Description
Installed Websocket for OBS Studio on Windows 10.
I can reach the websocket on my local pc, but not from another pc within the local network. 
It will not connect. 
I did uncheck the public option in the network access I got when installing the plugin, but all pc's in the local network are on Private network mode. 

##### Steps to reproduce and other useful info
1. Install the websocket for OBS Studio on Windows 10. 
2. After instalation, uncheck the Public network option from the firewall settings. 
3. Try to access the websocket from another

##### Technical information
- **Operating System** : Windows 10 Pro
- **OBS Studio version** : 26.0.2
- **obs-websocket version** : 4.8

**Comment by mrsydster** [comment]
Turns out to be a firewall issue.... I feel stupid

**Comment by ricardovsilva** [comment]
@mrsydster how did you solved this?

**Comment by Vexxifi** [comment]
@ricardovsilva I had the same issue with my mobile app saying "Cannot connect to websocket" but found that the issue was just a result of using the Alpha 2 instead of the stable version. [YouTube Tutorial that helped me.](https://www.youtube.com/watch?v=NNKo0IfnlEk&t)
