### ISSUE TITLE
Enhancement Request - Toggle mute on mixer devices

### ISSUE THREAD

**Issue by Huesdon** [Palakis/obs-websocket#61]
I would like programmatic control of my mic/aux so that I can auto mute/unmute on specific events.

**Comment by Palakis** [comment]
@Huesdon In the meantime before this gets implemented, you can disable the default Mic device in OBS' settings and manually add it to your scenes as a source. It will then be visible and controllable through obs-websocket.

**Comment by Huesdon** [comment]
Oh wow, awesome. Thanks for the tip, I'll try that.

**Comment by Huesdon** [comment]
Hmm have you tested SetMute recently?
```
@app.route('/obs/setmute/<string:source>/<string:bool>')
def set_source_mute(source, bool):
    pp = pprint.PrettyPrinter(indent=2)
    request = {
        "request-type": "SetMute",
        "source": source,
        "mute": bool
    }
    pp.pprint(request)
    response = configuration.obs_send(json.dumps(request))
    return response
```

I am calling this via flask...

"http://127.0.0.1:5000/obs/setmute/SRC_Mic/true"

... and getting 200 OK response but nothing happens.
Names etc are all good as the following works perfectly:

"http://127.0.0.1:5000/obs/getmicstatus/SRC_Mic"

```
@app.route('/obs/getmicstatus/<string:source>')
def get_mic_status(source):
    pp = pprint.PrettyPrinter(indent=2)
    request = {
        "request-type": "GetVolume",
        "source": source       
    }
    response = configuration.obs_send(json.dumps(request))     
    j = json.loads(response)      
    pp.pprint(j)

    ismute = j['muted']    
  
    print('Current Mic Mute State: %s' % str(ismute))    
    return str(ismute)
```

**Comment by Palakis** [comment]
Works fine on my end when OBS has Studio Mode disabled. However, this returns OK but does nothing when in Studio Mode and the preview doesn't have the specified source in it.

**Comment by Palakis** [comment]
@Huesdon Btw I just discovered that can control the Desktop Audio and/or Mic/Aux sources by calling them with their localized name when calling one of the source-related request types. So the trick mentioned above isn't really useful.

e.g : in french, by calling GetVolume on a source "Audio du bureau", I get the volume for Desktop Audio.

**Comment by Palakis** [comment]
@Huesdon Nevermind what I said earlier. Using the latest codebase, I have no problem muting and unmuting sources, both in normal and Studio Mode.

**Comment by Palakis** [comment]
https://github.com/Palakis/obs-websocket/commit/5d290165a2820ce5d6de67492c64ffe992620b51 adds request type `GetSpecialSources`. This request type returns names of the configured mixer sources, which can then be used when calling `SetMute`, `GetVolume`, etc...
