### ISSUE TITLE
next new release ?

### ISSUE THREAD

**Issue by pubpub-zz** [Palakis/obs-websocket#610]
##### Description
Hi, thanks for your great job. I'm looking for a new release where the GetRecordingStatus will be available. Will you issue soon ? Thanks

**Comment by YorVeX** [comment]
[GetStreamingStatus](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getstreamingstatus) also includes the recording status.

**Comment by pubpub-zz** [comment]
Thanks for this advice but I need to know also the pause state. Really looking forward for next release ☺️

**Comment by YorVeX** [comment]
Ah, OK, and just listening for the [RecordingPaused](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#recordingpaused) and [RecordingResumed](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#recordingresumed) updates is not an option?

Of course this doesn't send you the initial status if your client connects while a recording is already running that might be paused or resumed, but I would assume that this a rather rare case so it might at least help you in the majority of situations.

**Comment by pubpub-zz** [comment]
thanks for the advice but I've developped a screen capture/annotation https://github.com/pubpub-zz/ppInk
I've introduced feature to control obs through obs-websocket. I'm just waiting for next official release to advise people to install it for full feature support. hoping it will happen soon...

**Comment by YorVeX** [comment]
> thanks for the advice but I've developped a screen capture/annotation https://github.com/pubpub-zz/ppInk
> I've introduced feature to control obs through obs-websocket. I'm just waiting for next official release to advise people to install it for full feature support. hoping it will happen soon...

Ah, looks like a cool piece of software. Well, let's hope a release is coming soon. Although if you want to know about that I guess asking on [their Discord](https://discord.gg/WBaSQ3A) is a better place than here.

**Comment by leafac** [comment]
Although [it doesn’t appear in the documentation](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getstreamingstatus), `GetStreamingStatus` is returning a field saying whether the recording is paused:

```console
$ npx obs-cli GetStreamingStatus
{
  'message-id': '1',
  'preview-only': false,
  'rec-timecode': '00:00:11.960',
  recording: true,
  'recording-paused': true,
  status: 'ok',
  streaming: false,
  messageId: '1',
  previewOnly: false,
  recTimecode: '00:00:11.960',
  recordingPaused: true
}
```

I’m running obs-websocket 4.8.

Maybe that’ll work for you, @pubpub-zz.

**Comment by pubpub-zz** [comment]
😳😳😳😳 
thanks @leafac 
I'm so ashamed to have seen that.: It is exactly what I need and even better it simplifies my program
can any confirm this feature will remain in future ?

**Comment by tt2468** [comment]
@pubpub-zz Currently there is GetRecordingStatus so as such we will eventually remove the recording stuff from GetStreamingStatus. Othwerwise the request will likely never be removed.

**Comment by pubpub-zz** [comment]
OK, I understand waiting for your next release for evaluation
