### ISSUE TITLE
[Feature] Manage every settings of OBS via WebSocket

### ISSUE THREAD

**Issue by donlucacorleone** [Palakis/obs-websocket#611]
##### Issue type
Feature request

##### Description
I'd like to have the possibility to manage all the settings we are used to set in the OBS UI "Settings" window via WebSocket API.

Especially, I'm interested in video bitrate and resolution as well as advancend streaming/recording settings.

##### Technical information
- **Operating System** : MacOS
- **OBS Studio version** : 26.0.2
- **obs-websocket version** : 4.8.0

**Comment by tt2468** [comment]
This is not as simple as just making a request to "manage every setting." OBS is incredibly complicated and many settings have different implementations. Bitrate and resolution are already requested.
