### ISSUE TITLE
Upload Scene Collection

### ISSUE THREAD

**Issue by ccMatrix** [Palakis/obs-websocket#612]
##### Issue type
- Feature request

##### Description
Add an endpoint to upload a scene collection file to the machine running OBS. The call would receive the `sc-name` of the collection as well as an encoded JSON payload that will be persisted in the scene collection folder. 

##### Steps to reproduce and other useful info
There is already `ListSceneCollections` as well as `SetCurrentSceneCollection` to find out which collection files exist and to select an existing one. However there is no way to simply create a new file. There is efforts going on to allow for more options in creating new sources and scenes. This feature would allow for easily creating a starting collection that can then be remote controlled using OBS websocket.

**Comment by tt2468** [comment]
While uploading of scene collection .json files is not something that we will do, perhaps a `CreateSceneCollection` request could be done.

**Comment by tt2468** [comment]
Now on the todo for 5.x. Thank you for your suggestion.
