### ISSUE TITLE
Feature request: Access to OBS_*_private_data API

### ISSUE THREAD

**Issue by captainwasabi** [Palakis/obs-websocket#614]
##### Issue type

- Feature request 

##### Description

I would like to request an interface to OBS private data via:
obs_apply_private_data
obs_get_private_data
obs_set_private_data

I have a complex custom source (LUA) that receives its state information via commands passed into private variables.  Previously (and probably for my current needs) I've written an obsPython script that just listens on a socket then passes the data into the obslua source.  This would cut out that middleman for me.

Thanks for a great system.

**Comment by tt2468** [comment]
Is there a reason that you can't use public data like the profile or global config?

**Comment by captainwasabi** [comment]
I can't even recall which script I was working on 8 months ago.  The private_data interface just seemed to be how this data was passed between running scripts&sources so exposing it to websockets just seemed a logical way to pass in the same data to the source but where the script could be running outside of OBS.

**Comment by tt2468** [comment]
Sorry, but this is not something we will implement. Private data is usually not saved, and is not designed to be worked with outside of internal systems.
