### ISSUE TITLE
Clear strategy regarding streaming stats/status - why deprecate Heartbeat mechanism?

### ISSUE THREAD

**Issue by YorVeX** [Palakis/obs-websocket#616]
##### Issue type
Feature request

##### Description
Currently from the perspective of a client the situation about how to get streaming+recording stats/status information is pretty chaotic and a clear strategy is not visible.

- The automatic StreamStatus event
  - is not sent when not streaming
  - is not sent while recording, although it contains a status field telling whether recording is active or not
    - however, it's missing the information for how long a recording has been running
    - there also is no RecordingStatus event that would fill this gap
  - is sent without demand during an active stream: it's a potential waste of resources for clients that don't need this info
  - contains redundant information that clients could calculate themselves (bytes-per-sec + kbits-per-sec, strain)
- The response to GetStreamingStatus contains streaming and recording status and times elapsed for both
- The response to GetStats contains generic stats that apply to both streaming and recording
- Compared to what the OBS Stats window shows some things are missing in all of these methods/events:
  - total data output for streaming
  - total data output for recording
  - recording bitrate
  - disk full in approx. (could be calculated by the client if the recording bitrate would be sent)
- all of the methods that can be polled lack the replay-buffer-active information that the StreamStatus event has

So when looking at each of these items they don't make sense as a single item (e.g. why include recording info in streaming status, but then only half of it?) and the combination of them doesn't make sense either:
- if a client only needs generic+streaming stats/status (without "total data output for streaming") and only when the stream is live it doesn't have to poll any data but only read the automatic StreamStatus event
- if a client only needs generic+streaming stats/status but also when the stream is not live it can either 1. alternate between using the automatic StreamStatus events when the stream is live and reverting to polling GetStats when it's not (LOL) or 2. ignore the StreamStatus events altogether and poll both GetStreamingStatus and GetStats - but that's not an option if the client needs the replay-buffer-active information, at least for this it would still have to read StreamStatus events
- if a client needs recording stats/status (solely or in addition to streaming stats/status) it always needs to poll both GetStreamingStatus and GetStats and if the client needs the replay-buffer-active information it has to read StreamStatus events in addition
- if a client completely needs all data, including things from the Heartbeat like total-stream-bytes and the replay-buffer-active information it actually needs to 1. read the automatic StreamStatus events, 2. poll GetStreamingStatus and GetStats and 3. call SetHeartbeat and read the automatic Heartbeats.

![image](https://user-images.githubusercontent.com/528974/99882585-d3917400-2c21-11eb-96b8-a6b39c85a499.png)

It seems that the Heartbeat mechanism was meant as a solution to this, giving all this information at once (and additional information that none of the above methods include, like total-stream-bytes), automatically every 2 seconds, but only when the client demands it.

I don't understand why it should be deprecated again in favor of the other existing mechanisms which are chaotic and incomplete, probably for backward compatibility reasons.

As someone who is programming a client that wants to use all of the data (and always, regardless of the stream being live or not) what should I do now? Use the heartbeat mechanism, missing the replay-buffer-active information and knowing that I have to rewrite it later when it's been deprecated? Or use all of the other mechanisms, with a mixture of automated events and polling but missing some information like total-stream-bytes? Or do everything, enable a heartbeat, read automatic events and poll data (again knowing I have to rewrite this again soon)?

So my wish would be that the Heartbeat mechanism is not deprecated and the Heartbeat also contains the replay-buffer-active information. Leave the other things there for backwards compatibility but recommend the Heartbeat mechanism for new client implementations.

##### Technical information
- **Operating System** : Windows 10 Pro, Version 2004
- **OBS Studio version** : 26.0.2 (64 bit)
- **obs-websocket version** : 4.8

**Comment by YorVeX** [comment]
This is how far I was able to get with implementing a remote stats window without Heartbeat.
![image](https://user-images.githubusercontent.com/528974/99884265-1efd4f80-2c2d-11eb-8edd-65f768846686.png)

**Comment by Zingabopp** [comment]
There's also `ListOutputs` and `GetOutputInfo` which give you that info (https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#output).

**Comment by YorVeX** [comment]
> There's also `ListOutputs` and `GetOutputInfo` which give you that info (https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#output).

Thanks a lot, this looks like the missing piece to the puzzle!

**Comment by YorVeX** [comment]
Using `ListOutputs` I was now able to additionally get
- "Dropped Frames (Network)" also when the stream is not live
- "Total Data Output" for both "Stream" and "Recording"
- Congestion, which I use to show a color indicator similar to the one at the buttom of the main window while live

Still missing is:
- Recording Bitrate
- "Disk full in (approx.)"

![image](https://user-images.githubusercontent.com/528974/100817148-d2452000-3447-11eb-907d-0daa0a97f74c.png)

**Comment by kellertobias** [comment]
How do I enable the `StreamStatus`? I don't get the messages at all

**Comment by tt2468** [comment]
Hi,

We've recently enabled Github discussions on this repo. Issues are now reserved only for bug reports and feature suggestions. If this issue is still relevant, I encourage you to open a new discussion for it.

I will make sure not to leave out any statistic information in 5.0.0's `GetStats` that was implemented in 4.x's various statistic systems.

Thanks

**Comment by YorVeX** [comment]
Sounds good, thanks!
