### ISSUE TITLE
When sending "SendCaptions" to websocket getting  error "invalid request type"

### ISSUE THREAD

**Issue by arisprung** [Palakis/obs-websocket#617]
Bug report 

When sending "SendCaptions" to websocket getting  error "invalid request type"

I am trying to send the SendCaptions request thru 2 solutions one is a nodejs example that is sending text thru StreamText https://github.com/EddieCameron/obs-websocket-streamtext-captions

Another is the new integration  with Web Captioner https://webcaptioner.com/help/integrations/obs

Operating system Mac Catalina
OBS version 26.02
obs socket version Closed_Captions_Plugin__v0.18b_MacOS

**Comment by arisprung** [comment]
Ok did some more research this is only  not working on my Mac. Working on my Windows...

**Comment by Palakis** [comment]
Yeah, some platforms didn't have captions enabled last time I check, so they were disabled accordingly. Apparently the situation has changed on macOS, so I may have to turn them on again on macOS.
