### ISSUE TITLE
Issues installing the plugin

### ISSUE THREAD

**Issue by allyssons** [Palakis/obs-websocket#62]
Hello, I am having this log error when trying to use the plugin. 

https://gist.github.com/2c585cb2f57bb6e70713b76a834bef6f

Any ideas of what this could be?

**Comment by Palakis** [comment]
I do not see something wrong in this log file. Can you please be more specific regarding this issue?

**Comment by allyssons** [comment]
I install the plugin and it does not appear in the OBs. I tried installing
manually and with the installator, but nothing change.

Em 08/04/2017 05:54, "Stéphane L." <notifications@github.com> escreveu:

**Comment by Palakis** [comment]
Where is OBS installed on your system?

**Comment by allyssons** [comment]
In the normal place, Program Files(x86)

Em 08/04/2017 07:52, "Stéphane L." <notifications@github.com> escreveu:

**Comment by Palakis** [comment]
The log file you provided has no mention of obs-websocket in it.

Go to `C:\Program Files (x86)\obs-studio\obs-plugins\32bit\` or `C:\Program Files (x86)\obs-studio\obs-plugins\64bit\` and tell me if a file named `obs-websocket.dll` is present in one of these directories.

**Comment by allyssons** [comment]
Yes, it is

Em 14/04/2017 16:07, "Stéphane L." <notifications@github.com> escreveu:

**Comment by Palakis** [comment]
@allyssons Can you please another log file WITH a stack trace?

**Comment by allyssons** [comment]
I was trying to get this log file with the stack trace, but I did not
figure out how to did it. I am sorry for my stupidity lol. Can you tell me
how to get it?

Em seg, 17 de abr de 2017 às 10:22, Stéphane L. <notifications@github.com>
escreveu:

**Comment by Palakis** [comment]
@allyssons On Windows, it is usually found in `%HOMEPATH%\AppData\Roaming\obs-studio\crashes`

**Comment by Palakis** [comment]
@allyssons I really don't understand what happens on your system. Which OS version is it?

**Comment by Palakis** [comment]
@allyssons Also, did you installed OBS with the installer or is it a portable install (with the Zip archive) ?

**Comment by allyssons** [comment]
I am using Windows 10 Home, and in this directory there is no files. I
installed OBS using both methods and got the same problem.

Em dom, 23 de abr de 2017 às 14:15, Stéphane L. <notifications@github.com>
escreveu:

**Comment by ricardovsilva** [comment]
Why is this issue closed? I'm facing same problem, is there any solution? If so I believe that will be good to point that here.
