### ISSUE TITLE
SetSceneItemRender should handle duplicated sources in the same scene 

### ISSUE THREAD

**Issue by gdhgdhgdh** [Palakis/obs-websocket#624]
##### Issue type
Feature request

##### Description
I have scenes where the `dj1` VLC media source exists in its original form and also as a `Copy -> Paste (Reference)` at a smaller size in the same scene so the video is perfectly synced, and more efficient than decoding twice.

This means that `dj1` appears twice in the list of Sources for the scene. If I rename either, the other is automatically renamed to the same thing.

When I call `SetSceneItemRender` with `source`: "dj1", `render`: false, only one of the two instances of `dj1` is hidden. I would happily pass the OBS `itemId` instead of the string `source` but `SetSceneItemRender` only supports string input :(

##### Technical information
- **Operating System** : Ubuntu 20.04
- **OBS Studio version** : 26.0.2 from Ubuntu PPA
- **obs-websocket version** : 4.8.0 .deb

**Comment by tt2468** [comment]
Closing since this should have been closed via #628
