### ISSUE TITLE
After upgrade OBS to 26.1, i cannot see preview

### ISSUE THREAD

**Issue by joint007** [Palakis/obs-websocket#630]
##### Issue type
Bug report

##### Description
After upgrade OBS to 26.1, i cannot see preview in http://obs-web.niek.tv client, after downgrade OBS to 26.0.2, everything is fine.

##### Steps to reproduce and other useful info
Upgrade OBS to version 26.1

##### Technical information
- **Operating System** : Windows Server 2019
- **OBS Studio version** : 26.1
- **obs-websocket version** : 4.8.0

**Comment by Frittenfett** [comment]
After upgrade to 26.1, I can't even see the plugin under "tools".
OBS Studio version : 26.1
obs-websocket version : 4.8.0

**Comment by tt2468** [comment]
Closing as it appears to be the same issue as #634
