### ISSUE TITLE
New request type: CloseProjector feature

### ISSUE THREAD

**Issue by DhSufi** [Palakis/obs-websocket#632]
Issue type

    Feature request

Description

obs-webscoket version 4.8 added "OpenProjector" request. It would be very useful to have also a "CloseProjector" request. Thanks you for your time and consideration. Best regards.

Technical information

- Windows/Mac :
- 26.0^ :
- obs-websocket 4.8 :

**Comment by tt2468** [comment]
Unfortunately there is no OBS api call for this at the moment.
