### ISSUE TITLE
List of possible sourceKind types for CreateSource

### ISSUE THREAD

**Issue by snobear** [Palakis/obs-websocket#633]
##### Issue type

- Feature request

##### Description

Hi, I'm looking to leverage [CreateSource](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#createsource) that I see is in the latest build, but I'm wondering where I can find a list of possible `sourceKind` types? Also `sourceSettings` params would be helpful too.

To be more specific, I'm looking to create an image source from a file or URL, but I may be interested in what other source types can be created. I Googled around in the OBS api docs, but no luck. I'm new to obs-websocket, so not sure the best place to find info. Thanks for the help!

##### Steps to reproduce and other useful info
NA

##### Technical information
- **Operating System** : OSX Catalina 10.15.7
- **OBS Studio version** : 26.1.0
- **obs-websocket version** : 4.x [build 20201216.20](https://dev.azure.com/Palakis/obs-websocket/_build/results?buildId=1549&view=results)

**Comment by snobear** [comment]
I was able to figure this out. I manually created some sources in OBS and then used `GetSourcesList` to spit out a list of my sources and then `GetSourcesSettings` to get a source's settings.

Example using [obs-websocket-js](https://github.com/haganbmj/obs-websocket-js):

```
const OBSWebSocket = require('obs-websocket-js');
const obs = new OBSWebSocket();

obs.on('ConnectionOpened', () => {
  obs.send('GetSourcesList').then(data => {
    console.log('GetSourcesList', data);
  });

  obs.send('GetSourceSettings', { 'sourceName': 'myimage' }).then(data => {
    console.log('GetSourceSettings', data);
  });
});

obs.connect();
```

So to add a local image use `"sourceKind": "image_source"`.  For example:

```
const OBSWebSocket = require('obs-websocket-js');
const obs = new OBSWebSocket();

let imgSource = {
  "sourceName": "myimage",
  "sourceKind": "image_source",
  "sceneName": "Scene",
  "sourceSettings": {
    'file': '/path/to/pic.jpg'
  },
  "setVisible": true
}

obs.on('ConnectionOpened', () => {
  obs.send('CreateSource', imgSource).then(data => {
    console.log('CreateSource result', data);
  }).catch((error) => {
    console.log("error", error)
  });
});

obs.connect();
```

**Comment by johnebgood** [comment]
I can't find any documentation for this, are we expected to write code to figure out how to use an API?

**Comment by tt2468** [comment]
Please don't hijack old issues like this.

5.x has `GetInputKindList`
