### ISSUE TITLE
requests: TakeSourceScreenshot is missing image formats on OBS v26.1

### ISSUE THREAD

**Issue by 7th-heaven** [Palakis/obs-websocket#634]
##### Issue type

 Bug report 

##### Description

After update OBS to 26.1.0 the  `TakeSourceScreenshot`  NOT functions correctly.
The exception message is " `unsupported picture format: jpg` ".

And in OBS 26.0.2 TakeSourceScreenshot functions correctly.
Plz check up. Thx. 
OBS log files did't show any thing....

##### Technical information
- **Operating System** :WIN10 PRO 1909
- **OBS Studio version** :26.1.0
- **obs-websocket version** :4.8

**Comment by tt2468** [comment]
Performing `GetVersion` on v26.1 shows only `bmp,pbm,pgm,png,ppm,xbm,xpm` as the supported image formats. This is likely due to the Qt upgrade done in 26.1.

**Comment by 7th-heaven** [comment]
Thx for reply. I tested bmp and png, works perfectly.

**Comment by Niek** [comment]
Several https://github.com/Niek/obs-web users have complained about this issue too. Should it be reported to upstream OBS? I think that it's pretty important to have JPG support.

**Comment by tt2468** [comment]
Palakis said he would take a look at it today. We think that Jim forgot to build OBS with Qt imageformats included. @Niek

**Comment by schierla** [comment]
The OBS Hotfix v26.1.1 does not seem to fix the problem.

**Comment by wigledejong** [comment]
I fixed it locally by copying some dll's from qt (qjpeg.dll and qjpegd.dll) to the imageformats folder of OBS. In my case it is C:\Program Files\obs-studio\bin\64bit\imageformats.

**Comment by 7th-heaven** [comment]
> 
> 
> I fixed it locally by copying some dll's from qt (qjpeg.dll and qjpegd.dll) to the imageformats folder of OBS. In my case it is C:\Program Files\obs-studio\bin\64bit\imageformats.

Does the version matter?
Png works fine, but it takes too much time to upload.

**Comment by wigledejong** [comment]
> > I fixed it locally by copying some dll's from qt (qjpeg.dll and qjpegd.dll) to the imageformats folder of OBS. In my case it is C:\Program Files\obs-studio\bin\64bit\imageformats.
> 
> Does the QT version matter?
> Png works fine, but it takes too much time to upload.
> I wish to fix it too.

I don't know if QT version matters. I saw in the obs-studio repo they use QT 5.15.2.

These dll's[QT jpegd dll.zip](https://github.com/Palakis/obs-websocket/files/5860636/QT.jpegd.dll.zip) work for me.

**Comment by 7th-heaven** [comment]
> 
> 
> > > I fixed it locally by copying some dll's from qt (qjpeg.dll and qjpegd.dll) to the imageformats folder of OBS. In my case it is C:\Program Files\obs-studio\bin\64bit\imageformats.
> > 
> > 
> > Does the QT version matter?
> > Png works fine, but it takes too much time to upload.
> > I wish to fix it too.
> 
> I don't know if QT version matters. I saw in the obs-studio repo they use QT 5.15.2.
> 
> These dll's [QT jpegd dll.zip](https://github.com/Palakis/obs-websocket/files/5860636/QT.jpegd.dll.zip) work for me.

I'v tried it on OBS 26.1.1. It's worked. Thanks for the dlls.

**Comment by schierla** [comment]
For me, it was enough to just replace qjpeg.dll, no need to include the debug dll (qjpegd.dll).

**Comment by RytoEX** [comment]
After a lot of testing, I've determined that this is because the `bin/64bit/imageformats/qjpeg.dll` file bundled with obs-websocket is from Qt 5.10.1 instead of Qt 5.15.2, which OBS Studio upgraded to in OBS Studio 26.1.0.  If obs-websocket bundles the correct version of the file, it will work again.

**Comment by tt2468** [comment]
Hey all, update for ya. I have a patch for everyone currently facing this issue, which adds the image formats back. This fix will be included in the upcoming v4.9.1 patch, but for now here's the process:

- Download https://tt2468.net/dl/imageformats.rar
- Press Win + R to open the run dialog, paste `C:\Program Files\obs-studio\bin\64bit\imageformats`, and press enter.
- Copy the DLL files located in the imageformates.rar archive to the location which has been opened.

Your folder should look something like this:
![image](https://user-images.githubusercontent.com/28720189/114533253-8dee3b80-9c02-11eb-9b6e-73ebb89fde24.png)

Restart OBS and the image formats should be there.
