### ISSUE TITLE
Scene transition events triggered when switching out of Studio Mode

### ISSUE THREAD

**Issue by macharborguy** [Palakis/obs-websocket#64]
Possible bug, when Studio Mode is being deactivated, the "TransitionBegin" and then "SwitchScenes" events immediately fire, even though no scenes switched.

**Comment by Palakis** [comment]
Can reproduce on my side. If it's a bug then this seems to come from OBS' API.

**Comment by tt2468** [comment]
This still happens, but since it's a behavior of the OBS api, it would be challenging to fix on the plugin side.
