### ISSUE TITLE
CreateScene not working

### ISSUE THREAD

**Issue by ordinansapp** [Palakis/obs-websocket#642]
##### Issue type
- Bug report 

##### Description
Seems that CreateScene function is not working. I've checked the documentation, says the function was implemented in 4.8 version, but response returns "invalid request type". Tried it on both Windows 10 and Ubuntu 20.04, using javascript API (Win) and CLI (Linux)

##### Steps to reproduce and other useful info
1. Install and set up obs-websocket and obs-cli
2. Call `CreateScene` using command `npx obs-cli CreateScene '{"sceneName": "test"}'`
3. Request fails with message:
`{
  "error": "invalid request type",
  "message-id": "1",
  "status": "error",
  "messageId": "1"
}`

Other methods (e.g. GetCurrentScene) seem to be working. 

##### Technical information
- **Operating System** : Ubuntu 20.04.1
- **OBS Studio version** : 26.02.2 (64 bit)
- **obs-websocket version** : 4.8

**Comment by tt2468** [comment]
`CreateScene` is a 4.9.0 feature. Looks like it was mislabeled in the documentation as a 4.8.0 feature. You'll have to use the latest nightly build here: https://dev.azure.com/Palakis/obs-websocket/_build/results?buildId=1576&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by ordinansapp** [comment]
Yeah, it works with nightly build, tnx!
