### ISSUE TITLE
Build with CreateScene & CreateSource

### ISSUE THREAD

**Issue by malinowskil123** [Palakis/obs-websocket#648]
Is there any way to get access to the build with CreateScene and CreateSource request?s

**Comment by tt2468** [comment]
https://dev.azure.com/Palakis/2687c5e1-1f5c-4326-8080-85cbdf4f4033/_apis/build/builds/1576/artifacts?artifactName=windows_build&api-version=6.0&%24format=zip

**Comment by malinowskil123** [comment]
Is there a mac os build available ?

**Comment by tt2468** [comment]
https://dev.azure.com/Palakis/2687c5e1-1f5c-4326-8080-85cbdf4f4033/_apis/build/builds/1576/artifacts?artifactName=macos_build&api-version=6.0&%24format=zip
