### ISSUE TITLE
'StreamStatus' Event not sending when stream is not live

### ISSUE THREAD

**Issue by macharborguy** [Palakis/obs-websocket#65]
Due to OBS Studio having Preview mode active upon launch, rather than a toggle in original OBS, part of me feels that the StreamStatus event needs an overhaul.

The data object should be sent to any connections all the time.

When not streaming or recording, OBS-Websocket should consider OBS Studio to be in preview mode, and keep sending the StreamStatus object every 2 seconds.

(Currently) StreamStatus is only sent if OBS Studio is Streaming.  It is not sent when Recording-only or Previewing the stream offair

**Comment by Palakis** [comment]
I agree that `StreamStatus` events should also be sent when recording, maybe with more detailed informations specific to recording.

But as of now, this is not something I want to implement, as there are more important things to do in obs-websocket. What you suggest is pretty easy to implement, so feel free to work on this and submit a Pull Request once you're confident about it.
