### ISSUE TITLE
Uninstall obs-websocket from Mac

### ISSUE THREAD

**Issue by andrearot** [Palakis/obs-websocket#651]
##### Description
Hello, how can I uninstall obs-websocket?
I found this thread but i can't find the mentioned files: https://github.com/Palakis/obs-websocket/issues/216

Thank you,
Andrea

##### Technical information
- **Operating System** : Mac Os Mojave 10.14.6
- **OBS Studio version** : 26.1.2
- **obs-websocket version** : obs-websocket-4.8.0-macOS.pkg

**Comment by nedimf** [comment]
This is pwd to that file ```/Library/Application Support/obs-studio/plugins/```.
cd to it ``` cd '/Library/Application Support/obs-studio/plugins/obs-websocket/bin'``` 
then just do ```rm -rf obs-websocket`` to delete it.

**Comment by andrearot** [comment]
> This is pwd to that file `/Library/Application Support/obs-studio/plugins/`.
> cd to it ` cd '/Library/Application Support/obs-studio/plugins/obs-websocket/bin'`
> then just do `rm -rf obs-websocket` to delete it.
> 
> Let me know if that helps @andrearot

Thank you for your reply but it doesn't work.

I don't have any "plugins" directory. 
This is what i find instead under Application Support directory:

<img width="193" alt="Schermata 2021-01-15 alle 20 11 36" src="https://user-images.githubusercontent.com/5303109/104768446-fc3f7100-576d-11eb-8b70-956ef33d933f.png">

What shall i do?

Thanks,
Andrea

**Comment by nedimf** [comment]
Can you get me pwd of that folder where you are? @andrearot

**Comment by andrearot** [comment]
Sure, here it is:

`Macintosh HD⁩ ▸ ⁨Utenti⁩ ▸ ⁨macbookpro⁩ ▸ ⁨Libreria⁩ ▸ ⁨Application Support⁩ ▸ ⁨obs-studio`

**Comment by nedimf** [comment]
Yeah, it seems it's different dir structures. Plugins for you might be in 
- ```Applications -> OBS.app```
-  Right click show package contents (1)
- ```Plugins ``` (2)

![1](https://user-images.githubusercontent.com/24845593/104811529-71f21e00-57fc-11eb-8019-b5095b8575c6.png)

![2](https://user-images.githubusercontent.com/24845593/104811533-80403a00-57fc-11eb-8d87-00df01bdb1dc.png)

**Comment by andrearot** [comment]
Ok, I tried Show Package Contents but I still can't find the directory:

<img width="301" alt="Schermata 2021-01-16 alle 13 30 00" src="https://user-images.githubusercontent.com/5303109/104811964-4a508500-57ff-11eb-8efa-dec4854784ca.png">

**Comment by nedimf** [comment]
At this point, I'm not even sure it's installed. Can you open ```OBS Studio -> Tools -> OBS Websocket```

**Comment by andrearot** [comment]
Hi nedimf,
here is what I can see if I open Tools section in OBS ("Strumenti" in italian means "Tools"):

<img width="1077" alt="Schermata 2021-01-17 alle 10 43 13" src="https://user-images.githubusercontent.com/5303109/104836866-2483b880-58b1-11eb-84e5-aec7704774d4.png">

Thanks,
Andrea

**Comment by nedimf** [comment]
Very sorry for late response. To be honest, I have no idea what's happening there. Only what comes to my mind it's to try installing plugin again, and click on location to see where it will install it. Then send that location so we can check it, because all normal place where plugins should be installed are empty for you.

@andrearot

**Comment by andrearot** [comment]
Ok, I've just reinstalled the plugin, now I have the following files in the following directories:

In
`/Library/Application Support/obs-studio/`
I have:
<img width="238" alt="Schermata 2021-01-19 alle 17 04 32" src="https://user-images.githubusercontent.com/5303109/105060366-98bc8880-5a78-11eb-9be7-865eabbc5d4a.png">

In
`Applications/OBS.app -> (Right click show package contents) -> Plugins/`
I have
<img width="272" alt="Schermata 2021-01-19 alle 17 08 06" src="https://user-images.githubusercontent.com/5303109/105060646-ee913080-5a78-11eb-8e0e-c8fe67f0c046.png">

Is something changed now? Can I uninstall plugin? If so, can you tell me how?

Thanks a lot,
Andrea

**Comment by nedimf** [comment]
I have installed same version of OBS as you have, and I still don't get why OBS-Socket is not shown in ```/Library/Application Support/obs-studio/```. So to further investigate issue 
![Screenshot 2021-01-19 at 20 02 00](https://user-images.githubusercontent.com/24845593/105080811-a6cad300-5a91-11eb-8d2c-1bae5d405a7a.png)

can you please go to Tools->Logs-> Current Logs and copy part under module loaded. 
After that please let me know what is in under ```obs-studio/plugin-config````` and ```obs-studio/basic``` from image above you sent. 
So we are looking for obs-websocket.so file, and after we find it, we can remove it.
@andrearot

**Comment by andrearot** [comment]
Ok, so here's the log:

`13:19:15.952: CPU Name: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
13:19:15.952: CPU Speed: 2300MHz
13:19:15.952: Physical Cores: 4, Logical Cores: 8
13:19:15.952: Physical Memory: 16384MB Total
13:19:15.952: OS Name: Mac OS X (NSMACHOperatingSystem)
13:19:15.952: OS Version: Version 10.14.6 (Build 18G6042)
13:19:15.952: Kernel Version: 18.7.0
13:19:15.957: hotkeys-cocoa: Using layout 'com.apple.keylayout.Italian-Pro'
13:19:15.959: Current Date/Time: 2021-01-20, 13:19:15
13:19:15.959: Browser Hardware Acceleration: true
13:19:15.959: Portable mode: false
13:19:16.273: OBS 26.1.2 (mac)
13:19:16.273: ---------------------------------
13:19:16.274: ---------------------------------
13:19:16.274: audio settings reset:
13:19:16.274: 	samples per sec: 48000
13:19:16.274: 	speakers:        2
13:19:16.310: ---------------------------------
13:19:16.310: Initializing OpenGL...
13:19:17.212: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce GT 750M OpenGL Engine
13:19:17.212: OpenGL loaded successfully, version 4.1 NVIDIA-12.0.24 355.11.10.50.10.103, shading language 4.10
13:19:17.320: ---------------------------------
13:19:17.320: video settings reset:
13:19:17.320: 	base resolution:   1280x720
13:19:17.320: 	output resolution: 1280x720
13:19:17.320: 	downscale filter:  Bicubic
13:19:17.320: 	fps:               30/1
13:19:17.320: 	format:            NV12
13:19:17.320: 	YUV mode:          709/Partial
13:19:17.320: NV12 texture support not available
13:19:17.320: Audio monitoring device:
13:19:17.320: 	name: Predefinito
13:19:17.320: 	id: default
13:19:17.321: ---------------------------------
13:19:17.357: Failed to load 'en-US' text for module: 'decklink-captions.so'
13:19:17.377: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
13:19:17.555: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
13:19:17.556: No blackmagic support
13:19:17.592: [mac-virtualcam] version=1.3.0
13:19:17.680: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
13:19:17.703: [obs-browser]: Version 2.10.0
13:19:17.703: [obs-browser]: CEF Version 85.0.0-HEAD.2273+g93b66a0+chromium-85.0.4183.121
13:19:17.859: [obs-browser]: OS version older than 10.15 Disabling hwaccel
13:19:18.170: VLC found, VLC video source enabled
13:19:18.906: [obs-websocket] you can haz websockets (version 4.8.0)
13:19:18.906: [obs-websocket] qt version (compile-time): 5.10.1 ; qt version (run-time): 5.15.2
13:19:18.909: [obs-websocket] module loaded!
13:19:18.910: ---------------------------------
13:19:18.910:   Loaded Modules:
13:19:18.910:     obs-websocket.so
13:19:18.910:     vlc-video.so
13:19:18.910:     text-freetype2.so
13:19:18.910:     rtmp-services.so
13:19:18.910:     obs-x264.so
13:19:18.910:     obs-vst.so
13:19:18.910:     obs-transitions.so
13:19:18.910:     obs-outputs.so
13:19:18.910:     obs-filters.so
13:19:18.910:     obs-ffmpeg.so
13:19:18.910:     obs-browser.so
13:19:18.910:     mac-vth264.so
13:19:18.910:     mac-virtualcam.so
13:19:18.910:     mac-syphon.so
13:19:18.910:     mac-decklink.so
13:19:18.910:     mac-capture.so
13:19:18.910:     mac-avcapture.so
13:19:18.910:     image-source.so
13:19:18.910:     frontend-tools.so
13:19:18.910:     decklink-ouput-ui.so
13:19:18.910:     decklink-captions.so
13:19:18.910:     coreaudio-encoder.so
13:19:18.910: ---------------------------------
13:19:18.910: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): dlopen(../obs-plugins/obs-browser.so, 257): image not found
13:19:18.910: 
13:19:18.911: ==== Startup complete ===============================================
13:19:18.939: All scene data cleared
13:19:18.939: ------------------------------------------------
13:19:18.976: coreaudio: device 'Built-in Microphone' initialized
13:19:18.976: [Loaded global audio device]: 'Microfono/disp. ausiliario'
13:19:18.980: Mac: Selected device 'FaceTime HD Camera'
13:19:18.982: Mac: Using preset 1280x720
13:19:19.067: Switched to scene 'Scena'
13:19:19.070: ------------------------------------------------
13:19:19.070: Loaded scenes:
13:19:19.070: - scene 'Scena':
13:19:19.070:     - source: 'Mac' (av_capture_input)
13:19:19.070: ------------------------------------------------
13:19:19.146: [obs-websocket] server started successfully on port 4444
13:19:19.146: [obs-websocket] io thread started
`

Here's what is under `obs-studio/plugin-config` :

<img width="297" alt="1" src="https://user-images.githubusercontent.com/5303109/105174526-fa393180-5b22-11eb-93a6-7e6007526bb4.png">
<img width="293" alt="2" src="https://user-images.githubusercontent.com/5303109/105174534-fc02f500-5b22-11eb-9e01-5b0a557f955b.png">


And here's what is under `obs-studio/basic ` :

<img width="289" alt="3" src="https://user-images.githubusercontent.com/5303109/105174608-189f2d00-5b23-11eb-8376-76a8aeae76ed.png">

Thanks,
Andrea

**Comment by nedimf** [comment]
At this point I'm quite clueless whats going on, it loads ```obs-websocket.so``` somehow. From where it loads it, it's mistery. As you can see, every module from your log, it loads from OBS.app->Plugins, so it makes no sense why ```obs-websocket.so``` it s not there. 
We checked if it's installed already, and it's running correctly.So at this point my only advice is to turn off obs-websocket,and continue using OBS normally. Sorry,  I couldn't be of more help @andrearot.

**Comment by andrearot** [comment]
It's not good news...

Thanks anyway,
Andrea

**Comment by nedimf** [comment]
Sure, will do!

**Comment by garrettreid** [comment]
> `Macintosh HD⁩ ▸ ⁨Utenti⁩ ▸ ⁨macbookpro⁩ ▸ ⁨Libreria⁩ ▸ ⁨Application Support⁩ ▸ ⁨obs-studio`

This looks a little strange to me, I interpret this as (English equivalent) `/Users/macbookpro/Library/Application Support/obs-studio`. Can you confirm you looked in the system-wide `Library` folder right on `Macintosh HD`, rather than your user's `Library`?

I think that would be (in your format) `Macintosh HD⁩ ▸ ⁨Libreria⁩ ▸ ⁨Application Support⁩ ▸ ⁨obs-studio`.

**Comment by andrearot** [comment]
You were right! I was seeking in the wrong place... now i took a look in the system-wide Library and i found (and deleted) it!

But I have to tell you that the first time i checked the both Library folders (system-wide and user) and the obs-studio folder wasn't there.

Thank you!
Andrea

**Comment by nedimf** [comment]
@andrearot be free to close this issue
