### ISSUE TITLE
Show active/not-active sources in events

### ISSUE THREAD

**Issue by fbosman** [Palakis/obs-websocket#656]
Now this marvelous program raises an event in case of switching of scenes.
We also need events when a source is switched on of off in the active scene.
Is this possible?

**Comment by fbosman** [comment]
You mean this one: 
SceneItemVisibilityChanged


Thanks, I missed that one, I’ll test it.

Met vriendelijke groet,

Frans Bosman


Verstuurd vanaf mijn iPhone

Op 19 jan. 2021 om 14:49 heeft lebaston100 <notifications@github.com> het volgende geschreven:

﻿
I think you are looking for this event https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#sceneitemvisibilitychanged

**Comment by tt2468** [comment]
Did it answer your question? If so, we can close the request

**Comment by fbosman** [comment]
Solved!  Thank you!
