### ISSUE TITLE
FEATURE REQUEST: Release CreateSource

### ISSUE THREAD

**Issue by MikaelX** [Palakis/obs-websocket#661]
##### Issue type
Feature request

##### Description
I would like to have a new release that includes CreateSource

##### Technical information
- **Operating System** : Mac OSX 11.1 ARM64
- **OBS Studio version** : 26.1.2
- **obs-websocket version** : 4.8.0

Would be great if we could also work on the workflow to get that up to par with deprecated issues like set-var. I can't build the source code on my arm64 due to ffmpeg fails to compile during obs-studio compilation.

**Comment by tt2468** [comment]
It is going to be released in 4.9 when 4.9 is available.
