### ISSUE TITLE
BUG: Cancel transition do not broadcast "TransitionEnd" event

### ISSUE THREAD

**Issue by gavalierm** [Palakis/obs-websocket#662]
##### Issue type

 - Bug report

##### Description
When you start transition with T-bar and return it to starting position (like from 0 to 50 percent and back to 0 ) you got only first event: TransitionBegin, but no TransitionEnd event.

##### Technical information
- **Operating System** : MacOSX
- **OBS Studio version** : Latest
- **obs-websocket version** : Latest

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks
