### ISSUE TITLE
Scene's not coming back as sources

### ISSUE THREAD

**Issue by Sabuto** [Palakis/obs-websocket#663]
##### Issue type

 - Bug report 

##### Description
Hi, I am really sorry if this has been answered before but, When i do ```GetSourcesList``` it doesn't return the scene's too, so for example i am trying to get a lit of sources that i can change filters on but it only returns the sources, I read somewhere else that it scenes are considered sources so it should return the scenes too? Essentially i am trying to build a list of each available source to be able to alter a filtervisibility.
Edit: But when i do ```SetSourceFilterVisibility``` on the scene it works fine.

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 26.0.2
- **obs-websocket version** : 4.8

**Comment by tt2468** [comment]
Indeed it seems to only return `input` sources. Our code should return all types of sources (`input`, `filter`, `transition`, `scene`), but we are using an OBS api function` obs_enum_sources()`, so the data we return is being provided by that. I will have to look into how OBS decides which sources to enumerate.

**Comment by tt2468** [comment]
Unfortunately, it appears that we are limited to only inputs being returned by `GetSourcesList`. Closing this as a wontfix as we will be implementing sources in a very different way in 5.0.0
