### ISSUE TITLE
Feature request: CreateSource

### ISSUE THREAD

**Issue by zakiahmdismail** [Palakis/obs-websocket#664]
##### Issue type
 Feature request

##### Description
I'm looking to do full automation from installing OBS to **add a Video Capture Source** as one of the sources to taking screenshots/recording. The installation and taking screenshot/recording are done and now I would like to request to add the CreateSource function. 

Do you have any plan to release CreateSource any time soon?

If not, do you have any other suggestions on how I can do this via automation.

**Comment by tt2468** [comment]
CreateSource is currently merged but not in a release yet. We plan on releasing it in v4.9 somewhere around the 10th.
