### ISSUE TITLE
GetSceneItemProperties 'width' and 'height' should return another value.

### ISSUE THREAD

**Issue by MarioMey** [Palakis/obs-websocket#670]
##### Issue type
- Bug report

##### Description
Supposedly, width and height are the final sceneitem size. They return the base width and height multiplied by their scale:

```cpp
// Utils.cpp:784
	obs_data_set_double(data, "width", baseSourceWidth * scale.x);
	obs_data_set_double(data, "height", baseSourceHeight * scale.y);
```
Shouldn't they be substracted by its crop values before multiplying them? Something like:
```cpp
// Utils.cpp:784
	obs_data_set_double(data, "width", (baseSourceWidth - crop.left - crop.right)* scale.x);
	obs_data_set_double(data, "height", (baseSourceHeight - crop.top - crop.bottom) * scale.y);
```
(I don't know C++, maybe it's misspelled)

Saddly, I don't use obs-websocket anymore 😢... because I programed my own OBS-OSC-PythonScript 0.1. I used to use obs-websocket-py and obs-websocket. Now, I don't send OSC messages to Python and Python to Websockets... it's slow and it crashes OBS several times. I directly send OSC messages to Python script 😉.

But I've been using obs-websockets-py for a time and now, I realized that GetSceneItemProperties should be different. As I fixed that in my code, websocket may copy me 😁.

Thank you very much for obs-websocket!

**Comment by tt2468** [comment]
I do agree that it is misleading, however we are returning data just like you would see in the Scene Item Transform window. Straying from the current format would likely be even more misleading. If users want the actual size of the item, they can run the arithmetic on their end. Potentially a note can be made to the docs or another field pair like `displayedHeight` could work as an intermediary.
