### ISSUE TITLE
[Feature Request] Streaming Network Status

### ISSUE THREAD

**Issue by Thelvaen** [Palakis/obs-websocket#673]
##### Issue type
Feature request

##### Description
It would be interesting to get network status (actual bitrate, configured bitrate, image loss %) available somewhere, so it can be displayed on a deckboard or something.

**Comment by tt2468** [comment]
https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getstats

https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#obsstats

This is what is available

**Comment by Thelvaen** [comment]
Yeah, but that's not quite what I'm looking for.

My ISP seems to have some Peering issue with Twitch (or with the intermediary operator, I'm not sure about that part), hence I'd like to detect when my upload bitrate goes really under the 6000kb/s configured so I can either stop streaming or try to change the ingest server I'm connected to.

I just took a look at the GetStats results, and its not providing me with the data I need.

**Comment by Thelvaen** [comment]
Do I need to create a new issue as you already closed it?

**Comment by Thelvaen** [comment]
For reference, the end point you mention provide the top part of the screen capture attached, while I need the bottom part of it.

![obs_stats](https://user-images.githubusercontent.com/19350574/107592311-f160ea80-6c0c-11eb-83f9-c005e9d9d5ea.png)
