### ISSUE TITLE
Homogenization of props : Kebab Case or Camel Case ?

### ISSUE THREAD

**Issue by evandikt** [Palakis/obs-websocket#677]
##### Issue type

This is not a Bug report or Feature request ...

- Feature request

##### Description

This question must have already been asked but I can't find it ...

In the protocol sometimes it happens that the properties of objects are in kebab-case and other times in camelCase, it's rather boring !
Being a dev using this API, I would find it easier to have one or the other of the methods but not having both !

Example in SceneItemAdded :

scene-name => sceneName
item-name => itemName
item-id => itemId

Thx for your amazing plugin 👍

**Comment by Palakis** [comment]
kebab-case props are there for retrocompatibility reasons. New additions and developments within the plugin must adhere to camelCase.

**Comment by Palakis** [comment]
Eventually, we'll make a breaking release that updates all props to camelCase.

**Comment by evandikt** [comment]
@Palakis It would be really great to make a version :)
Possibly a 5.0.0 ( if you follow semver ) ?

**Comment by evandikt** [comment]
@Palakis it's possible to have both ?

To keep retrocompatibility ?
And warn for deprecation on 5.X in docs ? 

For example :

SceneItemAdded {
scene-name
item-id
item-name
sceneName
itemName
itemId
}

**Comment by tt2468** [comment]
5.0.0 is a breaking release so no retro-compatability will be left.

**Comment by xurei** [comment]
Adding my two cents here : 
Would it be possible to keep the Kebab Case in version 5.0.0 as a deprecated field ?
This would give time to developers/streamers to update their clients...

**Comment by tt2468** [comment]
@xurei 5.0.0's low-level API is completely different, and many requests are barely comparable to 4.x requests, so unfortunately that would not be worth the effort to do.
