### ISSUE TITLE
FEATURE REQUEST: Be able to run a request from one OBS instance to react with another

### ISSUE THREAD

**Issue by mach7** [Palakis/obs-websocket#680]
##### Issue type
- Feature request

##### Description
My Setup: I use a copy of OBS Studio here in my home (in Utah) to produce a show for multiple clients. I use another copy of OBS (in Montana) to switch between cameras and feed the virtual camera output to OBS Ninja. 
The Request:
I would like a way to be able to have a scene on my home setup communicate with the remote copy of OBS and switch to a specific scene there. Allowing the feed to be changed to a different camera.

**Comment by tt2468** [comment]
obs-websocket cannot be used to script actions like this. We are only an interface with OBS. I suggest using one of the libraries [here](https://github.com/Palakis/obs-websocket#for-developers) to script the actions that you want.
