### ISSUE TITLE
BUG REPORT: Not working as intended

### ISSUE THREAD

**Issue by DualVission** [Palakis/obs-websocket#681]
##### Issue type

Bug report

##### Description

Websocket not functioning with 26.1.1.
##### Steps to reproduce and other useful info

Have the following:
- Logi Plugin
- NDI
Issue occurs when Qt5Websockets.dll is in plugins

##### Technical information
- **Operating System** : Windows 10 Pro Build 21313.rs_prerelease.210209
- **OBS Studio version** : 26.1.1
- **obs-websocket version** : 4.8/4.9
[Log File](https://github.com/Palakis/obs-websocket/files/5980680/2021-02-15.03-39-59.txt)

**Comment by tt2468** [comment]
Your obs-websocket version is 4.5.0. You should update.

**Comment by DualVission** [comment]
I definitely believe that is a possibility but I decidedly used the 4.9 installer... Odd. Thank you, I'll make sure to do that when I get back to my computer.
