### ISSUE TITLE
Change the password by ws request

### ISSUE THREAD

**Issue by ko3ak81** [Palakis/obs-websocket#682]
##### Issue type

Feature request 

##### Description
Add the ability to change the pass by WS request Immediately after the installation for Docker or headless environment. Currently, there is a prompt on the 1st run to sett the pass. if it is being ignored and the OBS restarted the default "changeme" pass doesn't work 

##### Technical information
- **Linux** :
- **26** :
- **4.9** :

**Comment by tt2468** [comment]
Since obs-websocket does not have a fundamental permissions system, allowing changing of the password over websocket would arguably expose a meaningful attack vector. I suggest generating a password yourself and setting it in the profile .ini file before loading OBS.
