### ISSUE TITLE
[Bug report] TransitionToProgram with-transition does not override transition overrides

### ISSUE THREAD

**Issue by duncte123** [Palakis/obs-websocket#683]
##### Issue type
Bug report

##### Description
When having a transition override on a scene (in my case with the [move plugin](https://obsproject.com/forum/resources/move-transition.913/)), the transition override gets played instead of the one I set in `with-transition`.

This behavior differs from using hotkeys to trigger the transition or clicking the button in obs

##### Steps to reproduce and other useful info

(debug log attached)
[obs websocket log.txt](https://github.com/Palakis/obs-websocket/files/5990974/obs.websocket.log.txt)

1. Create a transition override on both sources that you want to switch between
2. trigger a TransitionToProgram with the quick transition of your choice that differs from the overrides
3. The transition override gets played instead

##### Technical information
- **Operating System** : Windows 10 (OS build 19041.804)
- **OBS Studio version** : 26.1.1
- **obs-websocket version** : 4.9.0

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks
