### ISSUE TITLE
Websocket requiring multiple authentications for OBS tools (Bar Raider) in Stream Deck

### ISSUE THREAD

**Issue by TheHypeGoblin** [Palakis/obs-websocket#684]
##### Description

When setting up the features of OBS Tools in Stream Deck the websocket requires authentication for each tool source. First source authenticates fine, second source authentication is asked for again and it just sits on the authenticating dialogue forever. Using the same default port for all authentication settings.
![Ca
![Capture](https://user-images.githubusercontent.com/79219708/108246716-62c20100-7117-11eb-9ad9-0cb06a4b268d.JPG)
pture](https://user-images.githubusercontent.com/79219708/108246691-5b025c80-7117-11eb-841d-4ef0868f2599.JPG)

##### Technical information
- **Operating System** : Windows - latest version
- **OBS Studio version** : 26.1.1
- **obs-websocket version** : latest release as of 2/17/2021

**Comment by tt2468** [comment]
This issue is more suited for the OBS tools support, not for us, as we only maintain the plugin.
