### ISSUE TITLE
[Bug Report] Obs fader in decibels does not correspond to decimals values returned by SourceVolumeChanged

### ISSUE THREAD

**Issue by jordaofranca** [Palakis/obs-websocket#688]
##### Description

Obs fader in decibels does not correspond to decimals values returned by `SourceVolumeChanged`
When you set the volume under -45db, float values gets all closer to 0.01.

##### Steps to reproduce and other useful info

Try to use a fader from 0 to 1 and controle the obs volume or make it listen to obs mixer fader. You need to use `SourceVolumeChanged` and to ste it I've used `SetVolume`. Move faders in obs and in your fader. (I've used obs-websocket-js and react)

##### Technical information
- **Ubuntu** :
- **OBS Studio 26.1.1** :
- **obs-websocket 4.9** :

**Comment by tt2468** [comment]
`SourceVolumeChanged` returns the `mul` volume format (general f0-1) while it appears you are using the `useDecibel` flag, which of course is in decibel format. You will need to convert from `mul` to decibel via the method used here: https://github.com/obsproject/obs-studio/blob/master/libobs/media-io/audio-math.h#L31

**Comment by jordaofranca** [comment]
@tt2468 I'm not using decibels, I'm just comparing the mul sent to the decibel scale. Have you tried what I said? Create a fader using mul? there's no steps between 0.01 (equivalent to -45) and 0 (equivalent to -inf). If you send 1 it will 0, if you send 0.01 it will be -45 in OBS. I'm not using the `useDecibel`.

**Comment by jordaofranca** [comment]
Ok, got it. There's a disclaimer in Uppercase tellling that its not percentage. You can close it. Thanks for the help anyway. By the way, would be good to have the flag the way you've decribed @tt2468, 

> SourceVolumeChanged returns the mul volume format (general f0-1) while it appears you are using the useDecibel

There isn't any decibel flag for `SourceVolumeChanged`.

**Comment by tt2468** [comment]
I'll make a note to include decibel values along with the mul values in events. Not sure when I can get to the change.
