### ISSUE TITLE
OpenProjector monitor selection after being able to check its position or name

### ISSUE THREAD

**Issue by henry-delaruelle** [Palakis/obs-websocket#689]
##### Issue type

!--- - Feature request --
OpenProjector monitor selection after being able to check its position or name

##### Description

I use the openprojector message to open a fullscreen preview monitor to one of the 3 monitors connected to my computer.
Monitors 2 and 3 sometimes get a different monitor number after a reboot, resulting in the preview on the wrong screen.
In OBS i can see the name of the monitor and its position and  select the right monitor, but via the websocket i can not check if the monitor number is connected to the right monitor.

It would be helpfull if it would be possible to request the monitor configuration as visible in OBS (eg. PHL 272B8Q (2) 2560x1440 @ 2560,0) to determine the right monitor by its position in the multimonitor environment.

Being able to check is a fullscreen projector is allready open (to prevent multiple projectors on top of each other), and being able to close these projectors would be also be nice but is of less importance to me,

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 26.1.1
- **obs-websocket version** : 4.8.0

**Comment by tt2468** [comment]
This is not possible due to the nature of the functions we use in OBS

**Comment by henry-delaruelle** [comment]
Oke, sorry to hear that.

As an alternative i tried to use OpenProjector with -1 as the monitor, using the geometry parameter string. When i read the qt documentation this should be  x,y,width,height. When i use OpenProjector with these parameters, whatever i fill in, it results in a small preview window at the same position. 

obs.OpenProjector("preview", -1, "2560,0,2560,1440",null);

Is there something additional i should do to get a preview windows with the right position and size ?

**Comment by henry-delaruelle** [comment]
I have been struggling to find information about the used format of the geometry string., the link to the qt information was not very helpfull for me.

I found the geometry data in the ini file of OBS, and created a little example of how the interpret the data, this might be helpfull for other programmers so maybe you could use it in your documentation.


Example:

In windows, in the %appdata%\obs-studio folder, in the file global.ini there is a line that stores the geometry of the obs main window :

geometry=AdnQywADAAAAAAUqAAAB3wAACWIAAATXAAAFKwAAAf4AAAlhAAAE1gAAAAAAAAAACgAAAAUrAAAB/gAACWEAAATW

The geometry string is a base64 encoded bytearray containing the geometry data in Big Endian format. 

01 d9 d0 cb 00 03 00 00 00 00 05 2a 00 00 01 df 00 00 09 62 00 00 04 d7 00 00 05 2b 00 00 01 fe 00 00 09 61 00 00 04 d6 00 00 00 00 00 00 00 00 0a 00 00 00 05 2b 00 00 01 fe 00 00 09 61 00 00 04 d6

the following parameters are found in the array :

0x01d9d0cb : magicNumber
0x0003     : majorVersion
0x0000     : minorVersion

0x0000052a : frameGeometryX
0x000001df : frameGeometryY
0x00000962 : frameGeometrX2
0x000004d7 : frameGeometrY2

0x0000052b : normalGeometryX
0x000001fe : normalGeometryY
0x00000961 : normalGeometryX2
0x000004d6 : normalGeometryY2

0x00000000 : screenNumber

00         : windowMaximized
00         : windowFull
00000a00   : screenWidth

0x0000052b : screenGeometryX
0x000001fe : screenGeometryY
0x00000961 : screenGeometryX2
0x000004d6 : screenGeometryY2
