### ISSUE TITLE
Enhancement Request - Set Text setting on Text GDI+ source

### ISSUE THREAD

**Issue by pantonvich** [Palakis/obs-websocket#69]
Dynamically updating the Text setting in a Text GDI+ source.

**Comment by pantonvich** [comment]
I was trying to work on this myself as well - this kind of works but get an access violation when you exit out of obs - during the WSEvents::OnSceneItemDelete

so I'm clearly doing something wrong...

`
	obs_sceneitem_t *sceneItem = Utils::GetSceneItemFromName(scene, itemName);
	if (sceneItem != NULL)
	{
		if (req->hasField("text") ) {		
			obs_source_t* sceneItemSource = obs_sceneitem_get_source(sceneItem);
			const char *sceneItemSourceId = obs_source_get_id(sceneItemSource);

			if (strcmp(sceneItemSourceId, "text_gdiplus") == 0) {
				const char *text = obs_data_get_string(req->data, "text");
				obs_data_t* sourceSettings = obs_source_get_settings(scene); 
				obs_data_set_string(sourceSettings, "text", text);
				obs_source_update(sceneItemSource, sourceSettings);
				obs_data_release(sourceSettings);
			}
			obs_source_release(sceneItemSource);
		}
		obs_sceneitem_set_visible(sceneItem, isVisible);
		obs_sceneitem_release(sceneItem);
		req->SendOKResponse();`

**Comment by pantonvich** [comment]
if I comment out my two release statements it exits without an issue - 
```
//obs_data_release(sourceSettings);
//obs_source_release(sceneItemSource);`
```

**Comment by pantonvich** [comment]
this seams to be working - I'll test more over the next week - I've basically added text to the SetSourceRender - I'm guessing it would be easy to add other properties like font ect at the same time.

`
{\"message-id\":\"FeedLapsToGoOn\",\"request-type\":\"SetSourceRender\",\"source\":\"FeedLapsToGo\",\"render\":true,\"text\":\"1\"}"
`

code added in: void WSRequestHandler::HandleSetSceneItemRender(WSRequestHandler *req)
`

	obs_sceneitem_t *sceneItem = Utils::GetSceneItemFromName(scene, itemName);
	if (sceneItem != NULL)
	{
		if (req->hasField("text") ) {		
			obs_source_t* sceneItemSource = obs_sceneitem_get_source(sceneItem);
			const char *sceneItemSourceId = obs_source_get_id(sceneItemSource);
			if (strcmp(sceneItemSourceId, "text_gdiplus") == 0) {
				const char *text = obs_data_get_string(req->data, "text");
				obs_data_t* sourceSettings = obs_source_get_settings(scene); 
				obs_data_set_string(sourceSettings, "text", text);
				obs_source_update(sceneItemSource, sourceSettings);
				obs_data_release(sourceSettings);
			}
			//obs_source_release(sceneItemSource); 
		}
		obs_sceneitem_set_visible(sceneItem, isVisible);
		obs_sceneitem_release(sceneItem);
		req->SendOKResponse();
`

**Comment by Palakis** [comment]
Implemented in https://github.com/Palakis/obs-websocket/pull/94
