### ISSUE TITLE
Feature Request: GetPreviewSources / SetPreviewSources

### ISSUE THREAD

**Issue by VideoGameRoulette** [Palakis/obs-websocket#693]
Currently we have the ability to remotely manipulate sources in our currently broadcasted scene "Program", but we need a way to to manipulate the preview scene while something is running in current to get the next group ready for a smooth transition and quicker turn around times in events for setups.

Example 
Group A is live on Scene A
Group B is being set up on Scene B while Group A is Live so sources will be switched Scene B from Group A to Group B
Group A Finished Run Transist to Group B on Scene B
Group A is now on preview and might be using Scene C or Scene D ect

this helps allow remote users to get the preview scenes all setup remotely otherwise someone would need to be at the helm at all times to manually make these changes on the preview scene which right now with the pandemic isn't viable.

now with this said we can just have scenes for Group A and B seperated to get around this, but that means there will be 16 Scenes instead of 8 and we are trying to reduce the amount of Scenes in OBS especially when something as simple as a toggle in preview would make this possible and reduce the amount of scenes needed for such an event.

**Comment by tt2468** [comment]
Why not just run `GetPreviewScene` and then `GetSceneItemList` on the scene in order to return the scene items?

Also, we have an Issue template. Please use it next time.

**Comment by VideoGameRoulette** [comment]
ya I just noticed that was possible the other day I've been slowly digging thru the Protocol documentation and seeing things I didn't notice before browsing through the request and response data.
