### ISSUE TITLE
browser source self selection

### ISSUE THREAD

**Issue by paul-lrr** [Palakis/obs-websocket#695]
##### Issue type
 - Feature request 

##### Description
If a have a browser source _in OBS_ that is connecting to the obs-websocket, is there any way for that source to uniquely identify and manipulate itself?

##### Steps to reproduce and other useful info
A browser source can use the JavaScript library to connect to obs-websocket and use `GetSourcesList` to get all the sources in OBS, but I can't figure out how it can identify itself in that list. As far as I can tell, browser sources don't have access to any OBS-specific identifiers, such as their own name in OBS, their item ID or even the scene it is loaded on. `GetSourceSettings` can tell me the url of each browser source, but that won't uniquely identify a source if there are multiple instances of the same page. Any thoughts?

**Comment by tt2468** [comment]
This would need to be a feature request for the appropriate js bindings to be added to obs-browser. obs-websocket is simply incapable of providing a feature like this.

**Comment by paul-lrr** [comment]
Fair enough! thanks for the quick response
