### ISSUE TITLE
SetTextFreetype2Properties does not handle Umlauts, seems it doesn't properly decodes from UTF-8

### ISSUE THREAD

**Issue by Corion** [Palakis/obs-websocket#698]
##### Issue type

Bug report

##### Description

When sending a message like the following (note the "ö" in the name:

    {
          "source" : "Text.NextSpeaker",
          "request-type" : "SetTextFreetype2Properties",
          "text" : "Daniel Böhmer, Max Maischein",
          "message-id" : "10"
    }

... the scene item text gets changed to 

    Daniel BÃ¶hmer, Max Maischein

This looks as if the `text` field is not UTF-8 decoded when using the data from the websocket.

##### Steps to reproduce and other useful info

1. Add a "Text (Freetype 2) scene item, name it `Text.NextSpeaker` (or whatever).
2. Set its text to a character above 128, using for example the above message.
3. Watch the scene item get the undecoded glyphs, not the UTF-8 glyphs.

##### Technical information
- **Operating System** : Debian Linux 10 (Buster)
- **OBS Studio version** : 26.1.2-139
- **obs-websocket version** : Git Version 6bb33fa18b2ae2b0454842cd9aa2ec963e844b73

**Comment by tt2468** [comment]
And to confirm, this works properly when setting it via the UI? Because on our end, these are the steps we take

- Import json via `obs_data_create_from_json()`
- Pass data object around a bit
- `obs_data_set_string(settings, "text", obs_data_get_string(request.parameters(), "text"));`

So we never directly handle the text, however, using obs_data_get_string() returns `const char*` so... /shrug

**Comment by Corion** [comment]
Ow. Yes - when I manually set the text, I get back invalid UTF-8 , because the string is passed through verbatim/unencoded. So it seems that the real bug is in OBS itself resp. its API where it passes back char* ...

Unfortunately this means that we cannot use any non-ASCII character, as it will result in invalid JSON messages. At least my JSON decoder insists on receiving proper UTF-8 :-(

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks
