### ISSUE TITLE
Feature Request / Query - SetSourceFilterSettings to allow removing options

### ISSUE THREAD

**Issue by Wol** [Palakis/obs-websocket#699]
##### Issue type
- Feature request

##### Description
With the `SetSourceFilterSettings` call, there isn't a way to remove an option seemingly. I'm trying to update a settings value on a `color_filter` filter from: `{ color: 0x123456, opacity: 100 }` to just `{ opacity: 100 }`

Having a look into the source code, it uses `obs_data_apply` to merge options in, but this doesn't support removing options. `obs_data_erase` seems to allow this however. I was going to try doing a PR for this, but want some guidance on the best API to implement, whether to update the existing `SetSourceFilterSettings` option so that null / undefined or something can remove an item, or whether to add a new `ClearSourceFilterSettings` or `RemoveSourceFilterSettings` option which I could pass with `{ color: true }` or something like that?

**Comment by tt2468** [comment]
To be honest, I can't think of a very good way to implement an erase function other than to add a bool parameter which runs obs_data_clear() before doing obs_data_apply(). This would be a change added to probably every request that allows setting of arbitrary json objects. We are doing some quite significant changes in v5.0.0, so this could be a good contender for a dedicated system.

**Comment by Wol** [comment]
Thanks for the reply. As a workaround for the time being, I've instead just actively set the value to the default value shown in the source code for the given feature, rather than allowing it to pick its own default.  This has solved the issue I was having, but actively setting it to a value which is defined as a default in someone else's code, when I can't get the defaults myself seems a bit off. 

It's not a high priority one either way! 👍
