### ISSUE TITLE
StartStreaming fails, but StartStopStreaming works

### ISSUE THREAD

**Issue by mitrousis** [Palakis/obs-websocket#70]
Version: obs-websocket 4.0.0, Windows binary install

Calling StartStreaming request (example):
{"request-type": "StartStreaming", "message-id": "abcd"}

Returns: 
1:31:12 : { "error": "invalid request type", "message-id": "abcd", "status": "error" }

Calling StopStartStreaming works as expected:
{"request-type": "StartStopStreaming", "message-id": "abcd"}

**Comment by Palakis** [comment]
`StartStreaming` and associated commands were added AFTER the release of 4.0.0. Here's the protocol spec for 4.0.0 : https://github.com/Palakis/obs-websocket/blob/4.0.0/PROTOCOL.md
