### ISSUE TITLE
Feature request: StartVirtualCamera StopVirtualCamera

### ISSUE THREAD

**Issue by Meetsch** [Palakis/obs-websocket#700]
##### Issue type
Feature request

##### Description
We currently have StartStreaming/StopStreaming and StartRecording/StopRecording, but the equivalent feature is missing for the new Virtual Camera feature.
In our use-case the ability to StopVirtualCamera via websocket is needed to automatically stop the virtual camera before shutting down a pc, because if we leave the virtual camera active we get a pop-up message asking to disable the virtual camera before exiting and this blocks the shutdown.
Note: we currently start the virtual camera using obs command line argument at startup, but we have no way to stop it other than with mouse click.

##### Technical information
- **Operating System** : Win10
- **OBS Studio version** : 26.1.1
- **obs-websocket version** : 4.9.0

**Comment by Alyss-Swanson** [comment]
Thank you for suggesting this Meetsch.  I just finished posting the same request in the forum. I might suggest, however, that we petition for a "GetVirtualCameraStatus" to be more fully symmetric with the _Record and _Stream controls. By the same token, it may be useful for some apps to have the StartStopVirtualCamera, as well as the PauseVirtualCamera and ResumeVirtualCamera.  All of that said and understanding how precious resources are your recommendation would seem to address the most vital elements.

**Comment by Meetsch** [comment]
FYI, I have advanced the implementation in a fork
https://github.com/Meetsch/obs-websocket/tree/feature/virtualcam

But before making a pull request I'm waiting for obs-studio to make a new release which will include the necessary api
https://github.com/obsproject/obs-studio/commit/3bc4e8ecbab768b3a700aba2d34fc2364179f6f2

**Comment by tt2468** [comment]
@Meetsch Go ahead and just make a PR and we'll label it accordingly.

**Comment by Meetsch** [comment]
@tt2468 I've just made the #708 PR for you to review and label appropriately.
As per the OBS Studio project, the required OBS-Studio v27.0 should be released by march 31.
