### ISSUE TITLE
"Authentication Failed" error produced when connections are made simultaneously

### ISSUE THREAD

**Issue by tylerstraub** [Palakis/obs-websocket#703]
##### Issue type
 - Bug report

##### Description
It appears that `obs-websocket` may not queue or throttle inbound connection requests, which creates the possibility for connections occurring at the same moment in time to be rejected with a misleading error ("Authentication Failed").

This problem was discovered by users of [Kruiser8/Kruiz-Control-Widget](https://github.com/Kruiser8/Kruiz-Control-Widget) running multiple instances of local WebSocket connections though Browser Sources.

The workaround put into place was to insert a random time delay interval before making a connection to the WebSocket server.

##### Steps to reproduce and other useful info
- If multiple WebSocket clients initialized from browser sources attempt to connect and authenticate at exactly the same moment, `obs-websocket` will reject the connection and output an "Authentication Failed" error. 
- In order to work around this issue, we had to  generate a random time delay before the client attempts to connect to the `obs-websocket`. As long as the various browser sources are not connecting at the same moment in time, everything works as expected. 

```
19:19:07.191: [obs-websocket] Request >> '{"auth":"23J+ClEecH20MB66bfLgpGeCo6LkkHg4NW7oDisRmf8=","request-type":"Authenticate","message-id":"1"}'
19:19:07.191: [obs-websocket] Response << '{
19:19:07.191:     "error": "Authentication Failed.",
19:19:07.191:     "message-id": "1",
19:19:07.191:     "status": "error"
19:19:07.191: }'
```

##### Technical information
- **Operating System** : bug was reproduced in both MacOS + Windows OBS
- **OBS Studio version** : 26.1.2
- **obs-websocket version** : 4.9.0

**Comment by tt2468** [comment]
Closing this as a wontfix, as we have no plans of fixing the issue in 4.x. 5.0.0 will not have this issue.
