### ISSUE TITLE
Filter Settings  - Max & Min value properties

### ISSUE THREAD

**Issue by Etuldan** [Palakis/obs-websocket#704]
##### Issue type
- Feature request

##### Description
Using [GetSourceFilters](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getsourcefilters) (or [GetSourceFilterInfo](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getsourcefilterinfo)) , it could be nice to be able to get Max and Min values of a filter setting.

##### Steps to reproduce and other useful info
I am using [SetSourceFilterSettings ](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#setsourcefiltersettings )but I can't guess which values are acceptable or not.

##### Technical information
- **Operating System** : Win10
- **OBS Studio version** : 21.1.1 (x64)
- **obs-websocket version** : 4.9.0

**Comment by tt2468** [comment]
Unfortunately, this is not possible within the OBS api.
