### ISSUE TITLE
Calling SetPreviewScene with an invalid name does not return an error

### ISSUE THREAD

**Issue by Lange** [Palakis/obs-websocket#71]
If I call `SetPreviewScene` with the name of a scene that does not exist in the current collection, obs-websocket returns a `status` of `ok`. I think it should return an error of some kind.

**Comment by Palakis** [comment]
Yes it should. I forgot to put a check for this...

**Comment by Palakis** [comment]
Fixed in https://github.com/Palakis/obs-websocket/commit/9ddfad99eaecc7ba82e39f9db27efe62bc10b1d5
