### ISSUE TITLE
TriggerHotkeyBySequence does not work with multiple keys

### ISSUE THREAD

**Issue by OlegShklyarov** [Palakis/obs-websocket#710]
I am trying to press alt+F2.
Send it like this:

obs.send('TriggerHotkeyBySequence', {
'keyModifiers.alt': true,
'keyId':"OBS_KEY_F2",
});

Does not work, why? Fires only F2

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks
