### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by ModcoLocko** [Palakis/obs-websocket#712]
The following packages have unmet dependencies:
  obs-websocket: Depends: obs-studio (>= 25.0.7) but it is not going to be installed
  
  
 Issue on pop os (unbuntu basically) linux using eddy to install.
 
 My obs version is 26.1.1, i assume this is an issue where the package isn't updated for this version.

**Comment by tt2468** [comment]
What method are you using to install? It's going to be looking with dpkg/apt for obs so if you have it under a different package name or not installed via dpkg, it's of course going to fail.
