### ISSUE TITLE
Allow AddSceneItem to set name of scene item

### ISSUE THREAD

**Issue by ccMatrix** [Palakis/obs-websocket#719]
##### Issue type
- Feature request

##### Description
When a source is added to a scene using `AddSceneItem` the name of the scene item is the same as the source. When a source is used multiple times then all scene items have the same name. This makes it impossible to differentiate them by name. While working with the itemId is a workaround for this it would be nice if we could specify the scene item name when we use `AddSceneItem`.

I propose an optional parameter itemName to be added to AddSceneItem for this case.

##### Steps to reproduce and other useful info
Create a scene with a source
Create a second scene and add the source using AddSceneItem
Create another source in the second scene using AddSceneItem
Use SetSceneItemProperties to set the position of the scene item using the Name of the scene item. Only first item in scene 2 will be changed.

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 26.1.1
- **obs-websocket version** : 4.9.0

**Comment by tt2468** [comment]
OBS scene items are just the name of the source. If you rename a scene item, it renames the source, which renames all other scene items for that source too.
