### ISSUE TITLE
PreviewSceneChanged is not emitted when calling TransitionToProgram

### ISSUE THREAD

**Issue by Lange** [Palakis/obs-websocket#72]
When `TransitionToProgram` is called (and runs successfully), `PreviewSceneChanged` is not emitted even though `SwitchScenes` is.

**Comment by Palakis** [comment]
Fixed in https://github.com/Palakis/obs-websocket/commit/d0118c63c054af34cac7ac3536bf95c3ba6cf27a (the `preview-api` branch has been merged into `master`, btw).
