### ISSUE TITLE
Missing Installer

### ISSUE THREAD

**Issue by DwarfsLord** [Palakis/obs-websocket#720]
##### Issue type

 - Bug report

##### Description
The Readme states that there should be an installer under /releases.
Neither the folder nor any .exe exist. (AFAIK)

On the other hand, I might just be too incompetent, and would appreciate a pointer in the right direction.

Thanks!

**Comment by tt2468** [comment]
https://github.com/Palakis/obs-websocket/releases/tag/4.9.0 is where you can find the latest release with the installer
