### ISSUE TITLE
Feature Request: Multiple Websocket Sessions

### ISSUE THREAD

**Issue by CravenInsomniac** [Palakis/obs-websocket#724]
##### Issue type

Feature request

##### Description
So my use-case is niche, and I run 2 instances of OBS. One to stream with and one in portable mode for recording and the the portable instance shares my gameplay with NDI. I'm currently attempting to setup my Elgato Stream Deck with my streaming instance (port 4444) and setting up Touch Portal with my recording instance (Port 4445). My issue is that after setting up my Stream Deck I cannot get my phone to connect. My understanding regarding websocket sessions is basically nil, so if it's not technically possible I understand. It'd be just one more reason to migrate to multiple pc setup.

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** :  26.1.1 (64bit)
- **obs-websocket version** : 4.9.0

**Comment by tt2468** [comment]
You can connect an infinite amount of sessions to a given websocket server.

Have you tried disabling windows firewall as a test?
