### ISSUE TITLE
playPause parameter in PlayPauseMedia isn't optional

### ISSUE THREAD

**Issue by gaeldemarseille** [Palakis/obs-websocket#725]
##### Description

playPause parameter in PlayPauseMedia isn't optional as opposed to what [protocol.md](docs/generated/protocol.md#playpausemedia) says.

> Note :Leaving out playPause toggles the current pause state

##### Steps to reproduce and other useful info

I used  [obs-websocket-js  (4.0.2)](https://github.com/haganbmj/obs-websocket-js) by Brendan Hagan to call the API
```
obs.send('PlayPauseMedia', {
    'sourceName': 'Media Source'
});
```
And in the debug logs I can see the _missing request parameters_ error

```
02:09:26.056: [obs-websocket] Request >> '{"source":"Media Source","request-type":"PlayPauseMedia","message-id":"5"}'
02:09:26.056: [obs-websocket] Response << '{
02:09:26.056:     "error": "missing request parameters",
02:09:26.056:     "message-id": "5",
02:09:26.056:     "status": "error"
02:09:26.056: }'
```

Once I added the playPause parameter, the request worked.
```
obs.send('PlayPauseMedia', {
    'sourceName': 'Media Source',
    'playPause': true
});
```

```
02:24:01.981: [obs-websocket] Request >> '{"sourceName":"Media Source","playPause":true,"request-type":"PlayPauseMedia","message-id":"4"}'
02:24:01.981: [obs-websocket] Update << '{
02:24:01.981:     "sourceKind": "ffmpeg_source",
02:24:01.981:     "sourceName": "Media Source",
02:24:01.981:     "update-type": "MediaPaused"
02:24:01.981: }'
02:24:01.981: [obs-websocket] Response << '{
02:24:01.981:     "message-id": "4",
02:24:01.981:     "status": "ok"
02:24:01.981: }'
```

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 26.1.1 (64 bit)
- **obs-websocket version** : 4.9.0

**Comment by TinaTiel** [comment]
Can also confirm this problem as well, while writing observation E2E tests for [websocket-obs-java](https://github.com/Twasi/websocket-obs-java).

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks
