### ISSUE TITLE
Control OBS multi-rtmp-plugin via websocket

### ISSUE THREAD

**Issue by jeremiasmanninen** [Palakis/obs-websocket#726]
##### Issue type
Feature request

##### Description

I would be very pleased if there were a way to start/stop specific multi RTMP streams by WebSocket. Getting the stream status (fps) would also be great!

Here is the plugin: https://github.com/sorayuki/obs-multi-rtmp/releases/

**Comment by tt2468** [comment]
Unfortunately we are restricted to mainly only controlling obs itself. (With some exceptions)

So integrations like this are pretty much just not possible.
