### ISSUE TITLE
SetSourceSettings doesn't update the source settings

### ISSUE THREAD

**Issue by illusdidi** [Palakis/obs-websocket#729]
##### Issue type
Bug report 
##### Description

I tried to deactivate a video capture device in OBS with **SetSourceSettings** with a commande like this :
```
obs.send('SetSourceSettings', {
  'sourceName': 'Avermedia capture',
  'sourceSettings': {'active': false}
});
```
If I do a **GetSourceSettings** after that the active status changed to "false" :
```
{ 'message-id': '5',
  sourceName: 'Avermedia capture',
  sourceSettings:
   { active: false,
     audio_device_id: 'CABLE Output (VB-Audio Virtual Cable):',
     audio_output_mode: 0,
     buffering: 0,
     frame_interval: 0,
     last_resolution: '1280x720',
     last_video_device_id:
```
But the source keeps activated.
##### Steps to reproduce and other useful info

Tried with obs-websocket-js and obscommand.exe
##### Technical information
- **Operating System** : Windows 10 64-bit
- **OBS Studio version** : 26.1.1 64-bit
- **obs-websocket version** : 4.9.0

**Comment by marcosknudsen** [comment]
I have the same problem, did you found the solution?

**Comment by tt2468** [comment]
This is generally a failure within the Video Capture Device source, not in obs-websocket. If your underlying issue is audio desync, users have reported that sending an empty `audio_device_id`, then setting it back to the original value resets the source.

**Comment by joshebosh** [comment]
not to necro closed post, but looking all over, landed here for this same issue... trying to click the "Activate" / "Deactivate" button for an usb wecam input... in my case I'm trying to have AutoHotKey detect an unplugged webcam and when it gets plugged back in, AHK will send to OBS to reactive the webcam upon detection... I experienced the same results as **illusdidi** was... and the emptying "video_device_id" and repopulating wasnt doing the trick either...

I found there was this API that can be used **PressInputPropertiesButton** which helped me achieve the goal by clicking the **activate** button... my input was named **Rear-Low-Left**

here's the gist of it when re-plugging in already known camera, and re-activating it in OBS via hitting [Ctrl+Alt+Win+c] twice, to decativate, and activate again...

```
#Include lib/OBSWebSocket.ahk
#Include lib/Array_Gui.ahk

global obsmc := new MyOBSController("ws://127.0.0.1:4455/")

class MyOBSController extends OBSWebSocket {

	GetInputSettingsResponse(data) {
		dump := JSON.Dump(data)
		;Clipboard := dump
		Array_Gui(data)
	}	
}

^!#c::
obsmc.PressInputPropertiesButton("Rear-Low-Left","activate")
obsmc.GetInputSettings("Rear-Low-Left")
Return
```
