### ISSUE TITLE
GetAuthRequired not returning Salt

### ISSUE THREAD

**Issue by haganbmj** [Palakis/obs-websocket#73]
Using the (latest) build with SHA 386e1f3
obs-studio 18.0.1
Sending `GetAuthRequired` doesn't return a `salt` interestingly.

```
{
    "authRequired": true,
    "challenge": "ovEBf8ew3qLnOJ6DM8017dMJUwOOQXDCcucZe/IieTw=",
    "message-id": "4",
    "status": "ok"
}
```

**Comment by Palakis** [comment]
@haganbmj With that same version, try to set your password again.

**Comment by haganbmj** [comment]
Will do when I get a chance later, I had tried the following, but somehow forgot to just try setting a new password.
- Restart OBS.
- Disable/Re-enable Authentication.
- Disable Authentication, Restart OBS, Re-enable Authentication.

**Comment by haganbmj** [comment]
Yep, loaded obs, verified I still couldn't get a salt. Changed password. Got salt.

**Comment by haganbmj** [comment]
Probably just some issue when upgrading.
