### ISSUE TITLE
[FEATURE REQUEST] Retrieve ALL the hotkey names available, in order to use it via `TriggerHotkeyByName`

### ISSUE THREAD

**Issue by BarRaider** [Palakis/obs-websocket#730]
##### Issue type
- Feature request

##### Description
Retrieve  ALL the hotkey names available, in order to use it via `TriggerHotkeyByName`

##### Steps to reproduce and other useful info
Looking at the Utils.cpp code:
https://github.com/Palakis/obs-websocket/blob/035767bbbbdb06684c87e000caeaf966ff22cff4/src/Utils.cpp#L638

Is it possible to retrieve ALL the hotkeys from the search and pass them to the client?

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 26
- **obs-websocket version** : 4.9

**Comment by tt2468** [comment]
Implemented in v5.0.0. Will not be included in any 4.x releases
