### ISSUE TITLE
Wont work with OBS 27.0.0

### ISSUE THREAD

**Issue by JeffWalnut** [Palakis/obs-websocket#731]
##### Description

The plugin wont connect to Touch Portal on OBS 27.0.0..
Please update ASAP
Please email me at: jonahwahlund2006@gmail.com
##### Steps to reproduce and other useful info
 After you have OBS 27.0.0 installed and the plugin.. when you try to connect to Touch Portal, it doesnt work..
https://obsproject.com/logs/zBmrXmJp6JCLBcge 

##### Technical information
- **Operating System** : Windows 10 pro
- **OBS Studio version** : 27.0.0
- **obs-websocket version** : Latest Version

**Comment by Palakis** [comment]
@JeffWalnut 

1) Touch Portails fails to authenticate with obs-websocket. **Make sure Touch Portal is configured with the right obs-websocket password**

```
20:00:52.611: [obs-websocket] you can haz websockets (version 4.9.0)
20:00:52.611: [obs-websocket] qt version (compile-time): 5.10.1 ; qt version (run-time): 5.15.2
20:00:52.612: [obs-websocket] module loaded!
[...]
20:06:14.047: [obs-websocket] new client connection from [::ffff:127.0.0.1]:50447
20:06:14.047: [obs-websocket] Request >> '{"request-type":"GetAuthRequired","message-id":"tp-5961877227550379770"}'
20:06:14.047: [obs-websocket] Response << '{
20:06:14.047:     "authRequired": true,
20:06:14.047:     "challenge": "[redacted]",
20:06:14.047:     "message-id": "tp-5961877227550379770",
20:06:14.047:     "salt": "[redacted]",
20:06:14.047:     "status": "ok"
20:06:14.047: }'
20:06:14.048: [obs-websocket] Request >> '{"request-type":"Authenticate","auth":"[redacted]","message-id":"tp737305438760353942"}'
20:06:14.048: [obs-websocket] Response << '{
20:06:14.048:     "error": "Authentication Failed.",
20:06:14.048:     "message-id": "tp737305438760353942",
20:06:14.048:     "status": "error"
20:06:14.048: }'
```

**Comment by JeffWalnut** [comment]
Hi,

Yes it is configured correctly.. obs says that it has connected..

it just wont work..

**Comment by tt2468** [comment]
It is not configured correctly. The password in obs-websocket and the password in touch portal do not match, as per the log you provided. If you are ultra confident that you have the password correct, then you will need to reach out to the touch portal devs, because we have not changed how our authentication system works and it is obs version agnostic.

**Comment by tt2468** [comment]
```
20:06:14.048: [obs-websocket] Request >> '{"request-type":"Authenticate","auth":"VzP76hYrs1j1xotuFxBr0VuDIIHr47Ddbh182YaJFoo=","message-id":"tp737305438760353942"}'
20:06:14.048: [obs-websocket] Response << '{
20:06:14.048:     "error": "Authentication Failed.",
20:06:14.048:     "message-id": "tp737305438760353942",
20:06:14.048:     "status": "error"
20:06:14.048: }'
20:06:14.049: [obs-websocket] Request >> '{"request-type":"GetStreamingStatus","message-id":"tp5788486361228713553"}'
20:06:14.049: [obs-websocket] Response << '{
20:06:14.049:     "error": "Not Authenticated",
20:06:14.049:     "message-id": "tp5788486361228713553",
20:06:14.049:     "status": "error"
20:06:14.049: }'
```

Touch portal fails to authenticate, then keeps trying to call the server and fails. This is a touch portal issue.
