### ISSUE TITLE
There is any way to send a command into a simple static HTTP page?

### ISSUE THREAD

**Issue by Barabba11** [Palakis/obs-websocket#735]
Hi! Sorry to create an issue for just a question, please forgive me
I'm not a web expert, I need to create a simple http static page with some buttons (images), click on them I want to change scene, there is any way to sent to websocket the command using "href" or something like that? May somebody write here an example? Thank you
like:
<div id="e1" class="cc07">
<a href="**something here to send to OBS***"> <br>Click here to change shene</a>
</div>

**Comment by tt2468** [comment]
You can use https://github.com/IRLToolkit/obs-websocket-http

To make websocket requests over http

**Comment by Barabba11** [comment]
thank you for your help, this sounds good but the PC wunning the small HTTP server is Windows, can I run it on Pythin for Windows too?

**Comment by Barabba11** [comment]
I was able to install it, simply I've installed python (checking the option to add it to PATH in the beginning of setup), then download your sip and put it in a folder, for example c:\1, then edit config.ino and put the correct info there. Then I became sure that pip is installed, typing <pip help>, then I've installed the needed modules executing <pip install -r requirements.txt>, and then I run the main.py.

Now I don't have any idea how to execute it from html page, I've tried something like:
<div id="e0" class="cc08">
		<a curl -XPOST -H "Content-type: application/json" -d '{"scene-name":"Scene2"}' 'http://192.168.24.2:81/emit/SetCurrentScene'>
		<a href="http://192.168.24.2/index.html"><img src="logo.jpg" border="0" alt="Logo" title="Logo"></a> 
	</div>
but this code is not well understood
Thank you for your kind help

**Comment by Barabba11** [comment]
If somebody would contribute, I would be very happy to help in any way, thanks

**Comment by tt2468** [comment]
Hi,

We've recently enabled Github discussions on this repo. Issues are now reserved only for bug reports and feature suggestions. If this issue is still relevant, I encourage you to open a new discussion for it.

Thanks
