### ISSUE TITLE
Feature Request: Option to create scene item duplicates rather than just references and set their visibility

### ISSUE THREAD

**Issue by christinna9031** [Palakis/obs-websocket#736]
##### Issue type
- Feature request

##### Description
DuplicateSceneItem command gives no option to choose whether we want to copy and paste a reference or a duplicate of a scene item. It always defaults to a reference. 
It would be also nice to be able to choose whether the duplicated item should be visible or not, similar to the setVisible request field when using CreateSource command. 

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 26.1.1 (and 27.0.0-rc2) 
- **obs-websocket version** : 4.9

**Comment by tt2468** [comment]
Scene items can be created via `CreateSceneItem` in 5.0.0. To completely duplicate a source will need to be done via 5.0.0's various requests. Not planning to implement a recursive source cloning system into 5.x
