### ISSUE TITLE
 can I redirect websockets with NGINX and Proxy server?

### ISSUE THREAD

**Issue by RssFra97** [Palakis/obs-websocket#737]
Good morning,
I need to be able to do a redirection from a linux machine with NGINX via reverse proxy otherwise I can't control OBS while I'm in IRL.
is it possible to do this? if so, how can I do it?

I have a home network configuration that does not allow me to exit directly from the PC running OBS

**Comment by RssFra97** [comment]
I have risoto with this NGINX configuration and I can reach OBS outbound via NGIX (SSL and port 443)

```
server {
  listen 443 ssl default_server;
  listen [::]:443 ssl default_server;
  server_name subdomain.domain.net;

  ssl_certificate /etc/letsencrypt/live/subdomain.domain.net/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/subdomain.domain.net/privkey.pem;


  location /obs/ws/ {
    proxy_pass http://192.168.x.xx:4444;
    proxy_http_version 1.1;
    proxy_read_timeout 3600;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
```

**Comment by tt2468** [comment]
Hi,

We've recently enabled Github discussions on this repo. Issues are now reserved only for bug reports and feature suggestions. If this issue is still relevant, I encourage you to open a new discussion for it.

Thanks
