### ISSUE TITLE
GetSpecialSources custom sources

### ISSUE THREAD

**Issue by Lombra** [Palakis/obs-websocket#74]
I didn't build the latest version to test, and I'm not really fluent in C++, but it looks like GetSpecialSources is hardcoded to return those five default audio channels? Would like to see support for custom audio channels, such as those used by VLC media sources, video capture devices, etc.

**Comment by Palakis** [comment]
`GetSpecialSources` returns the five (or less) configured desktop audio and mic/aux input sources which are not listed in the list of sources in a scene. You can list the rest of the sources through the childs of `GetSceneList`.
