### ISSUE TITLE
Setting Scene Item visibility to true does not work with browser source

### ISSUE THREAD

**Issue by BlakeHarriman** [Palakis/obs-websocket#747]
##### Issue type

 - Bug report

##### Description
Setting visibility to true for a Scene Item does not seem to work for me.   Setting it to false works just fine, but I am having no luck with setting it to true.  Looking through the logs it appears that it is not updating the visibility.  The browser source that I am attempting to change the visibility of is the same browser source that I am using to run the code with.  Is this possibly a limitation with setting the visibility of a browser source doing it this way?

##### Steps to reproduce and other useful info

const OBSWebSocket = require('obs-websocket-js')
const obs = new OBSWebSocket()

//This works
obs.send('SetSceneItemProperties', {item: 'MySourceName', visible: 'false'}).then(data => {
            console.log(data)
        }).catch(err => {
            console.log("Socket Error: " + err)
        });

//This does not work
obs.send('SetSceneItemProperties', {item: 'MySourceName', visible: 'true'}).then(data => {
            console.log(data)
        }).catch(err => {
            console.log("Socket Error: " + err)
        });

##### Technical information
- **Operating System** : Windows 10 64 bit
- **OBS Studio version** : 26.1.1
- **obs-websocket version** : v4.9.0

##### Logs
[2021-05-18 00-49-58.txt](https://github.com/Palakis/obs-websocket/files/6498538/2021-05-18.00-49-58.txt)

**Comment by BlakeHarriman** [comment]
It should be:
visible: true
instead of
visible: 'true'
Not sure why it works when false is a string, but I suppose it might just be that way.  I hope this helps anyone else who had a brain fart like me

**Comment by tt2468** [comment]
> Not sure why it works when false is a string, but I suppose it might just be that way.

We just accept a boolean value from the JSON. If using a boolean directly doesn't work, then there is something wrong on your end.

**Comment by BlakeHarriman** [comment]
> > Not sure why it works when false is a string, but I suppose it might just be that way.
> 
> We just accept a boolean value from the JSON. If using a boolean directly doesn't work, then there is something wrong on your end.

Yeah it works for both true and false when I send them as boolean values.  When I send false as a string, however, it still works.  It doesn't work when true is sent as a string.  I was just pointing out how it's weird that it would work for false, but not true when you send both of them as strings.

**Comment by tt2468** [comment]
Ah, I see.

Well I should say that in 5.x, fields must match the required type, otherwise the entire request will fail.
