### ISSUE TITLE
Extra symbol at the beginning of each displayed line (when using a command)

### ISSUE THREAD

**Issue by titanscity** [Palakis/obs-websocket#749]
##### Issue type

 - Bug report

##### Description

In OBS v 26.1.1 , each command created with streamlabs tchatbot v 1.0.2.64 is displayed in the tchat zone in OBS with one some extra symbol at the beginning of each line.
It appears either if the command contains several lines, it send several lines in the tchat (and all begin with a different extra symbol as * or > or ! (and more)  
##### Steps to reproduce and other useful info

Just create a command in streamlabs Chatbot containing different lines and launch the command in the main tchat. Each line will displayed with an extra symbol at the beginning.
[2021-05-19 06-29-40.txt](https://github.com/Palakis/obs-websocket/files/6505906/2021-05-19.06-29-40.txt)

##### Technical information
- **Operating System** : windows 10
- **OBS Studio version** : 26.1.1
- **obs-websocket version** : 4.9.0

**Comment by tt2468** [comment]
This issue is unrelated to obs-websocket.
