### ISSUE TITLE
Audio mixing events

### ISSUE THREAD

**Issue by Lombra** [Palakis/obs-websocket#75]
Tying in to #74, some events for audio channels would be useful. (even without custom sources)

- Sources changed (enabled/added)
- Muted/unmuted
- Volume changed (?)

**Comment by Palakis** [comment]
Sources toggle, add and remove events are already implemented. They might however need some testing with Studio Mode.
As for the volume and mute events, this will be part of a larger project that aims to implement scene-independent events.

**Comment by Lombra** [comment]
To clarify, there are events for toggling the default mixes, too? That must be >4.0.0 then?

**Comment by Palakis** [comment]
Events: no, not yet. Part of that project mentioned above.

**Comment by Palakis** [comment]
Oops, misclick.

**Comment by sebseb7** [comment]
volume change events would be great! to keep it in sync with a remote.
