### ISSUE TITLE
GetSceneList lightweight version  

### ISSUE THREAD

**Issue by Mesihas** [Palakis/obs-websocket#753]
##### Issue type

Feature request

##### Description

GetSceneList lightweight version  would be very good for those that want to use this great plugin with ESP32 or similar.
when there is 40 sources in a Collection the response gets too big and can't be handled.

Would be perfect to be able to configure the fields included in a response or create a reduced version of GetSceneList with minimal info.

**Comment by tt2468** [comment]
obs-websocket v5.0.0 does not include scene items in `GetSceneList`, so that should fulfill your needs (when it comes out)

**Comment by Mesihas** [comment]
Thanks,  will need to retrieve sources for each scene in v5.0.0. ? should I use GetSceneItems for that?

Now GetSceneList is very useful for me, the only problem is when the message gets to heavy for a ESP32

**Comment by tt2468** [comment]
You would call `GetSceneList` then call `GetSceneItemList` for each scene for 5.0.0
