### ISSUE TITLE
Get Window Dropdown List for Window Capture Source?

### ISSUE THREAD

**Issue by rooseveltrp** [Palakis/obs-websocket#754]
##### Issue type
- Feature request

##### Description
Hi, I'm not sure if it's already supported or not. Checked out the protocols doc but can't seem to find anything.

On OBS, when you are modifying the Properties for Window Capture source, it gives you a list of Windows that are active on the user's computer.

![window_list](https://user-images.githubusercontent.com/4078130/120004988-68947180-bfa5-11eb-82d6-9e418fa33bc1.jpg)

If you can expose an endpoint to get that list, we can dynamically create window sources and let the user pick a window or something.

Kinda surprised it's not supported already o.O

**Comment by rooseveltrp** [comment]
Luckily, I found a solution. It's not the best, but it'll do for now. Since I'm creating an electron app, it made things a bit easier.

1) Get a list of windows/screens using `desktopCapturer.getSources()`
2) Next, it's a matter of getting the desired title from the list, create the source and resetting it.

```
obs.send('CreateSource', {
	"sourceName": "SomeWindow",
	"sourceKind": "window_capture",
	"sceneName": "Scene",
	"sourceSettings": {
	    window_name: 'Activity Monitor'
  	}
})

obs.send('ResetSceneItem', {
	"item": "SomeWindow"
})
```

Thanks for creating `obs-websocket`. It's awesome!

**Comment by rooseveltrp** [comment]
Reopening the issue. The above method works on mac but not on windows.
I think everyone's life will be much easier if there was a endpoint that exposes the following info:
```
Window Title:ClassName:process.exe
```
For example:
```
{
  sourceName: 'WizardScreen',
  sourceSettings: { window: 'Calculator:Windows.UI.Core.CoreWindow:Calculator.exe' },
  sourceType: 'window_capture'
}
```

**Comment by rooseveltrp** [comment]
Found a possible workaround using the Electron desktopcapturer method.
Not sure how it will perform with multiple instances of a window. But it will do for now.
```
{
        window: `Calculator:0:Calculator.exe`,
        window_name: "Calculator",
        method: 2,
        priority: 1,
}
```

Key is to force the Capture Method to `Windows Graphics Capture`

**Comment by tt2468** [comment]
You will be able to achieve this via `GetInputPropertiesListPropertyItems` when v5.0.0 comes out. Support for this will not be added to v4.9.1.

**Comment by rooseveltrp** [comment]
> You will be able to achieve this via `GetInputPropertiesListPropertyItems` when v5.0.0 comes out. Support for this will not be added to v4.9.1.

Awesome @tt2468! It's an amazing plugin, thanks for making it!

**Comment by hanxiang-li** [comment]
obs.call('GetInputPropertiesListPropertyItems', {
            inputName: 'Monitor' + timer,
            propertyName: 'monitor'
        })
 Error: Unable to find a property by that name.
