### ISSUE TITLE
SetSceneItemRender true returns 200 but not working

### ISSUE THREAD

**Issue by udbellamy** [Palakis/obs-websocket#756]
##### Issue type
 - Bug report 

##### Description
The SetSceneItemRender render: true return OK but the source remains visible in OBS.
No issue with SetSceneItemRender render: false, the source hides as expected.

##### Steps to reproduce and other useful info
Via obs-cli on windows : 
```
.\obs-cli-win.exe -a localhost:4444 -p test SetSceneItemRender='{ \"source\": \"Diaporama\", \"render\": \"1\" }'

[
  {
    "message-id": "2",
    "status": "ok",
    "messageId": "2"
  }
]
```
On linux : 
```
./obs-cli-linux -a localhost:4444 -p test SetSceneItemRender='{  "source":  "Diaporama", "render ": "1" }'

[
  {
    "message-id": "2",
    "status": "ok",
    "messageId": "2"
  }
]
```

Same issue with obs-websocket-http

```
curl --location --request POST 'http://localhost:4445/emit/SetSceneItemRender' \
--header 'Content-type: application/json' \
--data-raw '{

    "source": "Diaporama",
    "render": "1"
   
}'
```

##### Technical information
- **Operating System** : Windows 10 and Ubuntu 16.04.6
- **OBS Studio version** : 26.1.1
- **obs-websocket version** :  4.9.0

**Comment by udbellamy** [comment]
Same issue with SetSceneItemProperties.
Does not work with the visible parameter (true or false, return OK but no change in OBS)
Works partially with the locked parameter (both return ok, only false works).

```
curl --location --request POST 'http://localhost:4445/call/SetSceneItemProperties' \
--header 'Content-type: application/json' \
--data-raw '{
    "item": "Alertbox",
    "visible": "1"
}'
```

**Comment by tt2468** [comment]
This sounds like an issue with the software you are using. SetSceneItemRender works as expected using simpleobsws
