### ISSUE TITLE
Send a websocket change scene from a simple http page

### ISSUE THREAD

**Issue by Barabba11** [Palakis/obs-websocket#757]
Hi mates, please forgive me to opena bug to solve this problem, I really don't know where else hit my head.. I've tried everything, for days searched everywhere, and I can't figure out how to do a very simple thing: change a scene clicking a button on a simple http page. 
May you kindly please write an HTML code example how this is possible? (I don't need feedbacks/confermations, just the simple command).
Thank you immensely

**Comment by macharborguy** [comment]
Generally speaking, this GitHub Issues tracker is for the obs-websocket plugin itself, and not for any issues regarding third-party libraries.

What you are looking for is the [OBS Websocket JS](https://github.com/haganbmj/obs-websocket-js) library/github, which has all of the examples you would need.  The main ReadMe even has a SetCurrentScene example

**Comment by Barabba11** [comment]
Thank you! You gave me a really precious suggestion, I've managed to do it! I've spent days asking around and nobody was able to gave me such answer. I'm really happy. 
Again sorry for disturb
