### ISSUE TITLE
Interface stability and compatibility

### ISSUE THREAD

**Issue by willie68** [Palakis/obs-websocket#759]
First of all I would like to thank you for this plugin. I think it's great. And as far as i see this plugin is the de facto standard for loose connection to obs. That's why i created this ticket.
When implementing an OBS integration in my ReCoS system, however, I noticed a few irregularities, that I would like to address with this ticket. ReCoS is a service in Go, so I tried to use Chris de Graaf's Go Client (https://github.com/christopher-dG/go-obs-websocket). This generates the required code from the comments.json. The current version is based on plugin version 4.4. And it doesn't work against a 4.9 plugin because the interfaces on the plugin side has been changed. Another problem is that the generation also fails because of various missing types. Christian Muehlhaeuser (https://github.com/muesli/go-obs-websocket) version based on 4.7 does not work either. Also here because of changes in the plugin interface.
Example: up to version 4.7 (?) ListSceneCollection provided a simple list of Scene Collection names (String). After version 4.7 it delivered an array of objects (in go normally map[string]interface{}). (Incidentally, I did not find this change in the history) Such changes break the interface and are difficult to intercept on the client side.
Of course you could say that software A needs plug-in version X. But what about software B that needs plug-in version Y? Can you install the same plugin in different versions?
Therefore my request: It would be nice, if a little more care could be put on the interface in the next versions. Don't get me wrong, it's open source and everyone sacrifices their free time here, but it would still be very nice, if changes to the interface were only made in major versions. Extensions are of course excluded. But even here you should make sure that you do not change interfaces once they have been introduced. A Version 2 of the method can be introduced at any time. It doesn’t make the interface easier, but doesn’t break any existing software. Possibly a 2-stage procedure would also help here: Method as pre-release version: Thus not every client has to implement the feature and then in the next version as a stable, if you are sure that the interface fits that way.

**Comment by tt2468** [comment]
This is precisely what we are targeting for the v5.0.0 rewrite. It's an almost completely different RPC api, with a focus on consistency. At this stage we are not focusing much on documentation though, so the comments.json will be useless:

https://github.com/Palakis/obs-websocket/tree/master
