### ISSUE TITLE
Linker-Error: cannot find -lobs-frontend-api

### ISSUE THREAD

**Issue by ghandmann** [Palakis/obs-websocket#76]
Hi,
i'm trying to build OBS-WebSocket on a Debian 9 (Stretch). I've successfully build OBS-Studio.
But then the OBS-WebSocket Plugin fails to find the obs-frontend-api library. The library is created by the OBS-Studio Buildprocess. But it looks like, your Project lacks the right Linker-Options to find the location of the library?

Probably important: I don't install OBS-Studio after building, since these builds are only meant for Jenkins runs. But - as i peeked into the CMakeList.txt - the obs-frontend-api isn't respecting any "non standard" path for Linux system, right?

To clarify: On my Ubuntu Development system where OBS-Studio is installed normally i don't encounter this problem.

Building with gcc 6.3.0 and cmake 3.7.2 in a debian 9 docker container.

Edit: Current workaround is to set the `LIBRARY_PATH` env variable before `make`ing the plugin.

**Comment by Palakis** [comment]
@ghandmann Configure OBS Studio with `CMAKE_INSTALL_PREFIX=/usr` and, after building, install it (`sudo make install`). The Frontend API's library will then be put in a standard location where the linker can find it.
