### ISSUE TITLE
How can I retrieve all audio sources such as the OBS mixer via Websockets?

### ISSUE THREAD

**Issue by RssFra97** [Palakis/obs-websocket#762]
##### Issue type
How can I retrieve all audio sources such as the OBS mixer via Websockets?

I can't figure out which is the right method to call and the procedure I need to understand if it's an audio source

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 27
- **obs-websocket version** : 4.9.0

**Comment by tt2468** [comment]
You can use GetSourcesList to retrieve all input sources, then tell what kind of source it is by its kind. The global audio sources can be retrieved with `GetSpecialSources`

**Comment by RssFra97** [comment]
> You can use GetSourcesList to retrieve all input sources, then tell what kind of source it is by its kind. The global audio sources can be retrieved with `GetSpecialSources`

from what I have seen it only gives me the desktop and microphone audio not all the audio I can control in the OBS mixer
