### ISSUE TITLE
OBS hangs - looks like websocket may be the cause

### ISSUE THREAD

**Issue by shaunpond** [Palakis/obs-websocket#771]
##### Issue type

Bug report

##### Description

Hi, recently I've stated getting lockups in OBS when using websocket (via BArRaider's StreamDeck plugin) to change profile in OBS. There are two scenarios that I can determine: 1) when the scene change is triggered, nothing happens - i.e., the scene is unchanged. 2) If I establish a new link from the streamdeck plugin to OBS with OBS I see things like this:
09:43:50.972: [obs-websocket] Update << '{"profile":"Hutton","update-type":"ProfileChanged"}'
09:43:50.972: [obs-websocket] Websocket connection with client '[::ffff:127.0.0.1]:51833' closed (disconnected). Code is 1001, reason is: 'Server stopping'
09:43:50.972: [obs-websocket] IO thread exited.

and OBS hangs - I get an hourglass mousepointer and cannot interact with OBS at all. I appreciate that there are three things in play here: OBS itself, websocket and the streamdeck plugin. The other two players have scratched their heads and basically said "we don't think it's our fault". I'm happy to do whatever testing is necessary to try to determine where the problem lies, as i appreciate that this may be an edge case that I'm hitting... Please help me OBSwan, you're my only hope...
##### Steps to reproduce and other useful info

use websocket to change OBS profile, then perform more actions using websocket
##### Technical information
- **Operating System** :
- Win 10 pro 20H2
- **OBS Studio version** :
- 27.0.1
- **obs-websocket version** :
4.9.1
[2021-06-12 10-54-50.txt](https://github.com/Palakis/obs-websocket/files/6647460/2021-06-12.10-54-50.txt)

**Comment by tt2468** [comment]
Hello, a few questions.

- Does this issue happen with v4.9.0?
- There's a lot in the log here. Are these requests in the log performed automatically or are they the result of manual input to the streamdeck?
- The hang appears to happen during profile change. If you disable the websocket server then switch profiles manually via the gui, does it still hang?

**Comment by shaunpond** [comment]
Hi, yes it did happen with 4.9.0, but it only started failing recently - that may have coincided with upgrading websocket, but I can’t be sure.

The log entries should be because of streamdeck actions. I can make it fail most times now, so I am happy to go back and create a new log if you'd like?

If I change profiles manually, even with websocket enabled, it works fine.

Shaun

**Comment by tt2468** [comment]
Hmm, this sounds like it's a difficult issue to track down then. I have a few theories, but without a reliable way to reproduce the issue, I unfortunately can't provide much help. All of our focus is on the new 5.0.0 rewrite right now, so unfortunately I don't have much time to delegate. I can at least say that 5.0.0 should not have this issue, as we do not restart the websocket server when the profile changes.

If you can figure out a way to reproduce the issue reliably, let me know and I'll try to replicate it on my end.

**Comment by shaunpond** [comment]
Here are my steps to reproduce:

1.	Reset link in BarRaider OBS plugin, and re-enter server credentials.
2.	Press Streamdeck button running a multi-action with OBS Tools “set profile action”, followed by OBS studio action “record”

 

Zip file with OBS log (debug logging enabled for websocket) and OBS tools plugin log (I appreciate this log is not yours, but hoped that the timestamps might hold an extra clue

Expected result: profile would change, and recording starts

Observed result: OBS studio becomes “not responding”

 

Shaun

**Comment by shaunpond** [comment]
I appreciate that you won’t be looking to fix this in the 4.x releases, I just wondered if you’d had chance to look at the log and determine that this will be a non-issue with 5.x? Then I can stop worrying and go with a manual switch of profiles in the meantime 😊

Thanks

 

Shaun
