### ISSUE TITLE
Request `TakeSourceScreenshot` causes error 1009

### ISSUE THREAD

**Issue by Gamemap** [Palakis/obs-websocket#774]
##### Issue type

- Bug report

##### Description

I request `TakeSourceScreenshot` every second, but after a few frames I get error code 1009 and get disconnected from OBS Websocket.

##### Steps to reproduce and other useful info

[2021-06-17 15-49-06.txt](https://github.com/Palakis/obs-websocket/files/6670777/2021-06-17.15-49-06.txt)
Sorry, but I don't have more information.

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 27.0.1
- **obs-websocket version** : 4.9.1

**Comment by tt2468** [comment]
As the websocket protocol states, code 1009 means that you are receiving frames that are too large for your set maximum:
![image](https://user-images.githubusercontent.com/28720189/122416675-c8938d80-cf3d-11eb-8e13-95e387409c3c.png)

You need to tell your client's websocket library to use a larger maximum frame size, as to not get disconnected by screenshots.

**Comment by Gamemap** [comment]
It works now.
Thank you, now I have learned something new.

**Comment by abdusa** [comment]
Good job youmake
