### ISSUE TITLE
Extend SetVolume to go over time

### ISSUE THREAD

**Issue by BarryCarlyon** [Palakis/obs-websocket#777]
##### Issue type

- Feature request

##### Description

SetVolume will instantly change the volume.

In order to "gradual fade out" a volume source, you would need to "spam" the socket with `SetVolume` with a new different value.

So extend `SetVolume` to include a `time` parameter, so it will take the defined time to reach the target volume from current volume. And the plugin itself does the math to "slide"/figure out the steps the volume down. Rather than spamming the Socket with commands.

**Comment by tt2468** [comment]
Unfortunately this is not currently possible within OBS, without a torque setting being implemented to their api. I suggest that you do the appropriate calculations on your end and send requests to change the volume accordingly.
