### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by mayeaux** [Palakis/obs-websocket#782]
![Screen Shot 2021-06-22 at 23 37 04](https://user-images.githubusercontent.com/7200471/123003029-e7b57380-d3b2-11eb-8a16-2b4ef37e7303.jpg)
On OS X 

Should be 'sensitive' not 'sensetive'

**Comment by tt2468** [comment]
Yes, however development of 4.x has been abandoned, so this would be categorized as a wontfix.
