### ISSUE TITLE
LNK2001 Error unresolved external symbol related to obs_frontend_

### ISSUE THREAD

**Issue by sim-sliver** [Palakis/obs-websocket#79]
I'm getting a bunch of errors when building in visual studio,

> 2>  Generating Code...
> 2>obs-frontend-api.exp : error LNK2001: unresolved external symbol "void __cdecl obs_frontend_set_callbacks_internal(struct obs_frontend_callbacks *)" (?obs_frontend_set_callbacks_internal@@YAXPEAUobs_frontend_callbacks@@@Z)
> 2>obs-frontend-api.exp : error LNK2001: unresolved external symbol obs_frontend_add_event_callback
> 2>WSEvents.obj : error LNK2001: unresolved external symbol obs_frontend_add_event_callback
> 2>obs-frontend-api.exp : error LNK2001: unresolved external symbol obs_frontend_add_save_callback
> 2>obs-frontend-api.exp : error LNK2001: unresolved external symbol obs_frontend_add_tools_menu_item
> 2>obs-frontend-api.exp : error LNK2001: unresolved external symbol obs_frontend_add_tools_menu_qaction
> 2>obs-websocket.obj : error LNK2001: unresolved external symbol obs_frontend_add_tools_menu_qaction
> 2>obs-frontend-api.exp : error LNK2001: unresolved external symbol obs_frontend_get_current_profile
> 2>WSRequestHandler.obj : error LNK2001: unresolved external symbol obs_frontend_get_current_profile
> 2>obs-frontend-api.exp : error LNK2001: unresolved external symbol obs_frontend_get_current_scene
> 2>WSRequestHandler.obj : error LNK2001: unresolved external symbol obs_frontend_get_current_scene
> 2>WSEvents.obj : error LNK2001: unresolved external symbol obs_frontend_get_current_scene
> 2>Utils.obj : error LNK2001: unresolved external symbol obs_frontend_get_current_scene
> 2>obs-frontend-api.exp : error LNK2001: unresolved external symbol obs_frontend_get_current_scene_collection
> 2>WSRequestHandler.obj : error LNK2001: unresolved external symbol obs_frontend_get_current_scene_collection
> 2>obs-frontend-api.exp : error LNK2001: unresolved external symbol obs_frontend_get_current_transition
> .......
> 
> 

Any ideas why? I'm compiling with OBS Studio 18.0.1 using VS2015 64bit.

**Comment by Palakis** [comment]
- Did you set the `OBS_FRONTEND_LIB` variable in CMake? Is it pointing to the correct location of a `obs-frontend-api.lib` file for the current CPU arch?
- VS2015 isn't a problem if your build of OBS uses VS2015 too. Otherwise, don't mix VS versions between obs and the plugin.

**Comment by Palakis** [comment]
@sim-sliver Any update on this?
