### ISSUE TITLE
obs-websocket not loading

### ISSUE THREAD

**Issue by SlashScreen** [Palakis/obs-websocket#793]
Hi, I'm using OBS version 26.1.1 64 Bit.
I've been attempting to install this plugin, but the logs show it is not loading. I have already deleted the QT5 network thing like all the other issues.
What can I do to fix this?

**Comment by tt2468** [comment]
Please use discussions in the future.

You likely need to upgrade your OBS version. v4.9.1 will not load on 26.1.1

**Comment by SyrothTV** [comment]
Installed the app and win10 plugins.  I'm unable to get the iosApp to detect obs on the win10 client.  I've manually added tcp & udp port rules and cannot get connected either manual or auto.

**Comment by tt2468** [comment]
@SyrothTV For the record, we do not have any official client software. Help for software should go towards the respective client developers.
