### ISSUE TITLE
the  transitionBegin api request problem

### ISSUE THREAD

**Issue by sai99110** [Palakis/obs-websocket#796]
When I used the (TransitionBegin) api to request, the obs-websocket server returned to me: invalid request type. Why is this?

The request parameters are:
           {request-type: "TransitionBegin", message-id: "4"}

- **Operating System** :  mac os
- **OBS Studio version** :  26.1.2
- **obs-websocket version** :  4.9.1

**Comment by tt2468** [comment]
TransitionBegin is an event, not a request.
