### ISSUE TITLE
GetSourceSettings Feature

### ISSUE THREAD

**Issue by ambates** [Palakis/obs-websocket#797]
##### Issue type
Feature request

##### Description
Would it be possible to add extra data to the `GetSourceSettings` request? I have a very specific request whereby I want to change the NDI source. However I do not have sight of the options not selected. Therefore I can only change the value if I already new the value. 

##### Steps to reproduce and other useful info
When sending across the `GetSourceSettings`  request with a known `sourceName` the response back includes `sourceSettings`, but that object doesn't includes settings which could be used, only values which are selected.

```
sourceSettings : {
    latency: 0
    ndi_bw_mode: 0
    ndi_fix_alpha_blending: false
    ndi_recv_hw_accel: false
    ndi_source_name: "WINDOWS-VEEG7EC (MS Teams - Adam Bates)"
    ndi_sync: 1
    yuv_colorspace: 2
    yuv_range: 1
}
```

If it doesn't feel appropriate to add settings which are not set, but instead available could there be a `GetSourceSettingValues` or similar? whereby a param of `ndi_source_name` could be sent which returns an array of options. I am sure there will be other source settings which have a range of options.

**Comment by tt2468** [comment]
Use GetSourceDefaultSettings

**Comment by ambates** [comment]
Many thanks, I have just checked and for `ndi_source` the response is 

```
defaultSettings:
   latency: 0
   ndi_bw_mode: 0
   ndi_sync: 2
   yuv_colorspace: 2
   yuv_range: 1
}
```
Sadly, there is not the range of sources which could be selected. 
```

**Comment by tt2468** [comment]
That is not possible in 4.x. Those options will be available as `GetInputPropertiesListPropertyItems` in 5.0.0

**Comment by ambates** [comment]
Thank you. Great project too :-)
