### ISSUE TITLE
SourceAudioSyncOffsetChanged uses wrong data type for syncOffset, therefore can't display high values

### ISSUE THREAD

**Issue by YorVeX** [Palakis/obs-websocket#800]
##### Issue type
- Bug report

##### Description
Since syncOffset is Nanoseconds it can go to really high values. However, the field currently seems to be of a 32 bit integer datatype, because the highest value it can represent is a syncOffset of 2147 ms (= 2147000000 ns). Any value above that will lead to an overflow and cause the update to give wrong values. The data type should be changed to a 64 bit integer to solve that problem.

##### Steps to reproduce and other useful info
For Sync Offset in OBS set a value above 2147 ms and check the syncOffset field sent in the SourceAudioSyncOffsetChanged update. E.g. for 2148 ms I get:
`{"sourceName":"Mic/Aux","syncOffset":-2146967296,"update-type":"SourceAudioSyncOffsetChanged"}`

##### Technical information
- **Operating System** : Windows 10 Pro 64 Bit
- **OBS Studio version** : 27.0.1
- **obs-websocket version** : 4.9.1

**Comment by tt2468** [comment]
Going to have to be a wontfix due to 5.0.0 being in development. 5.0.0's version of the request will definitely use milliseconds and 64 bit integers.
