### ISSUE TITLE
Feature request: call javascript in the browser source

### ISSUE THREAD

**Issue by ethaniel** [Palakis/obs-websocket#807]
##### Issue type
- Feature request

##### Description
It would be amazing to be able to call any javascript function on the browser source. I rely on obs-websocket to alter the sources on the scene and would like to relay that (or any other) info into the browser page, so it could adjust to the changes. 

I am aware that OBS has scene change callbacks, but since I stay within one scene, it's not a viable option for me.

**Comment by tt2468** [comment]
Sorry, but considering the extensive changes that would be required to implement it on the obs-browser side, this addition is not in the scope of the obs-websocket project.

**Comment by 5opr4ni** [comment]
It's a pity this is not possible. In CasparCG you can do a CALL to any exposed function which making really advanced dynamic "Templates" possible, without setting up a back-end server for the web content.
