### ISSUE TITLE
OBS websocket installed, does not show up in tools

### ISSUE THREAD

**Issue by Barnsten** [Palakis/obs-websocket#809]
##### Issue type

- Bug report 

##### Description

Installed websocket with the exe file, rebooted computer and then ran OBS, does not show up in tools. Even tried uninstalling OBS and reinstalling both OBS and websocket. Still doesn't show up in tools. 
##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 27.0.1
- **obs-websocket version** : 5.0

**Comment by tt2468** [comment]
Would you be able to provide an OBS log?

Also, I see that you're some build of 5.0. There is not currently any applications that support 5.0's protocol, so I just want to confirm that you are installing 5.0 for development purposes.

**Comment by Barnsten** [comment]
Yes I did download obs-websocket 5.0.0-alpha1
Which version should I use?

**Comment by tt2468** [comment]
If you're intending to use the normal version of obs-websocket, go here: https://github.com/Palakis/obs-websocket/releases/tag/4.9.1

**Comment by Barnsten** [comment]
Thank you, that fixed the problem :)
