### ISSUE TITLE
Issue with Elgato Stream Deck

### ISSUE THREAD

**Issue by bhndbrwneyes** [Palakis/obs-websocket#81]
Been using this plugin for a few days integrated with my Twitch channel bot. It allows privileged users to send a chat command and change my scenes on the fly. I just got the Elgato Stream Deck so I can easily change my scenes with the touch of a button. The Elgato Stream Deck software renders the Websocket plugin inoperable. I can use the stream deck to change scenes but I can no longer get commands in my channel to work as well unless I uninstall the stream deck.

**Comment by Palakis** [comment]
Just tested this with 4.1 and the latest codebase on Win 8.1 by unpacking Elgato's installer and copying the plugin to OBS, and I don't notice anything wrong. No problems with default port 4444, I can get and set the current scene (for what I tested so far). Gonna do further testing in a Win 10 VM.

Which server port is configured in your obs-websocket settings?

**Comment by Palakis** [comment]
Also, can you tell me if your channel bot connects successfully (even if commands don't seem to work) to obs-websocket when Stream Deck is installed?

**Comment by Palakis** [comment]
@bhndbrwneyes According to [this](https://obsproject.com/forum/threads/obs-websocket-remote-control-of-obs-studio-made-easy.58018/page-3#post-297549), this issue is fixed in the latest update of ESD's software. Can you confirm this?

**Comment by ThatGirlSlays** [comment]
Yes the issue has been fixed.
