### ISSUE TITLE
Unable to install in pop-os

### ISSUE THREAD

**Issue by MrBillC** [Palakis/obs-websocket#812]
##### Issue type

<--- - Bug report -->

##### Description
Unable to install on pop!-os.  Get error that required dependency missing.
Depends: obs-studio (>= 26.1.0)
But I do have OBS Studio 27.0.1 installed and working

##### Technical information
- **Operating System** : pop!-os 20.04
- **OBS Studio version** :27.0.1
- **obs-websocket version** :4.9.1-1

**Comment by tt2468** [comment]
We don't provide official support for popos. It sounds like OBS is not installed in dpkg under the name `obs-studio`.
