### ISSUE TITLE
Alpha plugins DLL "not loaded" Windows OBS 27.0.1 (64 bit)

### ISSUE THREAD

**Issue by haxsyn** [Palakis/obs-websocket#818]
OBS Log reports:
Module '../../obs-plugins/64bit/obs-websocket.dll' not loaded

Windows 10 Home : Version	21H1 : OS build	19043.1165
OBS 27.0.1 (64 bits)
obs-websocket 5.0.0-alpha2

First time install (i.e. no previous plugin versions) using the Windows installer : "dll not loaded"
Manually copied over files from .zip files : "dll not loaded"
Ran uninstaller and attempted same (installer and zip) for "alpha1" with same results.

Ran uninstaller and ran installer for 4.9.1 : It worked.

[OBS Log file attached]
[2021-09-14 10-26-01.txt](https://github.com/Palakis/obs-websocket/files/7160805/2021-09-14.10-26-01.txt)

**Comment by tore1005** [comment]
I get this all the time on OBS Remote control, can you help me?
Error: Error: connect ECONNREFUSED 127.0.0.1:4444

**Comment by tt2468** [comment]
As the release states on the first line, you must use 27.1.0 or above:
![image](https://user-images.githubusercontent.com/28720189/133332122-2f3bfd53-994d-4efe-9124-a454cc6ca427.png)

Additionally, 5.0.0 versions use a new protocol and no applications currently support it, hence why it is pre-release. You are probably looking for 4.9.1

**Comment by tore1005** [comment]
Version 5.0.0 dont appear on my obs, versión 4.9.1 yes but when y try to Connect my gaming pc with obs remote control appear this error :
Error: Error: connect ECONNREFUSED 127.0.0.1:4444
 
I try diferent ports and still dont work.. i really need this to hide map on one Game when i am on stream

**Comment by tt2468** [comment]
@tore1005 As said in literally my last message, use 4.9.1.

**Comment by tore1005** [comment]
My english is bad, but i think you dont understand me.. i am using 4.9.1 and get this error when i try to reconnect 
Error: connect ECONNREFUSED 127.0.0.1:4444
Versión 5 not appear on obs
Versión 4.9.1 i get this error
I Hope you can understand me, i really need fix this
