### ISSUE TITLE
Enabled/Disabling Studio Mode

### ISSUE THREAD

**Issue by haganbmj** [Palakis/obs-websocket#82]
This is subjective, I could see an argument for this staying as is.

When Studio Mode is activated `StudioModeSwitched` is emit, but not `PreviewSceneChanged` to indicate what the preview scene has been initialized as. 

I'd imagine this is because OBS itself seems to set the Preview Scene to whatever is the output scene in the background when its not visible, so there technically is no scene change when Studio Mode is enabled. It would also explain why the preview scene gets set back to whatever is active when Studio Mode is disabled.
I know there are a lot of bugs surrounding preview mode with the obs api, so this might just be something that would be adjusted there instead.

**Comment by Palakis** [comment]
Shouldn't be hard to manually trigger a `PreviewSceneChanged` event from `WSEvents::StudioModeClicked`. Do you believe it is possible for you to try to implement this? (tell me if you run into any trouble with this)

**Comment by Lange** [comment]
I'm running into this as well and would appreciate the extra `PreviewSceneChanged` event.
