### ISSUE TITLE
building on windows

### ISSUE THREAD

**Issue by pantonvich** [Palakis/obs-websocket#83]
I'm having a hard time getting this to build on windows.
first question is perl required as I get this: Could NOT find Perl (missing:  PERL_EXECUTABLE) 

I'm getting lots of link errors when I try and compile - so I think I've got some path type of issue

3>Utils.obj : error LNK2019: unresolved external symbol obs_sceneitem_visible referenced in function "public: static struct obs_data * __cdecl Utils::GetSceneItemData(struct obs_scene_item *)" (?GetSceneItemData@Utils@@SAPEAUobs_data@@PEAUobs_scene_item@@@Z)

cmake aslo doesn't seam to want to find w32-pthreads so I've set it and my other paths as follows:

set(QTDIR "C:/obs-dev/Qt5.7.0_2013/5.7/msvc2013_64")
set(LIBOBS_INCLUDE_DIR "C:/obs-dev/new-repo/obs-studio/libobs")
set(LIBOBS_LIB "C:/obs-dev/new-repo/obs-studio/build64/libobs/Debug/obs.lib")
set(OBS_FRONTEND_LIB "C:/obs-dev/new-repo/obs-studio/build64/UI/obs-frontend-api/Debug/obs-frontend-api.lib")
set (W32_PTHREADS_LIB "C:/obs-dev/new-repo/obs-studio/build64/deps/w32-pthreads/Debug/w32-pthreads.lib")
set(W32_PTHREADS_INCLUDE_DIR "C:/obs-dev/new-repo/obs-studio/deps/w32-pthreads")	

any help would be appreciated - I've been trying for two days...
thanks Pete

**Comment by Palakis** [comment]
@pantonvich That Perl warning isn't an issue. However the link error is quite strange.
Instead of setting these variables in CMakeLists.txt, set them in cmake-gui.

**Comment by pantonvich** [comment]
I've made some progress - but get a cmake error on coping files over while building - but I"m able to copy the obs-sockets.dll into the obs-studio plug-in and run obs-studio in debug mode

maybe I'm still setting up the gui wrong - here's what I did to get to this point.

cmake_build_type  Debug
what directory should be used for LibObs_include_dir?
C:/obs-dev/new-repo/obs-studio/build64/libobs/libobs.dir
C:/obs-dev/new-repo/obs-studio/build64/libobs
C:/obs-dev/new-repo/obs-studio/libobs

I've tried all three and LibObs_DIR was returned with:
C:/obs-dev/new-repo/obs-studio/build/libobs

So I set it to /build64 /libobs directly via gui

still couldn't find W32_PTHREADS_LIB so I set it to:
C:/obs-dev/new-repo/obs-studio/build64/deps/w32-pthreads/Debug/w32-pthreads.lib

here are the errors I'm getting now

3>  obs-websocket.vcxproj -> C:\obs-dev\new-repo\obs-websocket\build64\Debug\obs-websocket.dll
3>EXEC : CMake error : cmake version 3.4.3
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: The command "setlocal
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if 0==1 ( "C:/Program Files (x86)/CMake/bin/cmake.exe" -E copy /bin/Qt5WebSockets.dll /bin/Qt5Network.dll C:/obs-dev/new-repo/obs-websocket/build64/Debug )
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd

**Comment by pantonvich** [comment]
so i had to split this line into two to get it to work:

if 1==1 ( "C:/Program Files (x86)/CMake/bin/cmake.exe" -E copy C:/obs-dev/Qt5.7.0_2013/5.7/msvc2013_64/bin/Qt5WebSocketsd.dll C:/obs-dev/Qt5.7.0_2013/5.7/msvc2013_64/bin/Qt5Networkd.dll C:/obs-dev/new-repo/obs-websocket/build64/Debug )

becomes:

if 1==1 ( "C:/Program Files (x86)/CMake/bin/cmake.exe" -E copy C:/obs-dev/Qt5.7.0_2013/5.7/msvc2013_64/bin/Qt5WebSocketsd.dll C:/obs-dev/new-repo/obs-websocket/build64/Debug )
if 1==1 ( "C:/Program Files (x86)/CMake/bin/cmake.exe" -E copy C:/obs-dev/Qt5.7.0_2013/5.7/msvc2013_64/bin/Qt5Networkd.dll C:/obs-dev/new-repo/obs-websocket/build64/Debug )

**Comment by coccoalberto97** [comment]
> 

Hello, I'm facing the same issue, where did you change that line? I'm using cmake gui.
