### ISSUE TITLE
Request type for setting the sync offset values

### ISSUE THREAD

**Issue by jbroadway** [Palakis/obs-websocket#84]
#### Issue type
Feature request

#### Description
We're controlling OBS through your plugin in a Unity app (which is a lifesaver for us btw), and also doing "realtime" lip syncing for an avatar in our Unity app, which has an unpredictable delay offset between 200-800ms each time the app runs.

Currently, we have to set the sync offset manually, do a test recording to see if it's on, then adjust until it's correct. But if we could determine the delay in Unity, being able to dynamically set this via obs-websocket would save that trial and error on each run.

Thought I'd make a feature request, in case this might be useful to others too :)

#### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 19.0.2 64-bit

**Comment by Palakis** [comment]
@jbroadway Just to make things clear: you're talking about the audio sync offset, right?

**Comment by jbroadway** [comment]
@Palakis that's right, yes.

**Comment by decowboy** [comment]
I am very much in need of the same feature, with the addition that I would also have to change the video delay of various media sources, in order to use automation to keep them in sync.

**Comment by Palakis** [comment]
Implemented by https://github.com/Palakis/obs-websocket/pull/109
