### ISSUE TITLE
how to disable/enable preview

### ISSUE THREAD

**Issue by bookmarkies** [Palakis/obs-websocket#847]
obs version: 27.3.1
obs-websocket: 4.9.1

I want to use obs-websocket to control the preview switch, but I can't find the api in the documentation. I jusn see ["SetPreviewScene",](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#setpreviewscene), but it need Studio Mode Enable.
![image](https://user-images.githubusercontent.com/76272979/141101075-51b8c737-c1c6-41c9-8d6b-a9a19ab04514.png)

**Comment by tt2468** [comment]
Unfortunately this is not a feature of obs-websocket.
