### ISSUE TITLE
An example of a connection to the server is required.

### ISSUE THREAD

**Issue by vashda** [Palakis/obs-websocket#85]
I have long tried to understand how this works, but I could not do it. If this is not difficult, can you write a simple example of connecting to a server with authorization and ordering of events. Preferably in PHP.

**Comment by haganbmj** [comment]
On my phone, here's a high level.  
Connect to the address 
`GetAuthRequired` - if true then you'll get a salt/challenge. 
Use the salt/challenge to encrypt a password in sha256. 
Send the encrypted password with `Authenticate`

**Comment by haganbmj** [comment]
If you're looking for a client in php, I have no experience - but here's a quick example I found on a search. https://gist.github.com/ikwattro/908f64f8a3121dab6b0c

**Comment by vashda** [comment]
I understand how this works. I do not understand what and in what order it should be sent to the server. He simply does not respond to any request. We need an example. You can also use javascript. The main thing is to show authorization and listen to this server.

**Comment by haganbmj** [comment]
Wasn't sure if you wanted to run the socket on a php backend or a javascript frontend.

I've got pretty detailed info over on here for javascript https://github.com/haganbmj/obs-websocket-js
@Palakis has an implementation in C# https://github.com/Palakis/obs-websocket-dotnet

Both were linked in the Readme.

**Comment by vashda** [comment]
Preferred php backend. I know Javascript at an entry level. So I ask for a simple example. I saw the links. For me, the code from there was complicated.

**Comment by Palakis** [comment]
@vashda What doesn't works? Opening a WebSocket connection, or authenticating to the server using `GetAuthRequired` and `Authenticate`?

**Comment by vashda** [comment]
@Palakis I open the connection via fsockopen (). The connection to the server is successful. Then I try to send a request through fputs (). And get the answer through fgets (). The request like as leaves on the server and here I do not receive the answer. Maybe I'm not formulating the request correctly and so the server is not responding? Can you write a short example for clarity? With other socket servers, there are no such problems. They even respond to the connection.

**Comment by Palakis** [comment]
@vashda `fsockopen()` and `fputs()` are for raw sockets, not WebSockets which is a higher-level protocol relying on HTTP. You may want to have a look at [Pawl](https://github.com/ratchetphp/Pawl).

**Comment by vashda** [comment]
@Palakis This is strange, because my web server server works fine with these commands. Can the implementation example on php?

**Comment by vashda** [comment]
Suddenly I realized that the data is transmitted through JSON. It became a little clearer but still without implementation ideas on php

**Comment by vashda** [comment]
Thank you all for your help, I did not find a normal solution for php. Basically, these are third-party libraries of varying degrees of efficiency. This does not suit me so I'll have to look for another solution.

**Comment by Palakis** [comment]
@vashda Did you managed to achieve what you want?
