### ISSUE TITLE
Add transition information in TransitionBegin

### ISSUE THREAD

**Issue by FourCourtJester** [Palakis/obs-websocket#86]
#### Issue type
Feature request

#### Description
`SwitchScenes` fires only when the new scene has completed its transition. `TransitionBegin` lets me know that a transition is happening, but not where it's going to.

#### Request of information
New event (ie - `onBeforeSwitchScene`) with the current scene selected AND the intended target scene, or modify `TransitionBegin` to include the same data.

#### Side note
Is there plans for a `TransitionEnd` ? Or modifying `TransitionBegin` to include transition duration?

**Comment by FourCourtJester** [comment]
So a pseudo workaround right now is that on `BeginTransition` you can immediately fire a `GetCurrentScene` to retrieve the NEW scene you are transitioning to.

I feel having an exposed event such as `onBeforeBeginTransition` or `onBeforeSwitchScenes` would still be beneficial for management.

For example, if I need to change to a different transition than the current transition, I cannot execute `SetCurrentTransition` before `TransitionBegin`.

**Comment by Palakis** [comment]
- There's no plan for a `TransitionEnd` event since `SwitchScenes` implicitly serves this purpose.
- I believe `TransitionBegin` should include transition type and duration.

**Comment by FourCourtJester** [comment]
Thanks, looking forward to the next release!

**Comment by Palakis** [comment]
Implemented in https://github.com/Palakis/obs-websocket/commit/c7190cb94a0a65f9ed1fd1a0a5effdc9d72b2efd
