### ISSUE TITLE
SetSourceRender "true" not working

### ISSUE THREAD

**Issue by ScriptedKitten** [Palakis/obs-websocket#88]
#### Issue type
Bug

#### Description
On Request type "SetSourceRender" with parameter "true" nothing happens,
parameter "false" is working

#### Technical information
- **Operating System** : Windows 10 Pro
- **OBS Studio version** : 19.0.2

**Comment by Palakis** [comment]
The expected value is a boolean, not a string. So `"render": "true"` is not the same as `"render": true`

**Comment by ScriptedKitten** [comment]
Ah that was the Problem, thanks.
