### ISSUE TITLE
Feature Request: Save replay buffer

### ISSUE THREAD

**Issue by XBase-xOR** [Palakis/obs-websocket#90]
#### Issue type
Feature request

#### Description
I have written a tool that does an instant replay while live. Right now I have defined the F14 hotkey (which doesn't exist on my keyboard so it's otherwise not used) in OBS for the "Save Replay Buffer" action and then my tool sends an F14 keystroke to the OBS process using PostMessage().
Although that is working it's still somewhat hackish. Since the tool is already connected to OBS using your fine websocket interface it would be great if I could just use the websocket interface for that.

EDIT for further clarification:
Check [this screenshot](https://x-base.org/img/OBS_replay_buffer.png). The hotkeys with a green border are for functions that can also be triggered from the GUI on the main window. The hotkey with a red border however is the only way I know of to trigger writing of the file, there is no GUI button equivalent. And this is the functionality I am asking to be able to trigger from the websocket interface.

#### Technical information
- **Operating System** : Windows 10 64 Bit with Creators Update
- **OBS Studio version** : 18.0.1

**Comment by Palakis** [comment]
It's in the works: https://github.com/Palakis/obs-websocket/pull/104

**Comment by TStod** [comment]
Just found this repo. Noticed replay events/requests were not implemented. Went to file a feature request. Find this.

FeelsAmazingMan

**Comment by XBase-xOR** [comment]
@Palakis Thanks so much dude, changed my tool from using hotkey to the new API method and it works like a charm!
