### ISSUE TITLE
StopRecording and RecordingStopped are returned/sent too early

### ISSUE THREAD

**Issue by alvancamp** [Palakis/obs-websocket#91]
#### Issue type
Bug

#### Description
The `StopRecording` method returns before the recording has fully stopped. Likewise, the `RecordingStopped` event is emitted before the recording has fully stopped. This makes it difficult to quickly stop and re-start a recording.

#### Steps to reproduce
1. Start a recording in OBS
2. Send a `StopRecording` request.
3. When you receive a `RecordingStopped` event, immediately send a `StartRecording` request.
4. You will receive an error of `recording already active`.

#### Technical information
- **Operating System** : Windows 10 x64
- **OBS Studio version** : 19.0.2
- **obs-websocket version**: Windows build 739bd6f from appveyor.

**Comment by Lange** [comment]
For the time being I have worked around this by simply adding a 2.5 second timeout before I send my `StartRecording` command. Seems to get the job done.

**Comment by Palakis** [comment]
The behavior where `StopRecording` returns immediately is normal. However, that race condition is not and seems to happen in OBS' API itself.

**Comment by Palakis** [comment]
Hi @Lange. Does this issues still happens and affect you?

**Comment by Lange** [comment]
I've not had an opportunity to check, but it was easy enough to work around by just adding in my own delay, so this is not a particularly high-priority problem.

**Comment by OpaqueStephanie** [comment]
@Palakis I've run into a problem which seems related:
The reply from sending a  `StopRecording` message is recieved before the file has finished being output, meaning I can't perform tasks on the resulting file immediately (I'm trying to automatically upload it). I'm assuming the same is for `RecordingStopped` (the documentation isn't clear but it looks like it'd be sent at the same time as `StopRecording`'s reply)?

**Comment by Downchuck** [comment]
Ran into the same issue, RecordingStopped is sent too early; a subsequent call to start recording will not trigger; a subsequent call to StopRecording will report that recording is not active.  Note that GetOutputInfo will show that active: true.  This may be a case where another event is needed, so as to trigger when get output info changes activity status.

**Comment by Downchuck** [comment]
@Palakis What are your thought son this? My read is that it makes sense for recording stopped to trigger as it does, but that there does need to be an event, if the output so supports it, to notify the program when it has closed out the output.

**Comment by Downchuck** [comment]
We ended up with a delay node as well, polling for the event

**Comment by tt2468** [comment]
Hello,

We are closing this, as work on 4.x has stopped. If you experience the same issue when 5.0.0 comes out, please open a new Issue at that time.

Thanks
