### ISSUE TITLE
Link to Python client lib in the README?

### ISSUE THREAD

**Issue by Elektordi** [Palakis/obs-websocket#93]
#### Issue type
- [ ] Bug
- [ ] Feature request
- [X] Other

#### Description
Just to let you know I'm working on a Python client lib for OBS-Websocket:
https://github.com/Elektordi/obs-websocket-py

It's not finished yet, but stable enough to be used live (we are using it live for few days now, so far there was no problem)

Maybe you could add a link to it in the "For developers" section of your README, along with JS and .NET clients?

Thanks!

Guillaume

**Comment by Palakis** [comment]
Wow, thanks a lot Guillaume! This is really appreciated!
I'll have a look at it and add it in the README.

**Comment by Palakis** [comment]
@Elektordi sidenote : did you considered adding it to pip?

**Comment by Palakis** [comment]
Added in https://github.com/Palakis/obs-websocket/commit/ab38f3353037a0127c64ded11d027af4be440e42.

**Comment by Elektordi** [comment]
For adding it to PyPI, I'll take a look when I will have finished the features I want to include.
