### ISSUE TITLE
Python - SetCurrentScene() fails - scene does not exist.

### ISSUE THREAD

**Issue by JohnnyBlaze420** [Palakis/obs-websocket#97]
#### Issue type
- [X] Bug
- [ ] Feature request
- [ ] Other

#### Description
While using Python and obs-websocket-py trying to use SetCurrentScene results in

`<SetCurrentScene request({u"error" : u"requested scene does not exist"}) called: failed ({"scene-name" : u"s2"})>`

or any other name results in "scene does not exist" error, even if the scene does exists and is read by using GetSceneList().

#### Steps to reproduce
Make two scenes in OBS, "s1" and "s2". Then:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import obswebsocket as obsw
import obswebsocket.requests as obsr

client = obsw.obsws("localhost", 4444, "password")
client.connect()
scenes = client.call(obsr.GetSceneList()).dataout["scenes"]
newScene = scenes[1]
res = client.call(obsr.SetCurrentScene(newScene["name"]))
print res
client.disconnect()
```

#### Technical information
- **Operating System** : Windows 7 Pro x64 SP1
- **OBS Studio version** : 19.0.3 x32
- **Python version**: 2.7.13 x32
Using obs-websocket version 4.0 and obs-websocket-py version 0.1.

**Comment by Palakis** [comment]
Issues with the Python library belong here : https://github.com/Elektordi/obs-websocket-py/issues
